<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Paul Testa">
  <title>POLS 1600 – Week 11:</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-8979bb8451ddc1038f930ac611262c50.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint/kePrint.js"></script>

  <link href="../site_libs/lightable/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" align="left" data-background-image="images/pols1600_hex.png" data-background-position="90% 50%" data-background-size="40%" class="quarto-title-block center">
  <h1 class="title">Week 11:</h1>
  <p class="subtitle">Quantifying Uncertainty with Hypothesis Testing</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Paul Testa 
</div>
</div>
</div>

</section>
<section class="slide level2">

<p>class: inverse, center, middle # Overview</p>
</section>
<section id="general-plan" class="slide level2">
<h2>General Plan</h2>
<ul>
<li class="fragment"><p>Setup</p></li>
<li class="fragment"><p>Review: Confidence Intervals</p></li>
<li class="fragment"><p>Lecture : Hypothesis Testing</p></li>
<li class="fragment"><p>Demo: Final Projects</p></li>
</ul>
</section>
<section id="course-plan" class="slide level2">
<h2>Course Plan</h2>
<ul>
<li class="fragment"><p>April 18: Lecture – Hypothesis Testing</p></li>
<li class="fragment"><p>April 20 Lab – Hypothesis Testing and Interval Estimation</p></li>
<li class="fragment"><p>April 25: Lecture – Course Review</p></li>
<li class="fragment"><p>April 27: Workshop:</p></li>
<li class="fragment"><p>April 30: Take Home Final Exam</p></li>
<li class="fragment"><p>May ?: Tacos or Pizza with POLS 1140?</p></li>
<li class="fragment"><p>May 7: Take Home Final Exam due</p></li>
</ul>
<p>class:inverse, middle, center # 💪 ## Get set up to work</p>
</section>
<section id="new-packages" class="slide level2">
<h2>New packages</h2>
<p>To easily load survey data for our question, we’ll need the <code>anesr</code> package, which loads data from the American National Election Studies into R</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># Uncomment to uninstall package to download NES survey data</span></span>
<span id="cb1-2"><a></a><span class="co"># library(devtools)</span></span>
<span id="cb1-3"><a></a><span class="co"># install_github("jamesmartherus/anesr")</span></span>
<span id="cb1-4"><a></a><span class="fu">require</span>(anser)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="packages-for-today" class="slide level2">
<h2>Packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-2"><a></a>  <span class="do">## R Markdown</span></span>
<span id="cb2-3"><a></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,</span>
<span id="cb2-4"><a></a>  <span class="do">## Tidyverse</span></span>
<span id="cb2-5"><a></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,<span class="st">"purrr"</span>,</span>
<span id="cb2-6"><a></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb2-7"><a></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb2-8"><a></a>  <span class="st">"GGally"</span>, <span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb2-9"><a></a>  <span class="co"># Graphics:</span></span>
<span id="cb2-10"><a></a>  <span class="st">"scatterplot3d"</span>, <span class="co">#&lt;&lt;</span></span>
<span id="cb2-11"><a></a>  <span class="co"># Data </span></span>
<span id="cb2-12"><a></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>, </span>
<span id="cb2-13"><a></a>  <span class="co"># Analysis</span></span>
<span id="cb2-14"><a></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"modelr"</span>, <span class="st">"zoo"</span></span>
<span id="cb2-15"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-a-function-to-load-and-if-needed-install-packages" class="slide level2">
<h2>Define a function to load (and if needed install) packages</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>ipak <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb3-2"><a></a>    new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb3-3"><a></a>    <span class="cf">if</span> (<span class="fu">length</span>(new.pkg)) </span>
<span id="cb3-4"><a></a>        <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-5"><a></a>    <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-6"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-packages-for-today" class="slide level2">
<h2>Load packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">ipak</span>(the_packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   kableExtra            DT        texreg     tidyverse     lubridate 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      forcats         haven      labelled         purrr         ggmap 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      ggrepel      ggridges      ggthemes        ggpubr        GGally 
         TRUE          TRUE          TRUE          TRUE          TRUE 
       scales       dagitty         ggdag       ggforce scatterplot3d 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      COVID19          maps       mapdata           qss    tidycensus 
         TRUE          TRUE          TRUE          TRUE          TRUE 
    dataverse DeclareDesign        modelr           zoo 
         TRUE          TRUE          TRUE          TRUE </code></pre>
</div>
</div>
<p>class:inverse, middle, center # 🔍 # Review ## Confidence Intervals</p>
</section>
<section id="confidence-intervals" class="slide level2">
<h2>Confidence Intervals</h2>
<ul>
<li class="fragment"><p>Statistical inference involves quantifying uncertainty about what could have happened</p></li>
<li class="fragment"><p>We can describe this uncertainty in terms of a sampling distribution (what could have happened had we had a different sample)</p></li>
<li class="fragment"><p>The standard deviation of a sampling distribution describes its width (spread) and is called a standard error</p></li>
<li class="fragment"><p>Standard errors decrease with by the <span class="math inline">\(\sqrt{N}\)</span> where <span class="math inline">\(N\)</span> is the size of our sample</p></li>
<li class="fragment"><p>We can estimate standard errors via simulation or analytically.</p>
<ul>
<li class="fragment"><p>Simulations require fewer assumptions, but take more time.</p></li>
<li class="fragment"><p>Analytic estimates are are quick, but require more assumptions.</p></li>
</ul></li>
<li class="fragment"><p>We use standard errors to construct confidence intervals which we interpret as describing a range of plausible values for the thing we’re trying to estimate.</p></li>
<li class="fragment"><p>Any one 95% confidence interval may or may not contain the truth, but in repeated sampling, 95% of the intervals we construct would contain the truth.</p></li>
</ul>
</section>
<section id="standard-errors-of-regression-coefficients" class="slide level2">
<h2>Standard Errors of Regression Coefficients</h2>
<p>Last class, we calculated the standard error of a sample mean using bootstrapping.</p>
<p>We can take the same approach for regression coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/df_drww.rda"</span>))</span>
<span id="cb6-2"><a></a></span>
<span id="cb6-3"><a></a><span class="co"># Fit model</span></span>
<span id="cb6-4"><a></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(support_war01 <span class="sc">~</span> age <span class="sc">+</span> education_n <span class="sc">+</span> sex, df_drww)</span>
<span id="cb6-5"><a></a><span class="co"># set seed</span></span>
<span id="cb6-6"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-7"><a></a><span class="co"># 1,000 bootstrap samples</span></span>
<span id="cb6-8"><a></a>boot <span class="ot">&lt;-</span> modelr<span class="sc">::</span><span class="fu">bootstrap</span>(df_drww, <span class="dv">1000</span>)</span>
<span id="cb6-9"><a></a><span class="co"># Estimate Boostrapped Models</span></span>
<span id="cb6-10"><a></a>m1_bs <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(boot<span class="sc">$</span>strap, <span class="sc">~</span> <span class="fu">lm</span>(support_war01 <span class="sc">~</span> age <span class="sc">+</span> education_n <span class="sc">+</span> sex, <span class="at">data =</span>.))</span>
<span id="cb6-11"><a></a><span class="co"># Tidy coefficients</span></span>
<span id="cb6-12"><a></a>m1_bs_df <span class="ot">&lt;-</span> <span class="fu">map_df</span>(m1_bs, tidy, <span class="at">.id =</span> <span class="st">"id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="bootstrapped-standard-errors" class="slide level2">
<h2>Bootstrapped Standard Errors</h2>
<p>Then we simply calculate the standard error of for the sampling distribution of each coefficient</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>m1_bs_df <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a></a>  <span class="fu">group_by</span>(term)<span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-4"><a></a>    <span class="at">bs_se =</span> <span class="fu">sd</span>(estimate)</span>
<span id="cb7-5"><a></a>  ) <span class="ot">-&gt;</span> m1_bs_se</span>
<span id="cb7-6"><a></a>m1_bs_se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  term           bs_se
  &lt;chr&gt;          &lt;dbl&gt;
1 (Intercept) 0.0564  
2 age         0.000717
3 education_n 0.0108  
4 sexMale     0.0223  </code></pre>
</div>
</div>
</section>
<section id="analytic-standard-errors." class="slide level2">
<h2>Analytic Standard Errors.</h2>
<p>Alternatively, we can derive the standard error of the sampling distribution <strong>analytically</strong> using <strong>asymptotic</strong> theory (e.g.&nbsp;the Central Limit Theorem).</p>
<p>The process starts by defining the quantity we want to know: the variance of our estimated coefficients <span class="math inline">\(\hat{\beta}\)</span> around their true values in the population <span class="math inline">\(\beta\)</span>:</p>
<p><span class="math display">\[V(\hat{\beta}|X) =(E[(\hat{\beta} - \beta)(\hat{\beta} - \beta)' |X]\]</span></p>
<p>Your textbook walks through the math to estimate this quantity on pages 375-380 for simple bivariate regression (i.e.&nbsp;a regression with 1 predictor)</p>
<p><a href="https://pols1600.paultesta.org/notes/10-notes.html#Assymptotic_Standard_Errors" target="_blank">In the notes</a>, you’ll find some further discussion of the math for the more general case of with multiple predictors.</p>
<p>This is also an excellent walk through of the <a href="https://towardsdatascience.com/a-deep-dive-into-the-variance-covariance-matrices-of-classical-linear-regression-models-4322b2cdc8e6" target="_blank">linear algebra</a></p>
</section>
<section id="analytic-standard-errors.-1" class="slide level2">
<h2>Analytic Standard Errors.</h2>
<p>Essentially, if you expand terms from:</p>
<p><span class="math display">\[V(\hat{\beta}|X) =(E[(\hat{\beta} - \beta)(\hat{\beta} - \beta)' |X]\]</span></p>
<p>make substitutions and some assumptions about the distribution of <span class="math inline">\(\epsilon\)</span>, you arrive at a formula for the “Variance Covariance Matrix” of the model:</p>
<p><span class="math display">\[V(\hat{\beta}|X) = \sigma^2(X'X)^{-1}\]</span> Which is a function of</p>
<ul>
<li class="fragment"><span class="math inline">\(\sigma^2\)</span> the “Sum of Square Errors”</li>
<li class="fragment"><span class="math inline">\((X'X)^{-1}\)</span> roughly captures the underlying variance and covariance of the predictors in your model, where:
<ul>
<li class="fragment"><span class="math inline">\(X\)</span> is a matrix of predictors (each row is an observation, each column a variable)</li>
<li class="fragment"><span class="math inline">\(X'X\)</span> is a symmetric maxtrix (like squaring a variable, but in linear algerba)</li>
<li class="fragment"><span class="math inline">\(X'X^{-1}\)</span> is the inverse of this matrix</li>
<li class="fragment"><span class="math inline">\(sigma^2(X'X)^{-1}\)</span> is like dividing <span class="math inline">\(\sigma^2\)</span> by <span class="math inline">\(X'X\)</span></li>
</ul></li>
</ul>
</section>
<section id="analytic-standard-errors.-2" class="slide level2">
<h2>Analytic Standard Errors.</h2>
<p>The square root of the elements on the diagonal of <span class="math inline">\(V(\hat{\beta}|X)\)</span> provides the standard error for each coefficient, which is larger if:</p>
<ul>
<li class="fragment">if <span class="math inline">\(\sigma^2\)</span> is large (When there’s a lot of unexplained variance, our uncertainty is high)</li>
<li class="fragment">the variance of <span class="math inline">\(X\)</span> is small (When predictors don’t vary much our uncertainty increases)</li>
</ul>
</section>
<section id="analytic-standard-errors.-3" class="slide level2">
<h2>Analytic Standard Errors.</h2>
<p>In practice, you will let your computer calculate these standard errors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value     Pr(&gt;|t|)
(Intercept)  0.277540588 0.0529197543  5.244555 1.797036e-07
age          0.009216952 0.0007129459 12.927982 2.827291e-36
education_n -0.015814493 0.0108357258 -1.459477 1.446491e-01
sexMale      0.094320479 0.0225358310  4.185356 3.017253e-05</code></pre>
</div>
</div>
</section>
<section id="analytic-standard-errors-by-hand" class="slide level2">
<h2>Analytic Standard Errors by Hand</h2>
<p>Just for fun:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co"># Sum of Squared Residuals</span></span>
<span id="cb11-2"><a></a>sigma_2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(m1)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>m1<span class="sc">$</span>df.residual</span>
<span id="cb11-3"><a></a><span class="co"># X transpose X</span></span>
<span id="cb11-4"><a></a>XtXinv <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(<span class="fu">model.matrix</span>(m1))<span class="sc">%*%</span><span class="fu">model.matrix</span>(m1))</span>
<span id="cb11-5"><a></a><span class="co"># SE is square root of diagonal of Variance Covariance Matrix</span></span>
<span id="cb11-6"><a></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(sigma_2<span class="sc">*</span>XtXinv))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age  education_n      sexMale 
0.0529197543 0.0007129459 0.0108357258 0.0225358310 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coef[,<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age  education_n      sexMale 
0.0529197543 0.0007129459 0.0108357258 0.0225358310 </code></pre>
</div>
</div>
</section>
<section id="constructing-confidence-intervals-for-regression-coefficients" class="slide level2 scrollable">
<h2>Constructing Confidence Intervals for Regression Coefficients</h2>
<ol type="1">
<li class="fragment"><p>Estimate the model to obtain coefficients <span class="math inline">\(\hat{\beta}\)</span></p></li>
<li class="fragment"><p>Calculate Standard Errors using simulation or asymptotic theory</p></li>
<li class="fragment"><p>Choose desired confidence level <span class="math inline">\(\alpha\)</span> with a corresponding critical value <span class="math inline">\(z_{\alpha/2}\)</span> derived from an approximation of the hypotehtical sampling distribution</p></li>
<li class="fragment"><p>Construct a <span class="math inline">\((1-\alpha)\times 100 \%\)</span> percent confidence interval:</p></li>
</ol>
<p><span class="math display">\[CI(\alpha) = [\hat{\beta} - z_{\alpha/2} \times \text{standard error}, \hat{\beta} + z_{\alpha/2} \times \text{standard error}]\]</span></p>
<ol type="1">
<li class="fragment">Estimate the model to obtain coefficients <span class="math inline">\(\hat{\beta}\)</span></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>beta <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1)</span>
<span id="cb15-2"><a></a>beta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age  education_n      sexMale 
 0.277540588  0.009216952 -0.015814493  0.094320479 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li class="fragment">Calculate Standard Errors using simulation or asymptotic theory</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>se <span class="ot">&lt;-</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>coef[,<span class="dv">2</span>]</span>
<span id="cb17-2"><a></a>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age  education_n      sexMale 
0.0529197543 0.0007129459 0.0108357258 0.0225358310 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="co"># Similar to bs</span></span>
<span id="cb19-2"><a></a>m1_bs_se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  term           bs_se
  &lt;chr&gt;          &lt;dbl&gt;
1 (Intercept) 0.0564  
2 age         0.000717
3 education_n 0.0108  
4 sexMale     0.0223  </code></pre>
</div>
</div>
</section>
<section id="constructing-confidence-intervals-for-regression-coefficients-1" class="slide level2 scrollable">
<h2>Constructing Confidence Intervals for Regression Coefficients</h2>
<ol start="3" type="1">
<li class="fragment">Calculate critical value</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>z_fs <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">qt</span>(.<span class="dv">05</span><span class="sc">/</span><span class="dv">2</span>, m1<span class="sc">$</span>df.residual))</span>
<span id="cb21-2"><a></a>z_fs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.961591</code></pre>
</div>
</div>
<ul>
<li class="fragment">Note: For finite samples we use a <span class="math inline">\(t\)</span> distribution…</li>
</ul>
</section>
<section id="constructing-confidence-intervals-for-regression-coefficients-2" class="slide level2">
<h2>Constructing Confidence Intervals for Regression Coefficients</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>ll <span class="ot">&lt;-</span> beta <span class="sc">-</span> z_fs <span class="sc">*</span>se</span>
<span id="cb23-2"><a></a>ul <span class="ot">&lt;-</span> beta <span class="sc">+</span> z_fs <span class="sc">*</span>se</span>
<span id="cb23-3"><a></a><span class="fu">cbind</span>(ll,ul)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      ll          ul
(Intercept)  0.173733660 0.381347516
age          0.007818443 0.010615460
education_n -0.037069758 0.005440772
sexMale      0.050114390 0.138526568</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="co"># Compare to R:</span></span>
<span id="cb25-2"><a></a><span class="fu">confint</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %      97.5 %
(Intercept)  0.173733660 0.381347516
age          0.007818443 0.010615460
education_n -0.037069758 0.005440772
sexMale      0.050114390 0.138526568</code></pre>
</div>
</div>
</section>
<section id="presenting-confidence-intervals-in-a-regression-table" class="slide level2">
<h2>Presenting Confidence Intervals in a Regression Table:</h2>
<pre><code>
```{r, results="asis"}`r''`
texreg::htmlreg(m1, 
  digits = 3, 
  ci.force = T)
```</code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>texreg<span class="sc">::</span><span class="fu">htmlreg</span>(m1,</span>
<span id="cb28-2"><a></a>        <span class="at">digits =</span> <span class="dv">3</span>, </span>
<span id="cb28-3"><a></a>        <span class="at">ci.force =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.278<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[ 0.174; 0.381]
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.009<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[ 0.008; 0.011]
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
education_n
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.016
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[-0.037; 0.005]
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
sexMale
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.094<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[ 0.050; 0.138]
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.107
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.106
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1463
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>*</sup> 0 outside the confidence interval.
</td>
</tr>
</tfoot>
</table>
</div>
</section>
<section id="tidying-regression-models" class="slide level2">
<h2>Tidying Regression Models</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>m1 <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a></a>  <span class="fu">tidy</span>(., <span class="at">conf.int =</span>  T) <span class="ot">-&gt;</span> m1_df</span>
<span id="cb29-3"><a></a>m1_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  0.278    0.0529        5.24 1.80e- 7  0.174     0.381  
2 age          0.00922  0.000713     12.9  2.83e-36  0.00782   0.0106 
3 education_n -0.0158   0.0108       -1.46 1.45e- 1 -0.0371    0.00544
4 sexMale      0.0943   0.0225        4.19 3.02e- 5  0.0501    0.139  </code></pre>
</div>
</div>
</section>
<section id="coefficient-plots-as-an-alternative-to-regression-tables" class="slide level2">
<h2>Coefficient Plots as an Alternative to Regression Tables</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>m1_df <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a></a>  <span class="fu">filter</span>(term <span class="sc">!=</span>  <span class="st">"(Intercept)"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, </span>
<span id="cb31-4"><a></a>             <span class="at">y=</span> term, </span>
<span id="cb31-5"><a></a>             <span class="at">xmin =</span> conf.low,</span>
<span id="cb31-6"><a></a>             <span class="at">xmax =</span> conf.high,</span>
<span id="cb31-7"><a></a>             <span class="at">label =</span> <span class="fu">round</span>(estimate,<span class="dv">3</span>)</span>
<span id="cb31-8"><a></a>             ))<span class="sc">+</span></span>
<span id="cb31-9"><a></a>  <span class="fu">geom_pointrange</span>()<span class="sc">+</span></span>
<span id="cb31-10"><a></a>  <span class="fu">geom_text</span>(<span class="at">vjust=</span><span class="sc">-</span><span class="fl">1.5</span>)<span class="sc">+</span></span>
<span id="cb31-11"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb31-12"><a></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<img data-src="11-slides-old_files/figure-html/unnamed-chunk-20-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="confidence-intervals-summary" class="slide level2">
<h2>Confidence Intervals: Summary</h2>
<p><strong>What is a sampling distribution?</strong></p>
<ul>
<li class="fragment">A distribution of values we would have observed upon repeated sampling</li>
<li class="fragment">Bootstrapping (sampling from a sample) approximates the width of the sampling distribution</li>
</ul>
<p><strong>What is a standard error?</strong></p>
<ul>
<li class="fragment">Standard deviation of the sampling distribution
<ul>
<li class="fragment">Describes the width or range of plausible observations we would see.</li>
<li class="fragment">Decreases as the sample size increases</li>
</ul></li>
</ul>
</section>
<section id="confidence-intervals-summary-1" class="slide level2">
<h2>Confidence Intervals: Summary</h2>
<p><strong>What is a confidence interval</strong></p>
<ul>
<li class="fragment">Coverage interval for a sampling distribution
<ul>
<li class="fragment">“A confidence interval is a way of expressing the precision or repeatability of a statistic, how much variation would likely be present across the possible different random samples from the population”</li>
</ul></li>
<li class="fragment">Three components:
<ul>
<li class="fragment">Point Estimate (i.e.&nbsp;a mean, or coefficient)</li>
<li class="fragment">Confidence Level (Often 95 percent by convention)</li>
<li class="fragment">Margin of Error (+/- some range (typically 2*SD for 95 percent CI))</li>
</ul></li>
<li class="fragment">Confidence is about the interval
<ul>
<li class="fragment">95 percent of the intervals construct in this manner would contain the truth.</li>
</ul></li>
</ul>
<p>class: inverse, center, middle # 💡 # Hypothesis Testing ## How likely is it that we would see what did if our hypothesis were true</p>
</section>
<section id="what-is-a-hypothesis-test" class="slide level2">
<h2>What is a hypothesis test</h2>
<ul>
<li class="fragment"><p>A formal way of assessing statistical evidence. Combines</p>
<ul>
<li class="fragment"><p><strong>Deductive reasoning</strong> (distribution of a test statistic, if the a null hypothesis were true )</p></li>
<li class="fragment"><p><strong>Inductive reasoning</strong> (based on the test statistic we observed, how likely is it that we would observe it if the null were true?)</p></li>
</ul></li>
</ul>
</section>
<section id="what-is-a-test-statistic" class="slide level2">
<h2>What is a test statistic?</h2>
<ul>
<li class="fragment"><p>A way of summarizing data</p>
<ul>
<li class="fragment"><p>difference of means</p></li>
<li class="fragment"><p>coefficients from a linear model</p></li>
<li class="fragment"><p><strong>coefficients from a linear model divded by their standard errors</strong></p></li>
<li class="fragment"><p>R^2</p></li>
</ul></li>
</ul>
</section>
<section id="what-is-a-null-hypothesis" class="slide level2">
<h2>What is a null hypothesis?</h2>
<ul>
<li class="fragment"><p>A statement about the world</p>
<ul>
<li class="fragment"><p>Only interesting if we reject it</p></li>
<li class="fragment"><p>Would yield a distribution of test statistics “under the null”</p></li>
<li class="fragment"><p>Typically something like “X has no effect on Y” (Null = no effect)</p></li>
<li class="fragment"><p>Never accept the null can only reject</p></li>
</ul></li>
</ul>
</section>
<section id="what-is-a-p-value" class="slide level2">
<h2>What is a p-value?</h2>
<ul>
<li class="fragment"><p>A p-value is a conditional probability summarizing the likelihood of observing a test statistic as far from our hypothesis or farther, if our hypothesis were true.</p></li>
<li class="fragment"><p>It’s the area in the “tails of the curve” of the distribution of the test statistic under the null.</p></li>
</ul>
</section>
<section id="how-do-we-do-hypothesis-testing" class="slide level2 scrollable">
<h2>How do we do hypothesis testing?</h2>
<ol start="0" type="1">
<li class="fragment">Posit a hypothesis (e.g.&nbsp;<span class="math inline">\(\beta = 0\)</span>)</li>
</ol>
<p>–</p>
<ol type="1">
<li class="fragment">Calculate the test statistic (e.g.&nbsp;<span class="math inline">\((\hat{\beta}-\beta)/se_\beta\)</span>)</li>
</ol>
<p>–</p>
<ol start="2" type="1">
<li class="fragment">Derive the distribution of the test statistic under the null via</li>
</ol>
<ul>
<li class="fragment">Simulation</li>
<li class="fragment">Asymptotic theory</li>
</ul>
<p>–</p>
<ol start="3" type="1">
<li class="fragment"><p>Compare the test statistic to the distribution under the null</p>
<ul>
<li class="fragment">If it’s in the tails <span class="math inline">\(\to\)</span> very unlikely that we would observe what we did if our hypothesis were true</li>
</ul></li>
</ol>
<p>–</p>
<ol start="4" type="1">
<li class="fragment">Calculate p-value
<ul>
<li class="fragment">Quantify how often we would see test statistics as big or bigger</li>
<li class="fragment">Two-side tests: how often do we see test statics as big or bigger in absolute value as our observed test statistic</li>
<li class="fragment">One-side test: how often do we see test statistics as extreme as our observed statistic in a particular direction (positive/negative)</li>
</ul></li>
</ol>
<p>–</p>
<ol start="5" type="1">
<li class="fragment">Reject or fail to reject/retain our hypothesis based on some threshold of statistical significance (e.g.&nbsp;p &lt; 0.05)</li>
</ol>
</section>
<section id="outcomes-of-hypothesis-tests" class="slide level2">
<h2>Outcomes of Hypothesis Tests</h2>
<ul>
<li class="fragment"><p>Two conclusions from of a hypothesis test: we can reject or fail to reject a hypothesis test.</p></li>
<li class="fragment"><p><strong>We never “accept” a hypothesis</strong>, since there are, in theory, an infinite number of other hypotheses we could have tested.</p></li>
</ul>
<p>Our decision can produce four outcomes and two types of error:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Reject <span class="math inline">\(H_0\)</span></th>
<th>Fail to Reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> is true</td>
<td>False Positive</td>
<td>Correct!</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_0\)</span> is false</td>
<td>Correct!</td>
<td>False Negative</td>
</tr>
</tbody>
</table>
</section>
<section id="outcomes-of-hypothesis-tests-1" class="slide level2">
<h2>Outcomes of Hypothesis Tests</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Reject <span class="math inline">\(H_0\)</span></th>
<th>Fail to Reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> is true</td>
<td>False Positive</td>
<td>Correct!</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_0\)</span> is false</td>
<td>Correct!</td>
<td>False Negative</td>
</tr>
</tbody>
</table>
<p>Suppose we chose to reject a hypothesis if our p-value was less than 0.05.</p>
<p>What we’re saying is that we’re willing to falsely reject our hypothesis 5 times out of 100.</p>
<p>Typically we want to minimize this false positive rate (Type 1 error), but there’s a trade off:</p>
<ul>
<li class="fragment">Reducing Type 1 error means, we’re more likely to make a Type 2 error – failing to reject when our null is false.</li>
</ul>
<p>class:inverse, middle, center # 💪 ## Application: Hypothesis Testing for Linear Models</p>
</section>
<section id="posit-a-null-hypothesis" class="slide level2">
<h2>0. Posit a Null Hypothesis</h2>
<ul>
<li class="fragment"><p>Typically, we will test a null hypothesis that the coefficient for variable <span class="math inline">\(X\)</span> equals 0 (e.g.&nbsp;<span class="math inline">\(H_0: \beta_x = 0\)</span> )</p></li>
<li class="fragment"><p>Our alternative hypothesis in a two sided test then is that <span class="math inline">\(\beta_0\)</span> doesn’t equal 0 (<span class="math inline">\(H_1: \beta_x \neq 0\)</span>)</p></li>
<li class="fragment"><p>In a one-sided test, our alternative is directional (<span class="math inline">\(H_1: \beta_x &gt; 0\)</span> or <span class="math inline">\(H_1: \beta_x &lt; 0\)</span> )</p>
<ul>
<li class="fragment">One-sided tests are rare in practice – need a strong substantive reason for directional expectation</li>
</ul></li>
</ul>
</section>
<section id="calculate-the-test-statistic" class="slide level2">
<h2>1. Calculate the test statistic</h2>
<p>For a linear regression, we could use the <span class="math inline">\(\hat{\beta}\)</span> as our test statistic.</p>
<p>In practice, we we use a “t-stat” which is our observed coefficiet, <span class="math inline">\(\hat{\beta}\)</span> minus our hypothesized value <span class="math inline">\(\beta\)</span> (e.g.&nbsp;0), divided by the standard error of <span class="math inline">\(\hat{\beta}\)</span>.</p>
<p><span class="math display">\[t= \frac{\hat\beta-\beta}{\widehat{SE}_{\hat{\beta}}} \sim \text{Students's } t \text{ with } n-k \text{ degrees of freedom}\]</span> Fisher showed that this statistic from a regression follows a <span class="math inline">\(t\)</span> distribution – which looks like a normal distribution but with “fatter tails” (e.g.&nbsp;more probability assigned to extreme values)</p>
</section>
<section id="calculate-the-test-statistic-in-r" class="slide level2">
<h2>1. Calculate the test statistic in R</h2>
<p>We can caclulate test statistics from our model by dividing the coefficients by their standard errors</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a>t_stat <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1) <span class="sc">/</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>coef[,<span class="dv">2</span>]</span>
<span id="cb32-2"><a></a>t_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age education_n     sexMale 
   5.244555   12.927982   -1.459477    4.185356 </code></pre>
</div>
</div>
<p>Which is exactly what the third column of <code>summary()</code> shows</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value     Pr(&gt;|t|)
(Intercept)  0.277540588 0.0529197543  5.244555 1.797036e-07
age          0.009216952 0.0007129459 12.927982 2.827291e-36
education_n -0.015814493 0.0108357258 -1.459477 1.446491e-01
sexMale      0.094320479 0.0225358310  4.185356 3.017253e-05</code></pre>
</div>
</div>
</section>
<section id="derive-the-distribution-of-the-test-statistic-under-the-null-via" class="slide level2">
<h2>2. Derive the distribution of the test statistic under the null via</h2>
<p>Two approaches:</p>
<ul>
<li class="fragment"><p>Simulation: Calculate test statistics in a world where <span class="math inline">\(H_0\)</span> is true</p></li>
<li class="fragment"><p>Asymptotic theory: Use statistics to approximate this distribution</p></li>
</ul>
</section>
<section id="derive-the-distribution-of-the-test-statistic-under-the-null" class="slide level2">
<h2>2. Derive the distribution of the test statistic under the null</h2>
<p>We can make the null true, by <strong>randomly permuting</strong> (sampling without replacement) the outcome of our model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="co"># One perumtation</span></span>
<span id="cb36-2"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb36-3"><a></a>df_drww<span class="sc">$</span>support_war01_null <span class="ot">&lt;-</span> <span class="fu">sample</span>(df_drww<span class="sc">$</span>support_war01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our permuted outcome is now uncorrelated with any predictors, it’s just a random sample of 0s, and 1s.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">cor</span>(df_drww<span class="sc">$</span>support_war01, df_drww<span class="sc">$</span>age, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3093656</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a><span class="fu">cor</span>(df_drww<span class="sc">$</span>support_war01_null, df_drww<span class="sc">$</span>age, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0005132924</code></pre>
</div>
</div>
</section>
<section id="derive-the-distribution-of-the-test-statistic-under-the-null-1" class="slide level2">
<h2>2. Derive the distribution of the test statistic under the null</h2>
<p>As such when we estimate a model with data where we have made our null hypothesis true (e.g <span class="math inline">\(\beta = 0\)</span> for all predictors), we get coefficients that are close to 0. Of course, by chance some might be a little negative, or a little positive.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a>m1_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(support_war01_null <span class="sc">~</span> age <span class="sc">+</span> education_n <span class="sc">+</span> sex, df_drww)</span>
<span id="cb41-2"><a></a></span>
<span id="cb41-3"><a></a><span class="fu">tidy</span>(m1_null)<span class="sc">%&gt;%</span><span class="fu">mutate_if</span>(is.numeric, round,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term        estimate std.error statistic p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)     0.74      0.05     13.6     0   
2 age             0         0        -0.07    0.94
3 education_n    -0.01      0.01     -0.8     0.43
4 sexMale         0.02      0.02      0.65    0.52</code></pre>
</div>
</div>
</section>
<section id="derive-the-distribution-of-the-test-statistic-under-the-null-2" class="slide level2">
<h2>2. Derive the distribution of the test statistic under the null</h2>
<p>The logic of hypothesis testing is to compare what we observed, to what we could have observed when our null is true.</p>
<p>By repeatedly permuting our outcome, estimating models, caclulating test statistics to generate the distributions <strong>under the null</strong></p>
<p>To do this, we’ll write a function to make our life easier:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>my_null_fn <span class="ot">&lt;-</span> <span class="cf">function</span>(</span>
<span id="cb43-2"><a></a>  <span class="at">df=</span>df_drww, </span>
<span id="cb43-3"><a></a>  <span class="at">y =</span> <span class="st">"support_war01"</span>, </span>
<span id="cb43-4"><a></a>  <span class="at">f =</span> <span class="fu">formula</span>(m1)</span>
<span id="cb43-5"><a></a>  ){</span>
<span id="cb43-6"><a></a>  df[, y] <span class="ot">&lt;-</span> <span class="fu">sample</span>(df[,y])</span>
<span id="cb43-7"><a></a>  m <span class="ot">&lt;-</span> <span class="fu">lm</span>(f, df)</span>
<span id="cb43-8"><a></a>  stat <span class="ot">&lt;-</span> <span class="fu">summary</span>(m)<span class="sc">$</span>coef[,<span class="dv">3</span>]</span>
<span id="cb43-9"><a></a>  <span class="fu">return</span>(stat)</span>
<span id="cb43-10"><a></a>}</span>
<span id="cb43-11"><a></a><span class="fu">my_null_fn</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age education_n     sexMale 
 11.0493734   1.8113230   0.9787517   0.6637328 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a><span class="fu">my_null_fn</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age education_n     sexMale 
 13.8126681   0.3840811  -1.4405531  -0.9781048 </code></pre>
</div>
</div>
</section>
<section id="derive-the-distribution-of-the-test-statistic-under-the-null-3" class="slide level2">
<h2>2. Derive the distribution of the test statistic under the null</h2>
<p>Then we’ll use the <code>replicate()</code> function to repeat this process 1000, saving the distribution of test statistics <span class="math inline">\(((\hat{\beta}-\beta)/se_\beta)\)</span> to an object called <code>m1_null</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb47-2"><a></a>m1_null <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">t</span>(</span>
<span id="cb47-3"><a></a>  <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">my_null_fn</span>(df_drww, <span class="st">"support_war01"</span>,<span class="fu">formula</span>(m1)))))</span>
<span id="cb47-4"><a></a><span class="fu">head</span>(m1_null)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X.Intercept.         age education_n    sexMale
1     13.58601 -0.06917489  -0.7952217  0.6460818
2     11.04937  1.81132298   0.9787517  0.6637328
3     13.81267  0.38408113  -1.4405531 -0.9781048
4     13.15015  0.04525689  -0.9986349  1.0681923
5     13.41492 -0.59487147   0.4026906 -1.5637179
6     13.43857 -1.11574477   0.3126860 -0.7188458</code></pre>
</div>
</div>
</section>
<section id="derive-the-distribution-of-the-test-statistic-under-the-null-4" class="slide level2">
<h2>2. Derive the distribution of the test statistic under the null</h2>
<p>We can visualize this distribution of test statistics for the <code>education_n</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a>m1_null <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(education_n))<span class="sc">+</span></span>
<span id="cb49-3"><a></a>  <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb49-4"><a></a>  <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb49-5"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb49-6"><a></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<img data-src="11-slides-old_files/figure-html/unnamed-chunk-29-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="compare-permutation-distribution-to-asymptotic-t-distribution" class="slide level2">
<h2>2. Compare Permutation Distribution to Asymptotic t-Distribution</h2>
<p>This simulated distribution (grey) can be approximated by a <span class="math inline">\(t\)</span> distribution (black), with <span class="math inline">\(n\)</span> (the number of observations) minus <span class="math inline">\(k\)</span> (the number of coefficients in our model) degrees of freedom.</p>
<ul>
<li class="fragment">Roughly, you can think of “degrees of freedom” as a way of reflecting the fact that we have to estimate parameters of the distribution, and so we use up pieces of information (degrees of freedom),</li>
<li class="fragment">Because we’re estimating parameters our uncertainty (the spread of the distribution) increases as the degrees of freedom decreases</li>
<li class="fragment">For a small <span class="math inline">\(N\)</span> reducing degrees of freedom, can increase uncertainty a lot</li>
<li class="fragment">For a large <span class="math inline">\(N\)</span> the differences are minute</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a>m1_null <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(education_n))<span class="sc">+</span></span>
<span id="cb50-3"><a></a>  <span class="fu">geom_density</span>(<span class="at">col =</span> <span class="st">"grey"</span>)<span class="sc">+</span></span>
<span id="cb50-4"><a></a>  <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb50-5"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb50-6"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span>dt,<span class="at">args =</span><span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df.residual), <span class="co">#&lt;&lt;</span></span>
<span id="cb50-7"><a></a>                <span class="at">xlim =</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>))<span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb50-8"><a></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<img data-src="11-slides-old_files/figure-html/unnamed-chunk-31-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="compare-the-test-statistic-to-the-distribution-assuming-the-null-were-true" class="slide level2">
<h2>3. Compare the test statistic to the distribution assuming the null were true</h2>
<p>Next we’ll compare our observed test statistic -1.45 to its hypothesized distribution under the null</p>
<ul>
<li class="fragment">For a two sided test, we interested in absolute distance from the null, so we’ll put lines at both -1.45 and 1.45</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a>m1_null <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(education_n))<span class="sc">+</span></span>
<span id="cb51-3"><a></a>  <span class="fu">geom_density</span>(<span class="at">col =</span> <span class="st">"grey"</span>)<span class="sc">+</span></span>
<span id="cb51-4"><a></a>  <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb51-5"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb51-6"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span>dt,<span class="at">args =</span><span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df.residual),</span>
<span id="cb51-7"><a></a>                <span class="at">xlim =</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>))<span class="sc">+</span></span>
<span id="cb51-8"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span>t_stat[<span class="st">"education_n"</span>], <span class="at">linetype =</span> <span class="dv">3</span>)<span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb51-9"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span>t_stat[<span class="st">"education_n"</span>]<span class="sc">*-</span><span class="dv">1</span>, <span class="at">linetype =</span> <span class="dv">3</span>)<span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb51-10"><a></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<img data-src="11-slides-old_files/figure-html/unnamed-chunk-33-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="calculate-p-value" class="slide level2">
<h2>4. Calculate p-value</h2>
<p>To quantify how often we would see test statistics as big or bigger, we can simply take the mean of a logical comparison of the absolute value of the test statistics under the null greater than the absolute value of our observed test statistic</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a><span class="co"># Simulation</span></span>
<span id="cb52-2"><a></a><span class="fu">mean</span>(<span class="fu">abs</span>(m1_null<span class="sc">$</span>education_n) <span class="sc">&gt;</span> <span class="fu">abs</span>(t_stat[<span class="st">"education_n"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.145</code></pre>
</div>
</div>
<p>Or, we can calculate the area under the curve for a <span class="math inline">\(t\)</span>-distribution, as with 1459 degrees of freedom, that is less than -1.45 and multiply this by 2 (because the distribution is symetric), to get the p-value</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a></a><span class="co"># Asymptotic</span></span>
<span id="cb54-2"><a></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t_stat[<span class="st">"education_n"</span>], m1<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>education_n 
  0.1446491 </code></pre>
</div>
</div>
</section>
<section id="calculate-p-value-1" class="slide level2">
<h2>4. Calculate p-value</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a></a><span class="co"># Asymptotic</span></span>
<span id="cb56-2"><a></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t_stat[<span class="st">"education_n"</span>], m1<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>education_n 
  0.1446491 </code></pre>
</div>
</div>
<p>Os exactly what R’s <code>summary()</code> function returns:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a></a><span class="co"># R's summary</span></span>
<span id="cb58-2"><a></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coef[<span class="dv">4</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Estimate   Std. Error      t value     Pr(&gt;|t|) 
9.432048e-02 2.253583e-02 4.185356e+00 3.017253e-05 </code></pre>
</div>
</div>
<p>Visually, these calculations look like this:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a></a>m1_null <span class="sc">%&gt;%</span></span>
<span id="cb60-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(education_n))<span class="sc">+</span></span>
<span id="cb60-3"><a></a>  <span class="fu">geom_density</span>(<span class="at">col=</span><span class="st">"grey"</span>)<span class="sc">+</span></span>
<span id="cb60-4"><a></a>  <span class="fu">geom_rug</span>(<span class="at">col =</span> <span class="fu">ifelse</span>(<span class="fu">abs</span>(m1_null<span class="sc">$</span>education_n) <span class="sc">&gt;=</span> <span class="fu">abs</span>(t_stat[<span class="st">"education_n"</span>]), <span class="st">"red"</span>,<span class="st">"black"</span>))<span class="sc">+</span> <span class="co">#&lt;&lt;</span></span>
<span id="cb60-5"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span><span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb60-6"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span>t_stat[<span class="st">"education_n"</span>], <span class="at">linetype =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb60-7"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span>t_stat[<span class="st">"education_n"</span>]<span class="sc">*-</span><span class="dv">1</span>, <span class="at">linetype =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb60-8"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span>dt,<span class="at">args =</span><span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df.residual),</span>
<span id="cb60-9"><a></a>                <span class="at">xlim =</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>))<span class="sc">+</span></span>
<span id="cb60-10"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span>dt,<span class="at">args =</span><span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df.residual), <span class="co">#&lt;&lt;</span></span>
<span id="cb60-11"><a></a>                <span class="at">geom =</span><span class="st">"area"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>,t_stat[<span class="st">"education_n"</span>]),<span class="co">#&lt;&lt;</span></span>
<span id="cb60-12"><a></a>                <span class="at">alpha =</span> .<span class="dv">5</span>,<span class="at">fill =</span><span class="st">"red"</span>)<span class="sc">+</span><span class="co">#&lt;&lt;</span></span>
<span id="cb60-13"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span>dt, <span class="at">args =</span><span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df.residual), <span class="co">#&lt;&lt;</span></span>
<span id="cb60-14"><a></a>                <span class="at">geom =</span><span class="st">"area"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">abs</span>(t_stat[<span class="st">"education_n"</span>]),<span class="fl">3.5</span>),<span class="co">#&lt;&lt;</span></span>
<span id="cb60-15"><a></a>                <span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">fill =</span><span class="st">"red"</span>)<span class="sc">+</span><span class="co">#&lt;&lt;</span></span>
<span id="cb60-16"><a></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<img data-src="11-slides-old_files/figure-html/unnamed-chunk-39-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="reject-or-fail-to-rejectretain-our-hypothesis" class="slide level2">
<h2>Reject or fail to reject/retain our hypothesis</h2>
<p>For an estimated p-value of 0.145 for coefficient on <code>education_n</code> and a significance threshold of p &lt; 0.05, we would…</p>
<p>–</p>
<p>Fail to reject the null hypothesis that <span class="math inline">\(H_0: \beta_{education} = 0\)</span></p>
<p>Because in a world where the truth was <span class="math inline">\(\beta_{education} = 0\)</span> test statistics reflecting coefficients as far as <span class="math inline">\(t-stat = |-1.459|\)</span> about 14.5 percent of the time.</p>
<p>If we were to reject the null, 14.5 percent of the time, we would be making a Type-1 error | False Positive | concluding there was a relationship when in fact their wasn’t.</p>
<p>class:inverse, middle, center # Break</p>
<p>class:inverse, middle, center # Final Projects</p>
</section>
<section id="timelines-this-week" class="slide level2">
<h2>Timelines: This Week</h2>
<p><strong>NOTE: I’m leaving these slides in for nw</strong></p>
<ul>
<li class="fragment"><p>Feedback on Data today</p></li>
<li class="fragment"><p>Questions/office hours today tomorrow/by appointment</p></li>
<li class="fragment"><p>Thursday: Work on analyzing your data</p></li>
<li class="fragment"><p>Drafts are still due April 24th.</p></li>
<li class="fragment"><p>Your draft need not, and probably will not, be a completed project.</p></li>
<li class="fragment"><p>At a minimum what you want is:</p>
<ul>
<li class="fragment">A clean data set</li>
<li class="fragment">Exploratory descriptives</li>
<li class="fragment">Initial results</li>
</ul></li>
<li class="fragment"><p>The rest can come later. Our goal on Thursday is to move you from the data portions of your projects, into the analysis.</p></li>
</ul>
</section>
<section id="timelines-next-week" class="slide level2">
<h2>Timelines: Next Week</h2>
<ul>
<li class="fragment"><p>Tuesday, April 26: Workshop: Review and Presentations</p></li>
<li class="fragment"><p>Thursday April 28: Workshop: Producing Presentations</p>
<ul>
<li class="fragment">7-10 Slides</li>
<li class="fragment">Drafts/Analysis, just need to fill those slides</li>
</ul></li>
<li class="fragment"><p>Sunday, May 1: Presentations due (Monday at the latests)</p></li>
</ul>
</section>
<section id="timelines-first-week-of-may" class="slide level2">
<h2>Timelines: First Week of May:</h2>
<ul>
<li class="fragment"><p>Tuesday, May 3: Presentations</p></li>
<li class="fragment"><p>Thursday, May 5: Last class and Food?</p>
<ul>
<li class="fragment">Class at Dolores at 5pm?</li>
<li class="fragment">Bagels/Treats in class</li>
</ul></li>
<li class="fragment"><p>Sunday May 8: Final Papers Due</p></li>
</ul>
</section>
<section id="strucutre-of-final-paper-and-drafts" class="slide level2 scrollable">
<h2>Strucutre of Final Paper and Drafts:</h2>
<p>Seven sections:</p>
<ol type="1">
<li class="fragment">Introduction (5 percent, ~ 4 paragraphs)</li>
<li class="fragment">Theory and Expectations (10 percent, ~4+ paragraphs)</li>
<li class="fragment">Data (20 percent ~ 4+ paragraphs)</li>
<li class="fragment">Design (25 percent ~ 5+ paragraphs)</li>
<li class="fragment">Results (25 percent ~ 5+ paragraphs)</li>
<li class="fragment">Conclusion (5 percent ~ 3+ paragraphs)</li>
<li class="fragment">Appendix (10 percent ~ Variable codebook and all the R code for your project)</li>
</ol>
</section>
<section id="focus-on-for-sunday" class="slide level2 scrollable">
<h2>Focus on for Sunday</h2>
<p>Seven sections:</p>
<ol type="1">
<li class="fragment">Introduction (5 percent, ~ 4 paragraphs)</li>
<li class="fragment">Theory and Expectations (10 percent, ~4+ paragraphs)</li>
<li class="fragment"><strong>Data</strong> (20 percent ~ 4+ paragraphs)</li>
<li class="fragment"><em>Design</em> (25 percent ~ 5+ paragraphs)</li>
<li class="fragment"><strong>Results</strong> (25 percent ~ 5+ paragraphs)</li>
<li class="fragment">Conclusion (5 percent ~ 3+ paragraphs)</li>
<li class="fragment">Appendix (10 percent ~ Variable codebook and all the R code for your project)</li>
</ol>
</section>
<section id="motivating-questions" class="slide level2">
<h2>Motivating Questions:</h2>
<p>In the reset of today’s class, we’ll get some practice putting together the various skills you need for your drafts by exploring the following:</p>
<ul>
<li class="fragment"><p>How does partisanship shape American’s perceptions of vaccines?</p></li>
<li class="fragment"><p>Who is skeptical of the benefits of vaccination?</p></li>
<li class="fragment"><p>Have these perceptions about vaccines changed over time?</p></li>
</ul>
</section>
<section id="tasks" class="slide level2">
<h2>Tasks:</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p>Get setup to work</p></li>
<li class="fragment"><p>Load our data</p></li>
<li class="fragment"><p>Recode our data</p></li>
<li class="fragment"><p>Summarize our data</p></li>
<li class="fragment"><p>Specify our expectations</p></li>
<li class="fragment"><p>Estimate models to test these expectations</p></li>
<li class="fragment"><p>Present and interpret results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals (review)</li>
<li class="fragment">Hypothesis tests (new!)</li>
</ul></li>
</ul>
<p>class:inverse, middle, center # 💪 ## Get set up to work</p>
</section>
<section id="new-packages-1" class="slide level2">
<h2>New packages</h2>
<p>To easily load survey data for our question, we’ll need the <code>anesr</code> package, which loads data from the American National Election Studies into R</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a><span class="co"># Uncomment to uninstall package to download NES survey data</span></span>
<span id="cb61-2"><a></a><span class="co"># library(devtools)</span></span>
<span id="cb61-3"><a></a><span class="co"># install_github("jamesmartherus/anesr")</span></span>
<span id="cb61-4"><a></a><span class="fu">require</span>(anesr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="packages-for-today-1" class="slide level2">
<h2>Packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb62-2"><a></a>  <span class="do">## R Markdown</span></span>
<span id="cb62-3"><a></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,</span>
<span id="cb62-4"><a></a>  <span class="do">## Tidyverse</span></span>
<span id="cb62-5"><a></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,<span class="st">"purrr"</span>,</span>
<span id="cb62-6"><a></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb62-7"><a></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb62-8"><a></a>  <span class="st">"GGally"</span>, <span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb62-9"><a></a>  <span class="co"># Graphics:</span></span>
<span id="cb62-10"><a></a>  <span class="st">"scatterplot3d"</span>, <span class="co">#&lt;&lt;</span></span>
<span id="cb62-11"><a></a>  <span class="co"># Data </span></span>
<span id="cb62-12"><a></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>, </span>
<span id="cb62-13"><a></a>  <span class="co"># Analysis</span></span>
<span id="cb62-14"><a></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"modelr"</span>, <span class="st">"zoo"</span></span>
<span id="cb62-15"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-a-function-to-load-and-if-needed-install-packages-1" class="slide level2">
<h2>Define a function to load (and if needed install) packages</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a></a>ipak <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb63-2"><a></a>    new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb63-3"><a></a>    <span class="cf">if</span> (<span class="fu">length</span>(new.pkg)) </span>
<span id="cb63-4"><a></a>        <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-5"><a></a>    <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-6"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-packages-for-today-1" class="slide level2">
<h2>Load packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a></a><span class="fu">ipak</span>(the_packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   kableExtra            DT        texreg     tidyverse     lubridate 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      forcats         haven      labelled         purrr         ggmap 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      ggrepel      ggridges      ggthemes        ggpubr        GGally 
         TRUE          TRUE          TRUE          TRUE          TRUE 
       scales       dagitty         ggdag       ggforce scatterplot3d 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      COVID19          maps       mapdata           qss    tidycensus 
         TRUE          TRUE          TRUE          TRUE          TRUE 
    dataverse DeclareDesign        modelr           zoo 
         TRUE          TRUE          TRUE          TRUE </code></pre>
</div>
</div>
<p>class:inverse, center, middle # 💪 ## Loading Data</p>
</section>
<section id="data" class="slide level2">
<h2>Data</h2>
<p>Now that we have <code>anesr</code> installed, let’s load data from the 2016 and 2020 National Election Studies:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a></a><span class="co"># Load data</span></span>
<span id="cb66-2"><a></a><span class="fu">data</span>(timeseries_2016, <span class="at">package =</span> <span class="st">"anesr"</span>)</span>
<span id="cb66-3"><a></a><span class="fu">data</span>(timeseries_2020, <span class="at">package =</span> <span class="st">"anesr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And copy those data frames into new dataframes with shorter names</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a></a><span class="co"># Rename datasets</span></span>
<span id="cb67-2"><a></a>nes16 <span class="ot">&lt;-</span> timeseries_2016</span>
<span id="cb67-3"><a></a>nes20 <span class="ot">&lt;-</span> timeseries_2020</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>class:inverse, center, middle # 💪 ## Recoding Data</p>
</section>
<section id="finding-variables-of-interest" class="slide level2">
<h2>Finding variables of interest</h2>
<p>Our primary outcome of interest are beliefs about vaccines.</p>
<p>Variables <code>V162162x</code> in the 2016 NES and <code>V202383x</code> in the 2020 NES will serve as our primary outcome of interest, summarizing respondents answer to the following question:</p>
<blockquote>
<p>Do the health benefits of vaccinations generally outweigh the risks, do the risks outweigh the benefits, or is there no difference?</p>
</blockquote>
<p>Similarly, <code>V161158x</code> in the 2016 NES and <code>V201231x</code> in the 2020 NES will serve our key predictor (respondent’s partisanship).</p>
<p>Finally, we’ll control respondents’ age, using <code>V161267</code> in the 2016 NES and <code>V201507x</code> in the 2020 NES</p>
<p>Let’s take a look at the values and distributions of these raw variables and think about what we need to do to recode these data so that they are suitable for analysis</p>
</section>
<section id="look-at-the-distribution-and-coding-of-our-outcome-vaccine-beliefs" class="slide level2">
<h2>Look at the distribution and coding of our outcome: Vaccine Beliefs</h2>
<p>The variables in the NES datasets are of a class <code>labelled</code> which allows numeric values to have substantive labels</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a></a><span class="fu">class</span>(nes16<span class="sc">$</span>V162162x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "haven_labelled"</code></pre>
</div>
</div>
<p>Our outcome variable has the following labels:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a></a>labelled<span class="sc">::</span><span class="fu">val_labels</span>(nes16<span class="sc">$</span>V162162x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   -9. Refused 
                                            -9 
                                -8. Don't know 
                                            -8 
-7. No post data, deleted due to incomplete IW 
                                            -7 
                -6. No post-election interview 
                                            -6 
                      1. Benefits much greater 
                                             1 
                2. Benefits moderately greater 
                                             2 
                  3. Benefits slightly greater 
                                             3 
                              4. No difference 
                                             4 
                     5. Risks slightly greater 
                                             5 
                   6. Risks moderately greater 
                                             6 
                         7. Risks much greater 
                                             7 </code></pre>
</div>
</div>
<p>And distribution of responses:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a></a><span class="fu">table</span>(nes16<span class="sc">$</span>V162162x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  -9   -8   -7   -6    1    2    3    4    5    6    7 
  21   28   86  536 1687  726  258  539   96  211   82 </code></pre>
</div>
</div>
</section>
<section id="recoding-our-outcome-variable" class="slide level2">
<h2>Recoding our outcome variable</h2>
<p>What transformations do we need to make to <code>V162162x</code> in <code>nes16</code> and <code>V202383x</code> in <code>nes20</code> so that these variables are suitable for analysis?</p>
<p>–</p>
<ul>
<li class="fragment">Recode negative values to be <code>NA</code></li>
</ul>
<p>–</p>
<ul>
<li class="fragment">Reverse code so that higher values indicate greater belief in the benefits of vaccines</li>
</ul>
<p>–</p>
<ul>
<li class="fragment">Create an indicator of people who are skeptical of the benefits of vaccines</li>
</ul>
</section>
<section id="recoding-v162162x-in-2016-nes" class="slide level2">
<h2>Recoding V162162x in 2016 NES</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a></a>nes16 <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb74-3"><a></a>    <span class="co"># Make Negative values NA, Reverse Code So Higher Values = Benefits &gt; Risks</span></span>
<span id="cb74-4"><a></a>    <span class="at">vaccine_benefits =</span> <span class="fu">ifelse</span>(V162162x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, (V162162x<span class="dv">-8</span>)<span class="sc">*-</span><span class="dv">1</span>),</span>
<span id="cb74-5"><a></a>    <span class="co"># Indicator of vaccine skepticism (Risks &gt; Benefits)</span></span>
<span id="cb74-6"><a></a>    <span class="at">vaccine_skeptic01 =</span> <span class="fu">case_when</span>(</span>
<span id="cb74-7"><a></a>      vaccine_benefits <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb74-8"><a></a>      vaccine_benefits <span class="sc">&lt;=</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb74-9"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb74-10"><a></a>    )</span>
<span id="cb74-11"><a></a>  ) <span class="ot">-&gt;</span> nes16 <span class="co"># Save recodes to nes16</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recoding-v202383x-in-2020-nes" class="slide level2">
<h2>Recoding V202383x in 2020 NES</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a></a>nes20 <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb75-3"><a></a>    <span class="co"># Make Negative values NA, Reverse Code So Higher Values = Benefits &gt; Risks</span></span>
<span id="cb75-4"><a></a>    <span class="at">vaccine_benefits =</span> <span class="fu">ifelse</span>(V202383x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, (V202383x<span class="dv">-8</span>)<span class="sc">*-</span><span class="dv">1</span>),</span>
<span id="cb75-5"><a></a>    <span class="co"># Indicator of vaccine skepticism (Risks &gt; Benefits)</span></span>
<span id="cb75-6"><a></a>    <span class="at">vaccine_skeptic01 =</span> <span class="fu">case_when</span>(</span>
<span id="cb75-7"><a></a>      vaccine_benefits <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb75-8"><a></a>      vaccine_benefits <span class="sc">&lt;=</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb75-9"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb75-10"><a></a>    )</span>
<span id="cb75-11"><a></a>  ) <span class="ot">-&gt;</span> nes20 <span class="co"># Save recodes to nes20</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recoding-predictors" class="slide level2">
<h2>Recoding Predictors</h2>
<p>Now we repeat this process for our key predictor, partisanship.</p>
<ul>
<li class="fragment"><p>Recode the the summary partisanship variables <code>V161158x</code> in <code>nes16</code> and <code>V201231x</code> in <code>nes20</code></p></li>
<li class="fragment"><p>Create indicators from this recoded variable that classify partisanship as categorical variable (with Democrats as the reference category)</p></li>
</ul>
<p>And our covariate, age variables <code>V161267</code> in <code>nes16</code> and <code>V201507x</code> in <code>nes20</code></p>
<ul>
<li class="fragment">Recode negative values to be <code>NA</code></li>
</ul>
</section>
<section id="recoding-partisanship-v161158x-in-2016-nes" class="slide level2">
<h2>Recoding Partisanship (V161158x) in 2016 NES</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a></a>nes16 <span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb76-3"><a></a>    <span class="at">pid =</span> <span class="fu">ifelse</span>(V161158x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V161158x),</span>
<span id="cb76-4"><a></a>    <span class="at">pid3cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb76-5"><a></a>      pid <span class="sc">&lt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Democrat"</span>,</span>
<span id="cb76-6"><a></a>      pid <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Independent"</span>,</span>
<span id="cb76-7"><a></a>      pid <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Republican"</span>,</span>
<span id="cb76-8"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Independent"</span></span>
<span id="cb76-9"><a></a>    ) <span class="sc">%&gt;%</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>,<span class="st">"Independent"</span>,<span class="st">"Republican"</span>)),</span>
<span id="cb76-10"><a></a>    <span class="at">age =</span> <span class="fu">ifelse</span>(V161267 <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V161267)</span>
<span id="cb76-11"><a></a>  ) <span class="ot">-&gt;</span> nes16</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recoding-partisanship-v201231x-in-2020-nes" class="slide level2">
<h2>Recoding Partisanship (V201231x) in 2020 NES</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a></a>nes20 <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb77-3"><a></a>    <span class="at">pid =</span> <span class="fu">ifelse</span>(V201231x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V201231x),</span>
<span id="cb77-4"><a></a>    <span class="at">pid3cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb77-5"><a></a>      pid <span class="sc">&lt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Democrat"</span>,</span>
<span id="cb77-6"><a></a>      pid <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Independent"</span>,</span>
<span id="cb77-7"><a></a>      pid <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Republican"</span>,</span>
<span id="cb77-8"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Independent"</span></span>
<span id="cb77-9"><a></a>    ) <span class="sc">%&gt;%</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>,<span class="st">"Independent"</span>,<span class="st">"Republican"</span>)),</span>
<span id="cb77-10"><a></a>    <span class="at">age =</span> <span class="fu">ifelse</span>(V201507x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V201507x)</span>
<span id="cb77-11"><a></a>  ) <span class="ot">-&gt;</span> nes20</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="progress-report" class="slide level2">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><strong>Summarize our data</strong>📥</p></li>
<li class="fragment"><p>Specify our expectations</p></li>
<li class="fragment"><p>Estimate models to test these expectations</p></li>
<li class="fragment"><p>Presenting and interpreting results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals (review)</li>
<li class="fragment">Hypothesis tests (new!)</li>
</ul></li>
</ul>
<p>class:inverse, center, middle # 💪 ## Summarizing data</p>
</section>
<section id="tables-of-descriptive-statistics" class="slide level2 scrollable">
<h2>Tables of descriptive statistics</h2>
<ol type="1">
<li class="fragment"><p>Create a object with the names of the variables you want to summarize</p></li>
<li class="fragment"><p>Select these variables</p></li>
<li class="fragment"><p>Pivot the data</p></li>
<li class="fragment"><p>Calculate summary statistics</p></li>
<li class="fragment"><p>Format as an html table</p></li>
</ol>
</section>
<section id="tables-of-descriptive-statistics-1" class="slide level2">
<h2>Tables of descriptive statistics</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a></a><span class="co"># 1. Create a object with the names of the variables you want to summarize</span></span>
<span id="cb78-2"><a></a>the_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"vaccine_skeptic01"</span>,<span class="st">"pid"</span>,<span class="st">"age"</span>)</span>
<span id="cb78-3"><a></a><span class="co"># 2. Select these variables</span></span>
<span id="cb78-4"><a></a>nes16 <span class="sc">%&gt;%</span></span>
<span id="cb78-5"><a></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(the_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb78-6"><a></a><span class="co"># 3. Pivot the data</span></span>
<span id="cb78-7"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb78-8"><a></a>    <span class="at">cols =</span> <span class="fu">all_of</span>(the_vars),</span>
<span id="cb78-9"><a></a>    <span class="at">names_to =</span> <span class="st">"Variable"</span></span>
<span id="cb78-10"><a></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb78-11"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb78-12"><a></a>    <span class="at">Variable =</span> <span class="fu">factor</span>(Variable, <span class="at">levels =</span> the_vars)</span>
<span id="cb78-13"><a></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb78-14"><a></a>  <span class="fu">arrange</span>(Variable)<span class="sc">%&gt;%</span></span>
<span id="cb78-15"><a></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Variable)<span class="sc">%&gt;%</span></span>
<span id="cb78-16"><a></a>  <span class="co"># 3. Calculate summary statistics</span></span>
<span id="cb78-17"><a></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb78-18"><a></a>    <span class="at">min =</span> <span class="fu">min</span>(value, <span class="at">na.rm=</span>T),</span>
<span id="cb78-19"><a></a>    <span class="at">p25 =</span> <span class="fu">quantile</span>(value, <span class="at">na.rm=</span>T, <span class="at">prob =</span> <span class="fl">0.25</span>),</span>
<span id="cb78-20"><a></a>    <span class="at">Median =</span> <span class="fu">quantile</span>(value, <span class="at">na.rm=</span>T, <span class="at">prob =</span> <span class="fl">0.5</span>),</span>
<span id="cb78-21"><a></a>    <span class="at">mean =</span> <span class="fu">mean</span>(value, <span class="at">na.rm=</span>T),</span>
<span id="cb78-22"><a></a>    <span class="at">p75 =</span> <span class="fu">quantile</span>(value, <span class="at">na.rm=</span>T, <span class="at">prob =</span> <span class="fl">0.25</span>),</span>
<span id="cb78-23"><a></a>    <span class="at">max =</span> <span class="fu">max</span>(value, <span class="at">na.rm=</span>T),</span>
<span id="cb78-24"><a></a>    <span class="at">missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(value))</span>
<span id="cb78-25"><a></a>  ) <span class="ot">-&gt;</span> sum_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="format-table" class="slide level2">
<h2>Format Table</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a></a>knitr<span class="sc">::</span><span class="fu">kable</span>(sum_tab,</span>
<span id="cb79-2"><a></a>             <span class="at">caption =</span> <span class="st">"Descriptive Statistics"</span>,</span>
<span id="cb79-3"><a></a>             <span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb79-4"><a></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb79-5"><a></a>  kableExtra<span class="sc">::</span><span class="fu">pack_rows</span>(<span class="st">"Outcome"</span>, <span class="at">start_row =</span> <span class="dv">1</span>, <span class="at">end_row =</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb79-6"><a></a>  kableExtra<span class="sc">::</span><span class="fu">pack_rows</span>(<span class="st">"Key Predictors"</span>, <span class="at">start_row =</span> <span class="dv">2</span>, <span class="at">end_row =</span><span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb79-7"><a></a>  kableExtra<span class="sc">::</span><span class="fu">pack_rows</span>(<span class="st">"Covariates"</span>, <span class="at">start_row =</span> <span class="dv">3</span>, <span class="at">end_row =</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<caption>Descriptive Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p25</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p75</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="1">
<td colspan="8" style="border-bottom: 1px solid"><strong>Outcome</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">vaccine_skeptic01</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">671</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="8" style="border-bottom: 1px solid"><strong>Key Predictors</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">pid</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="8" style="border-bottom: 1px solid"><strong>Covariates</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">age</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">49.58</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">121</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="progress-report-1" class="slide level2">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><em>Summarize our data</em> ✅</p></li>
<li class="fragment"><p><strong>Specify our expectations</strong> 📥</p></li>
<li class="fragment"><p>Estimate models to test these expectations</p></li>
<li class="fragment"><p>Presenting and interpreting results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals (review)</li>
<li class="fragment">Hypothesis tests (new!)</li>
</ul></li>
</ul>
<p>class:inverse, center, middle # 💪 ## Specificying Expecations</p>
</section>
<section id="specificying-expecations" class="slide level2">
<h2>Specificying Expecations</h2>
<p>Consider our first two motivating questions</p>
<ul>
<li class="fragment"><p>How does partisanship shape American’s perceptions of vaccines?</p></li>
<li class="fragment"><p>Who is skeptical of the benefits of vaccination?</p></li>
</ul>
<p>And some illustrative stereotypes:</p>
<ul>
<li class="fragment">“Republicans are <em>anti-science</em>”</li>
<li class="fragment">“Liberal always for Goopy <em>pseudo-science</em>”</li>
<li class="fragment">“Independents love to <em>do their own research</em>”</li>
</ul>
<p>What are the empirical implications of these claims?</p>
</section>
<section id="specificying-expecations-1" class="slide level2">
<h2>Specificying Expecations</h2>
<p>Similarly, consider our third question:</p>
<ul>
<li class="fragment">Have these perceptions about vaccines changed over time?</li>
</ul>
<p>And some similar simplified claims:</p>
<ul>
<li class="fragment">“The Covid-19 vaccine is a miracle of modern science”</li>
<li class="fragment">“Social media is rife with misinformation about the Covid-19 vaccine”</li>
<li class="fragment">“Politicians are politicizing vaccine politics for political benefits”</li>
</ul>
<p>What are the empirical implications of these claims?</p>
</section>
<section id="specificying-expecations-2" class="slide level2">
<h2>Specificying Expecations</h2>
<p>Our goal is to take claims/conventional wisdom/theories, and derive their empirical implications:</p>
<ul>
<li class="fragment"><strong>H1: Partisan Differences in Vaccine Skepticism</strong>
<ul>
<li class="fragment"><strong>H1a:</strong> Republicans will be the most skeptical of vaccines</li>
<li class="fragment"><strong>H1b:</strong> Democrats will be the most skeptical of vaccines</li>
<li class="fragment"><strong>H1a:</strong> Independents will be the most skeptical of vaccines</li>
</ul></li>
<li class="fragment"><strong>H2: Temporal Differences in Vaccine Skepticism</strong>
<ul>
<li class="fragment"><strong>H2a:</strong> Vaccine skepticism will decrease from 2016 to 2020 with the widespread roll out of the Covid-19 vaccine</li>
<li class="fragment"><strong>H2b:</strong> Vaccine skepticism will increase from 2016 to 2020 with increased amounts of misinformation about the Covid-19 vaccine</li>
</ul></li>
<li class="fragment"><strong>H3: Partisan Difference in Vaccine Skepticism Over Time</strong> Partisan differences in Vaccine Skepticism will increase from 2016 to 2020 with the politicization of Covid-19 policies</li>
</ul>
</section>
<section id="motivating-your-expectations." class="slide level2">
<h2>Motivating your expectations.</h2>
<p>In your papers, unlike in these slides, your expectations should be grounded in existing theory, research, and evidence. For the present question, we might cite sources such as:</p>
<ul>
<li class="fragment"><p>Enders, Adam M., and Steven M. Smallpage. “Informational cues, partisan-motivated reasoning, and the manipulation of conspiracy beliefs.” Political Communication 36.1 (2019): 83-102.</p></li>
<li class="fragment"><p>Stecula, Dominik A., and Mark Pickup. “How populism and conservative media fuel conspiracy beliefs about COVID-19 and what it means for COVID-19 behaviors.” Research &amp; Politics 8.1 (2021): 2053168021993979.</p></li>
<li class="fragment"><p>Jennings, Will, et al.&nbsp;“Lack of trust, conspiracy beliefs, and social media use predict COVID-19 vaccine hesitancy.” Vaccines 9.6 (2021): 593.</p></li>
<li class="fragment"><p>Hollander, Barry A. “Partisanship, individual differences, and news media exposure as predictors of conspiracy beliefs.” Journalism &amp; Mass Communication Quarterly 95.3 (2018): 691-713.</p></li>
</ul>
</section>
<section id="model-specification" class="slide level2">
<h2>Model Specification</h2>
<p>Translate these expectations into empirical models requires choices about <strong>how to specify our models</strong></p>
<p>–</p>
<ul>
<li class="fragment"><p>How should we measure/operationalize our outcome</p>
<ul>
<li class="fragment">Should we measure beliefs about vaccines with 7-point ordinal scale or as a binary indicator of vaccine skepticism</li>
</ul></li>
<li class="fragment"><p>How should we measure/operationalize our key predictor(s)</p>
<ul>
<li class="fragment">Should we measure partisanship using a 7 point scale or as categorical variable?</li>
</ul></li>
<li class="fragment"><p>What should we control for in our model?</p>
<ul>
<li class="fragment">Factors likely to predict both our outcome and our key predictor of interest</li>
</ul></li>
</ul>
<p>–</p>
<ul>
<li class="fragment"><p>There are rarely definitive answers to these questions.</p></li>
<li class="fragment"><p>In practice, we will often estimate <strong>multiple models</strong> to try and show that our findings are <strong>robust</strong> to alternative modeling strategies/specifications</p></li>
</ul>
</section>
<section id="model-specification-1" class="slide level2 scrollable">
<h2>Model Specification</h2>
<p>For your projects, every group will almost surely estimate some form of the following:</p>
<ol type="1">
<li class="fragment"><p>Baseline bivariate model: The simplest test of the relationship between your outcome and key predictor</p></li>
<li class="fragment"><p>Multiple regression model: A test of the robustness of this relationship, controlling for alternative explanations</p></li>
</ol>
<p>In practice, I suspect you may estimate multiple regression models such as:</p>
<ul>
<li class="fragment"><p>Alternative specifications/operationalizations of outcomes and predictors</p></li>
<li class="fragment"><p>Interaction models to test conditional relationships</p></li>
<li class="fragment"><p>Polynomial models to test non-linear relationships</p></li>
</ul>
</section>
<section id="translating-theoretical-expectations-into-empirical-models" class="slide level2">
<h2>Translating Theoretical Expectations into Empirical Models</h2>
<p>Before we estimate our models in R, we will write down our models formally and empirical implications of our theoretical expectations in terms of the coefficients of our model.</p>
<p>For example, test for partisan differences in vaccine skepticism, we might fit the following baseline model:</p>
<p><span class="math display">\[\text{Vaccine Skepticism} = \beta_0 + \beta_1 \text{PID}_{7pt} + X\beta + \epsilon\]</span> - If <span class="math inline">\(\beta_1\)</span> is positive this is consistent with <strong>H1a</strong> (greater skepticism among Republicans), - If <span class="math inline">\(\beta_2\)</span> is negative this is consistent with <strong>H1b</strong> (greater skepticism among Democrats),</p>
<p>But how could we test <strong>H1c</strong> – greater skepticism among Independents, who are “4s” on <span class="math inline">\(\text{PID}_{7pt}\)</span>?</p>
</section>
<section id="translating-theoretical-expectations-into-empirical-models-1" class="slide level2">
<h2>Translating Theoretical Expectations into Empirical Models</h2>
<p>We could fit a polynomial regression, including both partisanship and partinaship squared to allow the relationship between partisanship and vaccine skepticism to vary non-linearly</p>
<p><span class="math display">\[\text{Vaccine Skepticism} = \beta_0 + \beta_1 \text{PID}_{7pt} +  \beta_2 \text{PID}_{7pt}^2+ X\beta+ \epsilon\]</span> Or we could estimate a model treating Partisanship as a <strong>categorical</strong> variable rather than an <strong>ordinal interval</strong> variable. In our recoding, we set <code>"Democrat"</code> to be the first level of the variable <code>pid3cat</code>, so the model R will estimate by default is:</p>
<p><span class="math display">\[\text{Vaccine Skepticism} = \beta_0 + \beta_1 \text{PID}_{Ind} +  \beta_2 \text{PID}_{Rep}+ X\beta + \epsilon\]</span></p>
</section>
<section id="testing-differences-over-time." class="slide level2">
<h2>Testing differences over time.</h2>
<p>Testing Hypotheses 2 and 3 involve making comparisons across models estimated on data from different surveys.</p>
<p>Formally, testing these expectations is a little more complicated</p>
<ul>
<li class="fragment">we could pool our two surveys together include an interaction term for survey year</li>
</ul>
<p>For our purposes, we’ll treat these as more qualitative/exploratory hypotheses:</p>
<ul>
<li class="fragment"><p>H2a/b implies overall rates of vaccine skepticism will be lower/higher in 2020 compared to 2016</p></li>
<li class="fragment"><p>H3 implies that whatever partisan differences we find in 2016 should be larger in 2020.</p></li>
</ul>
</section>
<section id="progress-report-2" class="slide level2">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><em>Specify our expectations</em> ✅</p></li>
<li class="fragment"><p><strong>Estimate models to test these expectations</strong> 📥</p></li>
<li class="fragment"><p>Presenting and interpreting results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals (review)</li>
<li class="fragment">Hypothesis tests (new!)</li>
</ul></li>
</ul>
<p>class:inverse, center, middle # 💪 ## Estimating Empirical Models</p>
</section>
<section id="estimating-empirical-models" class="slide level2">
<h2>Estimating Empirical Models</h2>
<p>Having derived empirical implications of our theoretical expectations expressed in terms of linear regressions, now we simply have to estimate our models in R.</p>
<p>When estimating the <strong>same model</strong> on <strong>different datasets</strong> we can write the formulas once</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a></a>f1 <span class="ot">&lt;-</span> <span class="fu">formula</span>(vaccine_skeptic01 <span class="sc">~</span> pid <span class="sc">+</span> age)</span>
<span id="cb80-2"><a></a>f2 <span class="ot">&lt;-</span> <span class="fu">formula</span>(vaccine_skeptic01 <span class="sc">~</span> pid <span class="sc">+</span> <span class="fu">I</span>(pid<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> age)</span>
<span id="cb80-3"><a></a>f3 <span class="ot">&lt;-</span> <span class="fu">formula</span>(vaccine_skeptic01 <span class="sc">~</span> pid3cat <span class="sc">+</span> age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="estimating-empirical-models-1" class="slide level2">
<h2>Estimating Empirical Models</h2>
<p>And then pass it to <code>lm()</code> with different <code>data</code> arguments:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a></a>m1_2016 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f1, <span class="at">data =</span> nes16)</span>
<span id="cb81-2"><a></a>m1_2020 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f1, <span class="at">data =</span> nes20)</span>
<span id="cb81-3"><a></a>m2_2016 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f2, <span class="at">data =</span> nes16)</span>
<span id="cb81-4"><a></a>m2_2020 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f2, <span class="at">data =</span> nes20)</span>
<span id="cb81-5"><a></a>m3_2016 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f3, <span class="at">data =</span> nes16)</span>
<span id="cb81-6"><a></a>m3_2020 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f3, <span class="at">data =</span> nes20)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="estimating-empirical-models-2" class="slide level2">
<h2>Estimating Empirical Models</h2>
<p>If you’ve</p>
<ul>
<li class="fragment"><p>coded your data correctly</p></li>
<li class="fragment"><p>developed clear testable implications from your theoretical expectations</p></li>
</ul>
<p>Specifying and estimating empirical models is straightforward. Literally a few lines of code.</p>
</section>
<section id="progress-report-3" class="slide level2">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><em>Specify our expectations</em> ✅</p></li>
<li class="fragment"><p><em>Estimate models to test these expectations</em> ✅</p></li>
<li class="fragment"><p><em>Present our results</em> 📥</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals (review)</li>
<li class="fragment">Hypothesis testing (new!)</li>
</ul></li>
</ul>
<p>class:inverse, center, middle # 💪 ## Presenting and Interpreting Your Results</p>
</section>
<section id="presenting-and-interpreting-your-results" class="slide level2">
<h2>Presenting and Interpreting Your Results</h2>
<p>Presenting and interpreting your results is requires both art and science.</p>
<p>Your goal is to tell a story with your results, walking your reader through the substantive and statsitical interpretation of tables and figures.</p>
<p>Let’s start by producing a regression table, which provides a concise summary of multiple regression models.</p>
<p>Like figures, producing a good regression table is an interactive process.</p>
</section>
<section id="regression-tables-with-htmlreg" class="slide level2">
<h2>Regression Tables with htmlreg</h2>
<p>The following code produces a basic regression table.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a></a>texreg<span class="sc">::</span><span class="fu">htmlreg</span>(</span>
<span id="cb82-2"><a></a>  <span class="fu">list</span>(m1_2016,m2_2016,m3_2016,</span>
<span id="cb82-3"><a></a>       m1_2020,m2_2020,m3_2020)</span>
<span id="cb82-4"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regression-tables-with-htmlreg-1" class="slide level2">
<h2>Regression Tables with htmlreg</h2>
<div class="cell" data-layout-align="center">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 2
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 3
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 4
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 5
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 6
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.46<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.35<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.42<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.34<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.32<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.35<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.04)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.06<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.01)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid^2
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.01<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid3catIndependent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.17<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.20<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid3catRepublican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.02
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.10<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.01)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.05
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
</section>
<section id="customizing-our-regression-table" class="slide level2">
<h2>Customizing our Regression Table</h2>
<p>Let’s make this regression table more reader friendly and informative by:</p>
<ul>
<li class="fragment"><p>Giving the variables in substantive names</p></li>
<li class="fragment"><p>Reporting coefficients to 3 decimal places</p></li>
<li class="fragment"><p>Using a single significance threshold of <span class="math inline">\(p &lt; 0.05\)</span></p></li>
<li class="fragment"><p>Giving the models custom names</p></li>
<li class="fragment"><p>Adding a header to group models by year</p></li>
<li class="fragment"><p>Changing the caption of the table</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a></a>texreg<span class="sc">::</span><span class="fu">htmlreg</span>(</span>
<span id="cb83-2"><a></a>  <span class="fu">list</span>(m1_2016,m2_2016,m3_2016,</span>
<span id="cb83-3"><a></a>       m1_2020,m2_2020,m3_2020),</span>
<span id="cb83-4"><a></a>  <span class="co"># Reporting coefficients to 3 decimal places</span></span>
<span id="cb83-5"><a></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb83-6"><a></a>  <span class="co"># Using a single significance threshold </span></span>
<span id="cb83-7"><a></a>  <span class="at">stars =</span> <span class="fl">0.05</span>,</span>
<span id="cb83-8"><a></a>  <span class="co"># Giving the variables in substantive names</span></span>
<span id="cb83-9"><a></a>  <span class="at">custom.coef.names =</span> <span class="fu">c</span>(</span>
<span id="cb83-10"><a></a>    <span class="st">"(Intercept)"</span>,</span>
<span id="cb83-11"><a></a>    <span class="st">"PID (7pt)"</span>,</span>
<span id="cb83-12"><a></a>    <span class="st">"Age"</span>,</span>
<span id="cb83-13"><a></a>    <span class="st">"PID&lt;sup&gt;2&lt;/sup&gt; (7pt)"</span>,</span>
<span id="cb83-14"><a></a>    <span class="st">"Independent"</span>,</span>
<span id="cb83-15"><a></a>    <span class="st">"Republican"</span></span>
<span id="cb83-16"><a></a>  ),</span>
<span id="cb83-17"><a></a>  <span class="co"># Giving the models custom names</span></span>
<span id="cb83-18"><a></a>  <span class="at">custom.model.names =</span> <span class="fu">paste</span>(<span class="st">"Model"</span>,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)),</span>
<span id="cb83-19"><a></a>  <span class="co"># Adding a header to group models by year</span></span>
<span id="cb83-20"><a></a>  <span class="at">custom.header =</span> <span class="fu">list</span>(<span class="st">"NES 2016"</span> <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="st">"NES 2020"</span> <span class="ot">=</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>),</span>
<span id="cb83-21"><a></a>  <span class="co"># Changing the caption of the table</span></span>
<span id="cb83-22"><a></a>  <span class="at">caption =</span> <span class="st">"Partisanship and Vaccine Skepticism"</span></span>
<span id="cb83-23"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Partisanship and Vaccine Skepticism
</caption>
<thead>
<tr>
<th>
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2016
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2020
</th>
</tr>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 1
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 2
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 3
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 4
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 5
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 6
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.458<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.350<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.417<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.343<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.318<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.352<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.025)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.035)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.018)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.024)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.005
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.064<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.037<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.003)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID<sup>2</sup> (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.009<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.002
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.001)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Independent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.175<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.200<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Republican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.016
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.100<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.023
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.028
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.022
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.027
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
</section>
<section id="telling-a-story-with-regression" class="slide level2">
<h2>Telling a Story with Regression</h2>
<p>First, provide an overview the models presented in the table</p>
<ul>
<li class="fragment">Explain what each model is doing conceptually</li>
</ul>
<p>Then, start with your simplest model (Typically the first column in your table).</p>
<ul>
<li class="fragment">Use this as a chance to explain core concepts from the course
<ul>
<li class="fragment">What is regression</li>
<li class="fragment">How should I interpret a coefficient substantively</li>
<li class="fragment">How should I interepret the statistical signficance of a give coefficient</li>
</ul></li>
<li class="fragment">As you move from left to right (simple to more complex)
<ul>
<li class="fragment">you need not interpret every single coefficient in the model</li>
<li class="fragment">instead highlight the factors that are important for the reader to note (e.g.&nbsp;a comparison between one coefficient in model or another.)</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Partisanship and Vaccine Skepticism
</caption>
<thead>
<tr>
<th>
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2016
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2020
</th>
</tr>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 1
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 2
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 3
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 4
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 5
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 6
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.458<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.350<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.417<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.343<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.318<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.352<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.025)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.035)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.018)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.024)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.005
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.064<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.037<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.003)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID<sup>2</sup> (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.009<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.002
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.001)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Independent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.175<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.200<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Republican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.016
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.100<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.023
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.028
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.022
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.027
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul>
<li class="fragment"><p>Table 1 presents the results of three specifications exploring the relationship between partisanship and vaccine skepticism using data from the 2016 (Models 1-3) and 2020 (Models 4-5) National Election Studies.</p></li>
<li class="fragment"><p>Models 1 and 4 operationalize partisanship as a 7-point scale, where 1 corresponds to Strong Democrats, 4 to Indepndents, and 7 to Strong Republicans in the 2016 (Model 1) and 2020 (Model 2) surveys.</p></li>
<li class="fragment"><p>Models 2 and 5 allow the relationship between partisanship and vaccine skepticism to vary non-linear again for the 2016 (Model 2) and 2020 (Model 5) elections.</p></li>
<li class="fragment"><p>Models 3 and 6 treat partisanship as categorical variable, describing how Independents and Republicans differ from Democrats, the reference category in these models.</p></li>
<li class="fragment"><p>All models control age, since (put in substantive justification for controlling for age here)</p></li>
</ul>
</section>
<section id="story-testing-for-partisan-differences" class="slide level2">
<h2>Story: Testing for Partisan Differences</h2>
<ul>
<li class="fragment"><p>The results from Model 1 provide little initial evidence for partisan differences in vaccine skepticism in the 2016 Election.</p>
<ul>
<li class="fragment">The coefficient on the partisanship variable is -0.005, suggesting that a unit increase in partisanship (going from being a Strong Democrat to just a Democrat, or an Independent to an independent who leans Republican), is associated with just a 0.5 percentage point increase in the probability of being a vaccine skeptic (believing that the risks of vaccination outweigh the benefits or that their is no difference in the risks versus benefits).</li>
</ul></li>
<li class="fragment"><p>Furthermore the 95-percent confidence interval for this estimate (-0.011, 0.002) brackets 0, suggesting the true population estimate from this model could be either positive or negative. Similarly, we fail to reject the null hypothesis that the true coefficient on partisanship in this model is 0 as the test statistic for this estimate ( -1.38) corresponds to a p-value of 0.168 suggesting that we would see test statistics this large or larger fairly often when the true relationship was 0.</p></li>
<li class="fragment"><p>In some the results from Model 1 provide little support for any of the expectations described by <em>H1</em></p></li>
</ul>
</section>
<section id="testing-for-partisan-differences-model-2" class="slide level2">
<h2>Testing for Partisan Differences: Model 2</h2>
<ul>
<li class="fragment">While coefficients from Model 1 suggest little evidence of partisan differences in vaccine skepticism, the coefficients on both partisanship, and partisanship squared are statistically significant (p &lt; 0.05).</li>
</ul>
</section>
<section id="interpreting-model-2" class="slide level2">
<h2>Interpreting Model 2</h2>
<ul>
<li class="fragment">The coefficients from polynomial regressions can be difficult to interpret jointly and so Figure 1 presents the predicted values from Model 2, holding age constant at its sample mean.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a></a>pred_df_m2 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb84-2"><a></a>  <span class="at">pid =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>,</span>
<span id="cb84-3"><a></a>  <span class="at">age =</span> <span class="fu">mean</span>(nes16<span class="sc">$</span>age, <span class="at">na.rm=</span>T)</span>
<span id="cb84-4"><a></a>)</span>
<span id="cb84-5"><a></a>pred_df_m2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_df_m2, <span class="fu">predict</span>(m2_2016,pred_df_m2, <span class="at">interval =</span><span class="st">"confidence"</span>))</span>
<span id="cb84-6"><a></a>pred_df_m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  pid      age       fit       lwr       upr
1   1 49.58231 0.2366157 0.2082979 0.2649335
2   2 49.58231 0.2743408 0.2551659 0.2935157
3   3 49.58231 0.2945841 0.2729532 0.3162151
4   4 49.58231 0.2973457 0.2738012 0.3208902
5   5 49.58231 0.2826255 0.2611041 0.3041469
6   6 49.58231 0.2504236 0.2300546 0.2707925
7   7 49.58231 0.2007398 0.1688900 0.2325897</code></pre>
</div>
</div>
</section>
<section id="interpreting-model-2-1" class="slide level2">
<h2>Interpreting Model 2</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a></a>pred_df_m2 <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(pid, fit, <span class="at">ymin =</span>lwr, <span class="at">ymax =</span>upr))<span class="sc">+</span></span>
<span id="cb86-3"><a></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb86-4"><a></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span>.<span class="dv">2</span>, <span class="at">fill=</span><span class="st">"grey"</span>)<span class="sc">+</span></span>
<span id="cb86-5"><a></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb86-6"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Partisanship"</span>,</span>
<span id="cb86-7"><a></a>       <span class="at">y =</span> <span class="st">"Predicted Vaccine Skepticism"</span>,</span>
<span id="cb86-8"><a></a>       <span class="at">title =</span> <span class="st">"Independents are the most skeptical of vaccines"</span>,</span>
<span id="cb86-9"><a></a>       <span class="at">subtitle =</span> <span class="st">"Data: 2016 NES"</span></span>
<span id="cb86-10"><a></a>       )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpreting-model-2-2" class="slide level2">
<h2>Interpreting Model 2</h2>
<ul>
<li class="fragment">We see from Model 2 that 29.7 percent [27.3%, 32.1%] of Independents in the 2016 NES were predicted to be vaccine skeptics compared to 23.7 percent [20.8%, 26.5%] of Strong Democrats and only 20.1 percent [16.9%, 23.3%] of Strong Republicans.</li>
</ul>

<img data-src="11-slides-old_files/figure-html/unnamed-chunk-65-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="testing-for-partisan-differences-model-3" class="slide level2">
<h2>Testing for Partisan Differences: Model 3</h2>
<p>Model 3 tells a similar story to model 2. Again, adjusting for differences in vaccine skepticism explained by age, Model 3 predicts that 41.7 percent [37.7%, 45.6%] of Independents in the 2016 NES are vaccine skeptics compared to 24.2 percent [22.1%, 26.2%] of Democrats, and 22.6 percent [20.4%, 24.8%] of Republicans.</p>
<p>Note the coefficients from Model 3 imply that the differences between Independents and Democrats are statistically significant (<span class="math inline">\(\beta_{Ind} = 0.175, p &lt; 0.05\)</span>), the differences between Republicans and Democrats are not (<span class="math inline">\(\beta_{Rep} = -0.004, p = 0.31\)</span>)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a></a>pred_df_m3 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb87-2"><a></a>  <span class="at">pid3cat =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>, <span class="st">"Independent"</span>,<span class="st">"Republican"</span>),</span>
<span id="cb87-3"><a></a>  <span class="at">age =</span> <span class="fu">mean</span>(nes16<span class="sc">$</span>age, <span class="at">na.rm=</span>T)</span>
<span id="cb87-4"><a></a>)</span>
<span id="cb87-5"><a></a>pred_df_m3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_df_m3, <span class="fu">predict</span>(m3_2016,pred_df_m3, <span class="at">interval =</span><span class="st">"confidence"</span>))</span>
<span id="cb87-6"><a></a>pred_df_m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      pid3cat      age       fit       lwr       upr
1    Democrat 49.58231 0.2419547 0.2211228 0.2627867
2 Independent 49.58231 0.4169043 0.3773539 0.4564547
3  Republican 49.58231 0.2261496 0.2038046 0.2484947</code></pre>
</div>
</div>
</section>
<section id="testing-for-differences-over-time" class="slide level2">
<h2>Testing for Differences Over Time</h2>
<p>The results for the 2016 NES suggest political independents are most skeptical of vaccines.</p>
<p>The results for 2020 suggest the relationship between partisanship and vaccine skepticism has changed overtime.</p>
<div class="cell" data-layout-align="center">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Partisanship and Vaccine Skepticism
</caption>
<thead>
<tr>
<th>
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2016
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2020
</th>
</tr>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 1
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 2
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 3
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 4
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 5
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Mod 6
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.458<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.350<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.417<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.343<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.318<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.352<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.025)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.035)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.018)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.024)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.005
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.064<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.037<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.003)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID<sup>2</sup> (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.009<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.002
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.001)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Independent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.175<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.200<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Republican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.016
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.100<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.023
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.028
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.022
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.027
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
<ul>
<li class="fragment"><p>The coefficient on partisanship in model 4 is now positive and statistically significant (p &lt; 0.05), suggesting that as respondents become more Republican, they are more likely to be skeptical of vaccines</p></li>
<li class="fragment"><p>The coefficients from Model 5 suggest the relationship between partisanship skepticism is non linear, which is confirmed by model 6.</p></li>
<li class="fragment"><p>In Model 6, we see that independents remain the most skeptical of vaccines in 2020 <span class="math inline">\((\beta = 0.20,\, p &lt;0.05)\)</span>, but that Republicans now tend to be more skeptical of vaccines than Democrats <span class="math inline">\((\beta = 0.10,\, p &lt;0.05)\)</span></p></li>
</ul>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/pols1600_hex.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>POLS 1600</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/josephessig-source\.github\.io\/pols1600_site\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>