{
  "hash": "99bea9a1bf9bf51b278486df68baebe9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"POLS 1600\"\nsubtitle: \"Interpreting and Evaluating<br>Linear Models\"\ndate: last-modified\ndate-format: \"[Updated ]MMM D, YYYY\"\nformat: \n  revealjs:\n    theme: brownslides.scss\n    logo: images/pols1600_hex.png\n    footer: \"POLS 1600\"\n    multiplex: false\n    transition: fade\n    slide-number: c\n    incremental: true\n    center: false\n    menu: true\n    scrollable: true\n    highlight-style: github\n    progress: true\n    html-math-method: mathjax\n    code-overflow: wrap\n    chalkboard: true\n    # include-after-body: title-slide.html\n    title-slide-attributes:\n      align: left\n      data-background-image: images/pols1600_hex.png\n      data-background-position: 90% 50%\n      data-background-size: 40%\nfilters:\n  - openlinksinnewpage\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# {{< fa map-location>}} Overview {.inverse}\n\n## Class Plan\n\n- Announcements \n- Topics:\n  - What does it mean to control for X\n  - How to make predictions with regression\n  - Evaluating model fit\n  - Difference-in-Differences\n  - Set up for Lab 7\n\n## Goals\n\n- Regression models [partition variation]{.blue} in an outcome into variation explained by the model and not explained by the model\n\n- Individual regression coefficients reflect the [variation explained by that predictor]{.blue}, and [only that predictor]{.blue}\n\n- [Predicted values]{.blue} for regression models aid in [substantive interpretation]{.blue}\n\n- [Measures of model fit]{.blue} like $R^2$ can be useful for comparing different regression models\n\n- [Difference-in-differences]{.blue} designs combine [pre-post]{.blue} and [treatment-control]{.blue} comparisons to make [stronger causal claims]{.blue}.\n\n## Annoucements\n\n\n- [Assignment 2  Data:](https://josephessig-source.github.io/pols1600_site/assignments/a2.html/) due Sunday March 15\n\n- Lab 5 grades will be posted this week. \n\n## Setup: Packages for today\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Pacakges for today\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\"htmltools\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"easystats\", \"zoo\"\n)\n\nlapply(the_packages, library, character.only = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n [5] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n [9] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[13] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[17] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[21] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[25] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[29] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[33] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[2]]\n [1] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[3]]\n [1] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[4]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[5]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[6]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[7]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[8]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[9]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[10]]\n [1] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n [5] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n [9] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[13] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[17] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[21] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[25] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[29] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[33] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[37] \"datasets\"      \"methods\"       \"base\"         \n\n[[11]]\n [1] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n [5] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n [9] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[13] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[17] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[21] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[25] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[29] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[33] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[37] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[12]]\n [1] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n [5] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n [9] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[13] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[17] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[21] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[25] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[29] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[33] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[37] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[41] \"base\"         \n\n[[13]]\n [1] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n [5] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [9] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[13] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[17] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[21] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[25] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[29] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[33] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[37] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[41] \"methods\"       \"base\"         \n\n[[14]]\n [1] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n [5] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n [9] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[13] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[17] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[21] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[25] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[29] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[33] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[37] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[41] \"datasets\"      \"methods\"       \"base\"         \n\n[[15]]\n [1] \"scales\"        \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n [5] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n [9] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n[13] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[17] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[21] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[25] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[29] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[33] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[37] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[41] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[16]]\n [1] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n [5] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n [9] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[13] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[17] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[21] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[25] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[29] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[33] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[37] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[41] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[45] \"base\"         \n\n[[17]]\n [1] \"ggdag\"         \"dagitty\"       \"scales\"        \"ggpubr\"       \n [5] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n [9] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[13] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[17] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[21] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[25] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[29] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[33] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[37] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[41] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[45] \"methods\"       \"base\"         \n\n[[18]]\n [1] \"ggforce\"       \"ggdag\"         \"dagitty\"       \"scales\"       \n [5] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n [9] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n[13] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[17] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[21] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[25] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[29] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[33] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[37] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[41] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[45] \"datasets\"      \"methods\"       \"base\"         \n\n[[19]]\n [1] \"COVID19\"       \"ggforce\"       \"ggdag\"         \"dagitty\"      \n [5] \"scales\"        \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n [9] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n[13] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n[17] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[21] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[25] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[29] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[33] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[37] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[41] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[45] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[20]]\n [1] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [5] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n [9] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n[13] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[17] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[21] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[25] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[29] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[33] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[37] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[41] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[45] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[49] \"base\"         \n\n[[21]]\n [1] \"mapdata\"       \"maps\"          \"COVID19\"       \"ggforce\"      \n [5] \"ggdag\"         \"dagitty\"       \"scales\"        \"ggpubr\"       \n [9] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[13] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[17] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[21] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[25] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[29] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[33] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[37] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[41] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[45] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[49] \"methods\"       \"base\"         \n\n[[22]]\n [1] \"qss\"           \"mapdata\"       \"maps\"          \"COVID19\"      \n [5] \"ggforce\"       \"ggdag\"         \"dagitty\"       \"scales\"       \n [9] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n[13] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n[17] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[21] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[25] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[29] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[33] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[37] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[41] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[45] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[49] \"datasets\"      \"methods\"       \"base\"         \n\n[[23]]\n [1] \"tidycensus\"    \"qss\"           \"mapdata\"       \"maps\"         \n [5] \"COVID19\"       \"ggforce\"       \"ggdag\"         \"dagitty\"      \n [9] \"scales\"        \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n[13] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n[17] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n[21] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[25] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[29] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[33] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[37] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[41] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[45] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[49] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[24]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n[17] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[21] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[25] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[29] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[33] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[37] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[41] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[45] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[49] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[53] \"base\"         \n\n[[25]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n[17] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[21] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[25] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[29] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[33] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[37] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[41] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[45] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[49] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[53] \"base\"         \n\n[[26]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n[17] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[21] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[25] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[29] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[33] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[37] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[41] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[45] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[49] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[53] \"base\"         \n\n[[27]]\n [1] \"zoo\"           \"dataverse\"     \"tidycensus\"    \"qss\"          \n [5] \"mapdata\"       \"maps\"          \"COVID19\"       \"ggforce\"      \n [9] \"ggdag\"         \"dagitty\"       \"scales\"        \"ggpubr\"       \n[13] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[17] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[21] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[25] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[29] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[33] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[37] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[41] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[45] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[49] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[53] \"methods\"       \"base\"         \n```\n\n\n:::\n:::\n\n\n\n\n# {{< fa lightbulb >}} What does it mean to \"control for X\" {.inverse}\n\n## Regression models partition variance {.smaller}\n\nRegression models [partition variance]{.blue}, separating the [variation in the outcome]{.blue} **into** [variation explained by the predictors]{.blue} in our model and the [remaining variation not explained]{.blue} by these predictors\n\n$$\\begin{aligned}\n\\textrm{Total Variance} &= \\textrm{Variance Explained by Model} + \\textrm{Unexplained Variance} \\\\\n\\textrm{Observed} &= \\textrm{Predicted Value} + \\textrm{Error}\\\\\n\\textrm{Y} &=  E[Y|X] + \\epsilon\\\\\n\\textrm{Y} &=  X\\hat{\\beta} + \\hat{\\epsilon}\\\\\n\\textrm{Y} &= \\hat{Y} + \\hat{\\epsilon}\n\\end{aligned}$$\n\n## {.smaller}\n#### Coefficients describe the unique variance in Y explained by X (and only X)\n\n::: panel-tabset\n\n## Task\n\nThe coefficients in a regression model describe the variation in the outcome explained by that predictor, and only that predictor.\n\nLet's fit three models from last week's lab and look at how the coefficients change from model to model\n\n## {{< fa code >}}\n\n::: {.cell}\n\n```{.r .cell-code}\nload(url(\"https://josephessig-source.github.io/pols1600_site/files/data/06_lab.rda\"))\nm1 <- lm(new_deaths_pc_14day ~ rep_voteshare_std, covid_lab)\nm2 <- lm(new_deaths_pc_14day ~ rep_voteshare_std + med_age_std, covid_lab)\nm3 <- lm(new_deaths_pc_14day ~ rep_voteshare_std + med_age_std + med_income_std, covid_lab)\n```\n:::\n\n\n## {{< fa table >}}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhtmlreg(list(m1, m2, m3)) %>% HTML() %>% browsable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 3</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.07</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.07)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.02</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_income_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.22<sup>&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.07)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.44</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.29</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.28</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.40</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"4\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n```\n\n:::\n:::\n\n\n:::\n\n\n## Why do coefficients change when we control for variables?{.center}\n\n\n## Residualized Regression\n\n\nResidualized regression is a way of understanding what it means to [control for variables]{.blue} in a regression.\n\nResidualized regression provides a way of illustrating what we mean when we say the coefficients describe the unique variance in Y explained by some predictor $x$ (and only $x$)\n\nThis result is called the **Frisch-Waugh-Lovell (FWL) theorem**\n\n## What's a residual\n\n\n- [Residuals]{.blue} represent the part of the outcome variable, [not explained]{.blue} by the predictors in a model\n  - Difference between the observed $y$ and the predicted $\\hat{y}$\n  \n\n$$y = \\overbrace{\\beta_0 + \\beta_1x_1 + \\beta_2 x_2  + \\dots \\beta_j x_j}^{\\text{Predictors}} + \\underbrace{\\epsilon}_{\\text{Residuals}}$$\n\n## Residuals are uncorrelated with $X$ and $\\hat{y}${.smaller}\n\n::::{.columns}\n\n:::{.column width=40%}\n\nResiduals are uncorrelated with (orthogonal to) the predictors $X$, and predicted values $X\\beta$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Trust but verify\ncor(resid(m2),covid_lab$rep_voteshare_std) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.674688e-17\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(resid(m2),covid_lab$med_age_std)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.682706e-17\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(resid(m2),fitted(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.520407e-16\n```\n\n\n:::\n:::\n\n\n\n:::\n\n:::{.column width=55%}\n\n![](../files/llustration-of-the-linear-regression-model-as-a-projection-method.png)\n\n:::\n\n::::\n\n## {.smaller}\n#### Residualized Regression \n\n\n:::: panel-tabset\n\n## {{< fa lightbulb >}}\n\n:::{.nonincremental}\n\nFor a model like `m2` we can recover the coefficient on `rep_voteshare_std` by:\n  \n1. Regressing `new_deaths_pc_14day` on `med_age_std` to get the [residual]{.blue} variation in Covid-19 deaths [not explained]{.blue} by median age \n2. Regressing `rep_voteshare_std` on `med_age_std` to get the [residual]{.blue} variation in Republican Vote Share [not explained]{.blue} by median age \n3. Regressing the residuals from 1. (Deaths not explained by age) on the residuals from 2. (Vote share not explained by age) to obtain the [same]{.blue} coefficient from `m2` for `rep_voteshare_std`\n\nThe same principle holds for `m3`\n\n:::\n\n## {{< fa code >}} m2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Regressing `new_deaths_pc_14da` on `med_age_std`\nm2_death_by_age <- lm(new_deaths_pc_14day ~ med_age_std, covid_lab)\n# Save residuals\ncovid_lab$res_death_no_age <- resid(m2_death_by_age)\n\n# 2. Regressing `rep_voteshare_std` on `med_age_std` \nm2_repvs_by_age <- lm(rep_voteshare_std ~ med_age_std, covid_lab)\n# Save residuals\ncovid_lab$res_repvs_no_age <- resid(m2_repvs_by_age)\n\n# 3. Residualized regression of deaths on Rep Vote Share\nm2_res <- lm(res_death_no_age ~ res_repvs_no_age, covid_lab)\n\n# Mutliple regression\ncoef(m2)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrep_voteshare_std \n         0.230745 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Residualized regression\ncoef(m2_res)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nres_repvs_no_age \n        0.230745 \n```\n\n\n:::\n:::\n\n\n## {{< fa code >}} m3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Regressing `new_deaths_pc_14da` on `med_age_std` and med_income_std\nm3_death_by_age_income <- lm(new_deaths_pc_14day ~ med_age_std + med_income_std, covid_lab)\n# Save residuals\ncovid_lab$res_death_no_age_income <- resid(m3_death_by_age_income)\n\n# 2. Regressing `rep_voteshare_std` on `med_age_std` and med_income_std\nm3_repvs_by_age_income <- lm(rep_voteshare_std ~ med_age_std + med_income_std, covid_lab)\n# Save residuals\ncovid_lab$res_repvs_no_age_income <- resid(m3_repvs_by_age_income)\n\n# 3. Residualized regression of deaths on Rep Vote Share\nm3_res <- lm(res_death_no_age_income ~ res_repvs_no_age_income, covid_lab)\n\n# multiple regression coefficient\ncoef(m3)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrep_voteshare_std \n       0.07140446 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Same as  residualized regression coefficient\ncoef(m3_res)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nres_repvs_no_age_income \n             0.07140446 \n```\n\n\n:::\n:::\n\n::::\n\n## Why did the coefficient on Rep Vote Share change in `m3` but not `m2`?{.center}\n\n## {.smaller}\n\n## {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"1\">DV: Death</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Baseline</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.29</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"2\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n```\n\n:::\n:::\n\n\n##\n\n$$\n\\text{Covid-19 Deaths} = \\beta_0 + \\beta_1 \\text{Rep Vote Share}\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/venn_iv1-1.png){width=960}\n:::\n:::\n\n\n## {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">DV: Death</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"1\">DV: Vote Share</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"1\">DV: Res. Deaths</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Baseline</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mutliple</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Age</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Vote Share</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Deaths</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.06)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.14)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.12</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.06)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.14)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">res_repvs_no_age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.29</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.28</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.30</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"6\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n```\n\n:::\n:::\n\n\n\n##\n\n$$\n\\text{Deaths} = \\beta_0 + \\beta_1 \\text{Rep VS} + \\beta_2 \\text{Age}\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/venn_iv2-1.png){width=960}\n:::\n:::\n\n\n$\\beta_1$ doesn't change because `age` has no relationship to `deaths` in these data\n\n## {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">DV: Death</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"1\">DV: Vote Share</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"1\">DV: Res. Death</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Baseline</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Full</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">No Rep</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Vote Share</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Deaths</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.57<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.10)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.23<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.07</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.07)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.22<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.10)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_income_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.22<sup>&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.27<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.74<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.07)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.05)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.10)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">res_repvs_no_age_income</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.07</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.07)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.44</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.43</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.55</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.29</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.40</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.40</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.53</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.00</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"6\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n```\n\n:::\n:::\n\n\n\n##\n\n$$\n\\text{Deaths} = \\beta_0 + \\beta_1 \\text{Rep VS} + \\beta_2 \\text{Age} + \\beta_3 \\text{Income}\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/venn_iv3-1.png){width=960}\n:::\n:::\n\n\n$\\beta_1$ decreases because after controlling for `income` there is less unique variation explained only by `republican vote share`\n\n\n# {{< fa lightbulb >}} Using regression to make predictions {.inverse}\n\n## Using regression to produce predicted values {.smaller}\n\nCoefficients in a regression define a formula which produces a predicted value of the outcome $y$ when the predictors $X$ take particular values.\n\n$$\n\\begin{aligned}y &= \\overbrace{\\beta_0 + \\beta_1x_1 + \\beta_2 x_2  + \\dots \\beta_j x_j}^{\\text{Predictors}} + \\underbrace{\\epsilon}_{\\text{Residuals}} &\\\\\ny &= \\beta_0 + \\beta_1x_{rvs} + \\beta_2x_{age}+ \\beta_3x_{inc} + \\epsilon & \\text{m3}\\\\\ny &= 0.56 + 0.07x_{rvs} - 0.02 x_{age} - 0.22 x_{inc} + \\hat{\\epsilon} & \\text{estimated m3}\\\\\ny &= 0.56 + 0.07(-0.87) - 0.02(0.62) - 0.22(0.38) + \\hat{\\epsilon} & \\text{prediction for RI} \\\\\n\\overbrace{0.22}^{\\text{Observed}} &= \\underbrace{0.41}_{\\text{Predicted}} + \\overbrace{(-0.19)}^{\\text{Residual}} &\n\\end{aligned}\n$$\n\n## Producing Predicted Values in R {.smaller}\n\nThe basic steps to producing predicted values in R as follows:\n\n- Fit a model using `lm()`\n- Create a [prediction data frame]{.blue} using `expand_grid()`:\n  - [vary]{.blue} the values of [the predictor]{.blue} you're interested in\n  - [hold]{.blue} all the other predictors in your model [constant]{.blue} at some typical value.\n- Input the [model]{.blue} from `lm()` and the [prediction data frame]{.blue}, into the `predict()` function to obtain [predicted values]{.blue}. \n  - Save predictions as a new column in your [prediction data frame]{.blue} (I generally call them `fit`)\n- Plot predicted values in your [prediction data frame]{.blue} to help interpret your model\n\n## {.smaller}\n#### Are there decreasing returns to vaccination?\n\n:::: panel-tabset\n\n## Task\n\nSuppose we thought the [marginal effect]{.blue} -- (here, predicted change in deaths from a 1 percent increase in the percent of the population vaccinated) of vaccines varied.\n\nThere might be large gains from going to low to average rates of vaccination, but after a certain threshold, the decreases in deaths would taper off.\n\nWe could test this by including a [polynomial term]{.blue} `I(percent_vaccinated)^2` in our model.\n\nIncluding a polynomial term, allows the marginal effect to vary, based on the value of the predictor.\n\nIt's hard to interpret the coefficients on [polynomial terms]{.blue} (or interaction terms) just by looking at coefficients in a table\n\nInstead, we'll produce a plot of predicted values to test these claims\n\n## {{<fa code >}} m4\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(new_deaths_pc_14day ~ percent_vaccinated + I(percent_vaccinated^2) + rep_voteshare_std + med_age_std + med_income_std, covid_lab\n           )\n```\n:::\n\n\n## {{<fa table >}} Table\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">6.194<sup>&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(2.186)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">percent_vaccinated</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.169<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.077)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">percent_vaccinated^2</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.001</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.062</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.081)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.053</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.053)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_income_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.114</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.068)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.561</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.512</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"2\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n## {{<fa code >}} Predict\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_df <- expand_grid(\n  percent_vaccinated = sort(unique(covid_lab$percent_vaccinated)),\n  # Set standardized predictors to their means of 0\n  rep_voteshare_std = 0,\n  med_age_std = 0,\n  med_income_std = 0\n)\n\npred_df$fit <- predict(m4, newdata = pred_df)\n\npred_df %>% \n  ggplot(aes(percent_vaccinated, fit))+\n  geom_line()+\n  labs(\n    y = \"Predicted Covid-19 Deaths\\n(per capita, 14-day average)\",\n    x = \"Percent of State's population that's Vaccinated\"\n  ) + \n  theme_minimal() -> fig_m4\n```\n:::\n\n\n\n## {{<fa chart-line>}} Fig\n\nFor a typical state, early increases in vaccination rate are associated with larger declines in predicted deaths from Covid-19\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n::::\n\n\n# {{< fa lightbulb >}} Evaluating Model Fit {.inverse}\n\n## Evaluating Model Fit\n\nModels partition variance. We can summarize the overall fit of our model using measures like $R^2$\n\n$$R^2 = \\frac{\\text{variance(predicted values )}}{ \\text{variance(observed values )}}$$\n\n## R^2\n\nMore formally, you'll see $R^2$ defined in terms of \"Sums of Squares\"\n\n- TSS = [Total Sum of Squares]{.blue} = Variance of the Outcome\n- ESS = [Explained Sum of Squares]{.blue} = Variance of the Predicted Values\n- RSS = [Sum of Squared Residuals]{.blue} = Variance of the Residuals\n\n$$R^2 = \\frac{ESS}{TSS}= 1 - \\frac{RSS}{TSS}$$\n\n## Calculating $R^2$ in R{.smaller}\n\nWe could do it by hand, finding that our model explained about 43 percent of the observed variation deaths.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ESS / TSS\nvar(m3$fitted.values)/var(m3$model$new_deaths_pc_14day)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4393655\n```\n\n\n:::\n\n```{.r .cell-code}\n# 1 - RSS/TSS\n1 - var(m3$residuals)/var(m3$model$new_deaths_pc_14day)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4393655\n```\n\n\n:::\n:::\n\n\nBut generally we let the `summary()` function do it for us:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = new_deaths_pc_14day ~ rep_voteshare_std + med_age_std + \n    med_income_std, data = covid_lab)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.50751 -0.19703 -0.06278  0.20024  0.92320 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        0.56561    0.04425  12.782  < 2e-16 ***\nrep_voteshare_std  0.07140    0.06654   1.073  0.28869    \nmed_age_std       -0.01692    0.04744  -0.357  0.72296    \nmed_income_std    -0.21669    0.06660  -3.254  0.00211 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.316 on 47 degrees of freedom\nMultiple R-squared:  0.4394,\tAdjusted R-squared:  0.4036 \nF-statistic: 12.28 on 3 and 47 DF,  p-value: 4.689e-06\n```\n\n\n:::\n:::\n\n\n\n## Adjusted $R^2${.smaller}\n\n:::: panel-tabset\n\n## Adjusted $R^2$\n\n:::{.nonincremental}\n- One can show that a models $R^2$ [always increases]{.blue} as we [add predictors]{.blue}, even when they're unrelated to the outcome\n\n- The [adjusted $R^2$]{.blue} adjusts for this by weighting the $R^2$ of a model by the number of predictors\n\n$$\\text{adj. }R^2 = 1 - \\frac{RSS/(n-k)}{TSS/(n-1)}$$\n\n:::\n\n## {{< fa code >}} Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nex_df <- data.frame(\n  y = rnorm(100) \n  ) %>%\n    bind_cols(\n      data.frame(matrix(rnorm(10000), ncol=100))\n    ) %>% janitor::clean_names()\n\n\nthe_formulas <- list()\nfor(i in 2:51){\n  vars <- names(ex_df)[2:i]\n  the_formulas[[i-1]] <- paste(\"y~\",paste(vars,collapse = \"+\"))\n}\n\nthe_formulas %>% \n  purrr::map(as.formula) %>% \n  purrr::map(lm, data=ex_df) %>% \n  purrr::map(summary) %>% \n  purrr::map_df(glance) -> r2_df\n\nr2_df %>% \n  ggplot(aes(df, r.squared))+\n  geom_point(aes(col = \"R^2\"))+\n  geom_line()+\n  geom_point(aes(y=adj.r.squared,col = \"Adjusted R^2\"))+\n  geom_line(aes(y=adj.r.squared))+\n  labs(\n    x = \"Number of predictors\",\n    y = \"Proportion of Variance Explained\",\n    title = \"Adding unrelated predictors increases a model's R^2\\nwhile the Adjusted R^2 provides a better indicator of poor fit \",\n    col =\"Model fit\"\n  ) -> fig_r2\n```\n:::\n\n\n## {{< fa chart-line >}} Figure\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n::::\n\n## {.smaller}\n#### Using $R^2$ to compare models\n\n::::panel-tabset\n\n## ANOVA\n\nWhen models are *nested* (larger models contain all the predictors of smaller models), we can ask, does including the additional predictors in the larger model explain more variation in the outcome than we would expect would happen if we just added additional, random variable.\n\nFormally we call this process an [Analysis of Variance (ANOVA)](https://towardsdatascience.com/anova-for-regression-fdb49cf5d684#:~:text=It%20is%20the%20same%20as,or%20more%20categorical%20predictor%20variables.)\n\nLet's assess the added predictive power of `I(percent_vaccinated^2)` by estimating a model without it and comparing models using ANOVA \n\n## {{<fa code >}} m5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate model without polynomial\nm5 <- lm(new_deaths_pc_14day ~ percent_vaccinated  + rep_voteshare_std + med_age_std + med_income_std, covid_lab\n           )\n```\n:::\n\n\n## {{<fa table >}} Table\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 2</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">6.194<sup>&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">2.532<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(2.186)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.657)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">percent_vaccinated</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.169<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.035<sup>&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.077)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.012)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">percent_vaccinated^2</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.001</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.062</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.089</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.081)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.082)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.053</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.071</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.053)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.053)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_income_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.114</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.119</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.068)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.070)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.561</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.531</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.512</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.490</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"3\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n## {{<fa code >}} Anova\n\nThe anova suggests that including a polynomial provides a *marginal* improvement to fit (p < 0.10)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m5, m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: new_deaths_pc_14day ~ percent_vaccinated + rep_voteshare_std + \n    med_age_std + med_income_std\nModel 2: new_deaths_pc_14day ~ percent_vaccinated + I(percent_vaccinated^2) + \n    rep_voteshare_std + med_age_std + med_income_std\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1     46 3.9268                              \n2     45 3.6758  1   0.25098 3.0725 0.08644 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n::::\n\n\n## {.smaller}\n#### Standardized vs Non Standardized Predictors\n\n::::panel-tabset\n\n## {{<fa light-bulb>}}\n\nWhy are we using standardized predictors?\n\nStandardizing variables is a common transformation:\n\n$$z\\text{-scores of x} = \\frac{x_i - \\mu_{x}}{\\sigma_x}$$\nWhen variables are measured on very different scales or units (e.g. age in years, income in dollars), using standardized (or normalized) versions rescales them to a unit-less measures that all have:\n\n- a mean of `zero`\n- a standard deviation of `1`\n\n\n## {{<fa code >}} m6\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate model  with unstandardized predictors\nm6 <- lm(new_deaths_pc_14day ~ percent_vaccinated  + rep_voteshare + med_age + med_income, covid_lab\n           )\n```\n:::\n\n\n## {{<fa table >}} Table\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 2</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">2.532<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">2.470<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.657)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(1.063)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">percent_vaccinated</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.035<sup>&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.035<sup>&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.012)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.012)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.089</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.082)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.071</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.053)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_income_std</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.119</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.070)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">rep_voteshare</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.007</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.007)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.029</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.022)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">med_income</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.000</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.531</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.531</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.490</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.490</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">51</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"3\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n## {{<fa code >}} Comments\n\nWhen should you standardize variables? It depends on what you're trying to do.\n\n- It's the same information, just rescaled:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(m5)[5] # Standardized coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmed_income_std \n    -0.1188812 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(m6)[5] # Unstandaried\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  med_income \n-1.10947e-05 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(m6)[5]*sd(covid_lab$med_income) # Same as standardized\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmed_income \n-0.1188812 \n```\n\n\n:::\n:::\n\n\n\n- Can facilitate comparison and estimation\n\n- Might make interpretation easier (but the onus is on you to describe your models well)\n\n  - Don't standardize binary predictors\n\n\n::::\n\n# {{< fa lightbulb >}} Difference-in-Differences {.inverse}\n\n## Motivating Example: What causes Cholera? {.smaller background-image=https://www.finebooksmagazine.com/sites/default/files/styles/gallery_item/public/media-images/2020-11/map-lead-4.jpg?h=2ded5a3f&itok=Mn-K5rQc, background-opacity=.3}\n\n- In the 1800s, cholera was thought to be transmitted through the air.\n\n- Led John Snow (the physician, not from Game of Thrones) to explore the origins of Cholera, eventually concluding that cholera was transmitted through living organisms in water.\n\n- Leveraged a **natural experiment** in which one water company in London moved its pipes further upstream (reducing contamination for Lambeth), while other companies kept their pumps serving Southwark and Vauxhall in the same location. \n\n\n## Notation {.smaller}\n\nLet's adopt a little notation to help us think about the logic of Snow's design:\n\n- $D$: treatment indicator, 1 for treated neighborhoods (Lambeth), 0 for control neighborhoods (Southwark and Vauxhall)\n\n- $T$: period indicator, 1 if post treatment (1854), 0 if pre-treatment (1849).\n\n- $Y_{di}(t)$ the potential outcome of unit $i$ \n\n  - $Y_{1i}(t)$ the potential outcome of unit $i$ when treated between the two periods \n\n  - $Y_{0i}(t)$ the potential outcome of unit $i$ when control between the two periods \n\n\n## Causal Effects {.smaller}\n\nThe individual causal effect for unit i at time t is:\n\n$$\\tau_{it} = Y_{1i}(t) − Y_{0i}(t)$$\n\nWhat we observe is \n\n$$Y_i(t) = Y_{0i}(t)\\cdot(1 − D_i(t)) + Y_{1i}(t)\\cdot D_i(t)$$\n\n$D$ only equals 1, when $T$ equals 1, so we never observe $Y_0i(1)$ for the treated units. \n\nIn words, we don't know what Lambeth's outcome would have been in the second period, had they not been treated.\n\n\n## Average Treatment on Treated {.smaller}\n\nOur goal is to estimate the average effect of treatment on treated (ATT):\n\n\n$$\\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]$$\n\nThat is, what would have happened in Lambeth, had their water company not moved their pipes\n\n\n## Average Treatment on Treated {.smaller}\n\nOur goal is to estimate the average effect of treatment on treated (ATT):\n\nWhat we can observe is:\n\n|               | Pre-Period (T=0)  | Post-Period (T=1)  |\n|-|--|-|\n| Treated $D_{i}=1$  |  $E[Y_{0i}(0)\\vert D_i = 1]$ | $E[Y_{1i}(1)\\vert D_i = 1]$  |\n| Control $D_i=0$  |  $E[Y_{0i}(0)\\vert D_i = 0]$ | $E[Y_{0i}(1)\\vert D_i = 0]$  |\n\n\n## Data {.smaller}\n\nBecause potential outcomes notation is abstract, let's consider a modified description of the Snow's cholera death data from [Scott Cunningham](https://mixtape.scunning.com/difference-in-differences.html):\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Company                      | 1849 (T=0)| 1854 (T=1)|\n|:----------------------------|----------:|----------:|\n|Lambeth (D=1)                |         85|         19|\n|Southwark and Vauxhall (D=0) |        135|        147|\n\n\n:::\n:::\n\n\n\n## How can we estimate the effect of moving pumps upstream? {.smaller}\n\nRecall, our goal is to estimate the effect of the the treatment on the treated:\n\n$$\\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]$$\n\nLet's consider some strategies Snow could take to estimate this quantity:\n\n\n## Before vs after comparisons:{.smaller}\n\n:::{.nonincremental}\n- Snow could have compared Lambeth in 1854 $(E[Y_i(1)|D_i = 1] = 19)$ to Lambeth in 1849 $(E[Y_i(0)|D_i = 1]=85)$, and claimed that moving the pumps upstream led to **66 fewer cholera deaths.** \n\n- Assumes Lambeth's pre-treatment outcomes in 1849 are a good proxy for what its outcomes would have been in 1954 if the pumps hadn't moved $(E[Y_{0i}(1)|D_i = 1])$.\n\n- A skeptic might argue that Lambeth in 1849 $\\neq$ Lambeth in 1854\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Company </th>\n   <th style=\"text-align:right;\"> 1849 (T=0) </th>\n   <th style=\"text-align:right;\"> 1854 (T=1) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;color: blue !important;\"> Lambeth (D=1) </td>\n   <td style=\"text-align:right;font-weight: bold;color: blue !important;\"> 85 </td>\n   <td style=\"text-align:right;font-weight: bold;color: blue !important;\"> 19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Southwark and Vauxhall (D=0) </td>\n   <td style=\"text-align:right;\"> 135 </td>\n   <td style=\"text-align:right;\"> 147 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n\n## Treatment-Control comparisons in the Post Period. {.smaller}\n\n:::{.nonincremental}\n\n- Snow could have compared outcomes between Lambeth and S&V in 1954  ($E[Yi(1)|Di = 1] − E[Yi(1)|Di = 0]$), concluding that the change in pump locations led to **128 fewer deaths.**\n\n- Here the assumption is that the outcomes in S&V and in 1854 provide a good proxy for what would have happened in Lambeth in 1954 had the pumps not been moved $(E[Y_{0i}(1)|D_i = 1])$\n\n- Again, our skeptic could argue  Lambeth $\\neq$ S&V \n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Company </th>\n   <th style=\"text-align:right;\"> 1849 (T=0) </th>\n   <th style=\"text-align:right;\"> 1854 (T=1) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Lambeth (D=1) </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;font-weight: bold;color: red !important;\"> 19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Southwark and Vauxhall (D=0) </td>\n   <td style=\"text-align:right;\"> 135 </td>\n   <td style=\"text-align:right;font-weight: bold;color: red !important;\"> 147 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n## Difference in Differences {.smaller}\n\n:::{.nonincremental}\nTo address these concerns, Snow employed what we now call a [difference-in-differences]{.blue} design, \n\nThere are two, equivalent ways to view this design. \n\n$$\\underbrace{\\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\\}}_{\\text{1. Treat-Control |Post }}− \\overbrace{\\{E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}=0 ]\\}}^{\\text{Treated-Control|Pre}}$$\n\n- Difference 1: Average change between Treated and Control  in Post Period\n\n- Difference 2: Average change between Treated and Control  in Pre Period\n\n:::\n\n## Difference in Differences {.smaller}\n\n:::{.nonincremental}\n\n$$\\underbrace{\\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\\}}_{\\text{1. Treat-Control |Post }}− \\overbrace{\\{E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}=0 ]}^{\\text{Treated-Control|Pre}}$$\nIs equivalent to: \n\n$$\\underbrace{\\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(0)|D_{i} = 1]\\}}_{\\text{Post - Pre |Treated }}− \\overbrace{\\{E[Y_{i}(1)|D_{i} = 0] − E[Y_{i}(0)|D_{i}=0 ]}^{\\text{Post-Pre|Control}}$$\n\n\n- Difference 1: Average change between Treated over time\n- Difference 2: Average change between Control over time\n\n:::\n\n## Difference in Differences {.smaller}\n\n\nYou'll see the DiD design represented both ways, but they produce the same result:\n\n$$\n\\tau_{ATT} = (19-147) - (85-135) = -78\n$$\n\n$$\n\\tau_{ATT} = (19-85) - (147-135) = -78\n$$\n\n\n## Identifying Assumption of a Difference in Differences Design {.smaller}\n\nThe key assumption in this design is what's known as the parallel trends assumption: $E[Y_{0i}(1) − Y_{0i}(0)|D_i = 1] = E[Y_{0i}(1) − Y_{0i}(0)|D_i = 0]$ \n\n- In words: If Lambeth hadn't moved its pumps, it would have followed a similar path as S&V\n\n## Parallel Trends\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/paralleltrends-1.png){width=960}\n:::\n:::\n\n\n## Using linear regression to estimate a Difference in Difference {.smaller}\n\n:::: panel-tabset\n\n## Concept\n\n- Recall that linear regression provides a...\n  - linear estimate of the conditional expectation function\n- In the canonical pre-post, treated and control DiD, $\\beta_3$ from the following linear regression will give us the ATT:\n\n:::{.fragment}\n\n$$\ny = \\beta_0 + \\beta_1 Post + \\beta_2 Treated + \\underbrace{\\beta_3Post\\times Treated}_{\\tau_{ATT}}\n$$\n\n:::\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncholera_df <- tibble(\n  Period = factor(c(\"Pre\",\"Pre\",\"Post\",\"Post\"),\n                  levels = c(\"Pre\",\"Post\")),\n  Year = c(1849,1849, 1854,1854),\n  Treated = factor(c(\"Control\",\"Treated\",\"Control\",\"Treated\")),\n  Company = c(\"S&V\",\"Lambeth\",\"S&V\",\"Lambeth\"),\n  Deaths = c(135,85,147,19)\n)\n\nm_did <- lm(Deaths~Period + Treated + Period:Treated, cholera_df)\n\nm_did\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Deaths ~ Period + Treated + Period:Treated, data = cholera_df)\n\nCoefficients:\n              (Intercept)                 PeriodPost  \n                      135                         12  \n           TreatedTreated  PeriodPost:TreatedTreated  \n                      -50                        -78  \n```\n\n\n:::\n:::\n\n\n## Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3699a5db5ebcec73f506\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3699a5db5ebcec73f506\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\"],[\"Pre\",\"Pre\",\"Post\",\"Post\"],[1849,1849,1854,1854],[\"Control\",\"Treated\",\"Control\",\"Treated\"],[\"S&amp;V\",\"Lambeth\",\"S&amp;V\",\"Lambeth\"],[135,85,147,19]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Period<\\/th>\\n      <th>Year<\\/th>\\n      <th>Treated<\\/th>\\n      <th>Company<\\/th>\\n      <th>Deaths<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,5]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Period\",\"targets\":1},{\"name\":\"Year\",\"targets\":2},{\"name\":\"Treated\",\"targets\":3},{\"name\":\"Company\",\"targets\":4},{\"name\":\"Deaths\",\"targets\":5}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n## DiD\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">135.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Post (1854)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">12.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Treated (Lambeth)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-50.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Post X Treated (DID)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-78.00</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">1.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">4</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"2\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n## Figure\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-slides_files/figure-revealjs/didfig-1.png){width=960}\n:::\n:::\n\n\n\n\n:::{.nonincremental}\n\n- $\\beta_0=$ Outcome in control (S&V) before treatment\n- $\\beta_1=$ Fixed, [unit invariant]{.blue} differences between [pre]{.blue} and [post]{.blue} periods\n- $\\beta_2=$ Fixed, [time invariant]{.blue} differences between [treated]{.blue} and [control]{.blue}\n- $\\beta_3=$ [Difference-in-Differences]{.blue} = $E[Y_{1i}(1) -  Y_{0i}(1)|D=1]$\n\n:::\n\n::::\n\n\n\n\n## Summary {.smaller}\n\n- A Difference in Differences (DiD, or diff-in-diff) design combines a pre-post comparison, with a treated and control comparison\n  \n- Differencing twice accounts for fixed differences [across units]{.blue} and [between periods]{.blue}\n  - But not time varying differences across units...\n  \n- The key identifying assumption of a DiD design is the assumption of [parallel trends]{.blue}\n  - Absent treatment, treated and control groups\nwould see the same changes over time.\n  - Hard to prove, possible to test\n\n\n\n## Extensions and limitations {.smaller}\n\n- Diff-in-Diff easy to estimate with linear regression\n- Generalizes to multiple periods and treatment interventions\n  - More pre-treatment periods allow you assess \"parallel trends\" assumption\n- Alternative methods \n  - Synthetic control\n  - Event Study Designs\n- What if you have multiple treatments or treatments that come and go?\n  - Panel Matching\n  - Generalized Synthetic control\n\n\n## Applications{.smaller}\n\n- [Card and Krueger (1994)](https://www.nber.org/papers/w4509) What effect did raising the minimum wage in NJ have on employment\n\n- [Abadie, Diamond, & Hainmueller (2014)](https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12116?casa_token=_ceCu4SwzTEAAAAA%3AP9aeaZpT_Zh1VdWKXx_tEmzaJTtMJ1n0eG7EaYlvJZYN000re33cfMAI2O8N8htFJjOsln2GyVeQql4) What effect did German Unification have on economic development in West Germany\n\n- [Malesky, Nguyen and Tran (2014)](https://www.cambridge.org/core/journals/american-political-science-review/article/impact-of-recentralization-on-public-services-a-differenceindifferences-analysis-of-the-abolition-of-elected-councils-in-vietnam/3477854BAAFE152DC93C594169D64F58) How does decentralization influence public services?\n\n\n\n\n\n# {{< fa home >}} Summary {.inverse}\n\n## Summary - Linear Regression{.smaller}\n\n- Linear regression produces linear estimates of the Conditional Expectation Function\n\n- We estimate linear regression using `lm()`\n\n:::{.fragment}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm( y ~ x1 + x2 + x3, data = df)\n```\n:::\n\n\n:::\n\n- We interpret linear regression by: looking at the [sign]{.blue}, [size]{.blue}, and, eventually, [significance]{.blue} of coefficients\n\n  - the intercept $(\\beta_0)$ corresponds to the model's prediction when every other predictor is zero\n  - the other $\\beta$s describe how $y$ changes with a [unit change] in $x$, controlling for other predictors in the model\n  \n- We present our results using [regression tables]{.blue} and [figures]{.blue} showing [predicted values]{.blue}\n\n\n## Summary - Difference-in-Differences{.smaller}\n\n- Difference-in-Differences (DiD) is a powerful research design for observational data that combines a [pre-post comparisons]{.blue} with a [treated and control]{.blue} comparisons\n  \n- Differencing twice accounts for fixed differences [across units]{.blue} and [between periods]{.blue}\n\n- DiD relies on an assumption of [parallel trends]{.blue}\n\n- We can use linear regression to estimate and generalize DiD designs\n\n\n# {{< fa code>}} Previewing Lab 7 {.inverse}\n\n## Replicating Grumbach and Hill (2022)\n\n- In this week's lab, we'll be conducting a partial replication of @Grumbach2022-zj [“Rock the Registration: Same Day Registration Increases Turnout of Young Voters.”](../files/readings/grumbach_hill_2021.pdf)\n\n- On Friday, we'll walk through \n  - the paper's design and argument\n  - setting up and exploring the data\n  - reproducing some descriptive figures\n\n- Next Friday, we'll focus on replicating and understanding the main results\n\n##\n\n![](images/07_grumbach2022.png)\n\n## General Structure of Labs 7-8\n\nLab 7:\n\n- Summarize the study\n- Download and load the data\n- Recode the data\n- Merge the data\n- Recreate Figures 1 and 2\n\nLab 8:\n\n- Estimate some baseline models to understand Two-Way Fixed Effects\n- Estimate some of the models in Figure 3\n- Extend the study, perhaps considering SDR by race or gender\n\n## Reading Grumbach and Hill (2022){.smaller}\n\nReading @Grumbach2022-zj, focus on being able to answer the following:\n\n- What's the research question? \n  - General RQ: First sentence, second paragraph, p. 405\n  - Specific RQs: p. 405-406\n\n- What's the theoretical framework?\n  - Intro and Theory of Registration, p. 407-409\n\n- What's the empirical design?\n  - Methods pp. 409-410\n- What's are the main results?\n  - Results pp. 410-413\n  - Figure 3 in particular\n\n## Q1: Download the replication files\n\nRather than downloading the files directly from the paper's [replication archives]{.blue}, in this lab, we will [download the replication files]{.blue} to your computers and then [load the data]{.blue} into R from [where they're saved]{.blue}\n\nPlease click [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/AW5LU8) and let's download the files together.\n\n\n\n## 1. Go to the paper's dataverse\n\nPlease click [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/AW5LU8)\n\n![](images/07_rep1.png)\n\n## 2. Log in through Brown\n\n![](images/07_rep2.png)\n\n\n## 3. Select all of the files\n\nMake sure to **Select all 11 files in this dataset**\n\n![](images/07_rep3.png)\n\n![](images/07_rep4.png)\n\n## 4. Download the files in their original format\n\n![](images/07_rep5.png)\n\n##\n### 5. Save and unzip the downloaded files into your course folder where your labs are saved\n\n![](images/07_rep6.png)\n\n## Q3: Load the data into R {.smaller}\n\nIf you've saved the dataverse_files [into the folder where your lab is saved]{.blue}, you should be able to run the following code after [setting the working directory]{.blue} to [source file location]{.blue}:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remember to set working directory:\n# Session > Set working directory > Source file location\n\n# Load fips_codes\nfips_codes <- read_csv(\"dataverse_files/fips_codes_website.csv\")%>%\n  janitor::clean_names()\n\n# Load policy data\ndata <- readRDS(\"dataverse_files/policy_data_updated.RDS\")%>%\n  janitor::clean_names()\n\n# Load CPS data\ncps <- read_csv(\"dataverse_files/cps_00021.csv\") %>%\n  janitor::clean_names()\n```\n:::\n\n",
    "supporting": [
      "07-slides_files\\figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}