{
  "hash": "04bf416e0561e75c03a4635d09cef405",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"POLS 1600\"\nsubtitle: \"Review and Presentation Prep\"\ndate: last-modified\ndate-format: \"[Updated ]MMM D, YYYY\"\nformat: \n  revealjs:\n    theme: brownslides.scss\n    logo: images/pols1600_hex.png\n    footer: \"POLS 1600\"\n    multiplex: false\n    transition: fade\n    slide-number: c\n    incremental: true\n    center: false\n    menu: true\n    scrollable: true\n    highlight-style: github\n    progress: true\n    code-overflow: wrap\n    html-math-method: mathjax\n    chalkboard: true\n    # include-after-body: title-slide.html\n    title-slide-attributes:\n      align: left\n      data-background-image: images/pols1600_hex.png\n      data-background-position: 90% 50%\n      data-background-size: 40%\nfilters:\n  - openlinksinnewpage\n  - webr\nwebr:\n  packages: ['dplyr',\"ggplot2\"]\n  autoload-packages: true\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# {{< fa map-location>}} Overview {.inverse}\n\n## Class Plan\n\n- Announcements\n- Presentations\n- Workshop / Review\n  - Predicted values from linear models\n\n\n## Annoucements\n\n- No lab this week; class canceled Friday\n- Wednesday April 22, Work on Presentations/Drafts in class\n- April 27- May 1 Presentations - 10-12 minutes each; will keep Friday as backup if not finished. \n\n\n## Setup: Packages for today\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Pacakges for today\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\"htmltools\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"patchwork\",\"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"easystats\", \"zoo\"\n)\n\n## Define a function to load (and if needed install) packages\n\nlapply(the_packages, library, character.only = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n [5] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n [9] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[13] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[17] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[21] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[25] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[29] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[33] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[2]]\n [1] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[3]]\n [1] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[4]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[5]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[6]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[7]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[8]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[9]]\n [1] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[10]]\n [1] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n [5] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n [9] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[13] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[17] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[21] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[25] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[29] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[33] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[37] \"datasets\"      \"methods\"       \"base\"         \n\n[[11]]\n [1] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n [5] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n [9] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[13] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[17] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[21] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[25] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[29] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[33] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[37] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[12]]\n [1] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n [5] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n [9] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[13] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[17] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[21] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[25] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[29] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[33] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[37] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[41] \"base\"         \n\n[[13]]\n [1] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n [5] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n [9] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[13] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[17] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[21] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[25] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[29] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[33] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[37] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[41] \"methods\"       \"base\"         \n\n[[14]]\n [1] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n [5] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n [9] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[13] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[17] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[21] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[25] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[29] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[33] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[37] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[41] \"datasets\"      \"methods\"       \"base\"         \n\n[[15]]\n [1] \"patchwork\"     \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n [5] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n [9] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n[13] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[17] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[21] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[25] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[29] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[33] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[37] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[41] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[16]]\n [1] \"scales\"        \"patchwork\"     \"ggpubr\"        \"ggthemes\"     \n [5] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n [9] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[13] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[17] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[21] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[25] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[29] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[33] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[37] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[41] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[45] \"base\"         \n\n[[17]]\n [1] \"dagitty\"       \"scales\"        \"patchwork\"     \"ggpubr\"       \n [5] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n [9] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[13] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[17] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[21] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[25] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[29] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[33] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[37] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[41] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[45] \"methods\"       \"base\"         \n\n[[18]]\n [1] \"ggdag\"         \"dagitty\"       \"scales\"        \"patchwork\"    \n [5] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n [9] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n[13] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[17] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[21] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[25] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[29] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[33] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[37] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[41] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[45] \"datasets\"      \"methods\"       \"base\"         \n\n[[19]]\n [1] \"ggforce\"       \"ggdag\"         \"dagitty\"       \"scales\"       \n [5] \"patchwork\"     \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n [9] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n[13] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n[17] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[21] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[25] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[29] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[33] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[37] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[41] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[45] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[20]]\n [1] \"COVID19\"       \"ggforce\"       \"ggdag\"         \"dagitty\"      \n [5] \"scales\"        \"patchwork\"     \"ggpubr\"        \"ggthemes\"     \n [9] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n[13] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[17] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[21] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[25] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[29] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[33] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[37] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[41] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[45] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[49] \"base\"         \n\n[[21]]\n [1] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [5] \"dagitty\"       \"scales\"        \"patchwork\"     \"ggpubr\"       \n [9] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[13] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[17] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[21] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[25] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[29] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[33] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[37] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[41] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[45] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[49] \"methods\"       \"base\"         \n\n[[22]]\n [1] \"mapdata\"       \"maps\"          \"COVID19\"       \"ggforce\"      \n [5] \"ggdag\"         \"dagitty\"       \"scales\"        \"patchwork\"    \n [9] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n[13] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n[17] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[21] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[25] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[29] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[33] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[37] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[41] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[45] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[49] \"datasets\"      \"methods\"       \"base\"         \n\n[[23]]\n [1] \"qss\"           \"mapdata\"       \"maps\"          \"COVID19\"      \n [5] \"ggforce\"       \"ggdag\"         \"dagitty\"       \"scales\"       \n [9] \"patchwork\"     \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n[13] \"ggrepel\"       \"ggmap\"         \"htmltools\"     \"DT\"           \n[17] \"kableExtra\"    \"texreg\"        \"see\"           \"report\"       \n[21] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[25] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[29] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[33] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[37] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[41] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[45] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[49] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[24]]\n [1] \"tidycensus\"    \"qss\"           \"mapdata\"       \"maps\"         \n [5] \"COVID19\"       \"ggforce\"       \"ggdag\"         \"dagitty\"      \n [9] \"scales\"        \"patchwork\"     \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"htmltools\"    \n[17] \"DT\"            \"kableExtra\"    \"texreg\"        \"see\"          \n[21] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[25] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[29] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[33] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[37] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[41] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[45] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[49] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[53] \"base\"         \n\n[[25]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"patchwork\"     \"ggpubr\"       \n[13] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[17] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[21] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[25] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[29] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[33] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[37] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[41] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[45] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[49] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[53] \"methods\"       \"base\"         \n\n[[26]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"patchwork\"     \"ggpubr\"       \n[13] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[17] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[21] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[25] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[29] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[33] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[37] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[41] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[45] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[49] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[53] \"methods\"       \"base\"         \n\n[[27]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"patchwork\"     \"ggpubr\"       \n[13] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[17] \"htmltools\"     \"DT\"            \"kableExtra\"    \"texreg\"       \n[21] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[25] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[29] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[33] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[37] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[41] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[45] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[49] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[53] \"methods\"       \"base\"         \n\n[[28]]\n [1] \"zoo\"           \"dataverse\"     \"tidycensus\"    \"qss\"          \n [5] \"mapdata\"       \"maps\"          \"COVID19\"       \"ggforce\"      \n [9] \"ggdag\"         \"dagitty\"       \"scales\"        \"patchwork\"    \n[13] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n[17] \"ggmap\"         \"htmltools\"     \"DT\"            \"kableExtra\"   \n[21] \"texreg\"        \"see\"           \"report\"        \"parameters\"   \n[25] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[29] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[33] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[37] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[41] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[45] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[49] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[53] \"datasets\"      \"methods\"       \"base\"         \n```\n\n\n:::\n:::\n\n\n\n# {{< fa magnifying-glass>}} Review {.inverse}\n\n\n## Motivating Questions {.smaller}\n\nIn the rest of today's class, we'll get some practice putting together the various skills you need for your drafts by exploring the following:\n\n- How does partisanship shape American's perceptions of vaccines?\n\n- Who is skeptical of the benefits of vaccination?\n\n- Have these perceptions about vaccines changed over time?\n\n## Tasks:{.smaller}\n\nTo explore these questions, we need to\n\n- Get setup to work\n\n- Load our data\n\n- Recode our data\n\n- Summarize our data\n\n- Specify our expectations\n\n- Estimate models to test these expectations\n\n- Present and interpret results using\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis tests \n\n## New packages\n\nTo easily load survey data for our question, we'll need the `anesr` package, which loads data from the American National Election Studies into R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# # Uncomment to uninstall package to download NES survey data\n# library(devtools)\n# install_github(\"jamesmartherus/anesr\")\nrequire(anesr)\n```\n:::\n\n\n## Data {.smaller}\n\nNow that we have `anesr` installed, let's load data from the 2016 and 2020 National Election Studies:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\ndata(timeseries_2016, package = \"anesr\")\ndata(timeseries_2020, package = \"anesr\")\n```\n:::\n\n\nAnd copy those data frames into new dataframes with shorter names\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rename datasets\nnes16 <- timeseries_2016\nnes20 <- timeseries_2020\n```\n:::\n\n\n## Finding variables: Outcomes {.smaller}\n\nOur primary outcome of interest are beliefs about vaccines.\n\nVariables `V162162x` in the 2016 NES and `V202383x` in the 2020 NES will serve as our primary outcome of interest, summarizing respondents answer to the following question:\n\n> Do the health benefits of vaccinations generally outweigh the risks, do the risks outweigh the benefits, or is there no difference?\n\n## Finding variables: Predictors {.smaller}\n\nSimilarly, `V161158x` in the 2016 NES and `V201231x` in the 2020 NES will serve our key predictor (respondent's partisanship).\n\nFinally, we'll control respondents' age, using `V161267` in the 2016 NES and `V201507x` in the 2020 NES\n\n\n## Examine Distributions: Vaccine Beliefs {.smaller}\n\nThe variables in the NES datasets are of a class `labelled` which allows numeric values to have substantive labels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"haven_labelled\"\n```\n\n\n:::\n:::\n\n\nOur outcome variable has the following labels:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabelled::val_labels(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                   -9. Refused \n                                            -9 \n                                -8. Don't know \n                                            -8 \n-7. No post data, deleted due to incomplete IW \n                                            -7 \n                -6. No post-election interview \n                                            -6 \n                      1. Benefits much greater \n                                             1 \n                2. Benefits moderately greater \n                                             2 \n                  3. Benefits slightly greater \n                                             3 \n                              4. No difference \n                                             4 \n                     5. Risks slightly greater \n                                             5 \n                   6. Risks moderately greater \n                                             6 \n                         7. Risks much greater \n                                             7 \n```\n\n\n:::\n:::\n\n\nAnd distribution of responses:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  -9   -8   -7   -6    1    2    3    4    5    6    7 \n  21   28   86  536 1687  726  258  539   96  211   82 \n```\n\n\n:::\n:::\n\n\n## Recoding outcome variables\n\n:::: panel-tabset\n\n## Tasks\n\nWhat transformations do we need to make to `V162162x` in `nes16` and `V202383x` in `nes20` so that these variables are suitable for analysis?\n\n- Recode negative values to be `NA`\n\n- Reverse code so that higher values indicate greater belief vaccines benefits\n\n- Create an indicator of people who are vaccine skeptics\n\n## {{< fa code >}} Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes16 %>%\n  mutate(\n    # Make Negative values NA, Reverse Code So Higher Values = Benefits > Risks\n    vaccine_benefits = ifelse(V162162x < 0, NA, (V162162x-8)*-1),\n    # Indicator of vaccine skepticism (Risks > Benefits)\n    vaccine_skeptic01 = case_when(\n      vaccine_benefits > 4 ~ 0,\n      vaccine_benefits <= 4 ~ 1,\n      TRUE ~ NA_real_\n    )\n  ) -> nes16 # Save recodes to nes16\n\nnes20 %>%\n  mutate(\n    # Make Negative values NA, Reverse Code So Higher Values = Benefits > Risks\n    vaccine_benefits = ifelse(V202383x < 0, NA, (V202383x-8)*-1),\n    # Indicator of vaccine skepticism (Risks > Benefits)\n    vaccine_skeptic01 = case_when(\n      vaccine_benefits > 4 ~ 0,\n      vaccine_benefits <= 4 ~ 1,\n      TRUE ~ NA_real_\n    )\n  ) -> nes20 # Save recodes to nes20\n```\n:::\n\n\n::::\n\n## Recoding Predictors\n\n:::: panel-tabset\n\n## Tasks\n\n:::{.nonincremental}\n\nNow we repeat this process for our key predictor, partisanship.\n\n- Recode partisanship variables `V161158x` in `nes16` and `V201231x` in `nes20`\n\n- Create indicators from this recoded variable that classify partisanship as categorical variable (with Democrats as the reference category)\n\nAnd our covariate, age variables `V161267` in `nes16` and `V201507x` in `nes20`\n\n- Recode negative values to be `NA`\n\n:::\n\n## {{<fa code >}} Code \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes16 %>%\n  mutate(\n    pid = ifelse(V161158x < 0, NA, V161158x),\n    pid3cat = case_when(\n      pid < 4 ~ \"Democrat\",\n      pid == 4 ~ \"Independent\",\n      pid > 4 ~ \"Republican\",\n      TRUE ~ \"Independent\"\n    ) %>% factor(., levels = c(\"Democrat\",\"Independent\",\"Republican\")),\n    age = ifelse(V161267 < 0, NA, V161267)\n  ) -> nes16\n\n## Recoding Partisanship (V201231x) in 2020 NES\n\nnes20 %>%\n  mutate(\n    pid = ifelse(V201231x < 0, NA, V201231x),\n    pid3cat = case_when(\n      pid < 4 ~ \"Democrat\",\n      pid == 4 ~ \"Independent\",\n      pid > 4 ~ \"Republican\",\n      TRUE ~ \"Independent\"\n    ) %>% factor(., levels = c(\"Democrat\",\"Independent\",\"Republican\")),\n    age = ifelse(V201507x < 0, NA, V201507x)\n  ) -> nes20\n```\n:::\n\n\n::::\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- **Summarize our data**📥\n\n- Specify our expectations\n\n- Estimate models to test these expectations\n\n- Presenting and interpreting results using\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis tests \n\n\n## Descriptive statistics (2016) {.smaller}\n\n:::: panel-tabset\n\n## Tasks \n\n1.  Create `the_vars`\n\n2.  Select these variables\n\n3.  Pivot the data\n\n4.  Calculate summary statistics\n\n5.  Format as an html table\n\n## {{< fa code >}} Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Create a object with the names of the variables you want to summarize\nthe_vars <- c(\"vaccine_skeptic01\",\"pid\",\"age\")\n# 2. Select these variables\nnes16 %>%\n  select(all_of(the_vars)) %>%\n# 3. Pivot the data\n  pivot_longer(\n    cols = all_of(the_vars),\n    names_to = \"Variable\"\n  )%>%\n  mutate(\n    Variable = factor(Variable, levels = the_vars)\n  )%>%\n  arrange(Variable)%>%\n  dplyr::group_by(Variable)%>%\n  # 3. Calculate summary statistics\n  dplyr::summarise(\n    min = min(value, na.rm=T),\n    p25 = quantile(value, na.rm=T, prob = 0.25),\n    Median = quantile(value, na.rm=T, prob = 0.5),\n    mean = mean(value, na.rm=T),\n    p75 = quantile(value, na.rm=T, prob = 0.25),\n    max = max(value, na.rm=T),\n    missing = sum(is.na(value))\n  ) -> sum_df \n\nsum_tab <- \nknitr::kable(sum_df,\n             caption = \"Descriptive Statistics\",\n             digits = 2) %>%\n  kableExtra::kable_styling() %>%\n  kableExtra::pack_rows(\"Outcome\", start_row = 1, end_row =1) %>%\n  kableExtra::pack_rows(\"Key Predictors\", start_row = 2, end_row =2) %>%\n  kableExtra::pack_rows(\"Covariates\", start_row = 3, end_row =3)\n```\n:::\n\n\n## {{<fa table >}} Table\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Descriptive Statistics</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> min </th>\n   <th style=\"text-align:right;\"> p25 </th>\n   <th style=\"text-align:right;\"> Median </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> p75 </th>\n   <th style=\"text-align:right;\"> max </th>\n   <th style=\"text-align:right;\"> missing </th>\n  </tr>\n </thead>\n<tbody>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Outcome</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> vaccine_skeptic01 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.26 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 671 </td>\n  </tr>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Key Predictors</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> pid </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 3.86 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Covariates</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> age </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:right;\"> 49.58 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 90 </td>\n   <td style=\"text-align:right;\"> 121 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::::\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- *Summarize our data* ✅\n\n- **Specify our expectations** 📥\n\n- Estimate models to test these expectations\n\n- Presenting and interpreting results using\n\n  - Tables\n  - Figures\n  - Confidence intervals (review)\n  - Hypothesis tests (new!)\n\n## Specificying Expecations {.smaller}\n\n:::{.nonincremental}\n\nConsider our first two motivating questions\n\n- How does partisanship shape American's perceptions of vaccines?\n\n- Who is skeptical of the benefits of vaccination?\n\nAnd some illustrative stereotypes:\n\n- \"Republicans are *anti-science*\"\n- \"Liberal always fall for Goopy *pseudo-science*\"\n- \"Independents love to *do their own research*\"\n\nWhat are the empirical implications of these claims?\n\n:::\n\n## Specificying Expecations {.smaller}\n\n:::{.nonincremental}\n\nSimilarly, consider our third question:\n\n- Have these perceptions about vaccines changed over time?\n\nAnd some similar simplified claims:\n\n- \"The Covid-19 vaccine is a miracle of modern science\"\n- \"Social media is rife with misinformation about the Covid-19 vaccine\"\n- \"Politicians are politicizing vaccine politics for political benefits\"\n\nWhat are the empirical implications of these claims?\n\n:::\n\n## Specificying Expecations {.smaller}\n\nOur goal is to take claims/conventional wisdom/theories, and derive their empirical implications:\n\n- **H1: Partisan Differences in Vaccine Skepticism**\n  - **H1a:** Republicans will be the most skeptical of vaccines\n  - **H1b:** Democrats will be the most skeptical of vaccines\n  - **H1c:** Independents will be the most skeptical of vaccines\n  \n## Specificying Expecations {.smaller}\n\n\n- **H2: Temporal Differences in Vaccine Skepticism**\n  - **H2a:** Vaccine skepticism will decrease from 2016 to 2020 with the widespread roll out of the Covid-19 vaccine\n  - **H2b:** Vaccine skepticism will increase from 2016 to 2020 with increased amounts of misinformation about the Covid-19 vaccine\n  \n- **H3: Partisan Difference in Vaccine Skepticism Over Time** Partisan differences in Vaccine Skepticism will increase from 2016 to 2020 with the politicization of Covid-19 policies\n\n## Motivating your expectations {.smaller}\n\nIn your final papers, unlike in these slides, your expectations should be grounded in existing theory, research, and evidence. For the present question, we might cite sources such as:\n\n- Enders, Adam M., and Steven M. Smallpage. \"Informational cues, partisan-motivated reasoning, and the manipulation of conspiracy beliefs.\" Political Communication 36.1 (2019): 83-102.\n\n- Stecula, Dominik A., and Mark Pickup. \"How populism and conservative media fuel conspiracy beliefs about COVID-19 and what it means for COVID-19 behaviors.\" Research & Politics 8.1 (2021): 2053168021993979.\n\n- Jennings, Will, et al. \"Lack of trust, conspiracy beliefs, and social media use predict COVID-19 vaccine hesitancy.\" Vaccines 9.6 (2021): 593.\n\n- Hollander, Barry A. \"Partisanship, individual differences, and news media exposure as predictors of conspiracy beliefs.\" Journalism & Mass Communication Quarterly 95.3 (2018): 691-713.\n\n## Model Specification {.smaller}\n\nTranslate these expectations into empirical models requires choices about **how to specify our models**\n\n- How should we measure/operationalize our outcome\n\n  - Should we measure beliefs about vaccines with 7-point ordinal scale or as a binary indicator of vaccine skepticism\n\n- How should we measure/operationalize our key predictor(s)\n\n  - Should we measure partisanship using a 7 point scale or as categorical variable?\n\n- What should we control for in our model?\n\n  - Factors likely to predict both our outcome and our key predictor of interest\n\n- There are rarely *definitive* answers to these questions. Instead, we will often estimate **multiple models** to try and show that our findings are **robust** to alternative specifications\n\n## Model Specification {.smaller}\n\nFor your projects, every group will almost surely estimate some form of the following:\n\n1.  Baseline bivariate model: The simplest test of the relationship between your outcome and key predictor\n\n2.  Multiple regression model: A test of the robustness of this relationship, controlling for alternative explanations\n\n## Model Specification {.smaller}\n\nIn practice, I suspect you may estimate multiple regression models such as:\n\n- Alternative specifications/operationalizations of outcomes and predictors\n\n- Interaction models to test conditional relationships\n\n- Polynomial models to test non-linear relationships\n\n## {.smaller}\n#### Translating Theoretical Claims into Empirical Expectations\n\nBefore we estimate our models in R, we will write down our models formally and empirical implications of our theoretical expectations in terms of the coefficients of our model.\n\nFor example, our baseline model might be:\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{7pt} + X\\beta + \\epsilon$$ \n\nIf $\\beta_1$ is positive this is consistent with **H1a** (greater skepticism among Republicans), - If $\\beta_2$ is negative this is consistent with **H1b** (greater skepticism among Democrats),\n\n- But how could we test **H1c** -- greater skepticism among Independents, who are \"4s\" on $\\text{PID}_{7pt}$?\n\n## {.smaller}\n#### Translating Theoretical Claims into Empirical Expectations\n\nWe could fit a polynomial regression, including both partisanship and \"partisanship squared\" to allow the relationship between partisanship and vaccine skepticism to vary non-linearly\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{7pt} +  \\beta_2 \\text{PID}_{7pt}^2+ X\\beta+ \\epsilon$$ \n\n## {.smaller}\n#### Translating Theoretical Claims into Empirical Expectations\n\nOr we could estimate a model treating Partisanship as a **categorical** variable rather than an **ordinal interval** variable. \n\nIn our recoding, we set `\"Democrat\"` to be the first level of the variable `pid3cat`, so the model R will estimate by default is:\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{Ind} +  \\beta_2 \\text{PID}_{Rep}+ X\\beta + \\epsilon$$\n\n## Testing differences over time {.smaller}\n\nTesting Hypotheses 2 and 3 involve making comparisons across models estimated on data from different surveys.\n\nFormally, testing these expectations is a little more complicated\n\n- we could pool our two surveys together include an interaction term for survey year\n\nFor our purposes, we'll treat these as more qualitative/exploratory hypotheses:\n\n- H2a/b implies overall rates of vaccine skepticism will be lower/higher in 2020 compared to 2016\n\n- H3 implies that whatever partisan differences we find in 2016 should be larger in 2020.\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- *Specify our expectations* ✅\n\n- **Estimate models to test these expectations** 📥\n\n- Presenting and interpreting results using\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis tests \n\n\n## Estimating Empirical Models \n\nHaving derived empirical implications of our theoretical expectations expressed in terms of linear regressions, now we simply have to estimate our models in R.\n\nWhen estimating the **same model** on **different datasets** we can write the formulas once\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf1 <- formula(vaccine_skeptic01 ~ pid + age)\nf2 <- formula(vaccine_skeptic01 ~ pid + I(pid^2) + age)\nf3 <- formula(vaccine_skeptic01 ~ pid3cat + age)\n```\n:::\n\n\n## Estimating Empirical Models\n\nAnd then pass it to `lm()` with different `data` arguments:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_2016 <- lm(formula = f1, data = nes16)\nm1_2020 <- lm(formula = f1, data = nes20)\nm2_2016 <- lm(formula = f2, data = nes16)\nm2_2020 <- lm(formula = f2, data = nes20)\nm3_2016 <- lm(formula = f3, data = nes16)\nm3_2020 <- lm(formula = f3, data = nes20)\n```\n:::\n\n\n## Estimating Empirical Models {.smaller}\n\n:::{.nonincremental}\n\nIf you've:\n\n- coded your data correctly\n\n- developed clear testable implications from your theoretical expectations\n\nSpecifying and estimating empirical models is straightforward. Literally a few lines of code.\n\n:::\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- *Specify our expectations* ✅\n\n- *Estimate models to test these expectations* ✅\n\n- *Present our results* 📥\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis testing\n\n## Presenting and Interpreting Your Results {.smaller}\n\nPresenting and interpreting your results is requires both art and science.\n\nYour goal is to tell a story with your results,\n\nLet's start by producing a regression table, which provides a concise summary of multiple regression models.\n\n\n## Regression Tables {.smaller}\n\n:::: panel-tabset\n\n## Tasks\n\n:::{.nonincremental}\n\n- Giving the variables in substantive names\n\n- Reporting coefficients to 3 decimal places\n\n- Using a single significance threshold of $p < 0.05$\n\n- Giving the models custom names\n\n- Adding a header to group models by year\n\n- Changing the caption of the table\n\n:::\n\n## {{< fa code >}} Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic\ntab_basic <- texreg::htmlreg(\n  list(m1_2016,m2_2016,m3_2016,\n       m1_2020,m2_2020,m3_2020)\n)\n\n# Formatted\ntab_better <- texreg::htmlreg(\n  list(m1_2016,m2_2016,m3_2016,\n       m1_2020,m2_2020,m3_2020),\n  # Reporting coefficients to 3 decimal places\n  digits = 3,\n  # Using a single significance threshold \n  stars = 0.05,\n  # Giving the variables in substantive names\n  custom.coef.names = c(\n    \"(Intercept)\",\n    \"PID (7pt)\",\n    \"Age\",\n    \"PID<sup>2</sup> (7pt)\",\n    \"Independent\",\n    \"Republican\"\n  ),\n  # Use SE instead o CIs\n  include.ci = F,\n  # Giving the models custom names\n  custom.model.names = paste(\"(\",c(1:6),\")\", sep=\"\"),\n  # Adding a header to group models by year\n  custom.header = list(\"NES 2016\" = 1:3, \"NES 2020\" = 4:6),\n  # Changing the caption of the table\n  caption = \"Partisanship and Vaccine Skepticism\"\n)\n```\n:::\n\n\n## {{< fa table >}} Basic\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 3</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 4</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 5</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 6</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.46<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.35<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.42<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.34<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.32<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.35<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.06<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.01)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid^2</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.01<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid3catIndependent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.17<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.20<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid3catRepublican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.10<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.01)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.05</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n## {{< fa table >}} Better\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(1)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(2)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(3)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(4)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(5)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(6)</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n::::\n\n## Telling a Story with Regression {.smaller}\n\n:::{.nonincremental}\n\nFirst, provide an overview the models presented in the table\n\n- Explain what each model is doing conceptually\n\nThen start with your simplest model (first column)\n\n- Use this as a chance to explain core concepts from the course\n  - What is regression\n  - How should I interpret a coefficient substantively\n  - How should I interepret the statistical signficance of a give coefficient\n- As you move from left to right (simple to more complex)\n  - you need not interpret every single coefficient in the model\n  - instead highlight the factors that are important for the reader to note (e.g. a comparison between one coefficient in model or another.)\n\n:::\n\n## Example {.smaller}\n\nTable 1 presents the results of three specifications exploring the relationship between partisanship and vaccine skepticism using data from the 2016 (Models 1-3) and 2020 (Models 4-5) National Election Studies.\n\nModels 1 and 4 operationalize partisanship as a 7-point scale, where 1 corresponds to Strong Democrats, 4 to Indepndents, and 7 to Strong Republicans in the 2016 (Model 1) and 2020 (Model 2) surveys.\n\nModels 2 and 5 allow the relationship between partisanship and vaccine skepticism to vary non-linear again for the 2016 (Model 2) and 2020 (Model 5) elections.\n\nModels 3 and 6 treat partisanship as categorical variable, describing how Independents and Republicans differ from Democrats, the reference category in these models.\n\nAll models control age, since (put in substantive justification for controlling for age here)\n\n## Story: Testing for Partisan Differences {.smaller}\n\n- The results from Model 1 provide little initial evidence for partisan differences in vaccine skepticism in the 2016 Election.\n\n  - The coefficient on the partisanship variable is -0.005, suggesting that a unit increase in partisanship (going from being a Strong Democrat to just a Democrat, or an Independent to an independent who leans Republican), is associated with just a 0.5 percentage point increase in the probability of being a vaccine skeptic (believing that the risks of vaccination outweigh the benefits or that their is no difference in the risks versus benefits).\n\n- Furthermore the 95-percent confidence interval for this estimate (-0.011, 0.002) brackets 0, suggesting the true population estimate from this model could be either positive or negative. Similarly, we fail to reject the null hypothesis that the true coefficient on partisanship in this model is 0 as the test statistic for this estimate ( -1.38) corresponds to a p-value of 0.168 suggesting that we would see test statistics this large or larger fairly often when the true relationship was 0.\n\n- In sum, the results from Model 1 provide little support for any of the expectations described by *H1*\n\n## Testing for Partisan Differences: Model 2 {.smaller}\n\n- While coefficients from Model 1 suggest little evidence of partisan differences in vaccine skepticism, the coefficients on both partisanship, and partisanship squared are statistically significant (p < 0.05).\n\n## Interpreting Model 2 {.smaller}\n\n:::: panel-tabset\n\n## Task\n\n- The coefficients from polynomial regressions can be difficult to interpret jointly and so Figure 1 presents the predicted values from Model 2, holding age constant at its sample mean.\n\n## {{< fa code >}}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_df_m2 <- expand_grid(\n  pid = 1:7,\n  age = mean(nes16$age, na.rm=T)\n)\npred_df_m2 <- cbind(pred_df_m2, predict(m2_2016,pred_df_m2, interval =\"confidence\"))\n\nfig_m2 <- pred_df_m2 %>%\n  ggplot(aes(pid, fit, ymin =lwr, ymax =upr))+\n  geom_line()+\n  geom_ribbon(alpha=.2, fill=\"grey\")+\n  theme_bw()+\n  labs(x = \"Partisanship\",\n       y = \"Predicted Vaccine Skepticism\",\n       title = \"Independents are the most skeptical of vaccines\",\n       subtitle = \"Data: 2016 NES\"\n       )\n```\n:::\n\n\n## {{< fa chart-lines>}} Figure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfig_m2\n```\n\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/pred-1.png){width=960}\n:::\n:::\n\n\n## Interpretation\n\nWe see from Model 2 that 29.7 percent \\[27.3%, 32.1%\\] of Independents in the 2016 NES were predicted to be vaccine skeptics compared to 23.7 percent \\[20.8%, 26.5%\\] of Strong Democrats and only 20.1 percent \\[16.9%, 23.3%\\] of Strong Republicans.\n\n::::\n\n## Interpreting Model 3 {.smaller}\n\n:::: panel-tabset\n\n## Interpretation\n\nModel 3 tells a similar story to model 2. Again, adjusting for differences in vaccine skepticism explained by age, Model 3 predicts that 41.7 percent \\[37.7%, 45.6%\\] of Independents in the 2016 NES are vaccine skeptics compared to 24.2 percent \\[22.1%, 26.2%\\] of Democrats, and 22.6 percent \\[20.4%, 24.8%\\] of Republicans.\n\nNote the coefficients from Model 3 imply that the differences between Independents and Democrats are statistically significant ($\\beta_{Ind} = 0.175, p < 0.05$), the differences between Republicans and Democrats are not ($\\beta_{Rep} = -0.004, p = 0.31$)\n\n## {{< fa code >}} Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_df_m3 <- expand_grid(\n  pid3cat = c(\"Democrat\", \"Independent\",\"Republican\"),\n  age = mean(nes16$age, na.rm=T)\n)\npred_df_m3 <- cbind(pred_df_m3, predict(m3_2016,pred_df_m3, interval =\"confidence\"))\npred_df_m3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pid3cat      age       fit       lwr       upr\n1    Democrat 49.58231 0.2419547 0.2211228 0.2627867\n2 Independent 49.58231 0.4169043 0.3773539 0.4564547\n3  Republican 49.58231 0.2261496 0.2038046 0.2484947\n```\n\n\n:::\n:::\n\n\n::::\n\n## {.smaller}\n\n\n\n```{.r .cell-code}\ntab_better\n```\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(1)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(2)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(3)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(4)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(5)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(6)</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n\n## Testing for Differences Over Time {.smaller}\n\nThe results for the 2016 NES suggest political independents are most skeptical of vaccines.\n\nThe results for 2020 suggest the relationship between partisanship and vaccine skepticism has changed overtime.\n\n- The coefficient on partisanship in model 4 is now positive and statistically significant (p \\< 0.05), suggesting that as respondents become more Republican, they are more likely to be skeptical of vaccines\n\n- The coefficients from Model 5 suggest the relationship between partisanship skepticism is non linear, which is confirmed by model 6.\n\n- In Model 6, we see that independents remain the most skeptical of vaccines in 2020 $(\\beta = 0.20,\\, p <0.05)$, but that Republicans now tend to be more skeptical of vaccines than Democrats $(\\beta = 0.10,\\, p <0.05)$\n\n# {{< fa magnifying-glass>}} Presentations {.inverse}\n\n## Presentations {.smaller}\n\n- Motivation\n\n- Research Question\n\n- Theory\n\n- Expectations\n\n- Data\n\n  - Summary\n\n  - Descriptive Table and/or Figure (Optional)\n\n- Design\n\n- Results\n\n  - Summary\n\n  - Table (Optional)\n\n  - Figure (Optional)\n\n- Conclusion\n\n-   Appendices (Extra Slides Optional)\n\n## Template\n\nLet's open up the [template](https://josephessig-source.github.io/pols1600_site/assignments/a5.html) and explore.\n\n",
    "supporting": [
      "12-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}