{
  "hash": "4ac6ff5de071333f6da154295c51dba1",
  "result": {
    "markdown": "---\ntitle: \"POLS 1600\"\nsubtitle: \"Prediction I / Linear Regression\"\ndate: last-modified\ndate-format: \"[Updated ]MMM D, YYYY\"\nformat: \n  revealjs:\n    theme: brownslides.scss\n    logo: images/pols1600_hex.png\n    footer: \"POLS 1600\"\n    multiplex: false\n    transition: fade\n    slide-number: c\n    incremental: true\n    center: false\n    menu: true\n    scrollable: true\n    html-math-method: mathjax\n    highlight-style: github\n    progress: true\n    code-overflow: wrap\n    chalkboard: true\n    # include-after-body: title-slide.html\n    title-slide-attributes:\n      align: left\n      data-background-image: images/pols1600_hex.png\n      data-background-position: 90% 50%\n      data-background-size: 40%\nfilters:\n  - openlinksinnewpage\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\n  cache: true\n---\n\n::: {.cell hash='05-slides_cache/revealjs/init_334d35322b786139d378bd1c4a10d860'}\n\n:::\n\n\n# {{< fa map-location>}} Overview {.inverse}\n\n## Overview\n\n- Class goals\n- Announcements\n\n## Learing goals {.smaller}\n\n- Focus on making predictions with linear regression \n\n- Introduce use of research design to make causal claims with observational data\n\n  - [Differences-in-Differences]{.blue}\n\n## Annoucements\n\n- Tutorial 5 due on Monday 3-2. \n\n- Resuming labs on Friday - [link here](https://josephessig-source.github.io/pols1600_site/labs/05-lab.qmd)\n\n- If any issues with group assignment, let me know after class.\n\n-  2nd group assignment next week - will be due Sunday, 3-8. \n\n## Packages for today\n\n\n::: {.cell hash='05-slides_cache/revealjs/packages_0f17e68e5f1679afe47a4c940dfa7f83'}\n\n```{.r .cell-code}\n## Pacakges for today\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"easystats\", \"zoo\"\n)\n\n#new.packages <- the_packages[!(the_packages %in% installed.packages()[,\"Package\"])]\n# \n# # 3. If there are any missing packages, install them\n# if(length(new.packages)) {\n#     install.packages(new.packages, dependencies = TRUE)}\n#\n## Define a function to load packages\n\nlapply(the_packages, library, character.only = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n [1] \"kableExtra\"    \"see\"           \"report\"        \"parameters\"   \n [5] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n [9] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[13] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[17] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[21] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[25] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[29] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[33] \"datasets\"      \"methods\"       \"base\"         \n\n[[2]]\n [1] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n [5] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n [9] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[13] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[17] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[21] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[25] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[29] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[33] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[3]]\n [1] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[4]]\n [1] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[5]]\n [1] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[6]]\n [1] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[7]]\n [1] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[8]]\n [1] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [5] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n [9] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[13] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[17] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[21] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[25] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[29] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[33] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[37] \"base\"         \n\n[[9]]\n [1] \"ggmap\"         \"texreg\"        \"DT\"            \"kableExtra\"   \n [5] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n [9] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[13] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[17] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[21] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[25] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[29] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[33] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[37] \"methods\"       \"base\"         \n\n[[10]]\n [1] \"ggrepel\"       \"ggmap\"         \"texreg\"        \"DT\"           \n [5] \"kableExtra\"    \"see\"           \"report\"        \"parameters\"   \n [9] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[13] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[17] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[21] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[25] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[29] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[33] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[37] \"datasets\"      \"methods\"       \"base\"         \n\n[[11]]\n [1] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"texreg\"       \n [5] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n [9] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[13] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[17] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[21] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[25] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[29] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[33] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[37] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[12]]\n [1] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n [5] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n [9] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[13] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[17] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[21] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[25] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[29] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[33] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[37] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[41] \"base\"         \n\n[[13]]\n [1] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n [5] \"ggmap\"         \"texreg\"        \"DT\"            \"kableExtra\"   \n [9] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[13] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[17] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[21] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[25] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[29] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[33] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[37] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[41] \"methods\"       \"base\"         \n\n[[14]]\n [1] \"scales\"        \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n [5] \"ggrepel\"       \"ggmap\"         \"texreg\"        \"DT\"           \n [9] \"kableExtra\"    \"see\"           \"report\"        \"parameters\"   \n[13] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[17] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[21] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[25] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[29] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[33] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[37] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[41] \"datasets\"      \"methods\"       \"base\"         \n\n[[15]]\n [1] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n [5] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"texreg\"       \n [9] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n[13] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[17] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[21] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[25] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[29] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[33] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[37] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[41] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[16]]\n [1] \"ggdag\"         \"dagitty\"       \"scales\"        \"ggpubr\"       \n [5] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n [9] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n[13] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[17] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[21] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[25] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[29] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[33] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[37] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[41] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[45] \"base\"         \n\n[[17]]\n [1] \"ggforce\"       \"ggdag\"         \"dagitty\"       \"scales\"       \n [5] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n [9] \"ggmap\"         \"texreg\"        \"DT\"            \"kableExtra\"   \n[13] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[17] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[21] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[25] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[29] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[33] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[37] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[41] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[45] \"methods\"       \"base\"         \n\n[[18]]\n [1] \"COVID19\"       \"ggforce\"       \"ggdag\"         \"dagitty\"      \n [5] \"scales\"        \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n [9] \"ggrepel\"       \"ggmap\"         \"texreg\"        \"DT\"           \n[13] \"kableExtra\"    \"see\"           \"report\"        \"parameters\"   \n[17] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[21] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[25] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[29] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[33] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[37] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[41] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[45] \"datasets\"      \"methods\"       \"base\"         \n\n[[19]]\n [1] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [5] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n [9] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"texreg\"       \n[13] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n[17] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[21] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[25] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[29] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[33] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[37] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[41] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[45] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[20]]\n [1] \"mapdata\"       \"maps\"          \"COVID19\"       \"ggforce\"      \n [5] \"ggdag\"         \"dagitty\"       \"scales\"        \"ggpubr\"       \n [9] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[13] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n[17] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[21] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[25] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[29] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[33] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[37] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[41] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[45] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[49] \"base\"         \n\n[[21]]\n [1] \"qss\"           \"mapdata\"       \"maps\"          \"COVID19\"      \n [5] \"ggforce\"       \"ggdag\"         \"dagitty\"       \"scales\"       \n [9] \"ggpubr\"        \"ggthemes\"      \"ggridges\"      \"ggrepel\"      \n[13] \"ggmap\"         \"texreg\"        \"DT\"            \"kableExtra\"   \n[17] \"see\"           \"report\"        \"parameters\"    \"performance\"  \n[21] \"modelbased\"    \"insight\"       \"effectsize\"    \"datawizard\"   \n[25] \"correlation\"   \"bayestestR\"    \"easystats\"     \"DeclareDesign\"\n[29] \"estimatr\"      \"fabricatr\"     \"randomizr\"     \"haven\"        \n[33] \"labelled\"      \"lubridate\"     \"forcats\"       \"stringr\"      \n[37] \"dplyr\"         \"purrr\"         \"readr\"         \"tidyr\"        \n[41] \"tibble\"        \"ggplot2\"       \"tidyverse\"     \"stats\"        \n[45] \"graphics\"      \"grDevices\"     \"utils\"         \"datasets\"     \n[49] \"methods\"       \"base\"         \n\n[[22]]\n [1] \"tidycensus\"    \"qss\"           \"mapdata\"       \"maps\"         \n [5] \"COVID19\"       \"ggforce\"       \"ggdag\"         \"dagitty\"      \n [9] \"scales\"        \"ggpubr\"        \"ggthemes\"      \"ggridges\"     \n[13] \"ggrepel\"       \"ggmap\"         \"texreg\"        \"DT\"           \n[17] \"kableExtra\"    \"see\"           \"report\"        \"parameters\"   \n[21] \"performance\"   \"modelbased\"    \"insight\"       \"effectsize\"   \n[25] \"datawizard\"    \"correlation\"   \"bayestestR\"    \"easystats\"    \n[29] \"DeclareDesign\" \"estimatr\"      \"fabricatr\"     \"randomizr\"    \n[33] \"haven\"         \"labelled\"      \"lubridate\"     \"forcats\"      \n[37] \"stringr\"       \"dplyr\"         \"purrr\"         \"readr\"        \n[41] \"tidyr\"         \"tibble\"        \"ggplot2\"       \"tidyverse\"    \n[45] \"stats\"         \"graphics\"      \"grDevices\"     \"utils\"        \n[49] \"datasets\"      \"methods\"       \"base\"         \n\n[[23]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"texreg\"       \n[17] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n[21] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[25] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[29] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[33] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[37] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[41] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[45] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[49] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[24]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"texreg\"       \n[17] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n[21] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[25] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[29] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[33] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[37] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[41] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[45] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[49] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[25]]\n [1] \"dataverse\"     \"tidycensus\"    \"qss\"           \"mapdata\"      \n [5] \"maps\"          \"COVID19\"       \"ggforce\"       \"ggdag\"        \n [9] \"dagitty\"       \"scales\"        \"ggpubr\"        \"ggthemes\"     \n[13] \"ggridges\"      \"ggrepel\"       \"ggmap\"         \"texreg\"       \n[17] \"DT\"            \"kableExtra\"    \"see\"           \"report\"       \n[21] \"parameters\"    \"performance\"   \"modelbased\"    \"insight\"      \n[25] \"effectsize\"    \"datawizard\"    \"correlation\"   \"bayestestR\"   \n[29] \"easystats\"     \"DeclareDesign\" \"estimatr\"      \"fabricatr\"    \n[33] \"randomizr\"     \"haven\"         \"labelled\"      \"lubridate\"    \n[37] \"forcats\"       \"stringr\"       \"dplyr\"         \"purrr\"        \n[41] \"readr\"         \"tidyr\"         \"tibble\"        \"ggplot2\"      \n[45] \"tidyverse\"     \"stats\"         \"graphics\"      \"grDevices\"    \n[49] \"utils\"         \"datasets\"      \"methods\"       \"base\"         \n\n[[26]]\n [1] \"zoo\"           \"dataverse\"     \"tidycensus\"    \"qss\"          \n [5] \"mapdata\"       \"maps\"          \"COVID19\"       \"ggforce\"      \n [9] \"ggdag\"         \"dagitty\"       \"scales\"        \"ggpubr\"       \n[13] \"ggthemes\"      \"ggridges\"      \"ggrepel\"       \"ggmap\"        \n[17] \"texreg\"        \"DT\"            \"kableExtra\"    \"see\"          \n[21] \"report\"        \"parameters\"    \"performance\"   \"modelbased\"   \n[25] \"insight\"       \"effectsize\"    \"datawizard\"    \"correlation\"  \n[29] \"bayestestR\"    \"easystats\"     \"DeclareDesign\" \"estimatr\"     \n[33] \"fabricatr\"     \"randomizr\"     \"haven\"         \"labelled\"     \n[37] \"lubridate\"     \"forcats\"       \"stringr\"       \"dplyr\"        \n[41] \"purrr\"         \"readr\"         \"tidyr\"         \"tibble\"       \n[45] \"ggplot2\"       \"tidyverse\"     \"stats\"         \"graphics\"     \n[49] \"grDevices\"     \"utils\"         \"datasets\"      \"methods\"      \n[53] \"base\"         \n```\n:::\n:::\n\n\n\n# {{< fa lightbulb >}} Simple Linear Regression {.inverse}\n\n## Understanding Linear Regression{.smaller}\n\n\n:::{.nonincremental}\n- **Conceptual**\n  - Simple linear regression estimates \"a line of best fit\" that summarizes relationships between two variables\n\n$$\ny_i = \\beta_0 + \\beta_1x_i + \\epsilon_i\n$$\n\n- **Practical**\n  - We estimate linear models in R using the `lm()` function\n\n\n::: {.cell hash='05-slides_cache/revealjs/unnamed-chunk-1_10ecd4d008764f4f2fcaec420c886484'}\n\n```{.r .cell-code}\nlm(y ~ x, data = df)\n```\n:::\n\n\n:::\n\n## Understanding Linear Regression{.smaller}\n\n:::{.nonincremental}\n\n- *Technical/Definitional*\n  - Linear regression chooses $\\beta_0$ and $\\beta_1$ to minimize the Sum of Squared Residuals (SSR):\n\n$$\\textrm{Find }\\hat{\\beta_0},\\,\\hat{\\beta_1} \\text{ arg min}_{\\beta_0, \\beta_1} \\sum (y_i-(\\beta_0+\\beta_1x_i))^2$$\n\n- *Theoretical*\n  - Linear regression provides a **linear** estimate of the conditional expectation function (CEF): $E[Y|X]$\n\n:::\n\n\n# {{< fa lightbulb >}} Conceptual: Linear Regression {.inverse}\n\n## Conceptual: Linear Regression\n\n- Regression is a tool for describing relationships.\n\n  - How does some outcome we're interested in tend to change as some predictor of that outcome changes?\n\n  - How does economic development vary with democracy?\n    \n    - Or how does democracy vary with economic development...\n\n  - How does economic development vary with democracy, adjusting for natural resources like oil and gas\n\n\n## Conceptual: Linear Regression {.smaller}\n\n:::{.nonincremental}\n\nMore formally:\n\n$$\ny_i = f(x_i) + \\epsilon\n$$\n\n- Y is a function of X plus some error, $\\epsilon$\n\n- Linear regression assumes that relationship between an outcome and a predictor can be described by a [linear](https://en.wikipedia.org/wiki/Linearity) function\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i + \\epsilon\n$$\n:::\n\n## Linear Regression and the Line of Best Fit {.smaller}\n\n:::{.nonincremental}\n\n\n- The goal of linear regression is to choose coefficients $\\beta_0$ and $\\beta_1$ to summarizes the relationship between $y$ and $x$\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i + \\epsilon\n$$\n\n- To accomplish this we need some sort of criteria.\n\n- For linear regression, that criteria is minimizing the error between what our model predicts $\\hat{y_i} = \\beta_0 + \\beta_1 x_i$ and what we actually observed $(y_i)$\n\n- More on this to come. But first...\n\n:::\n\n## Regression Notation{.smaller}\n\n- $y_i$ an **outcome variable** or thing we're trying to explain\n\n  - AKA: The dependent variable, The response variable, The left hand side of the model\n\n- $x_i$ a **predictor variables** or things we think explain variation in our outcome\n\n  - AKA: The independent variable, covariates, the right hand side of the model.\n\n  - Cap or No Cap: I'll use $X$ (should be $\\mathbf{X}$) to denote a set (matrix) of predictor variables. $y$ vs $Y$ can also have technical distinctions (Sample vs Population, observed value vs Random Variable, ...)\n\n- $\\beta$ a set of **unknown parameters** that describe the relationship between our outcome $y_i$ and our predictors $x_i$\n\n- $\\epsilon_i$ the **error term** representing variation in $y_i$ not explained by our model.\n\n- $\\hat{\\epsilon_i}$  is a residual, or an estimate of the error, given a model.\n\n## Linear Regression {.smaller}\n\n:::{.nonincremental}\n\n- We call this a bivariate regression, because there are only two variables\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i + \\epsilon_i\n$$\n\n- We call this a linear regression, because $y_i = \\beta_0 + \\beta_1 x_i$ is the equation for a line, where:\n\n  - $\\beta_0$ corresponds to the $y$ intercept, or the model's prediction when $x = 0$.\n\n  - $\\beta_1$ corresponds to the slope, or how $y$ is predicted to change as $x$ changes.\n:::\n\n## Linear Regression {.smaller}\n\n:::{.nonincremental}\n\n- If you find this notation confusing, try plugging in substantive concepts for what $y$ and $x$ represent\n- Say we wanted to know how attitudes to transgender people varied with age in the baseline survey from Lab 03.\n\nThe generic linear model\n\n$$y_i = \\beta_0 + \\beta_1 x_i + \\epsilon_i$$\n\nReflects:\n\n$$\\text{Transgender Feeling Thermometer}_i = \\beta_0 + \\beta_1\\text{Age}_i + \\epsilon_i$$\n:::\n\n# {{< fa lightbulb >}} Practical: Estimating a Linear Regression {.inverse}\n\n## Practical: Estimating a Linear Regression{.smaller}\n\n:::{.nonincremental}\n\n- We estimate linear regressions in `R` using the `lm()` function.\n- `lm()` requires two arguments:\n  - a `formula` argument of the general form `y ~ x` read as \"Y modeled by X\" or below \"Transgender Feeling Thermometer (`y`) modeled by (`~`) Age (`x`)\n  - a `data` argument telling R where to find the variables in the formula\n\n\n::: {.cell hash='05-slides_cache/revealjs/lmdata_e7fea831c346e2659804d085a49db4a9'}\n\n```{.r .cell-code}\nload(url(\"https://pols1600.paultesta.org/files/data/03_lab.rda\"))\nm1 <- lm(therm_trans_t0 ~ vf_age, data = df)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = therm_trans_t0 ~ vf_age, data = df)\n\nCoefficients:\n(Intercept)       vf_age  \n    62.8196      -0.2031  \n```\n:::\n:::\n\n\n:::\n\n## The `lm()` function{.smaller}\n\n:::{.nonincremental}\n\nThe coefficients from `lm()` are saved in object called `m1`\n\n\n::: {.cell hash='05-slides_cache/revealjs/printm1_c38befd6107e8f6760415071deff8496'}\n\n```{.r .cell-code}\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = therm_trans_t0 ~ vf_age, data = df)\n\nCoefficients:\n(Intercept)       vf_age  \n    62.8196      -0.2031  \n```\n:::\n:::\n\n\n`m1` actually contains a lot of information\n\n\n::: {.cell hash='05-slides_cache/revealjs/m1info_d04dcc4b05bcfb2f145b4ee1c3ff178b'}\n\n```{.r .cell-code}\nnames(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"coefficients\"  \"residuals\"     \"effects\"       \"rank\"         \n [5] \"fitted.values\" \"assign\"        \"qr\"            \"df.residual\"  \n [9] \"na.action\"     \"xlevels\"       \"call\"          \"terms\"        \n[13] \"model\"        \n```\n:::\n\n```{.r .cell-code}\nm1$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      vf_age \n 62.8195994  -0.2030711 \n```\n:::\n:::\n\n\n:::\n\n## Practical: Interpreting a Linear Regression{.smaller}\n\nWe can extract the intercept and slope from this simple bivariate model, using the `coef()` function\n\n\n::: {.cell hash='05-slides_cache/revealjs/m1coef_5112d36d47695b320e1f7fafe5024b5e'}\n\n```{.r .cell-code}\n# All the coefficients\ncoef(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      vf_age \n 62.8195994  -0.2030711 \n```\n:::\n\n```{.r .cell-code}\n# Just the intercept\ncoef(m1)[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n    62.8196 \n```\n:::\n\n```{.r .cell-code}\n# Just the slope\ncoef(m1)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    vf_age \n-0.2030711 \n```\n:::\n:::\n\n\n## Practical: Interpreting a Linear Regression{.smaller}\n\nThe two coefficients from `m1` define a line of best fit, summarizing how feelings toward transgender individuals change with age\n\n$$y_i = \\beta_0 + \\beta_1 x_i + \\epsilon_i$$\n\n$$\\text{Transgender Feeling Thermometer}_i = \\beta_0 + \\beta_1\\text{Age}_i + \\epsilon_i$$\n\n$$\\text{Transgender Feeling Thermometer}_i = 62.82 + -0.2 \\text{Age}_i + \\epsilon_i$$\n\n## Practical: Predicted values from a Linear Regression{.smaller}\n\n:::{.nonincremental}\n\n- Often it's useful for interpretation to obtain [predicted values]{.blue} from a regression.\n\n- To obtain predicted vales $(\\hat{y})$, we simply plug in a value for $x$ (In this case, $Age$) and evaluate our equation.\n\n- For example, might we expect attitudes to differ among an 18-year-old college student and their 68-year-old grandparent?\n\n$$\\hat{FT}_{x=18} = 62.82 + -0.2 \\times 18  = 59.16$$ $$\\hat{FT}_{x=65} = 62.82 + -0.2 \\times 68  = 49.01$$\n:::\n\n## Practical: Predicted values from a Linear Regression\n\nWe could do this by hand\n\n\n::: {.cell hash='05-slides_cache/revealjs/pred_man_c762ba31963bb80cbf0114a3bc95f9f3'}\n\n```{.r .cell-code}\ncoef(m1)[1] + coef(m1)[2] * 18\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   59.16432 \n```\n:::\n\n```{.r .cell-code}\ncoef(m1)[1] + coef(m1)[2] * 68\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   49.01076 \n```\n:::\n:::\n\n\n## Practical: Predicted values from a Linear Regression{.smaller}\n\nMore often we will:\n\n- Make a [prediction data frame]{.blue} (called `pred_df` below) with the values of interests\n- Use the `predict()` function with our linear model (`m1`) and `pred_df`\n- Save the predicted values to our new column in our prediction data frame\n\n## Practical: Predicted values from a Linear Regression\n\n\n::: {.cell hash='05-slides_cache/revealjs/pred_df_58a9fb6c1c1064116d4d8f69403d4271'}\n\n```{.r .cell-code}\n# Make prediction data frame\npred_df <- data.frame(\n  vf_age = c(18, 68)\n)\n# Predict FT for 18 and 68 year-olds\npredict(m1, newdata = pred_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1        2 \n59.16432 49.01076 \n```\n:::\n\n```{.r .cell-code}\n# Save predictions to data frame\npred_df$ft_trans_hat <- predict(m1, newdata = pred_df)\npred_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  vf_age ft_trans_hat\n1     18     59.16432\n2     68     49.01076\n```\n:::\n:::\n\n\n##\n#### Practical: Visualizing Linear Regression\n\n::: panel-tabset\n\n## Concept\nWe can visualize simple regression by:\n\n- plotting a scatter plot of the outcome (y-axis) and predictors (x-axis)\n\n- overlaying the line defined by `lm()`\n\n\n## Code\n\n::: {.cell hash='05-slides_cache/revealjs/fig_lm_code_33920b7b83eb852c62bc5f5d1bfa6c79'}\n\n```{.r .cell-code}\nload(url(\"https://pols1600.paultesta.org/files/data/03_lab.rda\"))\nfig_lm <- \n  ggplot(data=df, mapping=aes(vf_age,therm_trans_t0))+\n  geom_point(size=.5, alpha=.5)+\n  geom_abline(intercept = coef(m1)[1],\n              slope = coef(m1)[2],\n              col = \"blue\"\n              )+\n  geom_vline(xintercept = 0,linetype = 2)+\n  xlim(0,100)+\n  annotate(\"point\",\n           x = 0, y = coef(m1)[1],\n           col= \"red\",\n           )+\n annotate(\"text\",\n           label = \"beta[0] == 62.81\", \n           parse = TRUE,              \n           x = 1, y = coef(m1)[1]+5,\n           hjust = \"left\",\n           )+\n  labs(\n    x = \"Age\",\n    y = \"Feeling Thermometer toward\\nTransgender People\"\n  )+\n  theme_classic() -> fig_lm\n```\n:::\n\n\n\n## Intercept\n\n::: {.cell hash='05-slides_cache/revealjs/fig_lm_plot_8b115887ffcd54bd775fb764788187b0'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/fig_lm_plot-1.png){width=960}\n:::\n:::\n\n\n## Slope\n\n\n::: {.cell hash='05-slides_cache/revealjs/figlm1_710cc3ff2f2bba4d2999cae0288f13f0'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/figlm1-1.png){width=960}\n:::\n:::\n\n\n## Errors\n\n::: {.cell hash='05-slides_cache/revealjs/figlm1code_0b19f5ef534410b6789f61881e33865b'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/figlm1code-1.png){width=960}\n:::\n:::\n\n\n:::\n\n# {{< fa lightbulb >}} Technichal: Mechanics of Linear Regression {background-color=\"lightgrey\"}\n\n## How did `lm()` choose $\\beta_0$ and $\\beta_1${.smaller}\n\n:::{.nonincremental}\n\n- P: By minimizing the sum of squared errors, in procedure called Ordinary Least Squares (OLS) regression\n\n\n\n- Q: Ok, that's not really that helpful...\n\n  - What's an error?\n  - Why would we square and sum them\n  - How do we minimize them.\n\nP: Good questions!\n\n:::\n\n## What's an error? What's a residual{.smaller}\n\nRecall an error, $\\epsilon_i$, is the deviation of from an unknown true model\n\n$$\ny_i = f(x_i) + \\epsilon_i\n$$\n\nA residual, $\\hat{\\epsilon_i}$ is an estimate of the error obtained by taking the difference between the observed value of $y_i$ and what our model would predict, $\\hat{y_i}$ given some value of $x_i$. So for a model:\n\n$$y_i=\\beta_0+\\beta_1 x_{i} + \\epsilon_i$$\n\nWe simply subtract our model's prediction $\\beta_0+\\beta_1 x_{i}$ from the observed value, $y_i$\n\n$$\\hat{\\epsilon_i}=y_i-\\hat{y_i}=(Y_i-(\\beta_0+\\beta_1 x_{i}))$$\n \n\n## Why are we squaring and summing $\\epsilon${.smaller}\n\n:::{.nonincremental}\n\nThere are more mathy reasons for this, but at intuitive level, the Sum of Squared Residuals (SSR)\n\n- Squaring $\\epsilon$ treats positive and negative residuals equally.\n\n- Summing produces single value summarizing our models overall performance.\n\nThere are other criteria we could use (e.g. minimizing the sum of absolute errors), but SSR has some nice properties\n:::\n\n## How do we minimize $\\sum \\epsilon^2$ {.smaller}\n\nOLS chooses $\\beta_0$ and $\\beta_1$ to minimize $\\sum \\epsilon^2$, the Sum of Squared Residuals (SSR)\n\n$$\\textrm{Find }\\hat{\\beta_0},\\,\\hat{\\beta_1} \\text{ arg min}_{\\beta_0, \\beta_1} \\sum (y_i-(\\beta_0+\\beta_1x_i))^2$$\n\n## How did `lm()` choose $\\beta_0$ and $\\beta_1$ {.smaller}\n\nIn an intro stats course, we would walk through the process of finding\n\n$$\\textrm{Find }\\hat{\\beta_0},\\,\\hat{\\beta_1} \\text{ arg min}_{\\beta_0, \\beta_1} \\sum (y_i-(\\beta_0+\\beta_1x_i))^2$$ Which involves a little bit of calculus. The big payoff is that\n\n$$\\beta_0 = \\bar{y} - \\beta_1 \\bar{x}$$ And\n\n$$ \\beta_1 = \\frac{Cov(x,y)}{Var(x)}$$\n\n\n# {{< fa lightbulb >}} Theoretical:  OLS provides a linear estimate of CEF: E\\[Y|X\\]{.inverse}\n\n## Interpretations of Linear Regression{.smaller}\n\n[Timothy Lin](https://www.timlrx.com/tags/ols) provides a great overview of the various interpretations/motivations for linear regression.\n\n- A [least squares estimator](https://www.timlrx.com/blog/notes-on-regression-ols)\n\n- A [linear projection](https://www.timlrx.com/blog/notes-on-regression-geometry) of $y$ on the subspace spanned by $X\\beta$\n\n- A [method of moments estimator](https://www.timlrx.com/blog/notes-on-regression-method-of-moments)\n\n- A [maximum likelihood estimator](https://www.timlrx.com/blog/notes-on-regression-maximum-likelihood)\n\n- A [singular vector decomposition](https://www.timlrx.com/blog/notes-on-regression-singular-vector-decomposition)\n\n- A [**linear approximation of the conditional expectation function**](https://www.timlrx.com/blog/notes-on-regression-approximation-of-the-conditional-expectation-function#fn1)\n\n## The Conditional Expectation Function{.smaller}\n\nOf all the functions we could choose to describe the relationship between $Y$ and $X$,\n\n$$\nY_i = f(X_i) + \\epsilon_i\n$$\n\nthe conditional expectation of $Y$ given $X$ $(E[Y|X])$, has some appealing properties\n\n$$\nY_i = E[Y_i|X_i] + \\epsilon\n$$\n\nThe error, by definition, is uncorrelated with X and $E[\\epsilon|X]=0$\n\n$$\nE[\\epsilon|X] = E[Y - E[Y|X]|X]= E[Y|X] - E[Y|X] = 0\n$$\n\nOf all the possible functions $g(X)$, we can show that $E[Y_i|X_i]$ is the best predictor in terms of minimizing **mean squared error**\n\n$$\nE[ (Y - g(Y))^2] \\geq E[(Y - E[Y|X])^2] \n$$\n\n## {.smaller}\n#### Linear Approximations to the Conditional Expectation Function\n\n::: panel-tabset\n\n## Concept\n\n:::{.nonincremental}\n\n- We can then show (in a different class) that linear regression provides the best linear predictor of the CEF\n  - Chapter 3, of [Mostly Harmless Econometrics](https://bruknow.library.brown.edu/permalink/01BU_INST/9mvq88/alma991028523169706966)\n  - Chapter 4 of [Foundations of Agnostic Statistics](https://bruknow.library.brown.edu/permalink/01BU_INST/9mvq88/alma991000736119706966)\n- Furthermore, when the CEF is linear, it's equal exactly to OLS regression\n:::\n\n## CEF\n\n::: {.cell hash='05-slides_cache/revealjs/cef1code_452ea0b69ab8ca0cb06cacdfe424ee66'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/cef1code-1.png){width=960}\n:::\n:::\n\n\n## OLS\n\n::: {.cell hash='05-slides_cache/revealjs/cef2code_6185ff57f0e2ce6e61eeaaf57975bcfd'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/cef2code-1.png){width=960}\n:::\n:::\n\n\n:::\n\n## What you need to know about Regression {.smaller}\n\n:::{.nonincremental}\n\n- **Conceptual**\n  - Simple linear regression estimates a line of best fit that summarizes relationships between two variables\n\n$$\ny_i = \\beta_0 + \\beta_1x_i + \\epsilon_i\n$$\n\n- **Practical**\n  - We estimate linear models in R using the `lm()` function\n\n\n::: {.cell hash='05-slides_cache/revealjs/ols_6192376b49d12ece04501bbe25676bd3'}\n\n```{.r .cell-code}\nlm(y ~ x, data = df)\n```\n:::\n\n\n:::\n\n## What you need to know about Regression {.smaller}\n\n:::{.nonincremental}\n\n- *Technical/Definitional*\n  - Linear regression chooses $\\beta_0$ and $\\beta_1$ to minimize the Sum of Squared Residuals (SSR):\n\n$$\\textrm{Find }\\hat{\\beta_0},\\,\\hat{\\beta_1} \\text{ arg min}_{\\beta_0, \\beta_1} \\sum (y_i-(\\beta_0+\\beta_1x_i))^2$$\n\n- *Theoretical*\n  - Linear regression provides a **linear** estimate of the conditional expectation function (CEF): $E[Y|X]$\n\n:::\n\n# {{< fa lightbulb >}} Difference-in-Differences {.inverse}\n\n## Motivating Example: What causes Cholera? {.smaller background-image=https://www.finebooksmagazine.com/sites/default/files/styles/gallery_item/public/media-images/2020-11/map-lead-4.jpg?h=2ded5a3f&itok=Mn-K5rQc, background-opacity=.3}\n\n- In the 1800s, cholera was thought to be transmitted through the air.\n\n- John Snow (the physician, not the snack), to explore the origins eventunally concluding that cholera was transmitted through living organisms in water.\n\n- Leveraged a **natural experiment** in which one water company in London moved its pipes further upstream (reducing contamination for Lambeth), while other companies kept their pumps serving Southwark and Vauxhall in the same location. \n\n\n## Notation {.smaller}\n\nLet's adopt a little notation to help us think about the logic of Snow's design:\n\n- $D$: treatment indicator, 1 for treated neighborhoods (Lambeth), 0 for control neighborhoods (Southwark and Vauxhall)\n\n- $T$: period indicator, 1 if post treatment (1854), 0 if pre-treatment (1849).\n\n- $Y_{di}(t)$ the potential outcome of unit $i$ \n\n  - $Y_{1i}(t)$ the potential outcome of unit $i$ when treated between the two periods \n\n  - $Y_{0i}(t)$ the potential outcome of unit $i$ when control between the two periods \n\n\n## Causal Effects {.smaller}\n\nThe individual causal effect for unit i at time t is:\n\n$$\\tau_{it} = Y_{1i}(t) − Y_{0i}(t)$$\n\nWhat we observe is \n\n$$Y_i(t) = Y_{0i}(t)\\cdot(1 − D_i(t)) + Y_{1i}(t)\\cdot D_i(t)$$\n\n$D$ only equals 1, when $T$ equals 1, so we never observe $Y_0i(1)$ for the treated units. \n\nIn words, we don't know what Lambeth's outcome would have been in the second period, had they not been treated.\n\n\n## Average Treatment on Treated {.smaller}\n\nOur goal is to estimate the average effect of treatment on treated (ATT):\n\n\n$$\\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]$$\n\nThat is, what would have happened in Lambeth, had their water company not moved their pipes\n\n\n## Average Treatment on Treated {.smaller}\n\nOur goal is to estimate the average effect of treatment on treated (ATT):\n\nWe we can observe is:\n\n|               | Pre-Period (T=0)  | Post-Period (T=1)  |\n|-|--|-|\n| Treated $D_{i}=1$  |  $E[Y_{0i}(0)\\vert D_i = 1]$ | $E[Y_{1i}(1)\\vert D_i = 1]$  |\n| Control $D_i=0$  |  $E[Y_{0i}(0)\\vert D_i = 0]$ | $E[Y_{0i}(1)\\vert D_i = 0]$  |\n\n\n## Data {.smaller}\n\nBecause potential outcomes notation is abstract, let's consider a modified description of the Snow's cholera death data from [Scott Cunningham](https://mixtape.scunning.com/difference-in-differences.html):\n\n\n::: {.cell hash='05-slides_cache/revealjs/choleradat_1edc40de1f666c90a1f476fe85fbb1ea'}\n::: {.cell-output-display}\n|Company                      | 1849 (T=0)| 1854 (T=1)|\n|:----------------------------|----------:|----------:|\n|Lambeth (D=1)                |         85|         19|\n|Southwark and Vauxhall (D=0) |        135|        147|\n:::\n:::\n\n\n\n## How can we estimate the effect of moving pumps upstream? {.smaller}\n\nRecall, our goal is to estimate the effect of the the treatment on the treated:\n\n$$\\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]$$\n\nLet's conisder some strategies Snow could take to estimate this quantity:\n\n\n## Before vs after comparisons:{.smaller}\n\n:::{.nonincremental}\n- Snow could have compared Labmeth in 1854 $(E[Y_i(1)|D_i = 1] = 19)$ to Lambeth in 1849 $(E[Y_i(0)|D_i = 1]=85)$, and claimed that moving the pumps upstream led to **66 fewer cholera deaths.** \n\n- Assumes Lambeth's pre-treatment outcomes in 1849 are a good proxy for what its outcomes would have been in 1954 if the pumps hadn't moved $(E[Y_{0i}(1)|D_i = 1])$.\n\n- A skeptic might argue that Lambeth in 1849 $\\neq$ Lambeth in 1854\n\n\n\n::: {.cell hash='05-slides_cache/revealjs/unnamed-chunk-2_a62bca60098bd3d4b465530b8164863a'}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Company </th>\n   <th style=\"text-align:right;\"> 1849 (T=0) </th>\n   <th style=\"text-align:right;\"> 1854 (T=1) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;color: blue !important;\"> Lambeth (D=1) </td>\n   <td style=\"text-align:right;font-weight: bold;color: blue !important;\"> 85 </td>\n   <td style=\"text-align:right;font-weight: bold;color: blue !important;\"> 19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Southwark and Vauxhall (D=0) </td>\n   <td style=\"text-align:right;\"> 135 </td>\n   <td style=\"text-align:right;\"> 147 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n\n## Treatment-Control comparisons in the Post Period. {.smaller}\n\n:::{.nonincremental}\n\n- Snow could have compared outcomes between Lambeth and S&V in 1954  ($E[Yi(1)|Di = 1] − E[Yi(1)|Di = 0]$), concluding that the change in pump locations led to **128 fewer deaths.**\n\n- Here the assumption is that the outcomes in S&V and in 1854 provide a good proxy for what would have happened in Lambeth in 1954 had the pumps not been moved $(E[Y_{0i}(1)|D_i = 1])$\n\n- Again, our skeptic could argue  Lambeth $\\neq$ S&V \n\n\n::: {.cell hash='05-slides_cache/revealjs/unnamed-chunk-3_6c050f02fcec86b56bda9439883da7c0'}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Company </th>\n   <th style=\"text-align:right;\"> 1849 (T=0) </th>\n   <th style=\"text-align:right;\"> 1854 (T=1) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Lambeth (D=1) </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;font-weight: bold;color: red !important;\"> 19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Southwark and Vauxhall (D=0) </td>\n   <td style=\"text-align:right;\"> 135 </td>\n   <td style=\"text-align:right;font-weight: bold;color: red !important;\"> 147 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n## Difference in Differences {.smaller}\n\n:::{.nonincremental}\nTo address these concerns, Snow employed what we now call a [difference-in-differences]{.blue} design, \n\nThere are two, equivalent ways to view this design. \n\n$$\\underbrace{\\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\\}}_{\\text{1. Treat-Control |Post }}− \\overbrace{\\{E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}=0 ]}^{\\text{Treated-Control|Pre}}$$\n\n- Difference 1: Average change between Treated and Control  in Post Period\n\n- Difference 2: Average change between Treated and Control  in Pre Period\n\n:::\n\n## Difference in Differences {.smaller}\n\n:::{.nonincremental}\n\n$$\\underbrace{\\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\\}}_{\\text{1. Treat-Control |Post }}− \\overbrace{\\{E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}=0 ]}^{\\text{Treated-Control|Pre}}$$\nIs equivalent to: \n\n$$\\underbrace{\\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(0)|D_{i} = 1]\\}}_{\\text{Post - Pre |Treated }}− \\overbrace{\\{E[Y_{i}(1)|D_{i} = 0] − E[Y_{i}(0)|D_{i}=0 ]}^{\\text{Post-Pre|Control}}$$\n\n\n- Difference 1: Average change between Treated over time\n- Difference 2: Average change between Control over time\n\n:::\n\n## Difference in Differences {.smaller}\n\n\nYou'll see the DiD design represented both ways, but they produce the same result:\n\n$$\n\\tau_{ATT} = (19-147) - (85-135) = -78\n$$\n\n$$\n\\tau_{ATT} = (19-85) - (147-135) = -78\n$$\n\n\n## Identifying Assumption of a Difference in Differences Design {.smaller}\n\nThe key assumption in this design is what's known as the parallel trends assumption: $E[Y_{0i}(1) − Y_{0i}(0)|D_i = 1] = E[Y_{0i}(1) − Y_{0i}(0)|D_i = 0]$ \n\n- In words: If Lambeth hadn't moved its pumps, it would have followed a similar path as S&V\n\n## Parralel Trends\n\n\n::: {.cell hash='05-slides_cache/revealjs/paralleltrends_bfd019b80d2587fdcf5544746a581f9c'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/paralleltrends-1.png){width=960}\n:::\n:::\n\n\n\n## Using linear regression to estimate a Difference in Difference {.smaller}\n\n:::: panel-tabset\n\n## Concept\n\n- Recall that linear regression provides a...\n  - linear estimate of the conditional expectation function\n- In the canonincal pre-post, treated and control DiD, $\\beta_3$ from the following linear regression will give us the ATT:\n\n:::{.fragment}\n\n$$\ny = \\beta_0 + \\beta_1 Post + \\beta_2 Treated + \\underbrace{\\beta_3Post\\times Treated}_{\\tau_{ATT}}\n$$\n\n:::\n\n## Code\n\n\n::: {.cell hash='05-slides_cache/revealjs/didcode_ef513b460b742eb54d3bbea2a18d6535'}\n\n```{.r .cell-code}\ncholera_df <- tibble(\n  Period = factor(c(\"Pre\",\"Pre\",\"Post\",\"Post\"),\n                  levels = c(\"Pre\",\"Post\")),\n  Year = c(1849,1849, 1854,1854),\n  Treated = factor(c(\"Control\",\"Treated\",\"Control\",\"Treated\")),\n  Company = c(\"S&V\",\"Lambeth\",\"S&V\",\"Lambeth\"),\n  Deaths = c(135,85,147,19)\n)\n\nm_did <- lm(Deaths~Period + Treated + Period:Treated, cholera_df)\n\nm_did\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Deaths ~ Period + Treated + Period:Treated, data = cholera_df)\n\nCoefficients:\n              (Intercept)                 PeriodPost  \n                      135                         12  \n           TreatedTreated  PeriodPost:TreatedTreated  \n                      -50                        -78  \n```\n:::\n:::\n\n\n## Data\n\n\n::: {.cell hash='05-slides_cache/revealjs/diddata_4ebc5dbff10eb5ca3cff7ea0879bf2f2'}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3324fdf3e9c87c659172\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3324fdf3e9c87c659172\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\"],[\"Pre\",\"Pre\",\"Post\",\"Post\"],[1849,1849,1854,1854],[\"Control\",\"Treated\",\"Control\",\"Treated\"],[\"S&amp;V\",\"Lambeth\",\"S&amp;V\",\"Lambeth\"],[135,85,147,19]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Period<\\/th>\\n      <th>Year<\\/th>\\n      <th>Treated<\\/th>\\n      <th>Company<\\/th>\\n      <th>Deaths<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,5]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Period\",\"targets\":1},{\"name\":\"Year\",\"targets\":2},{\"name\":\"Treated\",\"targets\":3},{\"name\":\"Company\",\"targets\":4},{\"name\":\"Deaths\",\"targets\":5}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\n## DiD\n\n\n::: {.cell hash='05-slides_cache/revealjs/didtab_2263b6cafc3f72b094207847a7188167'}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">135.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Post (1854)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">12.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Treated (Lambeth)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-50.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Post X Treated (DID)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-78.00</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">1.00</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">4</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"2\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n:::\n\n\n## Figure\n\n\n::: {.cell hash='05-slides_cache/revealjs/didfig_9983e4d33a937d2da037328edcab8a0e'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/didfig-1.png){width=960}\n:::\n:::\n\n\n\n\n\n::::\n\n\n## Summary {.smaller}\n\n- A Difference in Differences (DiD, or diff-in-diff) design combines a pre-post comparison, with a treated and control comparison\n  \n  - Taking the pre-post difference removes any fixed differences between the units\n  \n  - Then taking the difference between treated and control differences removes any common differences over time\n\n- The key identifying assumption of a DiD design is the \"assumption of parallel trends\"\n  - Absent treatment, treated and control groups\nwould see the same changes over time.\n  - Hard to prove, possible to test\n\n\n## Extensions and limitations {.smaller}\n\n- Diff-in-Diff easy to estimate with linear regression\n- Generalizes to multiple periods and treatment interventions\n  - More pre-treatment periods allow you assess \"parallel trends\" assumption\n- Alternative methods \n  - Synthetic control\n  - Event Study Designs\n- What if you have multiple treatments or treatments that come and go?\n  - Panel Matching\n  - Generalized Synthetic control\n\n\n## Applications{.smaller}\n\n- [Card and Krueger (1994)](https://www.nber.org/papers/w4509) What effect did raising the minimum wage in NJ have on employment\n\n- [Abadie, Diamond, & Hainmueller (2014)](https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12116?casa_token=_ceCu4SwzTEAAAAA%3AP9aeaZpT_Zh1VdWKXx_tEmzaJTtMJ1n0eG7EaYlvJZYN000re33cfMAI2O8N8htFJjOsln2GyVeQql4) What effect did German Unification have on economic development in West Germany\n\n- [Malesky, Nguyen and Tran (2014)](https://www.cambridge.org/core/journals/american-political-science-review/article/impact-of-recentralization-on-public-services-a-differenceindifferences-analysis-of-the-abolition-of-elected-councils-in-vietnam/3477854BAAFE152DC93C594169D64F58) How does decentralization influence public services?\n\n\n# {{< fa code >}}Previewing the Lab\n\n## Red Covid{.smaller}\n\n\n::::{.columns}\n\n:::{.column width=\"45%\"}\n\n![](images/05_redcovid_orig.png)\n\n\n[Red Covid](https://www.nytimes.com/2021/09/27/briefing/covid-red-states-vaccinations.html) *New York Times*, 27 September, 2021\n:::\n\n:::{.column width=\"45%\"}\n![](images/05_covid.png)\n[Red Covid, an Update](https://www.nytimes.com/2022/02/18/briefing/red-covid-partisan-deaths-vaccines.html) *New York Times*, 18 February, 2022\n:::\n::::\n\n## Preview of the Lab{.smaller}\n\n[Please download]{.blue} Friday's lab [here](https://josephessig-source.github.io/pols1600_site/labs/05-lab.qmd)\n\n- Conceptually, this lab is designed to help reinforce the relationship between linear models like $y=\\beta_0 + \\beta_1x$ and the conditional expectation function $E[Y|X]$.\n\n- Substantively, we will explore whether David Leonhardt's claims about [Red Covid](https://www.nytimes.com/2021/09/27/briefing/covid-red-states-vaccinations.html) the political polarization of vaccines and its consequences\n\n## Lab: Questions 1-5: Review{.smaller}\n\nQuestions 1-5 are designed to [reinforce]{.blue} your [data wrangling]{.blue} skills.  In particular, you will get practice:\n\n  - Creating and recoding variables using `mutate()`\n  - Calculating a [moving average](https://en.wikipedia.org/wiki/Moving_average) or rolling mean using the `rollmean()` function from the `zoo` package\n  - Transforming the data on presidential elections so that it can be merged with the data on Covid-19 using the `pivot_wider()` function.\n  - [Merging data](https://r4ds.had.co.nz/relational-data.html) together using the `left_join()` function.\n\n\n\n## Lab: Questions 6-10: Simple Linear Regression{.smaller}\n\n- In question 6, you will see how calculating conditional means provides a simple test of \"Red Covid\" claim.\n\n- In question 7, you will see how a linear model returns the same information as these conditional means (in a sligthly different format)\n\n- In question 8, you will get practice interpreting linear models with continuous predictors (i.e. predictors that take on a range of values)\n\n- In question 9, you will get practice visualizing these models and using the figures help interpret your results substantively.\n\n- Question 10 asks you to play the role of a skeptic and consider what other factors might explain the relationships we found in Questions 6-9. We will explore these factors in next week's lab.\n\n## Before Friday\n\nThe following slides provide detailed explanations of all the code you'll need for each question. \n\n- [Please run this code before class on Friday]{.blue}\n\n- We will review this material together at the start of class, but you will spend most of our time on the Questions 6-10\n\n## Q1: Setup your workspace\n\n::: panel-tabset\n\n## Task\n\nQ1 asks you to setup your workspace\n\nThis means [loading]{.blue} and, if needed, [installing]{.blue} the packages you will use\n\n\n:::\n\n\n## Q2 Load the data\n\nTo explore Leonhardt's claims about *Red Covid*, we'll need data on:\n\n- Covid-19\n- The 2020 Presidential Election\n\n\n## Q2.1 Load the Covid-19 Data{.smaller}\n\nTo load data on Covid-19 just run this\n\n\n::: {.cell hash='05-slides_cache/revealjs/covid_cc11f2d894d13cac06910e279c7b7482'}\n\n```{.r .cell-code}\nload(url(\"https://pols1600.paultesta.org/files/data/covid.rda\"))\n```\n:::\n\n\n## Q2.2 Load Election Data {.smaller}\n\n::: panel-tabset\n\n## Task\n\nQ2.2. asks you to write code that will download data presidential elections from 1976 to 2020 from the MIT Election Lab's dataverse\n\n- Once you've installed the `dataverse` package you should be able to do this:\n\n## Code for Q2.2\n\n::: {.cell hash='05-slides_cache/revealjs/pres_data_f250742120e5c9fd180b5f2c2d8a34d5'}\n\n```{.r .cell-code}\n# Try this code first\nSys.setenv(\"DATAVERSE_SERVER\" = \"dataverse.harvard.edu\")\n\npres_df <- dataverse::get_dataframe_by_name(\n  \"1976-2020-president.tab\",\n  \"doi:10.7910/DVN/42MVDX\"\n)\n\n# If the code above fails, comment out and uncomment the code below:\n\n# load(url(\"https://pols1600.paultesta.org/files/data/pres_df.rda\"))\n```\n:::\n\n:::\n\n## Q3 Describe the structure of each dataset{.smaller}\n\nQuestion 3 asks you to [describe the structure]{.blue} of each dataset.\n\n- Specifically, it asks you to get a high level overview of `covid` and `pres_df` and describe the [unit of analysis]{.blue} in each dataset:\n  - Describe substantively what specific, observation each [row]{.blue} in the dataset corresponds to\n  - In covid `covid` dataset, the [unit of analysis]{.blue} is a [state-date]{.blue}\n\n## Q3 Describe the structure of each dataset{.smaller}\n\nHere's some possible code you could use to get a quick [HLO]{.blue} of each dataset:\n\n::: panel-tabset\n\n\n## HLO `covid`\n\n::: {.cell hash='05-slides_cache/revealjs/hlocovid_865d10e45037a25ae9f9cc91d31d220e'}\n\n```{.r .cell-code}\n# check names in `covid`\nnames(covid)\n\n# take a quick look values of each variable\n\nglimpse(covid)\n\n# Look at first few observations for:\n# date, administrative_area_level_2, \n\ncovid %>% \n  select(date, administrative_area_level_2) %>%\n  head()\n\n# Summarize data to get a better sense of the unit of observastion\n\ncovid %>% \n  group_by(administrative_area_level_2) %>%\n  summarise(\n    n = n(), # Number of observations for each state\n    start_date = min(date, na.rm = T),\n    end_date = max(date, na.rm=T)\n  ) -> hlo_covid_df\n\nhlo_covid_df\n\n\n# How many unique values of date and state are their:\n\nn_dates <- length(unique(covid$date))\nn_states <- length(unique(covid$administrative_area_level_2))\nn_dates\nn_states\n\n# If we had observations for every state on every date then the number of rows \n# in the data \ndim(covid)[1]\n# Should equal\ndim(covid)[1] == n_dates * n_states\n\n# This is what economists would call an unbalanced panel\n```\n:::\n\n\n## HLO `pres_df`\n\n\n::: {.cell hash='05-slides_cache/revealjs/hlopresdf_001072669030114c56d798819f15d4fe'}\n\n```{.r .cell-code}\n# check names in `pres_df`\nnames(pres_df)\n\n# take a quick look values of each variable\n\nglimpse(pres_df)\n\n# Unit of analysis is a year-state-candidate\npres_df %>% \n  select(year, state_po, candidate) %>%\n  head()\n\n# How many states?\nlength(unique(pres_df$state_po))\n\n\n\n# How many candidates and parties on the ballot in a given election year\npres_df %>% \n  group_by(year) %>%\n  summarise(\n    n_candidates = length(unique(candidate)),\n    # Look at both party_detailed and party_simplified\n    n_parties_detailed = length(unique(party_detailed)),\n    n_parties_simplified = length(unique(party_simplified))\n  ) -> hlo_pres_df\nhlo_pres_df\n\n# Look at 2020\n# pres_df$candidate[pres_df$year == \"2020\"]\n```\n:::\n\n:::\n \n \n## Q4 Recode the data for analysis\n\nUsing our understanding of the structure of the data, Q4 asks you to:\n\n\n- Recode the Covid-19 data like we've done before [plus]{.blue}\n- Calculate [rolling means]{.blue},  7 and 14 day averages\n- Reshape, recode, and filter the presidential election data\n\n\n\n## Q4.1 Recode the Covid-19{.smaller}\n\n::: panel-tabset\n\n## Task\nThis is the same code we've used before to create `covid_us` from `covid` with the addition of code to calculate a [rolling mean]{.blue} or [moving average]{.blue} of the number of new cases\n\n## Code for Q4.1\n\n::: {.cell hash='05-slides_cache/revealjs/covid19recode_3a7e22079856cee39cf10f9a37948553'}\n\n```{.r .cell-code}\n# Create a vector containing of US territories\nterritories <- c(\n  \"American Samoa\",\n  \"Guam\",\n  \"Northern Mariana Islands\",\n  \"Puerto Rico\",\n  \"Virgin Islands\"\n  )\n\n# Filter out Territories and create state variable\ncovid_us <- covid %>%\n  filter(!administrative_area_level_2 %in% territories)%>%\n  mutate(\n    state = administrative_area_level_2\n  )\n\n# Calculate new cases, new cases per capita, and 7-day average\n\ncovid_us %>%\n  dplyr::group_by(state) %>%\n  mutate(\n    new_cases = confirmed - lag(confirmed),\n    new_cases_pc = new_cases / population *100000,\n    new_cases_pc_7da = zoo::rollmean(new_cases_pc, \n                                     k = 7, \n                                     align = \"right\",\n                                     fill=NA )\n    ) -> covid_us\n\n# Recode facemask policy\n\ncovid_us %>%\nmutate(\n  # Recode facial_coverings to create face_masks\n    face_masks = case_when(\n      facial_coverings == 0 ~ \"No policy\",\n      abs(facial_coverings) == 1 ~ \"Recommended\",\n      abs(facial_coverings) == 2 ~ \"Some requirements\",\n      abs(facial_coverings) == 3 ~ \"Required shared places\",\n      abs(facial_coverings) == 4 ~ \"Required all times\",\n    ),\n    # Turn face_masks into a factor with ordered policy levels\n    face_masks = factor(face_masks,\n      levels = c(\"No policy\",\"Recommended\",\n                 \"Some requirements\",\n                 \"Required shared places\",\n                 \"Required all times\")\n    ) \n    ) -> covid_us\n\n# Create year-month and percent vaccinated variables\n\ncovid_us %>%\n  mutate(\n    year = year(date),\n    month = month(date),\n    year_month = paste(year, \n                       str_pad(month, width = 2, pad=0), \n                       sep = \"-\"),\n    percent_vaccinated = people_fully_vaccinated/population*100  \n    ) -> covid_us\n```\n:::\n\n\n## Template Code for Q4.2\n\n\n::: {.cell hash='05-slides_cache/revealjs/unnamed-chunk-4_880447c066531c75b1a511d55ac6bad1'}\n\n```{.r .cell-code}\n# Calculate new cases, new cases per capita, and 7-day average\n\ncovid_us %>%\n  dplyr::group_by(state) %>%\n  mutate(\n    new_cases = confirmed - lag(confirmed),\n    new_cases_pc = new_cases / population *100000,\n    new_cases_pc_7day = zoo::rollmean(new_cases_pc, \n                                     k = 7, \n                                     align = \"right\",\n                                     fill=NA )\n    ) -> covid_us\n```\n:::\n\n\n:::\n\n\n## Q4.2 Calculate Rolling Means of Covid Deaths{.smaller}\n\n::: panel-tabset\n\n## Task\n\nQ4.2 asks you to create new measures of the 7-day and 14-day averages of new deaths from Covid-19 per 100,000 residents\n\nIt encourages you to use the code `new_cases_pc_7da` as a template\n\nTo build your coding skills, try writing this yourself, then comparing it to the code in the next tab:\n\n## Code for Q4.2\n\n::: {.cell hash='05-slides_cache/revealjs/unnamed-chunk-5_abadf61e1d6c806414cc193c596e414a'}\n\n```{.r .cell-code}\ncovid_us %>%\n  dplyr::group_by(state) %>%\n  mutate(\n    new_deaths = deaths - lag(deaths),\n    new_deaths_pc = new_deaths / population *100000,\n    new_deaths_pc_7day = zoo::rollmean(new_deaths_pc, \n                                     k = 7, \n                                     align = \"right\",\n                                     fill=NA ),\n    new_deaths_pc_14day = zoo::rollmean(new_deaths_pc, \n                                     k = 14, \n                                     align = \"right\",\n                                     fill=NA )\n    ) -> covid_us\n```\n:::\n\n\n:::\n\n\n\n## Rolling Averages{.smaller} \n\nThe next slides [aren't necessary for the lab]{.blue} but are designed to illustrate:\n\n- the [concept of a rolling mean]{.blue}\n- [what]{.blue} the code does\n- [why]{.blue} might prefer rolling averages over daily values\n\n\n## Look at the output of `zoo::rollmean()`\n\n::: {.cell hash='05-slides_cache/revealjs/rollmean_ecfa8eafe1c53e30ef50f2c2aa3cb016'}\n\n```{.r .cell-code}\ncovid_us %>%\n  filter(date > \"2020-03-05\") %>%\n  select(date,new_cases_pc,new_cases_pc_7day)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52,580 × 4\n# Groups:   state [51]\n   state     date       new_cases_pc new_cases_pc_7day\n   <chr>     <date>            <dbl>             <dbl>\n 1 Minnesota 2020-03-06      NA                NA     \n 2 Minnesota 2020-03-07       0                NA     \n 3 Minnesota 2020-03-08       0.0177           NA     \n 4 Minnesota 2020-03-09       0                NA     \n 5 Minnesota 2020-03-10       0.0177           NA     \n 6 Minnesota 2020-03-11       0.0355           NA     \n 7 Minnesota 2020-03-12       0.0709           NA     \n 8 Minnesota 2020-03-13       0.0887            0.0329\n 9 Minnesota 2020-03-14       0.124             0.0507\n10 Minnesota 2020-03-15       0.248             0.0836\n# ℹ 52,570 more rows\n```\n:::\n:::\n\n\n## Comparing Daily Cases to Rolling Average{.smaller}\n\nThe following code illustrates how a 7-day rolling mean smooths (`new_cases_pc_7da`) over the [*noisiness*]{.blue} of the daily measure\n\n::: panel-tabset\n\n## Code\n\n::: {.cell hash='05-slides_cache/revealjs/plotmean_1056752e5355e1504daffbb3f70a3f8e'}\n\n```{.r .cell-code}\ncovid_us %>%\n  filter(date > \"2020-03-05\", \n         state == \"Minnesota\") %>%\n  select(date,\n         new_cases_pc,\n         new_cases_pc_7day)%>%\n  ggplot(aes(date,new_cases_pc ))+\n  geom_line(aes(col=\"Daily\"))+\n  # set y aesthetic for second line of rolling average\n  geom_line(aes(y = new_cases_pc_7day,\n                col = \"7-day average\")\n            ) +\n  theme(legend.position=\"bottom\")+\n    labs( col = \"Measure\",\n    y = \"New Cases Per 100k\", x = \"\",\n    title = \"Minnesota\"\n  ) -> fig_covid_mn \n```\n:::\n\n\n## Figure\n\n::: {.cell hash='05-slides_cache/revealjs/plotmean2_7576687414cefddfbe6c9d20b8430e1c'}\n::: {.cell-output-display}\n![](05-slides_files/figure-revealjs/plotmean2-1.png){width=960}\n:::\n:::\n\n:::\n\n## Q4.3 Recode Presidential data{.smaller}\n\n::: panel-tabset\n\n## Task\n\nQ4.3 Gives you a long list of steps to recode, reshape, and filter `pres_df` to produce `pres_df2020`\n\nMost of this is review but it can seem like a lot.\n\nWalk through the provided code and see if you can [map each conceptual step]{.blue} in Q4.3 to its [implementation in the code]{.blue}\n\n## Code for Q4.3\n\n\n::: {.cell hash='05-slides_cache/revealjs/pres_wrangle_dc4c50d6a6c8cce47ae3d34653cd0bb7'}\n\n```{.r .cell-code}\npres_df %>%\n  mutate(\n    year_election = year,\n    state = str_to_title(state),\n    # Fix DC\n    state = ifelse(state == \"District Of Columbia\", \"District of Columbia\", state)\n  ) %>%\n  filter(party_simplified %in% c(\"DEMOCRAT\",\"REPUBLICAN\"))%>%\n  filter(year == 2020) %>%\n  select(state, state_po, year_election, party_simplified, candidatevotes, totalvotes\n         ) %>%\n  pivot_wider(names_from = party_simplified,\n              values_from = candidatevotes) %>%\n  mutate(\n    dem_voteshare = DEMOCRAT/totalvotes *100,\n    rep_voteshare = REPUBLICAN/totalvotes*100,\n    winner = forcats::fct_rev(factor(ifelse(rep_voteshare > dem_voteshare,\"Trump\",\"Biden\")))\n  ) -> pres2020_df\n\n# Check Output:\n\nglimpse(pres2020_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 51\nColumns: 9\n$ state         <chr> \"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\"…\n$ state_po      <chr> \"AL\", \"AK\", \"AZ\", \"AR\", \"CA\", \"CO\", \"CT\", \"DE\", \"DC\", \"F…\n$ year_election <dbl> 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 20…\n$ totalvotes    <dbl> 2323282, 359530, 3387326, 1219069, 17500881, 3279980, 18…\n$ DEMOCRAT      <dbl> 849624, 153778, 1672143, 423932, 11110250, 1804352, 1080…\n$ REPUBLICAN    <dbl> 1441170, 189951, 1661686, 760647, 6006429, 1364607, 7147…\n$ dem_voteshare <dbl> 36.56999, 42.77195, 49.36469, 34.77506, 63.48395, 55.011…\n$ rep_voteshare <dbl> 62.031643, 52.833143, 49.055981, 62.395730, 34.320724, 4…\n$ winner        <fct> Trump, Trump, Biden, Trump, Biden, Biden, Biden, Biden, …\n```\n:::\n:::\n\n\n:::\n\n## Q5 merging data{.smaller}\n\n::: panel-tabset\n\n## Task\n\nQ5 asks you to merge the 2020 election data from `pres2020_df` into `covid_us` using the common `state` variable in each dataset using the function `left_join()`\n\n\n## Merge election data into Covid data\n\n\n::: {.cell hash='05-slides_cache/revealjs/merge_pres_494746b6b037a1ab399f3ffb357fa7bf'}\n\n```{.r .cell-code}\ndim(covid_us)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53678    61\n```\n:::\n\n```{.r .cell-code}\ndim(pres2020_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 51  9\n```\n:::\n\n```{.r .cell-code}\ncovid_us <- covid_us %>% left_join(\n  pres2020_df,\n  by = c(\"state\" = \"state\")\n)\ndim(covid_us) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53678    69\n```\n:::\n:::\n\n:::\n\n## Advice for merging {.smaller}\n\n::: panel-tabset\n\n## Advice\n\nWhen merging datasets:\n\n- Check the matches in your joining variables\n  - Make sure the values `state` are the same in each dataset \n  - Check for differences in spelling, punctuation, etc.\n- Check the [dimensions]{.blue} of output of your `left_join()`\n  - If there is a 1-1 match the number of rows should be the same before after\n\n## Illustration\n\n\n::: {.cell hash='05-slides_cache/revealjs/merge_check_4c58af2acf9fc0a2bbe303911bbf9041'}\n\n```{.r .cell-code}\n# Should be 51 states and DC in each\nsum(unique(pres_df$state) %in% covid_us$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\n# Look at each state variable\n## With [] index\npres_df$state[1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"ALABAMA\" \"ALABAMA\" \"ALABAMA\" \"ALABAMA\" \"ALABAMA\"\n```\n:::\n\n```{.r .cell-code}\ncovid_us$state[1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Minnesota\" \"Minnesota\" \"Minnesota\" \"Minnesota\" \"Minnesota\"\n```\n:::\n\n```{.r .cell-code}\n# Matching is case sensitive \n\n# make pres_df$state title case\n\n## Base R:\npres_df$state <- str_to_title(pres_df$state )\n## Tidy R:\npres_df %>% \n  mutate(\n    state = str_to_title(state )\n  ) -> pres_df\n\n# Should be 51\nsum(unique(pres_df$state) %in% covid_us$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 50\n```\n:::\n\n```{.r .cell-code}\n# Find the mismatch:\nunique(pres_df$state[!pres_df$state %in% covid_us$state])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"District Of Columbia\"\n```\n:::\n\n```{.r .cell-code}\n# Two equivalent ways to fix this mismatch\n## Base R: Quick fix to change spelling of DC\npres_df$state[pres2020_df$state == \"District Of Columbia\"] <- \"District of Columbia\"\n\n## Tidy R: Quick fix to change spelling of DC\n\npres_df %>% \n  mutate(\n    state = ifelse(test = state == \"District Of Columbia\",\n                   yes = \"District of Columbia\",\n                   no = state\n                   )\n  ) -> pres_df\n\n\n# Problem Solved\nsum(unique(pres2020_df$state) %in% covid_us$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 51\n```\n:::\n:::\n\n\n\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\r\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\r\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\r\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\r\n"
      ],
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    // dispatch for htmlwidgets\r\n    function fireSlideEnter() {\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n    }\r\n\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n      fireSlideEnter();\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}