<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>POLS 1600</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-8979bb8451ddc1038f930ac611262c50.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" align="left" data-background-image="images/pols1600_hex.png" data-background-position="90% 50%" data-background-size="40%" class="quarto-title-block center">
  <h1 class="title">POLS 1600</h1>
  <p class="subtitle">Uncertainty I: Confidence Intervals</p>

<div class="quarto-title-authors">
</div>

  <p class="date">Updated Apr 6, 2026</p>
</section>
<section>
<section id="overview" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-map-location" aria-label="map-location"></i> Overview</h1>

</section>
<section id="class-plan" class="slide level2">
<h2>Class Plan</h2>
<ul>
<li class="fragment">Announcements</li>
<li class="fragment">Topics:
<ul>
<li class="fragment">Sampling distributions and standard errors</li>
<li class="fragment">Confidence intervals</li>
<li class="fragment">Hypothesis testing</li>
<li class="fragment">Quantifying uncertainty for regression</li>
</ul></li>
</ul>
</section>
<section id="announcements" class="slide level2">
<h2>Announcements</h2>
<ul>
<li class="fragment"><p>Final regular lab this week (continuing with the ANES data)</p></li>
<li class="fragment"><p>Since you all decided on your own analysis and example code provided, no posted solutions for labs 9 and 10.</p></li>
<li class="fragment"><p>Next week’s lectures:</p>
<ul>
<li class="fragment">Finish discussion of Hypothesis Testing, Asymptotic vs.&nbsp;Permutation</li>
<li class="fragment">Course Review</li>
</ul></li>
<li class="fragment"><p>Next week’s lab:</p>
<ul>
<li class="fragment">Work on draft (A4)</li>
</ul></li>
</ul>
</section>
<section id="setup-packages-for-today" class="slide level2">
<h2>Setup: Packages for today</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="do">## Pacakges for today</span></span>
<span id="cb1-2"><a></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-3"><a></a>  <span class="do">## R Markdown</span></span>
<span id="cb1-4"><a></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,<span class="st">"htmltools"</span>,</span>
<span id="cb1-5"><a></a>  <span class="do">## Tidyverse</span></span>
<span id="cb1-6"><a></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,</span>
<span id="cb1-7"><a></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb1-8"><a></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb1-9"><a></a>  <span class="st">"patchwork"</span>,<span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb1-10"><a></a>  <span class="co"># Data </span></span>
<span id="cb1-11"><a></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>, </span>
<span id="cb1-12"><a></a>  <span class="co"># Analysis</span></span>
<span id="cb1-13"><a></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"easystats"</span>, <span class="st">"zoo"</span>, <span class="st">"boot"</span>, <span class="st">"modelr"</span> ,<span class="st">"purrr"</span></span>
<span id="cb1-14"><a></a>)</span>
<span id="cb1-15"><a></a></span>
<span id="cb1-16"><a></a><span class="do">## Define a function to load (and if needed install) packages</span></span>
<span id="cb1-17"><a></a></span>
<span id="cb1-18"><a></a><span class="fu">lapply</span>(the_packages, library, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1] "kableExtra"    "texreg"        "see"           "report"       
 [5] "parameters"    "performance"   "modelbased"    "insight"      
 [9] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[13] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[17] "randomizr"     "haven"         "labelled"      "lubridate"    
[21] "forcats"       "stringr"       "dplyr"         "purrr"        
[25] "readr"         "tidyr"         "tibble"        "ggplot2"      
[29] "tidyverse"     "stats"         "graphics"      "grDevices"    
[33] "utils"         "datasets"      "methods"       "base"         

[[2]]
 [1] "DT"            "kableExtra"    "texreg"        "see"          
 [5] "report"        "parameters"    "performance"   "modelbased"   
 [9] "insight"       "effectsize"    "datawizard"    "correlation"  
[13] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[17] "fabricatr"     "randomizr"     "haven"         "labelled"     
[21] "lubridate"     "forcats"       "stringr"       "dplyr"        
[25] "purrr"         "readr"         "tidyr"         "tibble"       
[29] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[33] "grDevices"     "utils"         "datasets"      "methods"      
[37] "base"         

[[3]]
 [1] "DT"            "kableExtra"    "texreg"        "see"          
 [5] "report"        "parameters"    "performance"   "modelbased"   
 [9] "insight"       "effectsize"    "datawizard"    "correlation"  
[13] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[17] "fabricatr"     "randomizr"     "haven"         "labelled"     
[21] "lubridate"     "forcats"       "stringr"       "dplyr"        
[25] "purrr"         "readr"         "tidyr"         "tibble"       
[29] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[33] "grDevices"     "utils"         "datasets"      "methods"      
[37] "base"         

[[4]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[5]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[6]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[7]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[8]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[9]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[10]]
 [1] "ggmap"         "htmltools"     "DT"            "kableExtra"   
 [5] "texreg"        "see"           "report"        "parameters"   
 [9] "performance"   "modelbased"    "insight"       "effectsize"   
[13] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[17] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[21] "haven"         "labelled"      "lubridate"     "forcats"      
[25] "stringr"       "dplyr"         "purrr"         "readr"        
[29] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[33] "stats"         "graphics"      "grDevices"     "utils"        
[37] "datasets"      "methods"       "base"         

[[11]]
 [1] "ggrepel"       "ggmap"         "htmltools"     "DT"           
 [5] "kableExtra"    "texreg"        "see"           "report"       
 [9] "parameters"    "performance"   "modelbased"    "insight"      
[13] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[17] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[21] "randomizr"     "haven"         "labelled"      "lubridate"    
[25] "forcats"       "stringr"       "dplyr"         "purrr"        
[29] "readr"         "tidyr"         "tibble"        "ggplot2"      
[33] "tidyverse"     "stats"         "graphics"      "grDevices"    
[37] "utils"         "datasets"      "methods"       "base"         

[[12]]
 [1] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
 [5] "DT"            "kableExtra"    "texreg"        "see"          
 [9] "report"        "parameters"    "performance"   "modelbased"   
[13] "insight"       "effectsize"    "datawizard"    "correlation"  
[17] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[21] "fabricatr"     "randomizr"     "haven"         "labelled"     
[25] "lubridate"     "forcats"       "stringr"       "dplyr"        
[29] "purrr"         "readr"         "tidyr"         "tibble"       
[33] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[37] "grDevices"     "utils"         "datasets"      "methods"      
[41] "base"         

[[13]]
 [1] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
 [5] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [9] "see"           "report"        "parameters"    "performance"  
[13] "modelbased"    "insight"       "effectsize"    "datawizard"   
[17] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[21] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[25] "labelled"      "lubridate"     "forcats"       "stringr"      
[29] "dplyr"         "purrr"         "readr"         "tidyr"        
[33] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[37] "graphics"      "grDevices"     "utils"         "datasets"     
[41] "methods"       "base"         

[[14]]
 [1] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
 [5] "ggmap"         "htmltools"     "DT"            "kableExtra"   
 [9] "texreg"        "see"           "report"        "parameters"   
[13] "performance"   "modelbased"    "insight"       "effectsize"   
[17] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[21] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[25] "haven"         "labelled"      "lubridate"     "forcats"      
[29] "stringr"       "dplyr"         "purrr"         "readr"        
[33] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[37] "stats"         "graphics"      "grDevices"     "utils"        
[41] "datasets"      "methods"       "base"         

[[15]]
 [1] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
 [5] "ggrepel"       "ggmap"         "htmltools"     "DT"           
 [9] "kableExtra"    "texreg"        "see"           "report"       
[13] "parameters"    "performance"   "modelbased"    "insight"      
[17] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[21] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[25] "randomizr"     "haven"         "labelled"      "lubridate"    
[29] "forcats"       "stringr"       "dplyr"         "purrr"        
[33] "readr"         "tidyr"         "tibble"        "ggplot2"      
[37] "tidyverse"     "stats"         "graphics"      "grDevices"    
[41] "utils"         "datasets"      "methods"       "base"         

[[16]]
 [1] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
 [5] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
 [9] "DT"            "kableExtra"    "texreg"        "see"          
[13] "report"        "parameters"    "performance"   "modelbased"   
[17] "insight"       "effectsize"    "datawizard"    "correlation"  
[21] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[25] "fabricatr"     "randomizr"     "haven"         "labelled"     
[29] "lubridate"     "forcats"       "stringr"       "dplyr"        
[33] "purrr"         "readr"         "tidyr"         "tibble"       
[37] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[41] "grDevices"     "utils"         "datasets"      "methods"      
[45] "base"         

[[17]]
 [1] "dagitty"       "scales"        "patchwork"     "ggpubr"       
 [5] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
 [9] "htmltools"     "DT"            "kableExtra"    "texreg"       
[13] "see"           "report"        "parameters"    "performance"  
[17] "modelbased"    "insight"       "effectsize"    "datawizard"   
[21] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[25] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[29] "labelled"      "lubridate"     "forcats"       "stringr"      
[33] "dplyr"         "purrr"         "readr"         "tidyr"        
[37] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[41] "graphics"      "grDevices"     "utils"         "datasets"     
[45] "methods"       "base"         

[[18]]
 [1] "ggdag"         "dagitty"       "scales"        "patchwork"    
 [5] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
 [9] "ggmap"         "htmltools"     "DT"            "kableExtra"   
[13] "texreg"        "see"           "report"        "parameters"   
[17] "performance"   "modelbased"    "insight"       "effectsize"   
[21] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[25] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[29] "haven"         "labelled"      "lubridate"     "forcats"      
[33] "stringr"       "dplyr"         "purrr"         "readr"        
[37] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[41] "stats"         "graphics"      "grDevices"     "utils"        
[45] "datasets"      "methods"       "base"         

[[19]]
 [1] "ggforce"       "ggdag"         "dagitty"       "scales"       
 [5] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
 [9] "ggrepel"       "ggmap"         "htmltools"     "DT"           
[13] "kableExtra"    "texreg"        "see"           "report"       
[17] "parameters"    "performance"   "modelbased"    "insight"      
[21] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[25] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[29] "randomizr"     "haven"         "labelled"      "lubridate"    
[33] "forcats"       "stringr"       "dplyr"         "purrr"        
[37] "readr"         "tidyr"         "tibble"        "ggplot2"      
[41] "tidyverse"     "stats"         "graphics"      "grDevices"    
[45] "utils"         "datasets"      "methods"       "base"         

[[20]]
 [1] "COVID19"       "ggforce"       "ggdag"         "dagitty"      
 [5] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
 [9] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
[13] "DT"            "kableExtra"    "texreg"        "see"          
[17] "report"        "parameters"    "performance"   "modelbased"   
[21] "insight"       "effectsize"    "datawizard"    "correlation"  
[25] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[29] "fabricatr"     "randomizr"     "haven"         "labelled"     
[33] "lubridate"     "forcats"       "stringr"       "dplyr"        
[37] "purrr"         "readr"         "tidyr"         "tibble"       
[41] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[45] "grDevices"     "utils"         "datasets"      "methods"      
[49] "base"         

[[21]]
 [1] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [5] "dagitty"       "scales"        "patchwork"     "ggpubr"       
 [9] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[13] "htmltools"     "DT"            "kableExtra"    "texreg"       
[17] "see"           "report"        "parameters"    "performance"  
[21] "modelbased"    "insight"       "effectsize"    "datawizard"   
[25] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[29] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[33] "labelled"      "lubridate"     "forcats"       "stringr"      
[37] "dplyr"         "purrr"         "readr"         "tidyr"        
[41] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[45] "graphics"      "grDevices"     "utils"         "datasets"     
[49] "methods"       "base"         

[[22]]
 [1] "mapdata"       "maps"          "COVID19"       "ggforce"      
 [5] "ggdag"         "dagitty"       "scales"        "patchwork"    
 [9] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
[13] "ggmap"         "htmltools"     "DT"            "kableExtra"   
[17] "texreg"        "see"           "report"        "parameters"   
[21] "performance"   "modelbased"    "insight"       "effectsize"   
[25] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[29] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[33] "haven"         "labelled"      "lubridate"     "forcats"      
[37] "stringr"       "dplyr"         "purrr"         "readr"        
[41] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[45] "stats"         "graphics"      "grDevices"     "utils"        
[49] "datasets"      "methods"       "base"         

[[23]]
 [1] "qss"           "mapdata"       "maps"          "COVID19"      
 [5] "ggforce"       "ggdag"         "dagitty"       "scales"       
 [9] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
[13] "ggrepel"       "ggmap"         "htmltools"     "DT"           
[17] "kableExtra"    "texreg"        "see"           "report"       
[21] "parameters"    "performance"   "modelbased"    "insight"      
[25] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[29] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[33] "randomizr"     "haven"         "labelled"      "lubridate"    
[37] "forcats"       "stringr"       "dplyr"         "purrr"        
[41] "readr"         "tidyr"         "tibble"        "ggplot2"      
[45] "tidyverse"     "stats"         "graphics"      "grDevices"    
[49] "utils"         "datasets"      "methods"       "base"         

[[24]]
 [1] "tidycensus"    "qss"           "mapdata"       "maps"         
 [5] "COVID19"       "ggforce"       "ggdag"         "dagitty"      
 [9] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
[13] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
[17] "DT"            "kableExtra"    "texreg"        "see"          
[21] "report"        "parameters"    "performance"   "modelbased"   
[25] "insight"       "effectsize"    "datawizard"    "correlation"  
[29] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[33] "fabricatr"     "randomizr"     "haven"         "labelled"     
[37] "lubridate"     "forcats"       "stringr"       "dplyr"        
[41] "purrr"         "readr"         "tidyr"         "tibble"       
[45] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[49] "grDevices"     "utils"         "datasets"      "methods"      
[53] "base"         

[[25]]
 [1] "dataverse"     "tidycensus"    "qss"           "mapdata"      
 [5] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [9] "dagitty"       "scales"        "patchwork"     "ggpubr"       
[13] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[17] "htmltools"     "DT"            "kableExtra"    "texreg"       
[21] "see"           "report"        "parameters"    "performance"  
[25] "modelbased"    "insight"       "effectsize"    "datawizard"   
[29] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[33] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[37] "labelled"      "lubridate"     "forcats"       "stringr"      
[41] "dplyr"         "purrr"         "readr"         "tidyr"        
[45] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[49] "graphics"      "grDevices"     "utils"         "datasets"     
[53] "methods"       "base"         

[[26]]
 [1] "dataverse"     "tidycensus"    "qss"           "mapdata"      
 [5] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [9] "dagitty"       "scales"        "patchwork"     "ggpubr"       
[13] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[17] "htmltools"     "DT"            "kableExtra"    "texreg"       
[21] "see"           "report"        "parameters"    "performance"  
[25] "modelbased"    "insight"       "effectsize"    "datawizard"   
[29] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[33] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[37] "labelled"      "lubridate"     "forcats"       "stringr"      
[41] "dplyr"         "purrr"         "readr"         "tidyr"        
[45] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[49] "graphics"      "grDevices"     "utils"         "datasets"     
[53] "methods"       "base"         

[[27]]
 [1] "dataverse"     "tidycensus"    "qss"           "mapdata"      
 [5] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [9] "dagitty"       "scales"        "patchwork"     "ggpubr"       
[13] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[17] "htmltools"     "DT"            "kableExtra"    "texreg"       
[21] "see"           "report"        "parameters"    "performance"  
[25] "modelbased"    "insight"       "effectsize"    "datawizard"   
[29] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[33] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[37] "labelled"      "lubridate"     "forcats"       "stringr"      
[41] "dplyr"         "purrr"         "readr"         "tidyr"        
[45] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[49] "graphics"      "grDevices"     "utils"         "datasets"     
[53] "methods"       "base"         

[[28]]
 [1] "zoo"           "dataverse"     "tidycensus"    "qss"          
 [5] "mapdata"       "maps"          "COVID19"       "ggforce"      
 [9] "ggdag"         "dagitty"       "scales"        "patchwork"    
[13] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
[17] "ggmap"         "htmltools"     "DT"            "kableExtra"   
[21] "texreg"        "see"           "report"        "parameters"   
[25] "performance"   "modelbased"    "insight"       "effectsize"   
[29] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[33] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[37] "haven"         "labelled"      "lubridate"     "forcats"      
[41] "stringr"       "dplyr"         "purrr"         "readr"        
[45] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[49] "stats"         "graphics"      "grDevices"     "utils"        
[53] "datasets"      "methods"       "base"         

[[29]]
 [1] "boot"          "zoo"           "dataverse"     "tidycensus"   
 [5] "qss"           "mapdata"       "maps"          "COVID19"      
 [9] "ggforce"       "ggdag"         "dagitty"       "scales"       
[13] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
[17] "ggrepel"       "ggmap"         "htmltools"     "DT"           
[21] "kableExtra"    "texreg"        "see"           "report"       
[25] "parameters"    "performance"   "modelbased"    "insight"      
[29] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[33] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[37] "randomizr"     "haven"         "labelled"      "lubridate"    
[41] "forcats"       "stringr"       "dplyr"         "purrr"        
[45] "readr"         "tidyr"         "tibble"        "ggplot2"      
[49] "tidyverse"     "stats"         "graphics"      "grDevices"    
[53] "utils"         "datasets"      "methods"       "base"         

[[30]]
 [1] "modelr"        "boot"          "zoo"           "dataverse"    
 [5] "tidycensus"    "qss"           "mapdata"       "maps"         
 [9] "COVID19"       "ggforce"       "ggdag"         "dagitty"      
[13] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
[17] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
[21] "DT"            "kableExtra"    "texreg"        "see"          
[25] "report"        "parameters"    "performance"   "modelbased"   
[29] "insight"       "effectsize"    "datawizard"    "correlation"  
[33] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[37] "fabricatr"     "randomizr"     "haven"         "labelled"     
[41] "lubridate"     "forcats"       "stringr"       "dplyr"        
[45] "purrr"         "readr"         "tidyr"         "tibble"       
[49] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[53] "grDevices"     "utils"         "datasets"      "methods"      
[57] "base"         

[[31]]
 [1] "modelr"        "boot"          "zoo"           "dataverse"    
 [5] "tidycensus"    "qss"           "mapdata"       "maps"         
 [9] "COVID19"       "ggforce"       "ggdag"         "dagitty"      
[13] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
[17] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
[21] "DT"            "kableExtra"    "texreg"        "see"          
[25] "report"        "parameters"    "performance"   "modelbased"   
[29] "insight"       "effectsize"    "datawizard"    "correlation"  
[33] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[37] "fabricatr"     "randomizr"     "haven"         "labelled"     
[41] "lubridate"     "forcats"       "stringr"       "dplyr"        
[45] "purrr"         "readr"         "tidyr"         "tibble"       
[49] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[53] "grDevices"     "utils"         "datasets"      "methods"      
[57] "base"         </code></pre>
</div>
</div>
</section>
<section id="goals" class="slide level2 smaller">
<h2>Goals:</h2>
<ul>
<li class="fragment"><p>A <span class="blue">sampling distribution</span> is a theoretical distribution of estimates obtained in repeated sampling</p>
<ul>
<li class="fragment">What could have happened?</li>
</ul></li>
<li class="fragment"><p>A <span class="blue">standard error</span> (SE) is the standard deviation of the sampling distribution</p></li>
<li class="fragment"><p>We can calculate SEs via <span class="blue">simulation</span> and <span class="blue">analytically</span></p></li>
<li class="fragment"><p>We can use SEs to construct <span class="blue">confidence intervals</span> and conduct <span class="blue">hypothesis tests</span> allowing us to <span class="blue">quantify uncertainty</span></p></li>
</ul>
</section></section>
<section>
<section id="sampling-distributions-and-standard-errors" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-concepts" aria-label="concepts"></i> Sampling distributions and standard errors</h1>

</section>
<section id="populations-and-samples" class="slide level2 smaller">
<h2>Populations and samples</h2>
<ul>
<li class="fragment"><p><span class="blue">Population</span>: All the cases from which you could have sampled</p></li>
<li class="fragment"><p><span class="blue">Parameter:</span> A quantity or quantities of interest often generically called <span class="math inline">\(\theta\)</span> (“theta”). What we want to learn about our population</p></li>
<li class="fragment"><p><span class="blue">Sample:</span> A (random) draw of observations from that population</p></li>
<li class="fragment"><p><span class="blue">Sample Size:</span> The number of observations in your draw (without replacement)</p></li>
</ul>
</section>
<section id="estimators-estimates-and-statistics" class="slide level2 smaller">
<h2>Estimators, estimates, and statistics</h2>
<ul>
<li class="fragment"><p><span class="blue">Estimator:</span> A rule for calculating an <em>estimate</em> of our parameter of interest.</p></li>
<li class="fragment"><p><span class="blue">Estimate:</span> The value produced by some estimator for some parameter from some data. Often called <span class="math inline">\(\hat{\theta}\)</span></p></li>
<li class="fragment"><p><span class="blue">Unbiased estimators:</span> <span class="math inline">\(E(\hat{\theta})=E(\theta)\)</span> On average, the estimates produced by some estimator will be centered around the truth</p></li>
<li class="fragment"><p><span class="blue">Consistent estimates:</span> <span class="math inline">\(\lim_{n\to \infty} \hat{\theta}_N = \theta\)</span> As the sample size increases, the estimates from an estimator converge in probability to the parameter value</p></li>
<li class="fragment"><p><span class="blue">Statistic:</span> A summary of the data (mean, regression coefficient, <span class="math inline">\(R^2\)</span>). An estimator without a specified target of inference</p></li>
</ul>
</section>
<section id="distrubtions-and-standard-errors" class="slide level2 smaller">
<h2>Distrubtions and standard errors</h2>
<ul>
<li class="fragment"><p><span class="blue">Sampling Distribution:</span> How some estimate would vary if you took <span class="blue">repeated samples</span> from the population</p></li>
<li class="fragment"><p><span class="blue">Standard Error:</span> The standard deviation of the sampling distribution</p></li>
<li class="fragment"><p><span class="blue">Resampling Distribution:</span> How some estimate would vary if you took repeated samples <span class="blue">from your sample WITH REPLACEMENT</span></p>
<ul>
<li class="fragment">“Sampling from our sample, as the sample was sampled from the population.”</li>
</ul></li>
</ul>
</section>
<section id="sampling-distributions" class="slide level2 smaller">
<h2>Sampling distributions</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Overview</a></li><li><a href="#tabset-1-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-1-3">N = 10</a></li><li><a href="#tabset-1-4">N = 30</a></li><li><a href="#tabset-1-5">N = 300</a></li><li><a href="#tabset-1-6">Comments</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<ul>
<li><p>Treat the 2024 NES pilot as the population</p></li>
<li><p>Take repeated samples of size N = 10, 30, 300</p></li>
<li><p>For each sample of size N, calculate the sample mean of <code>age</code></p></li>
<li><p>Plot the distribution of sample means (i.e.&nbsp;the sampling distribution)</p></li>
</ul>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Load Data</span></span>
<span id="cb3-2"><a></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://josephessig-source.github.io/pols1600_site/files/data/nes24.rda"</span>))</span>
<span id="cb3-3"><a></a></span>
<span id="cb3-4"><a></a><span class="co"># ---- Population ----</span></span>
<span id="cb3-5"><a></a></span>
<span id="cb3-6"><a></a><span class="co"># Population average</span></span>
<span id="cb3-7"><a></a>mu_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(df<span class="sc">$</span>age, <span class="at">na.rm=</span>T)</span>
<span id="cb3-8"><a></a><span class="co"># Population standard deviation</span></span>
<span id="cb3-9"><a></a>sd_age <span class="ot">&lt;-</span> <span class="fu">sd</span>(df<span class="sc">$</span>age, <span class="at">na.rm =</span> T)</span>
<span id="cb3-10"><a></a></span>
<span id="cb3-11"><a></a><span class="co"># ---- Function to Take Repeated Samples From Data ----</span></span>
<span id="cb3-12"><a></a></span>
<span id="cb3-13"><a></a>sample_data_fn <span class="ot">&lt;-</span> <span class="cf">function</span>(</span>
<span id="cb3-14"><a></a>    <span class="at">dat=</span>df, <span class="at">var=</span>age, <span class="at">samps=</span><span class="dv">1000</span>, <span class="at">sample_size=</span><span class="dv">10</span>,</span>
<span id="cb3-15"><a></a>    <span class="at">resample =</span> F){</span>
<span id="cb3-16"><a></a>  <span class="cf">if</span>(resample <span class="sc">==</span> F){</span>
<span id="cb3-17"><a></a>  df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-18"><a></a>  <span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span>samps,</span>
<span id="cb3-19"><a></a>  <span class="at">distribution =</span> <span class="st">"Sampling"</span>,</span>
<span id="cb3-20"><a></a>  <span class="at">size =</span> sample_size,</span>
<span id="cb3-21"><a></a>  <span class="at">sample_from =</span> <span class="st">"Population"</span>,</span>
<span id="cb3-22"><a></a>  <span class="at">pop_mean =</span> dat <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(., <span class="at">na.rm=</span>T),</span>
<span id="cb3-23"><a></a>  <span class="at">pop_sd =</span> dat <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">sd</span>(., <span class="at">na.rm=</span>T),</span>
<span id="cb3-24"><a></a>  <span class="at">se_asymp =</span> pop_sd <span class="sc">/</span> <span class="fu">sqrt</span>(size),</span>
<span id="cb3-25"><a></a>  <span class="at">ll_asymp =</span> pop_mean <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>se_asymp,</span>
<span id="cb3-26"><a></a>  <span class="at">ul_asymp =</span> pop_mean <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>se_asymp,</span>
<span id="cb3-27"><a></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-28"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-29"><a></a>    <span class="at">sample =</span> purrr<span class="sc">::</span><span class="fu">map</span>(sim, <span class="sc">~</span> <span class="fu">slice_sample</span>(dat <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)), <span class="at">n =</span> sample_size, <span class="at">replace =</span> F)),</span>
<span id="cb3-30"><a></a>    <span class="at">sample_mean =</span> purrr<span class="sc">::</span><span class="fu">map_dbl</span>(sample, \(x) x <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(.,<span class="at">na.rm=</span>T)),</span>
<span id="cb3-31"><a></a>    <span class="at">ll =</span> sample_mean <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(sample_mean),</span>
<span id="cb3-32"><a></a>    <span class="at">ul =</span> sample_mean <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(sample_mean)</span>
<span id="cb3-33"><a></a>  )</span>
<span id="cb3-34"><a></a>  }</span>
<span id="cb3-35"><a></a>  <span class="cf">if</span>(resample <span class="sc">==</span> T){</span>
<span id="cb3-36"><a></a>    df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-37"><a></a>  <span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span>samps,</span>
<span id="cb3-38"><a></a>  <span class="at">distribution =</span> <span class="st">"Resampling"</span>,</span>
<span id="cb3-39"><a></a>  <span class="at">size =</span> sample_size,</span>
<span id="cb3-40"><a></a>  <span class="at">sample_from =</span> <span class="st">"Sample"</span>,</span>
<span id="cb3-41"><a></a>  <span class="at">pop_mean =</span> dat <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(., <span class="at">na.rm=</span>T),</span>
<span id="cb3-42"><a></a>  <span class="at">pop_sd =</span> dat <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">sd</span>(., <span class="at">na.rm=</span>T),</span>
<span id="cb3-43"><a></a>  <span class="at">se_asymp =</span> pop_sd <span class="sc">/</span> <span class="fu">sqrt</span>(size),</span>
<span id="cb3-44"><a></a>  <span class="at">ll_asymp =</span> pop_mean <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>se_asymp,</span>
<span id="cb3-45"><a></a>  <span class="at">ul_asymp =</span> pop_mean <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>se_asymp,</span>
<span id="cb3-46"><a></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-47"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-48"><a></a>    <span class="at">sample =</span> purrr<span class="sc">::</span><span class="fu">map</span>(sim, <span class="sc">~</span> <span class="fu">slice_sample</span>(dat <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)), <span class="at">n =</span> sample_size, <span class="at">replace =</span> T)),</span>
<span id="cb3-49"><a></a>    <span class="at">sample_mean =</span> purrr<span class="sc">::</span><span class="fu">map_dbl</span>(sample, \(x) x <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(.,<span class="at">na.rm=</span>T))</span>
<span id="cb3-50"><a></a>  )</span>
<span id="cb3-51"><a></a>  }</span>
<span id="cb3-52"><a></a>  <span class="fu">return</span>(df)</span>
<span id="cb3-53"><a></a>}</span>
<span id="cb3-54"><a></a></span>
<span id="cb3-55"><a></a><span class="co"># ---- Plot Single Distribution -----</span></span>
<span id="cb3-56"><a></a></span>
<span id="cb3-57"><a></a>plot_distribution <span class="ot">&lt;-</span> <span class="cf">function</span>(the_pop,the_samp, the_var, ...){</span>
<span id="cb3-58"><a></a>  mu_pop <span class="ot">&lt;-</span> the_pop <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(the_var)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-59"><a></a>  mu_samp <span class="ot">&lt;-</span> the_samp <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(the_var)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-60"><a></a>  ll <span class="ot">&lt;-</span> the_pop <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(the_var)) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span>  <span class="fu">min</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-61"><a></a>  ul <span class="ot">&lt;-</span> the_pop <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(the_var)) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span> <span class="fu">max</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-62"><a></a>  p<span class="ot">&lt;-</span> the_samp <span class="sc">%&gt;%</span> </span>
<span id="cb3-63"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="sc">!!</span><span class="fu">enquo</span>(the_var)))<span class="sc">+</span></span>
<span id="cb3-64"><a></a>    <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb3-65"><a></a>    <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb3-66"><a></a>    <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb3-67"><a></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_samp, <span class="at">col =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb3-68"><a></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_pop, <span class="at">col =</span> <span class="st">"grey40"</span>,<span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb3-69"><a></a>    <span class="fu">xlim</span>(ll,ul)</span>
<span id="cb3-70"><a></a>  <span class="fu">return</span>(p)</span>
<span id="cb3-71"><a></a>}</span>
<span id="cb3-72"><a></a></span>
<span id="cb3-73"><a></a><span class="co"># ---- Plot multiple distributions ----</span></span>
<span id="cb3-74"><a></a></span>
<span id="cb3-75"><a></a>plot_samples <span class="ot">&lt;-</span> <span class="cf">function</span>(pop, x, variable,<span class="at">n_rows =</span> <span class="dv">4</span>, ...){</span>
<span id="cb3-76"><a></a>  sample_plots <span class="ot">&lt;-</span> x<span class="sc">$</span>sample[<span class="dv">1</span><span class="sc">:</span>(<span class="dv">4</span><span class="sc">*</span>n_rows)] <span class="sc">%&gt;%</span> </span>
<span id="cb3-77"><a></a>  purrr<span class="sc">::</span><span class="fu">map</span>( \(x) <span class="fu">plot_distribution</span>(<span class="at">the_pop=</span>pop, <span class="at">the_samp =</span> x, </span>
<span id="cb3-78"><a></a>                                     <span class="at">the_var =</span> <span class="sc">!!</span><span class="fu">enquo</span>(variable)))</span>
<span id="cb3-79"><a></a>  p <span class="ot">&lt;-</span> <span class="fu">wrap_elements</span>(<span class="fu">wrap_plots</span>(sample_plots[<span class="dv">1</span><span class="sc">:</span>(<span class="dv">4</span><span class="sc">*</span>n_rows)], <span class="at">ncol=</span><span class="dv">4</span>))</span>
<span id="cb3-80"><a></a>  <span class="fu">return</span>(p)</span>
<span id="cb3-81"><a></a>  </span>
<span id="cb3-82"><a></a>}</span>
<span id="cb3-83"><a></a></span>
<span id="cb3-84"><a></a><span class="co"># ---- Plot Combined Figure ----</span></span>
<span id="cb3-85"><a></a></span>
<span id="cb3-86"><a></a>plot_figure_fn <span class="ot">&lt;-</span> <span class="cf">function</span>(</span>
<span id="cb3-87"><a></a>    <span class="at">d=</span>df, </span>
<span id="cb3-88"><a></a>    <span class="at">v=</span>age, </span>
<span id="cb3-89"><a></a>    <span class="at">sim=</span><span class="dv">1000</span>, </span>
<span id="cb3-90"><a></a>    <span class="at">size=</span><span class="dv">10</span>,</span>
<span id="cb3-91"><a></a>    <span class="at">rows =</span> <span class="dv">4</span>){</span>
<span id="cb3-92"><a></a>  <span class="co"># Population average</span></span>
<span id="cb3-93"><a></a>  mu <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-94"><a></a>  sd <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">sd</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-95"><a></a>  se <span class="ot">&lt;-</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(size)</span>
<span id="cb3-96"><a></a>  <span class="co"># Range</span></span>
<span id="cb3-97"><a></a>  ll <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span>  <span class="fu">min</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-98"><a></a>  ul <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span> <span class="fu">max</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb3-99"><a></a>  <span class="co"># Population standard deviation</span></span>
<span id="cb3-100"><a></a>  <span class="co"># Sample data</span></span>
<span id="cb3-101"><a></a>  samp_df <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(<span class="at">dat=</span>d, <span class="at">var =</span> <span class="sc">!!</span><span class="fu">enquo</span>(v), <span class="at">samps =</span> sim, <span class="at">sample_size =</span> size)</span>
<span id="cb3-102"><a></a>  <span class="co"># Plot Population</span></span>
<span id="cb3-103"><a></a>  p_pop <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span></span>
<span id="cb3-104"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)))<span class="sc">+</span></span>
<span id="cb3-105"><a></a>      <span class="fu">geom_density</span>(<span class="at">col =</span><span class="st">"grey60"</span>)<span class="sc">+</span></span>
<span id="cb3-106"><a></a>      <span class="fu">geom_rug</span>(<span class="at">col =</span> <span class="st">"grey60"</span>, )<span class="sc">+</span></span>
<span id="cb3-107"><a></a>      <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu, <span class="at">col=</span><span class="st">"grey40"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb3-108"><a></a>      <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb3-109"><a></a>      <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Population"</span>)<span class="sc">+</span></span>
<span id="cb3-110"><a></a>      <span class="fu">xlim</span>(ll,ul)<span class="sc">+</span></span>
<span id="cb3-111"><a></a>      <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>))</span>
<span id="cb3-112"><a></a></span>
<span id="cb3-113"><a></a>  </span>
<span id="cb3-114"><a></a>  p_samps <span class="ot">&lt;-</span> <span class="fu">plot_samples</span>(<span class="at">pop=</span>d, <span class="at">x=</span> samp_df,<span class="at">variable =</span> <span class="sc">!!</span><span class="fu">enquo</span>(v),</span>
<span id="cb3-115"><a></a>                          <span class="at">n_rows =</span> rows)</span>
<span id="cb3-116"><a></a>  p_samps <span class="ot">&lt;-</span> p_samps <span class="sc">+</span> </span>
<span id="cb3-117"><a></a>    <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Repeated samples of size N ="</span>,size,<span class="st">"from the population"</span>))<span class="sc">+</span></span>
<span id="cb3-118"><a></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), </span>
<span id="cb3-119"><a></a>          <span class="at">plot.background =</span> <span class="fu">element_rect</span>(</span>
<span id="cb3-120"><a></a>            <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">linewidth =</span> <span class="dv">2</span>)</span>
<span id="cb3-121"><a></a>          )</span>
<span id="cb3-122"><a></a>  </span>
<span id="cb3-123"><a></a>  </span>
<span id="cb3-124"><a></a>  p_dist <span class="ot">&lt;-</span> samp_df <span class="sc">%&gt;%</span> </span>
<span id="cb3-125"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sample_mean))<span class="sc">+</span></span>
<span id="cb3-126"><a></a>  <span class="fu">geom_density</span>(<span class="at">col=</span><span class="st">"red"</span>,<span class="fu">aes</span>(<span class="at">y=</span> <span class="fu">after_stat</span>(ndensity)))<span class="sc">+</span></span>
<span id="cb3-127"><a></a>  <span class="fu">geom_rug</span>(<span class="at">col=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb3-128"><a></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v), <span class="at">y=</span> <span class="fu">after_stat</span>(ndensity)),</span>
<span id="cb3-129"><a></a>               <span class="at">col=</span><span class="st">"grey60"</span>)<span class="sc">+</span></span>
<span id="cb3-130"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu, <span class="at">col=</span><span class="st">"grey40"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb3-131"><a></a>  <span class="fu">xlim</span>(ll,ul)<span class="sc">+</span></span>
<span id="cb3-132"><a></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb3-133"><a></a>    <span class="fu">labs</span>(</span>
<span id="cb3-134"><a></a>      <span class="at">title =</span> <span class="st">"Sampling Distribution"</span></span>
<span id="cb3-135"><a></a>    )<span class="sc">+</span>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>))</span>
<span id="cb3-136"><a></a>  </span>
<span id="cb3-137"><a></a>  range_upper_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-138"><a></a>  <span class="at">x =</span> <span class="fu">seq</span>( ((ll<span class="sc">+</span>ul)<span class="sc">/</span><span class="dv">2</span> <span class="sc">-</span><span class="dv">5</span>), ((ll<span class="sc">+</span>ul)<span class="sc">/</span><span class="dv">2</span> <span class="sc">+</span><span class="dv">5</span>), <span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb3-139"><a></a>  <span class="at">xend =</span> <span class="fu">seq</span>(ll<span class="dv">-5</span>, ul<span class="sc">+</span><span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb3-140"><a></a>  <span class="at">y =</span> <span class="fu">rep</span>(<span class="dv">9</span>, <span class="dv">20</span>),</span>
<span id="cb3-141"><a></a>  <span class="at">yend =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">20</span>)</span>
<span id="cb3-142"><a></a>)</span>
<span id="cb3-143"><a></a>p_upper <span class="ot">&lt;-</span> range_upper_df <span class="sc">%&gt;%</span> </span>
<span id="cb3-144"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">xend =</span> xend, <span class="at">y=</span>y,<span class="at">yend=</span>yend))<span class="sc">+</span></span>
<span id="cb3-145"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb3-146"><a></a>    <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.05</span>, <span class="st">"npc"</span>))</span>
<span id="cb3-147"><a></a>  )<span class="sc">+</span></span>
<span id="cb3-148"><a></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb3-149"><a></a>  <span class="fu">coord_fixed</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>),</span>
<span id="cb3-150"><a></a>              <span class="at">xlim =</span><span class="fu">c</span>(ll<span class="dv">-5</span>,ul<span class="sc">+</span><span class="dv">5</span>),<span class="at">clip=</span><span class="st">"off"</span>)</span>
<span id="cb3-151"><a></a>  <span class="co"># Lower</span></span>
<span id="cb3-152"><a></a>  range_df <span class="ot">&lt;-</span> samp_df <span class="sc">%&gt;%</span> </span>
<span id="cb3-153"><a></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-154"><a></a>    <span class="at">min =</span> <span class="fu">min</span>(sample_mean),</span>
<span id="cb3-155"><a></a>    <span class="at">max =</span> <span class="fu">max</span>(sample_mean),</span>
<span id="cb3-156"><a></a>    <span class="at">mean =</span> <span class="fu">mean</span>(sample_mean)</span>
<span id="cb3-157"><a></a>  )</span>
<span id="cb3-158"><a></a>  </span>
<span id="cb3-159"><a></a>  plot_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-160"><a></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,</span>
<span id="cb3-161"><a></a>  <span class="co"># x = sort(rnorm(50, mu, sd)),</span></span>
<span id="cb3-162"><a></a>  <span class="at">x =</span> <span class="fu">sort</span>(<span class="fu">runif</span>(<span class="dv">50</span>, ll, ul)),</span>
<span id="cb3-163"><a></a>  <span class="at">xend =</span> <span class="fu">sort</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>, mu, se)),</span>
<span id="cb3-164"><a></a>  <span class="at">y =</span> <span class="dv">9</span>,</span>
<span id="cb3-165"><a></a>  <span class="at">yend =</span> <span class="dv">1</span></span>
<span id="cb3-166"><a></a>)</span>
<span id="cb3-167"><a></a></span>
<span id="cb3-168"><a></a>p_lower <span class="ot">&lt;-</span> plot_df <span class="sc">%&gt;%</span></span>
<span id="cb3-169"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x,y, <span class="at">group =</span>id))<span class="sc">+</span></span>
<span id="cb3-170"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend=</span>xend, <span class="at">yend=</span>yend),</span>
<span id="cb3-171"><a></a>               <span class="at">col =</span> <span class="st">"red"</span>,<span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.05</span>, <span class="st">"npc"</span>))</span>
<span id="cb3-172"><a></a>               )<span class="sc">+</span></span>
<span id="cb3-173"><a></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb3-174"><a></a>  <span class="fu">coord_fixed</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>),<span class="at">xlim =</span> <span class="fu">c</span>(ll,ul),<span class="at">clip=</span><span class="st">"off"</span>)</span>
<span id="cb3-175"><a></a></span>
<span id="cb3-176"><a></a>  </span>
<span id="cb3-177"><a></a>  design <span class="ot">&lt;-</span><span class="st">"##AAAA##</span></span>
<span id="cb3-178"><a></a><span class="st">            ##AAAA##</span></span>
<span id="cb3-179"><a></a><span class="st">            ##AAAA##</span></span>
<span id="cb3-180"><a></a><span class="st">            BBBBBBBB</span></span>
<span id="cb3-181"><a></a><span class="st">            BBBBBBBB</span></span>
<span id="cb3-182"><a></a><span class="st">            #CCCCCC#</span></span>
<span id="cb3-183"><a></a><span class="st">            #CCCCCC#</span></span>
<span id="cb3-184"><a></a><span class="st">            #CCCCCC#</span></span>
<span id="cb3-185"><a></a><span class="st">            #CCCCCC#</span></span>
<span id="cb3-186"><a></a><span class="st">            DDDDDDDD</span></span>
<span id="cb3-187"><a></a><span class="st">            DDDDDDDD</span></span>
<span id="cb3-188"><a></a><span class="st">            ##EEEE##</span></span>
<span id="cb3-189"><a></a><span class="st">            ##EEEE##</span></span>
<span id="cb3-190"><a></a><span class="st">            ##EEEE##"</span></span>
<span id="cb3-191"><a></a>  </span>
<span id="cb3-192"><a></a>  fig <span class="ot">&lt;-</span> p_pop <span class="sc">/</span> p_upper <span class="sc">/</span> p_samps <span class="sc">/</span> p_lower <span class="sc">/</span> p_dist <span class="sc">+</span></span>
<span id="cb3-193"><a></a>    <span class="fu">plot_layout</span>(<span class="at">design =</span> design)</span>
<span id="cb3-194"><a></a>  <span class="fu">return</span>(fig)</span>
<span id="cb3-195"><a></a></span>
<span id="cb3-196"><a></a></span>
<span id="cb3-197"><a></a>  </span>
<span id="cb3-198"><a></a>  </span>
<span id="cb3-199"><a></a>  </span>
<span id="cb3-200"><a></a>}</span>
<span id="cb3-201"><a></a></span>
<span id="cb3-202"><a></a><span class="co"># ---- Samples and Figures Varying Sample Size ----</span></span>
<span id="cb3-203"><a></a><span class="do">## N = 10</span></span>
<span id="cb3-204"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-205"><a></a>samp_n10 <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(<span class="at">sample_size  =</span> <span class="dv">10</span>, <span class="at">samps =</span> <span class="dv">1000</span>)</span>
<span id="cb3-206"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-207"><a></a>fig_n10 <span class="ot">&lt;-</span> <span class="fu">plot_figure_fn</span>(<span class="at">v=</span>age,<span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb3-208"><a></a></span>
<span id="cb3-209"><a></a><span class="do">## N = 30</span></span>
<span id="cb3-210"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-211"><a></a>samp_n30 <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(<span class="at">sample_size  =</span> <span class="dv">30</span>, <span class="at">samps =</span> <span class="dv">1000</span>)</span>
<span id="cb3-212"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-213"><a></a>fig_n30 <span class="ot">&lt;-</span> <span class="fu">plot_figure_fn</span>(<span class="at">size =</span> <span class="dv">30</span>,<span class="at">rows=</span><span class="dv">4</span>)</span>
<span id="cb3-214"><a></a></span>
<span id="cb3-215"><a></a><span class="do">## N = 300</span></span>
<span id="cb3-216"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-217"><a></a>samp_n300 <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(<span class="at">sample_size  =</span> <span class="dv">300</span>, <span class="at">samps =</span> <span class="dv">1000</span>)</span>
<span id="cb3-218"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-219"><a></a>fig_n300 <span class="ot">&lt;-</span> <span class="fu">plot_figure_fn</span>(<span class="at">size =</span> <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-3">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fign10-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fign30-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-5">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fign300-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-6">
<p>As the sample sample size increases:</p>
<ul>
<li><p>The width of the sampling distribution decreases (LLN)</p></li>
<li><p>The shape of the sampling distribution approximates a Normal distribution (CLT)</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="standard-errors" class="slide level2 smaller">
<h2>Standard errors</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Overview</a></li><li><a href="#tabset-2-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-2-3"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> SEs</a></li><li><a href="#tabset-2-4"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Coverage</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<ul>
<li><p>The standard error (SE) is simply the <span class="blue">standard deviation</span> of the sampling distribution.</p></li>
<li><p>The SE decreases as the sample size increases (by the LLN):</p></li>
<li><p>Approximately 95% of the sample means will be within 2 SEs of the population mean (CLT)</p></li>
</ul>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>se_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb4-2"><a></a>  <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"N ="</span>,<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">30</span>, <span class="dv">300</span>))),</span>
<span id="cb4-3"><a></a>  <span class="at">se =</span> <span class="fu">c</span>(<span class="fu">sd</span>(samp_n10<span class="sc">$</span>sample_mean),</span>
<span id="cb4-4"><a></a>         <span class="fu">sd</span>(samp_n30<span class="sc">$</span>sample_mean),</span>
<span id="cb4-5"><a></a>         <span class="fu">sd</span>(samp_n300<span class="sc">$</span>sample_mean)),</span>
<span id="cb4-6"><a></a>  <span class="at">SE =</span> <span class="fu">paste</span>(<span class="st">"SE ="</span>, <span class="fu">round</span>(se,<span class="dv">2</span>)),</span>
<span id="cb4-7"><a></a>  <span class="at">ll =</span> mu_age,</span>
<span id="cb4-8"><a></a>  <span class="at">ul =</span> mu_age <span class="sc">+</span> se,</span>
<span id="cb4-9"><a></a>  <span class="at">y =</span> <span class="fu">c</span>(.<span class="dv">3</span>,.<span class="dv">3</span>,.<span class="dv">45</span>),</span>
<span id="cb4-10"><a></a>  <span class="at">yend =</span> y</span>
<span id="cb4-11"><a></a>)</span>
<span id="cb4-12"><a></a></span>
<span id="cb4-13"><a></a>ci_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb4-14"><a></a>  <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"N ="</span>,<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">30</span>, <span class="dv">300</span>))),</span>
<span id="cb4-15"><a></a>  <span class="at">se =</span> <span class="fu">c</span>(<span class="fu">sd</span>(samp_n10<span class="sc">$</span>sample_mean),</span>
<span id="cb4-16"><a></a>         <span class="fu">sd</span>(samp_n30<span class="sc">$</span>sample_mean),</span>
<span id="cb4-17"><a></a>         <span class="fu">sd</span>(samp_n300<span class="sc">$</span>sample_mean)),</span>
<span id="cb4-18"><a></a>  <span class="at">mu =</span> mu_age,</span>
<span id="cb4-19"><a></a>  <span class="at">ll =</span> <span class="fu">round</span>(mu_age <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span>se,<span class="dv">2</span>),</span>
<span id="cb4-20"><a></a>  <span class="at">ul =</span> <span class="fu">round</span>(mu_age <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span>se,<span class="dv">2</span>),</span>
<span id="cb4-21"><a></a>  <span class="at">ci =</span> <span class="fu">paste</span>(<span class="st">"95 % Coverage Interval ["</span>,ll,<span class="st">";"</span>,ul,<span class="st">"]"</span>,<span class="at">sep=</span><span class="st">""</span>),</span>
<span id="cb4-22"><a></a>  <span class="at">y =</span> <span class="fu">c</span>(.<span class="dv">3</span>,.<span class="dv">3</span>,.<span class="dv">45</span>),</span>
<span id="cb4-23"><a></a>  <span class="at">yend =</span> y</span>
<span id="cb4-24"><a></a>)</span>
<span id="cb4-25"><a></a>sim_df <span class="ot">&lt;-</span> samp_n10 <span class="sc">%&gt;%</span> </span>
<span id="cb4-26"><a></a>  <span class="fu">bind_rows</span>(samp_n30) <span class="sc">%&gt;%</span> </span>
<span id="cb4-27"><a></a>  <span class="fu">bind_rows</span>(samp_n300) <span class="sc">%&gt;%</span> </span>
<span id="cb4-28"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-29"><a></a>    <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"N ="</span>,size))</span>
<span id="cb4-30"><a></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb4-31"><a></a>  <span class="fu">left_join</span>(ci_df) <span class="sc">%&gt;%</span> </span>
<span id="cb4-32"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-33"><a></a>    <span class="at">Coverage =</span> <span class="fu">case_when</span>(</span>
<span id="cb4-34"><a></a>      sample_mean <span class="sc">&gt;</span> ll_asymp <span class="sc">&amp;</span> sample_mean <span class="sc">&lt;</span> ul_asymp  <span class="sc">&amp;</span> size <span class="sc">==</span> <span class="dv">10</span><span class="sc">~</span> <span class="st">"#F8766D"</span>,</span>
<span id="cb4-35"><a></a>      sample_mean <span class="sc">&gt;</span> ll_asymp <span class="sc">&amp;</span> sample_mean <span class="sc">&lt;</span> ul_asymp  <span class="sc">&amp;</span> size <span class="sc">==</span> <span class="dv">30</span><span class="sc">~</span> <span class="st">"#00BA38"</span>,</span>
<span id="cb4-36"><a></a>      sample_mean <span class="sc">&gt;</span> ll_asymp <span class="sc">&amp;</span> sample_mean <span class="sc">&lt;</span> ul_asymp  <span class="sc">&amp;</span> size <span class="sc">==</span> <span class="dv">300</span><span class="sc">~</span> <span class="st">"#619CFF"</span>,</span>
<span id="cb4-37"><a></a>      T <span class="sc">~</span> <span class="st">"grey"</span></span>
<span id="cb4-38"><a></a>    )</span>
<span id="cb4-39"><a></a>  )</span>
<span id="cb4-40"><a></a></span>
<span id="cb4-41"><a></a></span>
<span id="cb4-42"><a></a></span>
<span id="cb4-43"><a></a>fig_se <span class="ot">&lt;-</span> sim_df <span class="sc">%&gt;%</span> </span>
<span id="cb4-44"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sample_mean, <span class="at">col =</span> <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb4-45"><a></a>  <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb4-46"><a></a>  <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb4-47"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_age, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb4-48"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb4-49"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>, <span class="at">ncol=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb4-50"><a></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb4-51"><a></a>  <span class="fu">guides</span>(<span class="at">col=</span><span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb4-52"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb4-53"><a></a>    <span class="at">data =</span> se_df,</span>
<span id="cb4-54"><a></a>    <span class="fu">aes</span>(<span class="at">x=</span> ll, <span class="at">xend =</span>ul, <span class="at">y =</span> y, <span class="at">yend =</span> yend)</span>
<span id="cb4-55"><a></a>  )<span class="sc">+</span></span>
<span id="cb4-56"><a></a>  <span class="fu">geom_text</span>(</span>
<span id="cb4-57"><a></a>    <span class="at">data =</span> se_df,</span>
<span id="cb4-58"><a></a>    <span class="fu">aes</span>(<span class="at">x =</span> ul, <span class="at">y =</span>y, <span class="at">label =</span> SE),</span>
<span id="cb4-59"><a></a>    <span class="at">hjust =</span> <span class="sc">-</span>.<span class="dv">25</span></span>
<span id="cb4-60"><a></a>  ) <span class="sc">+</span></span>
<span id="cb4-61"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb4-62"><a></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb4-63"><a></a>    <span class="at">x =</span> <span class="st">"Sampling Distributions of Sample Means"</span>,</span>
<span id="cb4-64"><a></a>    <span class="at">title =</span> <span class="st">"Standard Errors decrease with Sample Size"</span></span>
<span id="cb4-65"><a></a>  )</span>
<span id="cb4-66"><a></a></span>
<span id="cb4-67"><a></a>fig_coverage <span class="ot">&lt;-</span> sim_df <span class="sc">%&gt;%</span> </span>
<span id="cb4-68"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sample_mean,<span class="at">col=</span><span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb4-69"><a></a>  <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb4-70"><a></a>  <span class="fu">geom_rug</span>(<span class="at">col=</span>sim_df<span class="sc">$</span>Coverage)<span class="sc">+</span></span>
<span id="cb4-71"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_age, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb4-72"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb4-73"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>, <span class="at">ncol=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb4-74"><a></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,.<span class="dv">55</span>)<span class="sc">+</span></span>
<span id="cb4-75"><a></a>  <span class="fu">guides</span>(<span class="at">col=</span><span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb4-76"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb4-77"><a></a>    <span class="at">data =</span> ci_df,</span>
<span id="cb4-78"><a></a>    <span class="fu">aes</span>(<span class="at">x=</span> ll, <span class="at">xend =</span>ul, <span class="at">y =</span> y, <span class="at">yend =</span> yend)</span>
<span id="cb4-79"><a></a>  )<span class="sc">+</span></span>
<span id="cb4-80"><a></a>  <span class="fu">geom_text</span>(</span>
<span id="cb4-81"><a></a>    <span class="at">data =</span> ci_df,</span>
<span id="cb4-82"><a></a>    <span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span>y, <span class="at">label =</span> ci),</span>
<span id="cb4-83"><a></a>    <span class="at">hjust =</span> .<span class="dv">5</span>,</span>
<span id="cb4-84"><a></a>    <span class="at">nudge_y =</span>.<span class="dv">1</span></span>
<span id="cb4-85"><a></a>  ) <span class="sc">+</span></span>
<span id="cb4-86"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb4-87"><a></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb4-88"><a></a>    <span class="at">x =</span> <span class="st">"Sampling Distributions of Sample Means"</span>,</span>
<span id="cb4-89"><a></a>    <span class="at">title =</span> <span class="st">"Approximately 95% of sample means are within 2 SE of the population mean"</span></span>
<span id="cb4-90"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-2-3">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/figse-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/figcoverage-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="how-do-we-calculate-a-standard-error-from-a-single-sample" class="slide level2 center smaller">
<h2>How do we calculate a standard error from a single sample?</h2>
</section>
<section id="calculating-standard-errors" class="slide level2 smaller">
<h2>Calculating standard errors</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Two Approaches</a></li><li><a href="#tabset-3-2"><i class="fa-solid fa-code" aria-label="code"></i></a></li><li><a href="#tabset-3-3">N = 10</a></li><li><a href="#tabset-3-4">N = 30</a></li><li><a href="#tabset-3-5">N = 300</a></li><li><a href="#tabset-3-6">Simulation vs Analytic</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<ul>
<li><span class="blue">Simulation</span>:
<ul>
<li>Treat sample as population</li>
<li>Sample with replacement (“bootstrapping”)</li>
<li>Estimate SE from standard deviation of resampling distribution (“plug-in principle”)</li>
</ul></li>
<li><span class="blue">Analytic</span>
<ul>
<li>Characterize sampling distribution from sample mean and variance via asymptotic theory (the LLT and CLT)</li>
<li>For a sample mean, <span class="math inline">\(\bar{x}\)</span></li>
</ul></li>
</ul>
<p><span class="math display">\[
SE_{\bar{x}} = \frac{\sigma_x}{\sqrt(n)}
\]</span></p>
</div>
<div id="tabset-3-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>plot_resampling_fn <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">d=</span>df, <span class="at">v=</span>age, <span class="at">sim=</span><span class="dv">1000</span>, <span class="at">size=</span><span class="dv">10</span>,<span class="at">rows=</span><span class="dv">3</span>){</span>
<span id="cb5-2"><a></a>  <span class="co"># Population average</span></span>
<span id="cb5-3"><a></a>  mu <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">mean</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb5-4"><a></a>  <span class="co"># Population standard deviation and SE</span></span>
<span id="cb5-5"><a></a>  sd <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">sd</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb5-6"><a></a>  se <span class="ot">&lt;-</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(size)</span>
<span id="cb5-7"><a></a>  <span class="co"># Range</span></span>
<span id="cb5-8"><a></a>  ll <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span>  <span class="fu">min</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb5-9"><a></a>  ul <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">pull</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span> <span class="fu">max</span>(., <span class="at">na.rm=</span>T)</span>
<span id="cb5-10"><a></a>  <span class="co"># Resampling with replace</span></span>
<span id="cb5-11"><a></a>  <span class="co"># Draw 1 Sample</span></span>
<span id="cb5-12"><a></a>  sample <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(<span class="at">dat=</span>d, <span class="at">var =</span> <span class="sc">!!</span><span class="fu">enquo</span>(v), <span class="at">samps =</span> <span class="dv">1</span>, <span class="at">sample_size =</span> size, <span class="at">resample =</span> F)</span>
<span id="cb5-13"><a></a>  samp_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(sample<span class="sc">$</span>sample)</span>
<span id="cb5-14"><a></a>  <span class="co"># Resample from sample with replacement</span></span>
<span id="cb5-15"><a></a>  resamp_df <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(<span class="at">dat=</span>samp_df, <span class="at">var =</span> <span class="sc">!!</span><span class="fu">enquo</span>(v), <span class="at">samps =</span> sim, <span class="at">sample_size =</span> size, <span class="at">resample =</span> T)</span>
<span id="cb5-16"><a></a>  <span class="co"># Plot Population</span></span>
<span id="cb5-17"><a></a>  p_pop <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span></span>
<span id="cb5-18"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v)))<span class="sc">+</span></span>
<span id="cb5-19"><a></a>      <span class="fu">geom_density</span>(<span class="at">col =</span><span class="st">"grey60"</span>)<span class="sc">+</span></span>
<span id="cb5-20"><a></a>      <span class="fu">geom_rug</span>(<span class="at">col =</span> <span class="st">"grey60"</span>, )<span class="sc">+</span></span>
<span id="cb5-21"><a></a>      <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu, <span class="at">col=</span><span class="st">"grey40"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb5-22"><a></a>      <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb5-23"><a></a>      <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Population"</span>)<span class="sc">+</span></span>
<span id="cb5-24"><a></a>      <span class="fu">xlim</span>(ll,ul)<span class="sc">+</span></span>
<span id="cb5-25"><a></a>      <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>))</span>
<span id="cb5-26"><a></a></span>
<span id="cb5-27"><a></a>  p_samp <span class="ot">&lt;-</span> <span class="fu">plot_distribution</span>(<span class="at">the_pop =</span> d,</span>
<span id="cb5-28"><a></a>                              <span class="at">the_samp =</span> samp_df,</span>
<span id="cb5-29"><a></a>                              <span class="at">the_var =</span> age)<span class="sc">+</span></span>
<span id="cb5-30"><a></a>    <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Sample"</span>)<span class="sc">+</span></span>
<span id="cb5-31"><a></a>      <span class="fu">xlim</span>(ll,ul)<span class="sc">+</span></span>
<span id="cb5-32"><a></a>      <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>))</span>
<span id="cb5-33"><a></a>  </span>
<span id="cb5-34"><a></a>  p_samps <span class="ot">&lt;-</span> <span class="fu">plot_samples</span>(<span class="at">pop=</span>d, <span class="at">x=</span> resamp_df,<span class="at">variable =</span> <span class="sc">!!</span><span class="fu">enquo</span>(v), <span class="at">n_rows =</span>rows)</span>
<span id="cb5-35"><a></a>  p_samps <span class="ot">&lt;-</span> p_samps <span class="sc">+</span> </span>
<span id="cb5-36"><a></a>    <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Repeated samples with replacement</span><span class="sc">\n</span><span class="st">of size N ="</span>,size,<span class="st">"from sample"</span>))<span class="sc">+</span></span>
<span id="cb5-37"><a></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), </span>
<span id="cb5-38"><a></a>          <span class="at">plot.background =</span> <span class="fu">element_rect</span>(</span>
<span id="cb5-39"><a></a>            <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">linewidth =</span> <span class="dv">2</span>)</span>
<span id="cb5-40"><a></a>          )</span>
<span id="cb5-41"><a></a>  </span>
<span id="cb5-42"><a></a>  <span class="co"># Resampling Distribution</span></span>
<span id="cb5-43"><a></a>  </span>
<span id="cb5-44"><a></a>  </span>
<span id="cb5-45"><a></a>  p_dist <span class="ot">&lt;-</span> resamp_df <span class="sc">%&gt;%</span> </span>
<span id="cb5-46"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sample_mean))<span class="sc">+</span></span>
<span id="cb5-47"><a></a>  <span class="fu">geom_density</span>(<span class="at">col=</span><span class="st">"red"</span>,<span class="fu">aes</span>(<span class="at">y=</span> <span class="fu">after_stat</span>(ndensity)))<span class="sc">+</span></span>
<span id="cb5-48"><a></a>  <span class="fu">geom_rug</span>(<span class="at">col=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb5-49"><a></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="sc">!!</span><span class="fu">enquo</span>(v), <span class="at">y=</span> <span class="fu">after_stat</span>(ndensity)),</span>
<span id="cb5-50"><a></a>               <span class="at">col=</span><span class="st">"grey60"</span>)<span class="sc">+</span></span>
<span id="cb5-51"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">unique</span>(resamp_df<span class="sc">$</span>pop_mean), <span class="at">col=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"solid"</span>)<span class="sc">+</span></span>
<span id="cb5-52"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu, <span class="at">col=</span><span class="st">"grey40"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb5-53"><a></a>  <span class="fu">xlim</span>(ll,ul)<span class="sc">+</span></span>
<span id="cb5-54"><a></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb5-55"><a></a>    <span class="fu">labs</span>(</span>
<span id="cb5-56"><a></a>      <span class="at">title =</span> <span class="st">"Reampling Distribution"</span></span>
<span id="cb5-57"><a></a>    )<span class="sc">+</span>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>))</span>
<span id="cb5-58"><a></a>  </span>
<span id="cb5-59"><a></a>   range_upper_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb5-60"><a></a>  <span class="at">x =</span> <span class="fu">seq</span>( ((ll<span class="sc">+</span>ul)<span class="sc">/</span><span class="dv">2</span> <span class="sc">-</span><span class="dv">5</span>), ((ll<span class="sc">+</span>ul)<span class="sc">/</span><span class="dv">2</span> <span class="sc">+</span><span class="dv">5</span>), <span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb5-61"><a></a>  <span class="at">xend =</span> <span class="fu">seq</span>(ll<span class="dv">-5</span>, ul<span class="sc">+</span><span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb5-62"><a></a>  <span class="at">y =</span> <span class="fu">rep</span>(<span class="dv">9</span>, <span class="dv">20</span>),</span>
<span id="cb5-63"><a></a>  <span class="at">yend =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">20</span>)</span>
<span id="cb5-64"><a></a>)</span>
<span id="cb5-65"><a></a>p_upper <span class="ot">&lt;-</span> range_upper_df <span class="sc">%&gt;%</span> </span>
<span id="cb5-66"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">xend =</span> xend, <span class="at">y=</span>y,<span class="at">yend=</span>yend))<span class="sc">+</span></span>
<span id="cb5-67"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb5-68"><a></a>    <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.05</span>, <span class="st">"npc"</span>))</span>
<span id="cb5-69"><a></a>  )<span class="sc">+</span></span>
<span id="cb5-70"><a></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb5-71"><a></a>  <span class="fu">coord_fixed</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>),</span>
<span id="cb5-72"><a></a>              <span class="at">xlim =</span><span class="fu">c</span>(ll<span class="dv">-5</span>,ul<span class="sc">+</span><span class="dv">5</span>),<span class="at">clip=</span><span class="st">"off"</span>)</span>
<span id="cb5-73"><a></a>  <span class="co"># Lower</span></span>
<span id="cb5-74"><a></a>  range_df <span class="ot">&lt;-</span> resamp_df <span class="sc">%&gt;%</span> </span>
<span id="cb5-75"><a></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-76"><a></a>    <span class="at">min =</span> <span class="fu">min</span>(sample_mean),</span>
<span id="cb5-77"><a></a>    <span class="at">max =</span> <span class="fu">max</span>(sample_mean),</span>
<span id="cb5-78"><a></a>    <span class="at">mean =</span> <span class="fu">mean</span>(sample_mean)</span>
<span id="cb5-79"><a></a>  )</span>
<span id="cb5-80"><a></a>  </span>
<span id="cb5-81"><a></a>  plot_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb5-82"><a></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,</span>
<span id="cb5-83"><a></a>  <span class="co"># x = sort(rnorm(50, mu, sd)),</span></span>
<span id="cb5-84"><a></a>  <span class="at">x =</span> <span class="fu">sort</span>(<span class="fu">runif</span>(<span class="dv">50</span>, ll, ul)),</span>
<span id="cb5-85"><a></a>  <span class="at">xend =</span> <span class="fu">sort</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="fu">unique</span>(resamp_df<span class="sc">$</span>pop_mean), se)),</span>
<span id="cb5-86"><a></a>  <span class="at">y =</span> <span class="dv">9</span>,</span>
<span id="cb5-87"><a></a>  <span class="at">yend =</span> <span class="dv">1</span></span>
<span id="cb5-88"><a></a>)</span>
<span id="cb5-89"><a></a></span>
<span id="cb5-90"><a></a>p_lower <span class="ot">&lt;-</span> plot_df <span class="sc">%&gt;%</span></span>
<span id="cb5-91"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x,y, <span class="at">group =</span>id))<span class="sc">+</span></span>
<span id="cb5-92"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend=</span>xend, <span class="at">yend=</span>yend),</span>
<span id="cb5-93"><a></a>               <span class="at">col =</span> <span class="st">"red"</span>,<span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.05</span>, <span class="st">"npc"</span>))</span>
<span id="cb5-94"><a></a>               )<span class="sc">+</span></span>
<span id="cb5-95"><a></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb5-96"><a></a>  <span class="fu">coord_fixed</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>),<span class="at">xlim =</span> <span class="fu">c</span>(ll,ul),<span class="at">clip=</span><span class="st">"off"</span>)</span>
<span id="cb5-97"><a></a></span>
<span id="cb5-98"><a></a>  </span>
<span id="cb5-99"><a></a>  design <span class="ot">&lt;-</span><span class="st">"##AAAA##</span></span>
<span id="cb5-100"><a></a><span class="st">            ##AAAA##</span></span>
<span id="cb5-101"><a></a><span class="st">            ##AAAA##</span></span>
<span id="cb5-102"><a></a><span class="st">            ##BBBB##</span></span>
<span id="cb5-103"><a></a><span class="st">            ##BBBB##</span></span>
<span id="cb5-104"><a></a><span class="st">            ##BBBB##            </span></span>
<span id="cb5-105"><a></a><span class="st">            CCCCCCCC</span></span>
<span id="cb5-106"><a></a><span class="st">            CCCCCCCC</span></span>
<span id="cb5-107"><a></a><span class="st">            #DDDDDD#</span></span>
<span id="cb5-108"><a></a><span class="st">            #DDDDDD#</span></span>
<span id="cb5-109"><a></a><span class="st">            #DDDDDD#</span></span>
<span id="cb5-110"><a></a><span class="st">            #DDDDDD#</span></span>
<span id="cb5-111"><a></a><span class="st">            EEEEEEEE</span></span>
<span id="cb5-112"><a></a><span class="st">            EEEEEEEE</span></span>
<span id="cb5-113"><a></a><span class="st">            ##FFFF##</span></span>
<span id="cb5-114"><a></a><span class="st">            ##FFFF##</span></span>
<span id="cb5-115"><a></a><span class="st">            ##FFFF##"</span></span>
<span id="cb5-116"><a></a>  </span>
<span id="cb5-117"><a></a>  fig <span class="ot">&lt;-</span> p_pop <span class="sc">/</span> p_samp <span class="sc">/</span>p_upper <span class="sc">/</span> p_samps <span class="sc">/</span> p_lower <span class="sc">/</span> p_dist <span class="sc">+</span></span>
<span id="cb5-118"><a></a>    <span class="fu">plot_layout</span>(<span class="at">design =</span> design)</span>
<span id="cb5-119"><a></a>  <span class="fu">return</span>(fig)</span>
<span id="cb5-120"><a></a></span>
<span id="cb5-121"><a></a></span>
<span id="cb5-122"><a></a>  </span>
<span id="cb5-123"><a></a>  </span>
<span id="cb5-124"><a></a>  </span>
<span id="cb5-125"><a></a>}</span>
<span id="cb5-126"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb5-127"><a></a>resamp_n10 <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(</span>
<span id="cb5-128"><a></a>  <span class="at">dat =</span> <span class="fu">sample_data_fn</span>(<span class="at">samps =</span> <span class="dv">1</span>, <span class="at">sample_size =</span> <span class="dv">10</span>, <span class="at">resample =</span> T)<span class="sc">$</span>sample <span class="sc">%&gt;%</span>  <span class="fu">as.data.frame</span>(),</span>
<span id="cb5-129"><a></a>  <span class="at">sample_size =</span> <span class="dv">10</span>, </span>
<span id="cb5-130"><a></a>  <span class="at">resample =</span> T)</span>
<span id="cb5-131"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb5-132"><a></a>fig_n10_bs <span class="ot">&lt;-</span> <span class="fu">plot_resampling_fn</span>(<span class="at">size=</span><span class="dv">10</span>)</span>
<span id="cb5-133"><a></a></span>
<span id="cb5-134"><a></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb5-135"><a></a>resamp_n30 <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(</span>
<span id="cb5-136"><a></a>  <span class="at">dat =</span> <span class="fu">sample_data_fn</span>(<span class="at">samps =</span> <span class="dv">1</span>, <span class="at">sample_size =</span> <span class="dv">30</span>, <span class="at">resample =</span> T)<span class="sc">$</span>sample <span class="sc">%&gt;%</span>  <span class="fu">as.data.frame</span>(),</span>
<span id="cb5-137"><a></a>  <span class="at">samps =</span> <span class="dv">1000</span>, <span class="at">sample_size =</span> <span class="dv">30</span>, <span class="at">resample =</span> T)</span>
<span id="cb5-138"><a></a></span>
<span id="cb5-139"><a></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb5-140"><a></a>fig_n30_bs <span class="ot">&lt;-</span> <span class="fu">plot_resampling_fn</span>(<span class="at">size=</span><span class="dv">30</span>)</span>
<span id="cb5-141"><a></a></span>
<span id="cb5-142"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb5-143"><a></a>resamp_n300 <span class="ot">&lt;-</span> <span class="fu">sample_data_fn</span>(</span>
<span id="cb5-144"><a></a>  <span class="at">dat =</span> <span class="fu">sample_data_fn</span>(<span class="at">samps =</span> <span class="dv">1</span>, <span class="at">sample_size =</span> <span class="dv">300</span>, <span class="at">resample =</span> T)<span class="sc">$</span>sample <span class="sc">%&gt;%</span>  <span class="fu">as.data.frame</span>(),</span>
<span id="cb5-145"><a></a>  <span class="at">samps =</span> <span class="dv">1000</span>, <span class="at">sample_size =</span> <span class="dv">300</span>, <span class="at">resample =</span> T)</span>
<span id="cb5-146"><a></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb5-147"><a></a>fig_n300_bs <span class="ot">&lt;-</span> <span class="fu">plot_resampling_fn</span>(<span class="at">size=</span><span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-3-3">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fign10bs-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fign30bs-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-5">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fign300bs-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-6">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Bootstrap SE</th>
<th style="text-align: right;">Analytic SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5.74</td>
<td style="text-align: right;">5.61</td>
</tr>
<tr class="even">
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">3.24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">1.02</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="confidence-intervals" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-lightbulb" aria-label="lightbulb"></i> Confidence intervals</h1>

</section>
<section id="confidence-intervals-1" class="slide level2">
<h2>Confidence intervals</h2>
<p>Confidence intervals:</p>
<ul>
<li class="fragment"><p>provide a way of <span class="blue">quantifying uncertainty</span> about <span class="blue">estimates</span></p></li>
<li class="fragment"><p>describe a <span class="blue">range of plausible values</span> for an estimate</p></li>
<li class="fragment"><p>are a function of the <span class="blue">standard error</span> of the estimate, and the a <span class="blue">critical value</span> determined by <span class="math inline">\(\alpha\)</span>, which describes the degree of confidence we want</p></li>
</ul>
</section>
<section id="section-1" class="slide level2 smaller">
<h2></h2>
<h4 class="smaller" id="calculating-a-confidence-interval">Calculating a confidence interval</h4>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Steps</a></li><li><a href="#tabset-4-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-4-3"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Fig 1</a></li><li><a href="#tabset-4-4"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Fig 2</a></li><li><a href="#tabset-4-5"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Fig 3</a></li><li><a href="#tabset-4-6">Comments</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<ul>
<li><p>Choose <span class="blue">level of confidence</span> <span class="math inline">\((1-\alpha)\times 100%\)</span></p>
<ul>
<li><span class="math inline">\(\alpha = 0.05\)</span>, corresponds to a 95% confidence level.</li>
</ul></li>
<li><p>Derive the <span class="blue">sampling distribution</span> of the estimator</p>
<ul>
<li><span class="blue">Simulation:</span> bootstrap re-sampling</li>
<li><span class="blue">Analytically:</span> computing its mean and variance.</li>
</ul></li>
<li><p>Compute the <span class="blue">standard error</span></p></li>
<li><p>Compute the <span class="blue">critical value</span> <span class="math inline">\(z_{\alpha/2}\)</span></p>
<ul>
<li>as the <span class="math inline">\(1.96 = \Phi(z_{0.5/2})\)</span> for a 95% CI</li>
</ul></li>
<li><p>Compute the <span class="blue">lower and upper</span> confidence limits</p>
<ul>
<li>lower limit = <span class="math inline">\(\hat{\theta} - z_{\alpha/2}\times SE\)</span></li>
<li>upper limit = <span class="math inline">\(\hat{\theta} + z_{\alpha/2}\times SE\)</span></li>
</ul></li>
</ul>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>resamp_df <span class="ot">&lt;-</span> </span>
<span id="cb6-2"><a></a>  resamp_n10 <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a></a>  <span class="fu">bind_rows</span>(resamp_n30) <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a></a>  <span class="fu">bind_rows</span>(resamp_n300) <span class="sc">%&gt;%</span> </span>
<span id="cb6-5"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-6"><a></a>    <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"N ="</span>,size))</span>
<span id="cb6-7"><a></a>    )</span>
<span id="cb6-8"><a></a></span>
<span id="cb6-9"><a></a>resamp_ci_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-10"><a></a>  <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"N ="</span>,<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">300</span>))),</span>
<span id="cb6-11"><a></a>  <span class="at">mu =</span> <span class="fu">unique</span>(resamp_df<span class="sc">$</span>pop_mean),</span>
<span id="cb6-12"><a></a>  <span class="at">ll =</span> <span class="fu">unique</span>(resamp_df<span class="sc">$</span>ll_asymp),</span>
<span id="cb6-13"><a></a>  <span class="at">ul =</span> <span class="fu">unique</span>(resamp_df<span class="sc">$</span>ul_asymp),</span>
<span id="cb6-14"><a></a>  <span class="at">y =</span> <span class="fu">c</span>(.<span class="dv">3</span>, .<span class="dv">3</span>,.<span class="dv">5</span>)</span>
<span id="cb6-15"><a></a>)</span>
<span id="cb6-16"><a></a></span>
<span id="cb6-17"><a></a>fig_ci1 <span class="ot">&lt;-</span> resamp_df <span class="sc">%&gt;%</span> </span>
<span id="cb6-18"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sample_mean,</span>
<span id="cb6-19"><a></a>             <span class="at">col =</span> <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb6-20"><a></a>  <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb6-21"><a></a>  <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb6-22"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_age, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb6-23"><a></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> resamp_ci_df,</span>
<span id="cb6-24"><a></a>             <span class="fu">aes</span>(<span class="at">xintercept =</span> mu,</span>
<span id="cb6-25"><a></a>                 <span class="at">col =</span> <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb6-26"><a></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> resamp_ci_df,</span>
<span id="cb6-27"><a></a>               <span class="fu">aes</span>(<span class="at">x =</span> ll, <span class="at">xend =</span>ul, <span class="at">y =</span> y, <span class="at">yend =</span>y,</span>
<span id="cb6-28"><a></a>                   <span class="at">col =</span> <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb6-29"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>, <span class="at">ncol=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb6-30"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb6-31"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb6-32"><a></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb6-33"><a></a>    <span class="at">x =</span> <span class="st">"Resampling Distribution"</span>,</span>
<span id="cb6-34"><a></a>    <span class="at">title =</span> <span class="st">"95% Confidence Intervals"</span></span>
<span id="cb6-35"><a></a>  )</span>
<span id="cb6-36"><a></a>  </span>
<span id="cb6-37"><a></a></span>
<span id="cb6-38"><a></a>samp_ci_df <span class="ot">&lt;-</span> samp_n10 <span class="sc">%&gt;%</span> </span>
<span id="cb6-39"><a></a>  <span class="fu">bind_rows</span>(samp_n30) <span class="sc">%&gt;%</span> </span>
<span id="cb6-40"><a></a>  <span class="fu">bind_rows</span>(samp_n300) <span class="sc">%&gt;%</span> </span>
<span id="cb6-41"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-42"><a></a>    <span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">"N ="</span>,size))</span>
<span id="cb6-43"><a></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb6-44"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-45"><a></a>    <span class="at">Coverage =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-46"><a></a>      pop_mean <span class="sc">&gt;</span> ll <span class="sc">&amp;</span> pop_mean <span class="sc">&lt;</span> ul <span class="sc">~</span> <span class="st">"red"</span>,</span>
<span id="cb6-47"><a></a>      T <span class="sc">~</span> <span class="st">"black"</span></span>
<span id="cb6-48"><a></a>    )</span>
<span id="cb6-49"><a></a>  )</span>
<span id="cb6-50"><a></a></span>
<span id="cb6-51"><a></a>fig_ci2 <span class="ot">&lt;-</span> samp_ci_df <span class="sc">%&gt;%</span> </span>
<span id="cb6-52"><a></a>  <span class="fu">filter</span>(sim <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-53"><a></a>  <span class="fu">filter</span>(size <span class="sc">==</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-54"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> sample_mean, <span class="at">x=</span> sim))<span class="sc">+</span></span>
<span id="cb6-55"><a></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> ll, <span class="at">ymax =</span>ul, <span class="at">col=</span>Coverage))<span class="sc">+</span></span>
<span id="cb6-56"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mu_age, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb6-57"><a></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb6-58"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb6-59"><a></a>  <span class="fu">guides</span>(<span class="at">col =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb6-60"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>)</span>
<span id="cb6-61"><a></a></span>
<span id="cb6-62"><a></a>fig_ci3 <span class="ot">&lt;-</span> samp_ci_df <span class="sc">%&gt;%</span> </span>
<span id="cb6-63"><a></a>  <span class="fu">filter</span>(sim <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-64"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> sample_mean, <span class="at">x=</span> sim))<span class="sc">+</span></span>
<span id="cb6-65"><a></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> ll, <span class="at">ymax =</span>ul, <span class="at">col=</span>Coverage))<span class="sc">+</span></span>
<span id="cb6-66"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mu_age, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb6-67"><a></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb6-68"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb6-69"><a></a>  <span class="fu">guides</span>(<span class="at">col =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb6-70"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">`</span><span class="at">Sample Size</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-4-3">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/figci1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/figci2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-5">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/figci3-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-6">
<ul>
<li><p>Figure 1 shows 3 confidences intervals for 3 samples of different sizes (N = 10, 30, 300). The CIs for N = 10 and N = 300, intervals contain the truth (include the population mean). By chance, the CI for N=30 falls outside of the truth.</p></li>
<li><p>Figure 2 shows that our confidence is about the property of the interval. Over repeated sampling, 95% of the intervals would contain the truth, 5% percent would not.</p>
<ul>
<li>In any one sample, the population parameter either is or is not within the interval.</li>
</ul></li>
<li><p>Figure 3, shows that while the width of the interval declines with the sample size, the coverage properties remains the same.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="interpreting-confidence-intervals" class="slide level2 smaller">
<h2>Interpreting confidence intervals</h2>
<ul>
<li class="fragment"><p>Confidence intervals give a range of values that are likely to include the true value of the parameter <span class="math inline">\(\theta\)</span> with probability <span class="math inline">\((1-\alpha) \times 100\%\)</span></p>
<ul>
<li class="fragment"><span class="math inline">\(\alpha = 0.05\)</span> corresponds to a “95-percent confidence interval”</li>
</ul></li>
<li class="fragment"><p>Our “confidence” is about the interval</p></li>
<li class="fragment"><p>In repeated sampling, we expect that <span class="math inline">\((1-\alpha) \times 100\%\)</span> of the intervals we construct would contain the truth.</p></li>
<li class="fragment"><p>For any one interval, the truth, <span class="math inline">\(\theta\)</span>, either falls within in the lower and upper bounds of the interval or it does not.</p></li>
</ul>
</section></section>
<section>
<section id="hypothesis-testing" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-lightbulb" aria-label="lightbulb"></i> Hypothesis testing</h1>

</section>
<section id="what-is-a-hypothesis-test" class="slide level2">
<h2>What is a hypothesis test</h2>
<ul>
<li class="fragment"><p>A formal way of assessing statistical evidence. Combines</p>
<ul>
<li class="fragment"><p><span class="blue"><strong>Deductive reasoning</strong></span> distribution of a test statistic, if the a null hypothesis were true</p></li>
<li class="fragment"><p><span class="blue"><strong>Inductive reasoning</strong></span> based on the test statistic we observed, how likely is it that we would observe it if the null were true?</p></li>
</ul></li>
</ul>
</section>
<section id="what-is-a-test-statistic" class="slide level2 smaller">
<h2>What is a test statistic?</h2>
<ul>
<li class="fragment">A way of summarizing data
<ul>
<li class="fragment">difference of means</li>
<li class="fragment">coefficients from a linear model</li>
<li class="fragment"><strong>coefficients from a linear model divided by their standard errors</strong></li>
<li class="fragment">R^2</li>
<li class="fragment"><a href="https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test" target="_blank">Sums of ranks</a></li>
</ul></li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Different test statistics may be more or less appropriate depending on your data and questions.</p>
</div>
</div>
</div>
</div>
</section>
<section id="what-is-a-null-hypothesis" class="slide level2">
<h2>What is a null hypothesis?</h2>
<ul>
<li class="fragment"><p>A statement about the world</p>
<ul>
<li class="fragment"><p>Only interesting <span class="blue">if we reject</span> it</p></li>
<li class="fragment"><p>Would yield a distribution of test statistics <span class="blue">under the null</span></p></li>
<li class="fragment"><p>Typically something like “X has no effect on Y” (Null = no effect)</p></li>
<li class="fragment"><p><span class="blue">Never accept the null</span> can only reject</p></li>
</ul></li>
</ul>
</section>
<section id="what-is-a-p-value" class="slide level2 smaller">
<h2>What is a p-value?</h2>
<p>A p-value is a <span class="blue">conditional probability</span> summarizing the likelihood of <span class="blue">observing a test statistic</span> as far from our hypothesis or farther, <span class="blue">if our hypothesis were true</span>.</p>

<img data-src="10-slides_files/figure-revealjs/pval-1.png" width="960" class="r-stretch"></section>
<section id="how-do-we-do-hypothesis-testing" class="slide level2 smaller scrollable">
<h2>How do we do hypothesis testing?</h2>
<ol type="1">
<li class="fragment"><p>Posit a <span class="blue">hypothesis</span> (e.g.&nbsp;<span class="math inline">\(\beta = 0\)</span>)</p></li>
<li class="fragment"><p>Calculate the <span class="blue">test statistic</span> (e.g.&nbsp;<span class="math inline">\((\hat{\beta}-\beta)/se_\beta\)</span>)</p></li>
<li class="fragment"><p>Derive the <span class="blue">distribution</span> of the test statistic <span class="blue">under the null</span> via simulation or asymptotic theory</p></li>
<li class="fragment"><p>Compare the test statistic to the distribution under the null</p></li>
<li class="fragment"><p>Calculate <span class="blue">p-value</span> (Two Sided vs One sided tests)</p></li>
<li class="fragment"><p>Reject or fail to reject/retain our hypothesis based on some <span class="blue">threshold of statistical significance</span> (e.g.&nbsp;p &lt; 0.05)</p></li>
</ol>
</section>
<section id="outcomes-of-hypothesis-tests" class="slide level2 smaller">
<h2>Outcomes of hypothesis tests</h2>
<ul>
<li><p>Two conclusions from of a hypothesis test: we can reject or fail to reject a hypothesis test.</p></li>
<li><p><strong>We never “accept” a hypothesis</strong>, since there are, in theory, an infinite number of other hypotheses we could have tested.</p></li>
</ul>
<p>Our decision can produce four outcomes and two types of error:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Reject <span class="math inline">\(H_0\)</span></th>
<th>Fail to Reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> is true</td>
<td>False Positive</td>
<td>Correct!</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_0\)</span> is false</td>
<td>Correct!</td>
<td>False Negative</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Type 1 Errors:</strong> False Positive Rate (p &lt; 0.05)</li>
<li><strong>Type 2 Errors:</strong> False negative rate (1 - Power of test)</li>
</ul>
</section></section>
<section>
<section id="quantifying-uncertainty-in-regression" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-code" aria-label="code"></i> Quantifying uncertainty in regression</h1>

</section>
<section id="quantifying-uncertainty-in-regression-1" class="slide level2 smaller">
<h2>Quantifying uncertainty in regression</h2>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Overview</a></li><li><a href="#tabset-5-2"><i class="fa-solid fa-table" aria-label="table"></i> Raw</a></li><li><a href="#tabset-5-3"><i class="fa-solid fa-table" aria-label="table"></i> SEs</a></li><li><a href="#tabset-5-4"><i class="fa-solid fa-table" aria-label="table"></i> CIs</a></li><li><a href="#tabset-5-5"><i class="fa-solid fa-code" aria-label="code"></i></a></li><li><a href="#tabset-5-6"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Coefficient plot</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p>How do income and education shape political participation?</p>
<p>Let’s fit the following model</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1\text{income} + \beta_2 \text{education} + \epsilon
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(dv_participation <span class="sc">~</span>   education <span class="sc">+</span> income, df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And unpack the output</p>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">tidy</span>(m1) <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a></a>  <span class="fu">mutate_if</span>(is.numeric, \(x) <span class="fu">round</span>(x, <span class="dv">3</span>)) <span class="ot">-&gt;</span> m1_sum</span>
<span id="cb8-3"><a></a>m1_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         term estimate std.error statistic p.value conf.low conf.high   df
1 (Intercept)    0.312     0.080     3.910   0.000    0.155     0.468 1684
2   education    0.167     0.024     6.891   0.000    0.119     0.214 1684
3      income    0.007     0.010     0.671   0.502   -0.014     0.028 1684
           outcome
1 dv_participation
2 dv_participation
3 dv_participation</code></pre>
</div>
</div>
</div>
<div id="tabset-5-3">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">htmlreg</span>(m1,<span class="at">include.ci=</span>F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.31<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.08)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
education
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.17<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.01
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.01)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1687
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
RMSE
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1.29
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
<div id="tabset-5-4">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">htmlreg</span>(m1,<span class="at">include.ci=</span>T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.31<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[ 0.16; 0.47]
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
education
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.17<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[ 0.12; 0.21]
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.01
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
[-0.01; 0.03]
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1687
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
RMSE
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1.29
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>*</sup> 0 outside the confidence interval.
</td>
</tr>
</tfoot>
</table>
</div>
<div id="tabset-5-5">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>m1_coefplot <span class="ot">&lt;-</span> m1_sum <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(term, estimate))<span class="sc">+</span></span>
<span id="cb12-3"><a></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span>conf.high))<span class="sc">+</span></span>
<span id="cb12-4"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb12-5"><a></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb12-6"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb12-7"><a></a>    <span class="at">y =</span> <span class="st">"Estimate"</span>,</span>
<span id="cb12-8"><a></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb12-9"><a></a>    <span class="at">title =</span> <span class="st">"Coefficient plot"</span></span>
<span id="cb12-10"><a></a>  )<span class="sc">+</span></span>
<span id="cb12-11"><a></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-5-6">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/m1_coefplot_fig-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="estimates" class="slide level2 smaller">
<h2>Estimates</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Estimate</a></li><li><a href="#tabset-6-2"><i class="fa-solid fa-code" aria-label="code"></i></a></li><li><a href="#tabset-6-3">Comments</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>The estimate column are the regression coefficients, <span class="math inline">\(\beta\)</span></p>
<p>Recall, lm_robust() calculates these:</p>
<p><span class="math display">\[
\hat{\beta} = (X'X)^{-1}X'y
\]</span></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\beta\)</span>s describe substantive relationships between predictors (income, education) and the outcome (political participation)</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">coef</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   education      income 
0.311609712 0.166755964 0.007034253 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m1,<span class="at">data=</span>df)</span>
<span id="cb15-2"><a></a>y <span class="ot">&lt;-</span> <span class="fu">model.frame</span>(m1)<span class="sc">$</span>dv_participation</span>
<span id="cb15-3"><a></a>betas <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X)<span class="sc">%*%</span>X)<span class="sc">%*%</span><span class="fu">t</span>(X)<span class="sc">%*%</span>y</span>
<span id="cb15-4"><a></a>betas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   [,1]
(Intercept) 0.311609712
education   0.166755964
income      0.007034253</code></pre>
</div>
</div>
</div>
<div id="tabset-6-3">
<p>A unit increases in education is associated with about 0.16 more acts of political participation, while a unit increase in income is associated with 0.007 more acts of participation.</p>
<p>Note that both <code>income</code> and <code>education</code> are measured with ordinal scales</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">get_value_labels</span>(df<span class="sc">$</span>educ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    No HS credential High school graduate         Some college 
                   1                    2                    3 
       2-year degree        4-year degree            Post-grad 
                   4                    5                    6 </code></pre>
</div>
</div>
<p>Such that it might be unreasonable to assume <span class="blue">cardinality</span> (going from a 1 to 2 is the same as going from a 3 to 4)</p>
<ul>
<li class="fragment">Consider treating as factor / recoding variable</li>
</ul>
</div>
</div>
</div>
</section>
<section id="section-4" class="slide level2 smaller">
<h2></h2>
<h4 id="standard-errors-confidence-intervals">Standard errors &amp; confidence intervals</h4>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">SEs and CI</a></li><li><a href="#tabset-7-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-7-3"><i class="fa-solid fa-table" aria-label="table"></i> SEs</a></li><li><a href="#tabset-7-4"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> SEs</a></li><li><a href="#tabset-7-5">Comments</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>The default standard errors from <code>lm_robust()</code> are <a href="https://declaredesign.org/r/estimatr/articles/mathematical-notes.html" target="_blank">calculated</a> as follows</p>
<p><span class="math display">\[
SE_{\beta} = (X'X)^{-1}X'\text{diag}\left[\frac{e_i^2}{1-h_{ii}}\right]X(X'X)^{-1}
\]</span></p>
<p>Which we could also obtain via bootstrapping.</p>
<p>The confidence intervals are calculated as follows:</p>
<p><span class="math display">\[
CI = \beta \pm 1.96\times SE_\beta
\]</span></p>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="co"># 0 Set seed</span></span>
<span id="cb19-2"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb19-3"><a></a></span>
<span id="cb19-4"><a></a><span class="co"># 1,000 bootstrap samples</span></span>
<span id="cb19-5"><a></a>boot <span class="ot">&lt;-</span> modelr<span class="sc">::</span><span class="fu">bootstrap</span>(df <span class="sc">%&gt;%</span> <span class="fu">select</span>(dv_participation, income, education), <span class="dv">1000</span>)</span>
<span id="cb19-6"><a></a><span class="co"># Estimate Boostrapped Models</span></span>
<span id="cb19-7"><a></a>m1_bs <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(boot<span class="sc">$</span>strap, <span class="sc">~</span> <span class="fu">lm_robust</span>(dv_participation <span class="sc">~</span>  income <span class="sc">+</span> education, <span class="at">data =</span> .))</span>
<span id="cb19-8"><a></a></span>
<span id="cb19-9"><a></a><span class="co"># Tidy coefficients</span></span>
<span id="cb19-10"><a></a>m1_bs_df <span class="ot">&lt;-</span> <span class="fu">map_df</span>(m1_bs, tidy, <span class="at">.id =</span> <span class="st">"id"</span>)</span>
<span id="cb19-11"><a></a>m1_asymp_df <span class="ot">&lt;-</span> <span class="fu">tidy</span>(m1) <span class="sc">%&gt;%</span> </span>
<span id="cb19-12"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-13"><a></a>    <span class="at">term =</span> <span class="fu">factor</span>(term)</span>
<span id="cb19-14"><a></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb19-15"><a></a>  <span class="fu">select</span>(term,estimate, std.error,conf.low, conf.high) <span class="sc">%&gt;%</span> </span>
<span id="cb19-16"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-17"><a></a>    <span class="at">ll =</span> conf.low,</span>
<span id="cb19-18"><a></a>    <span class="at">ul =</span> conf.high,</span>
<span id="cb19-19"><a></a>    <span class="at">y =</span> <span class="fl">1.1</span>,</span>
<span id="cb19-20"><a></a>    <span class="at">type =</span> <span class="st">"Analytic"</span></span>
<span id="cb19-21"><a></a>  )</span>
<span id="cb19-22"><a></a></span>
<span id="cb19-23"><a></a>m1_bs_ci_df <span class="ot">&lt;-</span> m1_bs_df <span class="sc">%&gt;%</span></span>
<span id="cb19-24"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-25"><a></a>    <span class="at">term =</span> <span class="fu">factor</span>(term)</span>
<span id="cb19-26"><a></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb19-27"><a></a>  <span class="fu">group_by</span>(term) <span class="sc">%&gt;%</span> </span>
<span id="cb19-28"><a></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-29"><a></a>  <span class="at">beta =</span> <span class="fu">mean</span>(estimate,<span class="at">na.rm=</span>T),</span>
<span id="cb19-30"><a></a>  <span class="at">se =</span> <span class="fu">sd</span>(estimate,<span class="at">na.rm=</span>T)</span>
<span id="cb19-31"><a></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb19-32"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-33"><a></a>  <span class="at">ll =</span> beta <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>se,</span>
<span id="cb19-34"><a></a>  <span class="at">ul =</span> beta <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>se,</span>
<span id="cb19-35"><a></a>  <span class="at">y =</span> <span class="fl">1.05</span>,</span>
<span id="cb19-36"><a></a>  <span class="at">type =</span> <span class="st">"Bootstrap"</span></span>
<span id="cb19-37"><a></a>) </span>
<span id="cb19-38"><a></a></span>
<span id="cb19-39"><a></a><span class="co"># Compare SEs</span></span>
<span id="cb19-40"><a></a></span>
<span id="cb19-41"><a></a>compare_m1_se_tab <span class="ot">&lt;-</span></span>
<span id="cb19-42"><a></a>  <span class="fu">tibble</span>(</span>
<span id="cb19-43"><a></a>    <span class="st">`</span><span class="at">Predictor</span><span class="st">`</span> <span class="ot">=</span> m1_bs_ci_df<span class="sc">$</span>term,</span>
<span id="cb19-44"><a></a>    <span class="at">Estimate =</span> m1_asymp_df<span class="sc">$</span>estimate,</span>
<span id="cb19-45"><a></a>    <span class="st">`</span><span class="at">SE</span><span class="st">`</span> <span class="ot">=</span> m1_asymp_df<span class="sc">$</span>std.error,</span>
<span id="cb19-46"><a></a>     <span class="st">`</span><span class="at">CI</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"["</span>, <span class="fu">round</span>(m1_asymp_df<span class="sc">$</span>ll,<span class="dv">2</span>),</span>
<span id="cb19-47"><a></a>                  <span class="st">"; "</span>, <span class="fu">round</span>(m1_asymp_df<span class="sc">$</span>ul,<span class="dv">2</span>),<span class="st">"]"</span>,</span>
<span id="cb19-48"><a></a>                  <span class="at">sep =</span><span class="st">""</span>),</span>
<span id="cb19-49"><a></a>    <span class="st">`</span><span class="at">SE </span><span class="st">`</span> <span class="ot">=</span> m1_bs_ci_df<span class="sc">$</span>se,</span>
<span id="cb19-50"><a></a>    <span class="st">`</span><span class="at">CI </span><span class="st">`</span> <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"["</span>, <span class="fu">round</span>(m1_bs_ci_df<span class="sc">$</span>ll,<span class="dv">2</span>),</span>
<span id="cb19-51"><a></a>                  <span class="st">"; "</span>, <span class="fu">round</span>(m1_bs_ci_df<span class="sc">$</span>ul,<span class="dv">2</span>),<span class="st">"]"</span>,</span>
<span id="cb19-52"><a></a>                  <span class="at">sep =</span><span class="st">""</span>),</span>
<span id="cb19-53"><a></a>  )</span>
<span id="cb19-54"><a></a></span>
<span id="cb19-55"><a></a></span>
<span id="cb19-56"><a></a><span class="co"># Figure</span></span>
<span id="cb19-57"><a></a>fig_m1_bs <span class="ot">&lt;-</span> m1_bs_df <span class="sc">%&gt;%</span> </span>
<span id="cb19-58"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(estimate))<span class="sc">+</span></span>
<span id="cb19-59"><a></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y=</span><span class="fu">after_stat</span>(ndensity)))<span class="sc">+</span></span>
<span id="cb19-60"><a></a>  <span class="fu">geom_rug</span>()<span class="sc">+</span></span>
<span id="cb19-61"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb19-62"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>term,<span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb19-63"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb19-64"><a></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">1.2</span>)<span class="sc">+</span></span>
<span id="cb19-65"><a></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb19-66"><a></a>    <span class="at">data =</span> m1_asymp_df,</span>
<span id="cb19-67"><a></a>    <span class="fu">aes</span>(<span class="at">xintercept =</span> estimate)</span>
<span id="cb19-68"><a></a>  ) <span class="sc">+</span></span>
<span id="cb19-69"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb19-70"><a></a>    <span class="at">data =</span> m1_bs_ci_df,</span>
<span id="cb19-71"><a></a>    <span class="fu">aes</span>(<span class="at">x =</span> ll, <span class="at">xend =</span> ul,</span>
<span id="cb19-72"><a></a>        <span class="at">y =</span> y, <span class="at">yend =</span> y,</span>
<span id="cb19-73"><a></a>        <span class="at">col =</span> <span class="st">"Bootstrap"</span>)</span>
<span id="cb19-74"><a></a>    </span>
<span id="cb19-75"><a></a>  ) <span class="sc">+</span></span>
<span id="cb19-76"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb19-77"><a></a>    <span class="at">data =</span> m1_asymp_df,</span>
<span id="cb19-78"><a></a>    <span class="fu">aes</span>(<span class="at">x =</span> ll, <span class="at">xend =</span> ul,</span>
<span id="cb19-79"><a></a>        <span class="at">y =</span> y, <span class="at">yend =</span> y,</span>
<span id="cb19-80"><a></a>        <span class="at">col =</span> <span class="st">"Analytic"</span>)</span>
<span id="cb19-81"><a></a>    </span>
<span id="cb19-82"><a></a>  ) <span class="sc">+</span></span>
<span id="cb19-83"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb19-84"><a></a>    <span class="at">col =</span> <span class="st">"Confidence Interval"</span>,</span>
<span id="cb19-85"><a></a>    <span class="at">x =</span> <span class="st">"Bootstrapped Sampling Distribution</span><span class="sc">\n</span><span class="st"> of Coefficients"</span></span>
<span id="cb19-86"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-7-3">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Analytic
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Bootstrap
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">CI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.3116</td>
<td style="text-align: center;">0.0797</td>
<td style="text-align: center;">[0.16; 0.47]</td>
<td style="text-align: center;">0.0805</td>
<td style="text-align: left;">[0.15; 0.47]</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: center;">0.1668</td>
<td style="text-align: center;">0.0242</td>
<td style="text-align: center;">[0.12; 0.21]</td>
<td style="text-align: center;">0.0248</td>
<td style="text-align: left;">[0.12; 0.22]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: center;">0.0070</td>
<td style="text-align: center;">0.0105</td>
<td style="text-align: center;">[-0.01; 0.03]</td>
<td style="text-align: center;">0.0107</td>
<td style="text-align: left;">[-0.01; 0.03]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="tabset-7-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/figm1bs-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-7-5">
<ul>
<li class="fragment"><p>The main takeaway here is that for linear models, bootstrapped SEs and CIs are quite similar to those obtained via analytically (via math and asymptotic theory)</p></li>
<li class="fragment"><p>For common estimators and large samples, we’ll generally use analytic SEs (quicker)</p></li>
<li class="fragment"><p>For less common estimators (ratios of estimates), analytic estimates of the SEs may not exist. Bootstrapping will still provide valid SEs, provided we “sample from the sample, as the sample was drawn from the population”</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="test-statistics-and-p-values" class="slide level2 smaller">
<h2>Test statistics and p-values</h2>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Overview</a></li><li><a href="#tabset-8-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-8-3"><i class="fa-solid fa-table" aria-label="table"></i></a></li><li><a href="#tabset-8-4"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i></a></li><li><a href="#tabset-8-5">Comments</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>The test statistic (“t-stat”) reported by <code>lm()</code> and <code>lm_robust()</code> is our observed coefficient, <span class="math inline">\(\hat{\beta}\)</span> minus our hypothesized value <span class="math inline">\(\beta\)</span> (e.g.&nbsp;0), divided by the standard error of <span class="math inline">\(\hat{\beta}\)</span>.</p>
<p><span class="math display">\[t= \frac{\hat\beta-\beta}{\widehat{SE}_{\hat{\beta}}} \sim \text{Students's } t \text{ with } n-k \text{ degrees of freedom}\]</span> Which follows a <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution" target="_blank"><span class="math inline">\(t\)</span> distribution</a> – like a Normal with “heavier tails” (e.g.&nbsp;more probability assigned to extreme values)</p>
</div>
<div id="tabset-8-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="co"># Calculate t-stats</span></span>
<span id="cb20-2"><a></a></span>
<span id="cb20-3"><a></a>t_stat_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb20-4"><a></a>  <span class="at">x=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>,<span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb20-5"><a></a>  <span class="at">p =</span> <span class="fu">dt</span>(x,<span class="at">df=</span>m1<span class="sc">$</span>df[<span class="dv">1</span>] )</span>
<span id="cb20-6"><a></a>)</span>
<span id="cb20-7"><a></a></span>
<span id="cb20-8"><a></a></span>
<span id="cb20-9"><a></a>m1_tstat_educ <span class="ot">&lt;-</span> t_stat_df <span class="sc">%&gt;%</span> </span>
<span id="cb20-10"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>p))<span class="sc">+</span></span>
<span id="cb20-11"><a></a>  <span class="fu">stat_function</span>(</span>
<span id="cb20-12"><a></a>    <span class="at">fun=</span> dt, </span>
<span id="cb20-13"><a></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df[<span class="dv">1</span>]),</span>
<span id="cb20-14"><a></a>    <span class="at">geom =</span> <span class="st">"line"</span>,</span>
<span id="cb20-15"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(</span>
<span id="cb20-16"><a></a>      <span class="fu">min</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="fu">abs</span>(m1<span class="sc">$</span>statistic[<span class="dv">2</span>])<span class="sc">*-</span><span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span>)),</span>
<span id="cb20-17"><a></a>      <span class="fu">max</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="fu">abs</span>(m1<span class="sc">$</span>statistic[<span class="dv">2</span>])<span class="sc">+</span><span class="dv">1</span>))</span>
<span id="cb20-18"><a></a>      )</span>
<span id="cb20-19"><a></a>  )<span class="sc">+</span></span>
<span id="cb20-20"><a></a>  <span class="fu">stat_function</span>(</span>
<span id="cb20-21"><a></a>    <span class="at">fun=</span> dt, </span>
<span id="cb20-22"><a></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df[<span class="dv">1</span>]),</span>
<span id="cb20-23"><a></a>    <span class="at">geom =</span> <span class="st">"area"</span>,</span>
<span id="cb20-24"><a></a>    <span class="at">fill =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-25"><a></a>    <span class="at">alpha =</span> .<span class="dv">5</span>,</span>
<span id="cb20-26"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(m1<span class="sc">$</span>statistic[<span class="dv">2</span>],<span class="dv">4</span>)</span>
<span id="cb20-27"><a></a>  )<span class="sc">+</span></span>
<span id="cb20-28"><a></a>  <span class="fu">stat_function</span>(</span>
<span id="cb20-29"><a></a>    <span class="at">fun=</span> dt, </span>
<span id="cb20-30"><a></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df[<span class="dv">1</span>]),</span>
<span id="cb20-31"><a></a>    <span class="at">geom =</span> <span class="st">"area"</span>,</span>
<span id="cb20-32"><a></a>    <span class="at">fill =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-33"><a></a>    <span class="at">alpha =</span> .<span class="dv">5</span>,</span>
<span id="cb20-34"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="fu">abs</span>(m1<span class="sc">$</span>statistic[<span class="dv">2</span>])<span class="sc">*-</span><span class="dv">1</span>)</span>
<span id="cb20-35"><a></a>  )<span class="sc">+</span></span>
<span id="cb20-36"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> m1<span class="sc">$</span>statistic[<span class="dv">2</span>],</span>
<span id="cb20-37"><a></a>             <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-38"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb20-39"><a></a>   <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> m1<span class="sc">$</span>statistic[<span class="dv">2</span>]<span class="sc">*-</span><span class="dv">1</span>,</span>
<span id="cb20-40"><a></a>             <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-41"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb20-42"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb20-43"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb20-44"><a></a>    <span class="at">title =</span> <span class="st">"Education"</span>,</span>
<span id="cb20-45"><a></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"t-stat = "</span>,<span class="fu">round</span>(m1<span class="sc">$</span>statistic[<span class="dv">2</span>],<span class="dv">3</span>),</span>
<span id="cb20-46"><a></a>    <span class="st">"</span><span class="sc">\n</span><span class="st">Pr(&gt;|t|) = "</span>,</span>
<span id="cb20-47"><a></a>    <span class="fu">format</span>(<span class="fu">round</span>(m1<span class="sc">$</span>p.value[<span class="dv">2</span>],<span class="dv">3</span>),<span class="at">nsmall =</span> <span class="dv">3</span>),</span>
<span id="cb20-48"><a></a>    <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb20-49"><a></a>    ),</span>
<span id="cb20-50"><a></a>    <span class="at">x =</span> <span class="st">"Distribution of t-stat under the Null"</span></span>
<span id="cb20-51"><a></a>  )</span>
<span id="cb20-52"><a></a></span>
<span id="cb20-53"><a></a>m1_tstat_income <span class="ot">&lt;-</span> t_stat_df <span class="sc">%&gt;%</span> </span>
<span id="cb20-54"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>p))<span class="sc">+</span></span>
<span id="cb20-55"><a></a>  <span class="fu">stat_function</span>(</span>
<span id="cb20-56"><a></a>    <span class="at">fun=</span> dt, </span>
<span id="cb20-57"><a></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df[<span class="dv">1</span>]),</span>
<span id="cb20-58"><a></a>    <span class="at">geom =</span> <span class="st">"line"</span>,</span>
<span id="cb20-59"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(</span>
<span id="cb20-60"><a></a>      <span class="fu">min</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="fu">abs</span>(m1<span class="sc">$</span>statistic[<span class="dv">3</span>])<span class="sc">*-</span><span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span>)),</span>
<span id="cb20-61"><a></a>      <span class="fu">max</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="fu">abs</span>(m1<span class="sc">$</span>statistic[<span class="dv">3</span>])<span class="sc">+</span><span class="dv">1</span>))</span>
<span id="cb20-62"><a></a>      )</span>
<span id="cb20-63"><a></a>  )<span class="sc">+</span></span>
<span id="cb20-64"><a></a>  <span class="fu">stat_function</span>(</span>
<span id="cb20-65"><a></a>    <span class="at">fun=</span> dt, </span>
<span id="cb20-66"><a></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df[<span class="dv">1</span>]),</span>
<span id="cb20-67"><a></a>    <span class="at">geom =</span> <span class="st">"area"</span>,</span>
<span id="cb20-68"><a></a>    <span class="at">fill =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-69"><a></a>    <span class="at">alpha =</span> .<span class="dv">5</span>,</span>
<span id="cb20-70"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(m1<span class="sc">$</span>statistic[<span class="dv">3</span>],<span class="dv">4</span>)</span>
<span id="cb20-71"><a></a>  )<span class="sc">+</span></span>
<span id="cb20-72"><a></a>  <span class="fu">stat_function</span>(</span>
<span id="cb20-73"><a></a>    <span class="at">fun=</span> dt, </span>
<span id="cb20-74"><a></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> m1<span class="sc">$</span>df[<span class="dv">1</span>]),</span>
<span id="cb20-75"><a></a>    <span class="at">geom =</span> <span class="st">"area"</span>,</span>
<span id="cb20-76"><a></a>    <span class="at">fill =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-77"><a></a>    <span class="at">alpha =</span> .<span class="dv">5</span>,</span>
<span id="cb20-78"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="fu">abs</span>(m1<span class="sc">$</span>statistic[<span class="dv">3</span>])<span class="sc">*-</span><span class="dv">1</span>)</span>
<span id="cb20-79"><a></a>  )<span class="sc">+</span></span>
<span id="cb20-80"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> m1<span class="sc">$</span>statistic[<span class="dv">3</span>],</span>
<span id="cb20-81"><a></a>             <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-82"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb20-83"><a></a>   <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> m1<span class="sc">$</span>statistic[<span class="dv">3</span>]<span class="sc">*-</span><span class="dv">1</span>,</span>
<span id="cb20-84"><a></a>             <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb20-85"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb20-86"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb20-87"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb20-88"><a></a>    <span class="at">title =</span> <span class="st">"Income"</span>,</span>
<span id="cb20-89"><a></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"t-stat = "</span>,<span class="fu">round</span>(m1<span class="sc">$</span>statistic[<span class="dv">3</span>],<span class="dv">3</span>),</span>
<span id="cb20-90"><a></a>    <span class="st">"</span><span class="sc">\n</span><span class="st">Pr(&gt;|t|) = "</span>,</span>
<span id="cb20-91"><a></a>    <span class="fu">format</span>(<span class="fu">round</span>(m1<span class="sc">$</span>p.value[<span class="dv">3</span>],<span class="dv">3</span>),<span class="at">nsmall =</span> <span class="dv">3</span>),</span>
<span id="cb20-92"><a></a>    <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb20-93"><a></a>    ),</span>
<span id="cb20-94"><a></a>    <span class="at">x =</span> <span class="st">"Distribution of t-stat under the Null"</span></span>
<span id="cb20-95"><a></a>  )</span>
<span id="cb20-96"><a></a></span>
<span id="cb20-97"><a></a>fig_pvalue <span class="ot">&lt;-</span> m1_tstat_educ <span class="sc">+</span> m1_tstat_income</span>
<span id="cb20-98"><a></a></span>
<span id="cb20-99"><a></a><span class="co"># Compare Pvalues</span></span>
<span id="cb20-100"><a></a></span>
<span id="cb20-101"><a></a>compare_m1_pvalue <span class="ot">&lt;-</span></span>
<span id="cb20-102"><a></a>  <span class="fu">tibble</span>(</span>
<span id="cb20-103"><a></a>    <span class="st">`</span><span class="at">Predictor</span><span class="st">`</span> <span class="ot">=</span> m1_bs_ci_df<span class="sc">$</span>term,</span>
<span id="cb20-104"><a></a>    <span class="at">Estimate =</span> m1_asymp_df<span class="sc">$</span>estimate,</span>
<span id="cb20-105"><a></a>    <span class="at">SE =</span> m1_sum<span class="sc">$</span>std.error,</span>
<span id="cb20-106"><a></a>    <span class="st">`</span><span class="at">t-stat</span><span class="st">`</span> <span class="ot">=</span> m1_sum<span class="sc">$</span>statistic,</span>
<span id="cb20-107"><a></a>     <span class="st">`</span><span class="at">Pr(&gt;abs(t))</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">format</span>(<span class="fu">round</span>(m1_sum<span class="sc">$</span>p.value,<span class="dv">3</span>), <span class="at">nsmall=</span><span class="dv">3</span>)</span>
<span id="cb20-108"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-8-3">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t-stat</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pr(&gt;abs(t))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.312</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: right;">3.910</td>
<td style="text-align: left;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">6.891</td>
<td style="text-align: left;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.671</td>
<td style="text-align: left;">0.502</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="tabset-8-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fig_pvalue-1.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
</div>
<div id="tabset-8-5">
<ul>
<li><p>The p-value for the coefficient on education is less than 0.05, while the p-value for income is 0.50.</p></li>
<li><p>If there was no relationship between education and participation (<span class="math inline">\(H_0:\beta_2=0\)</span>), it would be quite unlikely that we would observed a test statistic of 6.89 or larger.</p></li>
<li><p>Similarly, test statistics as larger or larger than 0.671 occurs quite frequently in a world where there is no relationship (<span class="math inline">\(H_0:\beta_3=0\)</span>) between income and participation.</p></li>
<li><p>Thus we reject the null hypothesis for education, but fail to reject the null hypothesis for income in this model.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="predicted-values" class="slide level2 smaller">
<h2>Predicted values</h2>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Overview</a></li><li><a href="#tabset-9-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-9-3"><i class="fa-solid fa-table" aria-label="table"></i> Table</a></li><li><a href="#tabset-9-4"><i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Fig</a></li><li><a href="#tabset-9-5">Comments</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p>Let’s explore whether income and education condition each other’s relationship with participation using the following <span class="blue">interaction model</span></p>
<p><span class="math display">\[
y = \beta_0 +\beta_1 \text{educ} + \beta_2 \text{inc} + \beta_3\text{educ}\times\text{inc} + \epsilon
\]</span></p>
<p>To help our interpretations we’ll produce plots of <span class="blue">predicted values</span> of participation, at varying levels of income and education.</p>
</div>
<div id="tabset-9-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="co"># Fit model</span></span>
<span id="cb22-2"><a></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(dv_participation <span class="sc">~</span> education<span class="sc">*</span>income, df)</span>
<span id="cb22-3"><a></a></span>
<span id="cb22-4"><a></a></span>
<span id="cb22-5"><a></a><span class="co"># Regression Table</span></span>
<span id="cb22-6"><a></a>m2_tab <span class="ot">&lt;-</span> <span class="fu">htmlreg</span>(</span>
<span id="cb22-7"><a></a>  m2, </span>
<span id="cb22-8"><a></a>  <span class="at">include.ci =</span> F,</span>
<span id="cb22-9"><a></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb22-10"><a></a>  <span class="at">stars =</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.10</span>)</span>
<span id="cb22-11"><a></a>                    )</span>
<span id="cb22-12"><a></a></span>
<span id="cb22-13"><a></a><span class="co"># Predicted values</span></span>
<span id="cb22-14"><a></a></span>
<span id="cb22-15"><a></a><span class="co"># Data frame of values we want to make predictions at</span></span>
<span id="cb22-16"><a></a>pred_df <span class="ot">&lt;-</span><span class="fu">expand_grid</span>(</span>
<span id="cb22-17"><a></a>  <span class="at">income =</span> <span class="fu">sort</span>(<span class="fu">unique</span>(df<span class="sc">$</span>income)),</span>
<span id="cb22-18"><a></a>  <span class="at">education =</span> <span class="fu">quantile</span>(df<span class="sc">$</span>education, <span class="at">na.rm =</span> T)[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)]</span>
<span id="cb22-19"><a></a>)</span>
<span id="cb22-20"><a></a></span>
<span id="cb22-21"><a></a><span class="co"># Combine model predictions</span></span>
<span id="cb22-22"><a></a>pred_df <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_df, <span class="fu">predict</span>(m2, pred_df,</span>
<span id="cb22-23"><a></a>                                  <span class="at">interval =</span> <span class="st">"confidence"</span>)<span class="sc">$</span>fit)</span>
<span id="cb22-24"><a></a></span>
<span id="cb22-25"><a></a><span class="co"># Plot predicted values</span></span>
<span id="cb22-26"><a></a>fig_m2_pred <span class="ot">&lt;-</span> pred_df <span class="sc">%&gt;%</span> </span>
<span id="cb22-27"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-28"><a></a>    <span class="at">Education =</span> <span class="fu">ifelse</span>(education <span class="sc">==</span> <span class="dv">2</span>, <span class="st">"High school"</span>,<span class="st">"College"</span>)</span>
<span id="cb22-29"><a></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb22-30"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(income, fit, <span class="at">group=</span>Education))<span class="sc">+</span></span>
<span id="cb22-31"><a></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr,</span>
<span id="cb22-32"><a></a>                  <span class="at">fill =</span> Education),</span>
<span id="cb22-33"><a></a>              <span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb22-34"><a></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb22-35"><a></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb22-36"><a></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Predicted Participation"</span>,</span>
<span id="cb22-37"><a></a>       <span class="at">x =</span> <span class="st">"Income"</span>,</span>
<span id="cb22-38"><a></a>       <span class="at">title =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-9-3">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.060
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.151)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
education
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.242<sup>**</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.050)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.048<sup>**</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.024)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
education:income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.011<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.006)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.040
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1687
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
RMSE
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1.286
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>**</sup>p &lt; 0.05; <sup>*</sup>p &lt; 0.1
</td>
</tr>
</tfoot>
</table>
</div>
<div id="tabset-9-4">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="10-slides_files/figure-revealjs/fig_m2_pred-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-9-5">
<p>Low income individuals with a college degree participate at significantly higher rates than individuals with a similar levels of income with only a high school diploma.</p>
<p>Alternatively, we might say that the college educated tend to participate at similar levels, regardless of their level of income, while income has a marginally positive relationship with participation for those without college degrees.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Is this a causal relationship? What assumptions would we need to make a causal claim about the effects of education on participation?</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="references" class="slide level2">
<h2>References</h2>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/pols1600_hex.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>POLS 1600</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>