<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>POLS 1600</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-8979bb8451ddc1038f930ac611262c50.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" align="left" data-background-image="images/pols1600_hex.png" data-background-position="90% 50%" data-background-size="40%" class="quarto-title-block center">
  <h1 class="title">POLS 1600</h1>
  <p class="subtitle">Review and Presentation Prep</p>

<div class="quarto-title-authors">
</div>

  <p class="date">Updated Apr 20, 2026</p>
</section>
<section>
<section id="overview" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-map-location" aria-label="map-location"></i> Overview</h1>

</section>
<section id="class-plan" class="slide level2">
<h2>Class Plan</h2>
<ul>
<li class="fragment">Announcements</li>
<li class="fragment">Presentations</li>
<li class="fragment">Workshop / Review
<ul>
<li class="fragment">Predicted values from linear models</li>
</ul></li>
</ul>
</section>
<section id="annoucements" class="slide level2">
<h2>Annoucements</h2>
<ul>
<li class="fragment">No lab this week; class canceled Friday</li>
<li class="fragment">Wednesday April 22, Work on Presentations/Drafts in class</li>
<li class="fragment">April 27- May 1 Presentations - 10-12 minutes each; will keep Friday as backup if not finished.</li>
</ul>
</section>
<section id="setup-packages-for-today" class="slide level2">
<h2>Setup: Packages for today</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="do">## Pacakges for today</span></span>
<span id="cb1-2"><a></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-3"><a></a>  <span class="do">## R Markdown</span></span>
<span id="cb1-4"><a></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,<span class="st">"htmltools"</span>,</span>
<span id="cb1-5"><a></a>  <span class="do">## Tidyverse</span></span>
<span id="cb1-6"><a></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,</span>
<span id="cb1-7"><a></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb1-8"><a></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb1-9"><a></a>  <span class="st">"patchwork"</span>,<span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb1-10"><a></a>  <span class="co"># Data </span></span>
<span id="cb1-11"><a></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>, </span>
<span id="cb1-12"><a></a>  <span class="co"># Analysis</span></span>
<span id="cb1-13"><a></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"easystats"</span>, <span class="st">"zoo"</span></span>
<span id="cb1-14"><a></a>)</span>
<span id="cb1-15"><a></a></span>
<span id="cb1-16"><a></a><span class="do">## Define a function to load (and if needed install) packages</span></span>
<span id="cb1-17"><a></a></span>
<span id="cb1-18"><a></a><span class="fu">lapply</span>(the_packages, library, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1] "kableExtra"    "texreg"        "see"           "report"       
 [5] "parameters"    "performance"   "modelbased"    "insight"      
 [9] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[13] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[17] "randomizr"     "haven"         "labelled"      "lubridate"    
[21] "forcats"       "stringr"       "dplyr"         "purrr"        
[25] "readr"         "tidyr"         "tibble"        "ggplot2"      
[29] "tidyverse"     "stats"         "graphics"      "grDevices"    
[33] "utils"         "datasets"      "methods"       "base"         

[[2]]
 [1] "DT"            "kableExtra"    "texreg"        "see"          
 [5] "report"        "parameters"    "performance"   "modelbased"   
 [9] "insight"       "effectsize"    "datawizard"    "correlation"  
[13] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[17] "fabricatr"     "randomizr"     "haven"         "labelled"     
[21] "lubridate"     "forcats"       "stringr"       "dplyr"        
[25] "purrr"         "readr"         "tidyr"         "tibble"       
[29] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[33] "grDevices"     "utils"         "datasets"      "methods"      
[37] "base"         

[[3]]
 [1] "DT"            "kableExtra"    "texreg"        "see"          
 [5] "report"        "parameters"    "performance"   "modelbased"   
 [9] "insight"       "effectsize"    "datawizard"    "correlation"  
[13] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[17] "fabricatr"     "randomizr"     "haven"         "labelled"     
[21] "lubridate"     "forcats"       "stringr"       "dplyr"        
[25] "purrr"         "readr"         "tidyr"         "tibble"       
[29] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[33] "grDevices"     "utils"         "datasets"      "methods"      
[37] "base"         

[[4]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[5]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[6]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[7]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[8]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[9]]
 [1] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [5] "see"           "report"        "parameters"    "performance"  
 [9] "modelbased"    "insight"       "effectsize"    "datawizard"   
[13] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[17] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[21] "labelled"      "lubridate"     "forcats"       "stringr"      
[25] "dplyr"         "purrr"         "readr"         "tidyr"        
[29] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[33] "graphics"      "grDevices"     "utils"         "datasets"     
[37] "methods"       "base"         

[[10]]
 [1] "ggmap"         "htmltools"     "DT"            "kableExtra"   
 [5] "texreg"        "see"           "report"        "parameters"   
 [9] "performance"   "modelbased"    "insight"       "effectsize"   
[13] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[17] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[21] "haven"         "labelled"      "lubridate"     "forcats"      
[25] "stringr"       "dplyr"         "purrr"         "readr"        
[29] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[33] "stats"         "graphics"      "grDevices"     "utils"        
[37] "datasets"      "methods"       "base"         

[[11]]
 [1] "ggrepel"       "ggmap"         "htmltools"     "DT"           
 [5] "kableExtra"    "texreg"        "see"           "report"       
 [9] "parameters"    "performance"   "modelbased"    "insight"      
[13] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[17] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[21] "randomizr"     "haven"         "labelled"      "lubridate"    
[25] "forcats"       "stringr"       "dplyr"         "purrr"        
[29] "readr"         "tidyr"         "tibble"        "ggplot2"      
[33] "tidyverse"     "stats"         "graphics"      "grDevices"    
[37] "utils"         "datasets"      "methods"       "base"         

[[12]]
 [1] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
 [5] "DT"            "kableExtra"    "texreg"        "see"          
 [9] "report"        "parameters"    "performance"   "modelbased"   
[13] "insight"       "effectsize"    "datawizard"    "correlation"  
[17] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[21] "fabricatr"     "randomizr"     "haven"         "labelled"     
[25] "lubridate"     "forcats"       "stringr"       "dplyr"        
[29] "purrr"         "readr"         "tidyr"         "tibble"       
[33] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[37] "grDevices"     "utils"         "datasets"      "methods"      
[41] "base"         

[[13]]
 [1] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
 [5] "htmltools"     "DT"            "kableExtra"    "texreg"       
 [9] "see"           "report"        "parameters"    "performance"  
[13] "modelbased"    "insight"       "effectsize"    "datawizard"   
[17] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[21] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[25] "labelled"      "lubridate"     "forcats"       "stringr"      
[29] "dplyr"         "purrr"         "readr"         "tidyr"        
[33] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[37] "graphics"      "grDevices"     "utils"         "datasets"     
[41] "methods"       "base"         

[[14]]
 [1] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
 [5] "ggmap"         "htmltools"     "DT"            "kableExtra"   
 [9] "texreg"        "see"           "report"        "parameters"   
[13] "performance"   "modelbased"    "insight"       "effectsize"   
[17] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[21] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[25] "haven"         "labelled"      "lubridate"     "forcats"      
[29] "stringr"       "dplyr"         "purrr"         "readr"        
[33] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[37] "stats"         "graphics"      "grDevices"     "utils"        
[41] "datasets"      "methods"       "base"         

[[15]]
 [1] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
 [5] "ggrepel"       "ggmap"         "htmltools"     "DT"           
 [9] "kableExtra"    "texreg"        "see"           "report"       
[13] "parameters"    "performance"   "modelbased"    "insight"      
[17] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[21] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[25] "randomizr"     "haven"         "labelled"      "lubridate"    
[29] "forcats"       "stringr"       "dplyr"         "purrr"        
[33] "readr"         "tidyr"         "tibble"        "ggplot2"      
[37] "tidyverse"     "stats"         "graphics"      "grDevices"    
[41] "utils"         "datasets"      "methods"       "base"         

[[16]]
 [1] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
 [5] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
 [9] "DT"            "kableExtra"    "texreg"        "see"          
[13] "report"        "parameters"    "performance"   "modelbased"   
[17] "insight"       "effectsize"    "datawizard"    "correlation"  
[21] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[25] "fabricatr"     "randomizr"     "haven"         "labelled"     
[29] "lubridate"     "forcats"       "stringr"       "dplyr"        
[33] "purrr"         "readr"         "tidyr"         "tibble"       
[37] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[41] "grDevices"     "utils"         "datasets"      "methods"      
[45] "base"         

[[17]]
 [1] "dagitty"       "scales"        "patchwork"     "ggpubr"       
 [5] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
 [9] "htmltools"     "DT"            "kableExtra"    "texreg"       
[13] "see"           "report"        "parameters"    "performance"  
[17] "modelbased"    "insight"       "effectsize"    "datawizard"   
[21] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[25] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[29] "labelled"      "lubridate"     "forcats"       "stringr"      
[33] "dplyr"         "purrr"         "readr"         "tidyr"        
[37] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[41] "graphics"      "grDevices"     "utils"         "datasets"     
[45] "methods"       "base"         

[[18]]
 [1] "ggdag"         "dagitty"       "scales"        "patchwork"    
 [5] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
 [9] "ggmap"         "htmltools"     "DT"            "kableExtra"   
[13] "texreg"        "see"           "report"        "parameters"   
[17] "performance"   "modelbased"    "insight"       "effectsize"   
[21] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[25] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[29] "haven"         "labelled"      "lubridate"     "forcats"      
[33] "stringr"       "dplyr"         "purrr"         "readr"        
[37] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[41] "stats"         "graphics"      "grDevices"     "utils"        
[45] "datasets"      "methods"       "base"         

[[19]]
 [1] "ggforce"       "ggdag"         "dagitty"       "scales"       
 [5] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
 [9] "ggrepel"       "ggmap"         "htmltools"     "DT"           
[13] "kableExtra"    "texreg"        "see"           "report"       
[17] "parameters"    "performance"   "modelbased"    "insight"      
[21] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[25] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[29] "randomizr"     "haven"         "labelled"      "lubridate"    
[33] "forcats"       "stringr"       "dplyr"         "purrr"        
[37] "readr"         "tidyr"         "tibble"        "ggplot2"      
[41] "tidyverse"     "stats"         "graphics"      "grDevices"    
[45] "utils"         "datasets"      "methods"       "base"         

[[20]]
 [1] "COVID19"       "ggforce"       "ggdag"         "dagitty"      
 [5] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
 [9] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
[13] "DT"            "kableExtra"    "texreg"        "see"          
[17] "report"        "parameters"    "performance"   "modelbased"   
[21] "insight"       "effectsize"    "datawizard"    "correlation"  
[25] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[29] "fabricatr"     "randomizr"     "haven"         "labelled"     
[33] "lubridate"     "forcats"       "stringr"       "dplyr"        
[37] "purrr"         "readr"         "tidyr"         "tibble"       
[41] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[45] "grDevices"     "utils"         "datasets"      "methods"      
[49] "base"         

[[21]]
 [1] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [5] "dagitty"       "scales"        "patchwork"     "ggpubr"       
 [9] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[13] "htmltools"     "DT"            "kableExtra"    "texreg"       
[17] "see"           "report"        "parameters"    "performance"  
[21] "modelbased"    "insight"       "effectsize"    "datawizard"   
[25] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[29] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[33] "labelled"      "lubridate"     "forcats"       "stringr"      
[37] "dplyr"         "purrr"         "readr"         "tidyr"        
[41] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[45] "graphics"      "grDevices"     "utils"         "datasets"     
[49] "methods"       "base"         

[[22]]
 [1] "mapdata"       "maps"          "COVID19"       "ggforce"      
 [5] "ggdag"         "dagitty"       "scales"        "patchwork"    
 [9] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
[13] "ggmap"         "htmltools"     "DT"            "kableExtra"   
[17] "texreg"        "see"           "report"        "parameters"   
[21] "performance"   "modelbased"    "insight"       "effectsize"   
[25] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[29] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[33] "haven"         "labelled"      "lubridate"     "forcats"      
[37] "stringr"       "dplyr"         "purrr"         "readr"        
[41] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[45] "stats"         "graphics"      "grDevices"     "utils"        
[49] "datasets"      "methods"       "base"         

[[23]]
 [1] "qss"           "mapdata"       "maps"          "COVID19"      
 [5] "ggforce"       "ggdag"         "dagitty"       "scales"       
 [9] "patchwork"     "ggpubr"        "ggthemes"      "ggridges"     
[13] "ggrepel"       "ggmap"         "htmltools"     "DT"           
[17] "kableExtra"    "texreg"        "see"           "report"       
[21] "parameters"    "performance"   "modelbased"    "insight"      
[25] "effectsize"    "datawizard"    "correlation"   "bayestestR"   
[29] "easystats"     "DeclareDesign" "estimatr"      "fabricatr"    
[33] "randomizr"     "haven"         "labelled"      "lubridate"    
[37] "forcats"       "stringr"       "dplyr"         "purrr"        
[41] "readr"         "tidyr"         "tibble"        "ggplot2"      
[45] "tidyverse"     "stats"         "graphics"      "grDevices"    
[49] "utils"         "datasets"      "methods"       "base"         

[[24]]
 [1] "tidycensus"    "qss"           "mapdata"       "maps"         
 [5] "COVID19"       "ggforce"       "ggdag"         "dagitty"      
 [9] "scales"        "patchwork"     "ggpubr"        "ggthemes"     
[13] "ggridges"      "ggrepel"       "ggmap"         "htmltools"    
[17] "DT"            "kableExtra"    "texreg"        "see"          
[21] "report"        "parameters"    "performance"   "modelbased"   
[25] "insight"       "effectsize"    "datawizard"    "correlation"  
[29] "bayestestR"    "easystats"     "DeclareDesign" "estimatr"     
[33] "fabricatr"     "randomizr"     "haven"         "labelled"     
[37] "lubridate"     "forcats"       "stringr"       "dplyr"        
[41] "purrr"         "readr"         "tidyr"         "tibble"       
[45] "ggplot2"       "tidyverse"     "stats"         "graphics"     
[49] "grDevices"     "utils"         "datasets"      "methods"      
[53] "base"         

[[25]]
 [1] "dataverse"     "tidycensus"    "qss"           "mapdata"      
 [5] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [9] "dagitty"       "scales"        "patchwork"     "ggpubr"       
[13] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[17] "htmltools"     "DT"            "kableExtra"    "texreg"       
[21] "see"           "report"        "parameters"    "performance"  
[25] "modelbased"    "insight"       "effectsize"    "datawizard"   
[29] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[33] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[37] "labelled"      "lubridate"     "forcats"       "stringr"      
[41] "dplyr"         "purrr"         "readr"         "tidyr"        
[45] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[49] "graphics"      "grDevices"     "utils"         "datasets"     
[53] "methods"       "base"         

[[26]]
 [1] "dataverse"     "tidycensus"    "qss"           "mapdata"      
 [5] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [9] "dagitty"       "scales"        "patchwork"     "ggpubr"       
[13] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[17] "htmltools"     "DT"            "kableExtra"    "texreg"       
[21] "see"           "report"        "parameters"    "performance"  
[25] "modelbased"    "insight"       "effectsize"    "datawizard"   
[29] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[33] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[37] "labelled"      "lubridate"     "forcats"       "stringr"      
[41] "dplyr"         "purrr"         "readr"         "tidyr"        
[45] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[49] "graphics"      "grDevices"     "utils"         "datasets"     
[53] "methods"       "base"         

[[27]]
 [1] "dataverse"     "tidycensus"    "qss"           "mapdata"      
 [5] "maps"          "COVID19"       "ggforce"       "ggdag"        
 [9] "dagitty"       "scales"        "patchwork"     "ggpubr"       
[13] "ggthemes"      "ggridges"      "ggrepel"       "ggmap"        
[17] "htmltools"     "DT"            "kableExtra"    "texreg"       
[21] "see"           "report"        "parameters"    "performance"  
[25] "modelbased"    "insight"       "effectsize"    "datawizard"   
[29] "correlation"   "bayestestR"    "easystats"     "DeclareDesign"
[33] "estimatr"      "fabricatr"     "randomizr"     "haven"        
[37] "labelled"      "lubridate"     "forcats"       "stringr"      
[41] "dplyr"         "purrr"         "readr"         "tidyr"        
[45] "tibble"        "ggplot2"       "tidyverse"     "stats"        
[49] "graphics"      "grDevices"     "utils"         "datasets"     
[53] "methods"       "base"         

[[28]]
 [1] "zoo"           "dataverse"     "tidycensus"    "qss"          
 [5] "mapdata"       "maps"          "COVID19"       "ggforce"      
 [9] "ggdag"         "dagitty"       "scales"        "patchwork"    
[13] "ggpubr"        "ggthemes"      "ggridges"      "ggrepel"      
[17] "ggmap"         "htmltools"     "DT"            "kableExtra"   
[21] "texreg"        "see"           "report"        "parameters"   
[25] "performance"   "modelbased"    "insight"       "effectsize"   
[29] "datawizard"    "correlation"   "bayestestR"    "easystats"    
[33] "DeclareDesign" "estimatr"      "fabricatr"     "randomizr"    
[37] "haven"         "labelled"      "lubridate"     "forcats"      
[41] "stringr"       "dplyr"         "purrr"         "readr"        
[45] "tidyr"         "tibble"        "ggplot2"       "tidyverse"    
[49] "stats"         "graphics"      "grDevices"     "utils"        
[53] "datasets"      "methods"       "base"         </code></pre>
</div>
</div>
</section></section>
<section>
<section id="review" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-magnifying-glass" aria-label="magnifying-glass"></i> Review</h1>

</section>
<section id="motivating-questions" class="slide level2 smaller">
<h2>Motivating Questions</h2>
<p>In the rest of today’s class, we’ll get some practice putting together the various skills you need for your drafts by exploring the following:</p>
<ul>
<li class="fragment"><p>How does partisanship shape American’s perceptions of vaccines?</p></li>
<li class="fragment"><p>Who is skeptical of the benefits of vaccination?</p></li>
<li class="fragment"><p>Have these perceptions about vaccines changed over time?</p></li>
</ul>
</section>
<section id="tasks" class="slide level2 smaller">
<h2>Tasks:</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p>Get setup to work</p></li>
<li class="fragment"><p>Load our data</p></li>
<li class="fragment"><p>Recode our data</p></li>
<li class="fragment"><p>Summarize our data</p></li>
<li class="fragment"><p>Specify our expectations</p></li>
<li class="fragment"><p>Estimate models to test these expectations</p></li>
<li class="fragment"><p>Present and interpret results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals</li>
<li class="fragment">Hypothesis tests</li>
</ul></li>
</ul>
</section>
<section id="new-packages" class="slide level2">
<h2>New packages</h2>
<p>To easily load survey data for our question, we’ll need the <code>anesr</code> package, which loads data from the American National Election Studies into R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># # Uncomment to uninstall package to download NES survey data</span></span>
<span id="cb3-2"><a></a><span class="co"># library(devtools)</span></span>
<span id="cb3-3"><a></a><span class="co"># install_github("jamesmartherus/anesr")</span></span>
<span id="cb3-4"><a></a><span class="fu">require</span>(anesr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data" class="slide level2 smaller">
<h2>Data</h2>
<p>Now that we have <code>anesr</code> installed, let’s load data from the 2016 and 2020 National Election Studies:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="co"># Load data</span></span>
<span id="cb4-2"><a></a><span class="fu">data</span>(timeseries_2016, <span class="at">package =</span> <span class="st">"anesr"</span>)</span>
<span id="cb4-3"><a></a><span class="fu">data</span>(timeseries_2020, <span class="at">package =</span> <span class="st">"anesr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And copy those data frames into new dataframes with shorter names</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="co"># Rename datasets</span></span>
<span id="cb5-2"><a></a>nes16 <span class="ot">&lt;-</span> timeseries_2016</span>
<span id="cb5-3"><a></a>nes20 <span class="ot">&lt;-</span> timeseries_2020</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="finding-variables-outcomes" class="slide level2 smaller">
<h2>Finding variables: Outcomes</h2>
<p>Our primary outcome of interest are beliefs about vaccines.</p>
<p>Variables <code>V162162x</code> in the 2016 NES and <code>V202383x</code> in the 2020 NES will serve as our primary outcome of interest, summarizing respondents answer to the following question:</p>
<blockquote>
<p>Do the health benefits of vaccinations generally outweigh the risks, do the risks outweigh the benefits, or is there no difference?</p>
</blockquote>
</section>
<section id="finding-variables-predictors" class="slide level2 smaller">
<h2>Finding variables: Predictors</h2>
<p>Similarly, <code>V161158x</code> in the 2016 NES and <code>V201231x</code> in the 2020 NES will serve our key predictor (respondent’s partisanship).</p>
<p>Finally, we’ll control respondents’ age, using <code>V161267</code> in the 2016 NES and <code>V201507x</code> in the 2020 NES</p>
</section>
<section id="examine-distributions-vaccine-beliefs" class="slide level2 smaller">
<h2>Examine Distributions: Vaccine Beliefs</h2>
<p>The variables in the NES datasets are of a class <code>labelled</code> which allows numeric values to have substantive labels</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">class</span>(nes16<span class="sc">$</span>V162162x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "haven_labelled"</code></pre>
</div>
</div>
<p>Our outcome variable has the following labels:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>labelled<span class="sc">::</span><span class="fu">val_labels</span>(nes16<span class="sc">$</span>V162162x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   -9. Refused 
                                            -9 
                                -8. Don't know 
                                            -8 
-7. No post data, deleted due to incomplete IW 
                                            -7 
                -6. No post-election interview 
                                            -6 
                      1. Benefits much greater 
                                             1 
                2. Benefits moderately greater 
                                             2 
                  3. Benefits slightly greater 
                                             3 
                              4. No difference 
                                             4 
                     5. Risks slightly greater 
                                             5 
                   6. Risks moderately greater 
                                             6 
                         7. Risks much greater 
                                             7 </code></pre>
</div>
</div>
<p>And distribution of responses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">table</span>(nes16<span class="sc">$</span>V162162x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  -9   -8   -7   -6    1    2    3    4    5    6    7 
  21   28   86  536 1687  726  258  539   96  211   82 </code></pre>
</div>
</div>
</section>
<section id="recoding-outcome-variables" class="slide level2">
<h2>Recoding outcome variables</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Tasks</a></li><li><a href="#tabset-1-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>What transformations do we need to make to <code>V162162x</code> in <code>nes16</code> and <code>V202383x</code> in <code>nes20</code> so that these variables are suitable for analysis?</p>
<ul>
<li class="fragment"><p>Recode negative values to be <code>NA</code></p></li>
<li class="fragment"><p>Reverse code so that higher values indicate greater belief vaccines benefits</p></li>
<li class="fragment"><p>Create an indicator of people who are vaccine skeptics</p></li>
</ul>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>nes16 <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-3"><a></a>    <span class="co"># Make Negative values NA, Reverse Code So Higher Values = Benefits &gt; Risks</span></span>
<span id="cb12-4"><a></a>    <span class="at">vaccine_benefits =</span> <span class="fu">ifelse</span>(V162162x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, (V162162x<span class="dv">-8</span>)<span class="sc">*-</span><span class="dv">1</span>),</span>
<span id="cb12-5"><a></a>    <span class="co"># Indicator of vaccine skepticism (Risks &gt; Benefits)</span></span>
<span id="cb12-6"><a></a>    <span class="at">vaccine_skeptic01 =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-7"><a></a>      vaccine_benefits <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb12-8"><a></a>      vaccine_benefits <span class="sc">&lt;=</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb12-9"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb12-10"><a></a>    )</span>
<span id="cb12-11"><a></a>  ) <span class="ot">-&gt;</span> nes16 <span class="co"># Save recodes to nes16</span></span>
<span id="cb12-12"><a></a></span>
<span id="cb12-13"><a></a>nes20 <span class="sc">%&gt;%</span></span>
<span id="cb12-14"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-15"><a></a>    <span class="co"># Make Negative values NA, Reverse Code So Higher Values = Benefits &gt; Risks</span></span>
<span id="cb12-16"><a></a>    <span class="at">vaccine_benefits =</span> <span class="fu">ifelse</span>(V202383x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, (V202383x<span class="dv">-8</span>)<span class="sc">*-</span><span class="dv">1</span>),</span>
<span id="cb12-17"><a></a>    <span class="co"># Indicator of vaccine skepticism (Risks &gt; Benefits)</span></span>
<span id="cb12-18"><a></a>    <span class="at">vaccine_skeptic01 =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-19"><a></a>      vaccine_benefits <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb12-20"><a></a>      vaccine_benefits <span class="sc">&lt;=</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb12-21"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb12-22"><a></a>    )</span>
<span id="cb12-23"><a></a>  ) <span class="ot">-&gt;</span> nes20 <span class="co"># Save recodes to nes20</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="recoding-predictors" class="slide level2">
<h2>Recoding Predictors</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Tasks</a></li><li><a href="#tabset-2-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>Now we repeat this process for our key predictor, partisanship.</p>
<ul>
<li><p>Recode partisanship variables <code>V161158x</code> in <code>nes16</code> and <code>V201231x</code> in <code>nes20</code></p></li>
<li><p>Create indicators from this recoded variable that classify partisanship as categorical variable (with Democrats as the reference category)</p></li>
</ul>
<p>And our covariate, age variables <code>V161267</code> in <code>nes16</code> and <code>V201507x</code> in <code>nes20</code></p>
<ul>
<li>Recode negative values to be <code>NA</code></li>
</ul>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>nes16 <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-3"><a></a>    <span class="at">pid =</span> <span class="fu">ifelse</span>(V161158x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V161158x),</span>
<span id="cb13-4"><a></a>    <span class="at">pid3cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb13-5"><a></a>      pid <span class="sc">&lt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Democrat"</span>,</span>
<span id="cb13-6"><a></a>      pid <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Independent"</span>,</span>
<span id="cb13-7"><a></a>      pid <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Republican"</span>,</span>
<span id="cb13-8"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Independent"</span></span>
<span id="cb13-9"><a></a>    ) <span class="sc">%&gt;%</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>,<span class="st">"Independent"</span>,<span class="st">"Republican"</span>)),</span>
<span id="cb13-10"><a></a>    <span class="at">age =</span> <span class="fu">ifelse</span>(V161267 <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V161267)</span>
<span id="cb13-11"><a></a>  ) <span class="ot">-&gt;</span> nes16</span>
<span id="cb13-12"><a></a></span>
<span id="cb13-13"><a></a><span class="do">## Recoding Partisanship (V201231x) in 2020 NES</span></span>
<span id="cb13-14"><a></a></span>
<span id="cb13-15"><a></a>nes20 <span class="sc">%&gt;%</span></span>
<span id="cb13-16"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-17"><a></a>    <span class="at">pid =</span> <span class="fu">ifelse</span>(V201231x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V201231x),</span>
<span id="cb13-18"><a></a>    <span class="at">pid3cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb13-19"><a></a>      pid <span class="sc">&lt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Democrat"</span>,</span>
<span id="cb13-20"><a></a>      pid <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Independent"</span>,</span>
<span id="cb13-21"><a></a>      pid <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Republican"</span>,</span>
<span id="cb13-22"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Independent"</span></span>
<span id="cb13-23"><a></a>    ) <span class="sc">%&gt;%</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>,<span class="st">"Independent"</span>,<span class="st">"Republican"</span>)),</span>
<span id="cb13-24"><a></a>    <span class="at">age =</span> <span class="fu">ifelse</span>(V201507x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V201507x)</span>
<span id="cb13-25"><a></a>  ) <span class="ot">-&gt;</span> nes20</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="progress-report" class="slide level2 smaller">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><strong>Summarize our data</strong>📥</p></li>
<li class="fragment"><p>Specify our expectations</p></li>
<li class="fragment"><p>Estimate models to test these expectations</p></li>
<li class="fragment"><p>Presenting and interpreting results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals</li>
<li class="fragment">Hypothesis tests</li>
</ul></li>
</ul>
</section>
<section id="descriptive-statistics-2016" class="slide level2 smaller scrollable">
<h2>Descriptive statistics (2016)</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Tasks</a></li><li><a href="#tabset-3-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-3-3"><i class="fa-solid fa-table" aria-label="table"></i> Table</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<ol type="1">
<li class="fragment"><p>Create <code>the_vars</code></p></li>
<li class="fragment"><p>Select these variables</p></li>
<li class="fragment"><p>Pivot the data</p></li>
<li class="fragment"><p>Calculate summary statistics</p></li>
<li class="fragment"><p>Format as an html table</p></li>
</ol>
</div>
<div id="tabset-3-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="co"># 1. Create a object with the names of the variables you want to summarize</span></span>
<span id="cb14-2"><a></a>the_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"vaccine_skeptic01"</span>,<span class="st">"pid"</span>,<span class="st">"age"</span>)</span>
<span id="cb14-3"><a></a><span class="co"># 2. Select these variables</span></span>
<span id="cb14-4"><a></a>nes16 <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(the_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a></a><span class="co"># 3. Pivot the data</span></span>
<span id="cb14-7"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb14-8"><a></a>    <span class="at">cols =</span> <span class="fu">all_of</span>(the_vars),</span>
<span id="cb14-9"><a></a>    <span class="at">names_to =</span> <span class="st">"Variable"</span></span>
<span id="cb14-10"><a></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb14-11"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-12"><a></a>    <span class="at">Variable =</span> <span class="fu">factor</span>(Variable, <span class="at">levels =</span> the_vars)</span>
<span id="cb14-13"><a></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb14-14"><a></a>  <span class="fu">arrange</span>(Variable)<span class="sc">%&gt;%</span></span>
<span id="cb14-15"><a></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Variable)<span class="sc">%&gt;%</span></span>
<span id="cb14-16"><a></a>  <span class="co"># 3. Calculate summary statistics</span></span>
<span id="cb14-17"><a></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb14-18"><a></a>    <span class="at">min =</span> <span class="fu">min</span>(value, <span class="at">na.rm=</span>T),</span>
<span id="cb14-19"><a></a>    <span class="at">p25 =</span> <span class="fu">quantile</span>(value, <span class="at">na.rm=</span>T, <span class="at">prob =</span> <span class="fl">0.25</span>),</span>
<span id="cb14-20"><a></a>    <span class="at">Median =</span> <span class="fu">quantile</span>(value, <span class="at">na.rm=</span>T, <span class="at">prob =</span> <span class="fl">0.5</span>),</span>
<span id="cb14-21"><a></a>    <span class="at">mean =</span> <span class="fu">mean</span>(value, <span class="at">na.rm=</span>T),</span>
<span id="cb14-22"><a></a>    <span class="at">p75 =</span> <span class="fu">quantile</span>(value, <span class="at">na.rm=</span>T, <span class="at">prob =</span> <span class="fl">0.25</span>),</span>
<span id="cb14-23"><a></a>    <span class="at">max =</span> <span class="fu">max</span>(value, <span class="at">na.rm=</span>T),</span>
<span id="cb14-24"><a></a>    <span class="at">missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(value))</span>
<span id="cb14-25"><a></a>  ) <span class="ot">-&gt;</span> sum_df </span>
<span id="cb14-26"><a></a></span>
<span id="cb14-27"><a></a>sum_tab <span class="ot">&lt;-</span> </span>
<span id="cb14-28"><a></a>knitr<span class="sc">::</span><span class="fu">kable</span>(sum_df,</span>
<span id="cb14-29"><a></a>             <span class="at">caption =</span> <span class="st">"Descriptive Statistics"</span>,</span>
<span id="cb14-30"><a></a>             <span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-31"><a></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-32"><a></a>  kableExtra<span class="sc">::</span><span class="fu">pack_rows</span>(<span class="st">"Outcome"</span>, <span class="at">start_row =</span> <span class="dv">1</span>, <span class="at">end_row =</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-33"><a></a>  kableExtra<span class="sc">::</span><span class="fu">pack_rows</span>(<span class="st">"Key Predictors"</span>, <span class="at">start_row =</span> <span class="dv">2</span>, <span class="at">end_row =</span><span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-34"><a></a>  kableExtra<span class="sc">::</span><span class="fu">pack_rows</span>(<span class="st">"Covariates"</span>, <span class="at">start_row =</span> <span class="dv">3</span>, <span class="at">end_row =</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-3-3">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<caption>Descriptive Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p25</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p75</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="1">
<td colspan="8" style="border-bottom: 1px solid"><strong>Outcome</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">vaccine_skeptic01</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">671</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="8" style="border-bottom: 1px solid"><strong>Key Predictors</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">pid</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="8" style="border-bottom: 1px solid"><strong>Covariates</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">age</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">49.58</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">121</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="progress-report-1" class="slide level2 smaller">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><em>Summarize our data</em> ✅</p></li>
<li class="fragment"><p><strong>Specify our expectations</strong> 📥</p></li>
<li class="fragment"><p>Estimate models to test these expectations</p></li>
<li class="fragment"><p>Presenting and interpreting results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals (review)</li>
<li class="fragment">Hypothesis tests (new!)</li>
</ul></li>
</ul>
</section>
<section id="specificying-expecations" class="slide level2 smaller">
<h2>Specificying Expecations</h2>
<p>Consider our first two motivating questions</p>
<ul>
<li><p>How does partisanship shape American’s perceptions of vaccines?</p></li>
<li><p>Who is skeptical of the benefits of vaccination?</p></li>
</ul>
<p>And some illustrative stereotypes:</p>
<ul>
<li>“Republicans are <em>anti-science</em>”</li>
<li>“Liberal always fall for Goopy <em>pseudo-science</em>”</li>
<li>“Independents love to <em>do their own research</em>”</li>
</ul>
<p>What are the empirical implications of these claims?</p>
</section>
<section id="specificying-expecations-1" class="slide level2 smaller">
<h2>Specificying Expecations</h2>
<p>Similarly, consider our third question:</p>
<ul>
<li>Have these perceptions about vaccines changed over time?</li>
</ul>
<p>And some similar simplified claims:</p>
<ul>
<li>“The Covid-19 vaccine is a miracle of modern science”</li>
<li>“Social media is rife with misinformation about the Covid-19 vaccine”</li>
<li>“Politicians are politicizing vaccine politics for political benefits”</li>
</ul>
<p>What are the empirical implications of these claims?</p>
</section>
<section id="specificying-expecations-2" class="slide level2 smaller">
<h2>Specificying Expecations</h2>
<p>Our goal is to take claims/conventional wisdom/theories, and derive their empirical implications:</p>
<ul>
<li class="fragment"><strong>H1: Partisan Differences in Vaccine Skepticism</strong>
<ul>
<li class="fragment"><strong>H1a:</strong> Republicans will be the most skeptical of vaccines</li>
<li class="fragment"><strong>H1b:</strong> Democrats will be the most skeptical of vaccines</li>
<li class="fragment"><strong>H1c:</strong> Independents will be the most skeptical of vaccines</li>
</ul></li>
</ul>
</section>
<section id="specificying-expecations-3" class="slide level2 smaller">
<h2>Specificying Expecations</h2>
<ul>
<li class="fragment"><strong>H2: Temporal Differences in Vaccine Skepticism</strong>
<ul>
<li class="fragment"><strong>H2a:</strong> Vaccine skepticism will decrease from 2016 to 2020 with the widespread roll out of the Covid-19 vaccine</li>
<li class="fragment"><strong>H2b:</strong> Vaccine skepticism will increase from 2016 to 2020 with increased amounts of misinformation about the Covid-19 vaccine</li>
</ul></li>
<li class="fragment"><strong>H3: Partisan Difference in Vaccine Skepticism Over Time</strong> Partisan differences in Vaccine Skepticism will increase from 2016 to 2020 with the politicization of Covid-19 policies</li>
</ul>
</section>
<section id="motivating-your-expectations" class="slide level2 smaller">
<h2>Motivating your expectations</h2>
<p>In your final papers, unlike in these slides, your expectations should be grounded in existing theory, research, and evidence. For the present question, we might cite sources such as:</p>
<ul>
<li class="fragment"><p>Enders, Adam M., and Steven M. Smallpage. “Informational cues, partisan-motivated reasoning, and the manipulation of conspiracy beliefs.” Political Communication 36.1 (2019): 83-102.</p></li>
<li class="fragment"><p>Stecula, Dominik A., and Mark Pickup. “How populism and conservative media fuel conspiracy beliefs about COVID-19 and what it means for COVID-19 behaviors.” Research &amp; Politics 8.1 (2021): 2053168021993979.</p></li>
<li class="fragment"><p>Jennings, Will, et al.&nbsp;“Lack of trust, conspiracy beliefs, and social media use predict COVID-19 vaccine hesitancy.” Vaccines 9.6 (2021): 593.</p></li>
<li class="fragment"><p>Hollander, Barry A. “Partisanship, individual differences, and news media exposure as predictors of conspiracy beliefs.” Journalism &amp; Mass Communication Quarterly 95.3 (2018): 691-713.</p></li>
</ul>
</section>
<section id="model-specification" class="slide level2 smaller">
<h2>Model Specification</h2>
<p>Translate these expectations into empirical models requires choices about <strong>how to specify our models</strong></p>
<ul>
<li class="fragment"><p>How should we measure/operationalize our outcome</p>
<ul>
<li class="fragment">Should we measure beliefs about vaccines with 7-point ordinal scale or as a binary indicator of vaccine skepticism</li>
</ul></li>
<li class="fragment"><p>How should we measure/operationalize our key predictor(s)</p>
<ul>
<li class="fragment">Should we measure partisanship using a 7 point scale or as categorical variable?</li>
</ul></li>
<li class="fragment"><p>What should we control for in our model?</p>
<ul>
<li class="fragment">Factors likely to predict both our outcome and our key predictor of interest</li>
</ul></li>
<li class="fragment"><p>There are rarely <em>definitive</em> answers to these questions. Instead, we will often estimate <strong>multiple models</strong> to try and show that our findings are <strong>robust</strong> to alternative specifications</p></li>
</ul>
</section>
<section id="model-specification-1" class="slide level2 smaller scrollable">
<h2>Model Specification</h2>
<p>For your projects, every group will almost surely estimate some form of the following:</p>
<ol type="1">
<li class="fragment"><p>Baseline bivariate model: The simplest test of the relationship between your outcome and key predictor</p></li>
<li class="fragment"><p>Multiple regression model: A test of the robustness of this relationship, controlling for alternative explanations</p></li>
</ol>
</section>
<section id="model-specification-2" class="slide level2 smaller">
<h2>Model Specification</h2>
<p>In practice, I suspect you may estimate multiple regression models such as:</p>
<ul>
<li class="fragment"><p>Alternative specifications/operationalizations of outcomes and predictors</p></li>
<li class="fragment"><p>Interaction models to test conditional relationships</p></li>
<li class="fragment"><p>Polynomial models to test non-linear relationships</p></li>
</ul>
</section>
<section id="section" class="slide level2 smaller">
<h2></h2>
<h4 id="translating-theoretical-claims-into-empirical-expectations">Translating Theoretical Claims into Empirical Expectations</h4>
<p>Before we estimate our models in R, we will write down our models formally and empirical implications of our theoretical expectations in terms of the coefficients of our model.</p>
<p>For example, our baseline model might be:</p>
<p><span class="math display">\[\text{Vaccine Skepticism} = \beta_0 + \beta_1 \text{PID}_{7pt} + X\beta + \epsilon\]</span></p>
<p>If <span class="math inline">\(\beta_1\)</span> is positive this is consistent with <strong>H1a</strong> (greater skepticism among Republicans), - If <span class="math inline">\(\beta_2\)</span> is negative this is consistent with <strong>H1b</strong> (greater skepticism among Democrats),</p>
<ul>
<li class="fragment">But how could we test <strong>H1c</strong> – greater skepticism among Independents, who are “4s” on <span class="math inline">\(\text{PID}_{7pt}\)</span>?</li>
</ul>
</section>
<section id="section-1" class="slide level2 smaller">
<h2></h2>
<h4 id="translating-theoretical-claims-into-empirical-expectations-1">Translating Theoretical Claims into Empirical Expectations</h4>
<p>We could fit a polynomial regression, including both partisanship and “partisanship squared” to allow the relationship between partisanship and vaccine skepticism to vary non-linearly</p>
<p><span class="math display">\[\text{Vaccine Skepticism} = \beta_0 + \beta_1 \text{PID}_{7pt} +  \beta_2 \text{PID}_{7pt}^2+ X\beta+ \epsilon\]</span></p>
</section>
<section id="section-2" class="slide level2 smaller">
<h2></h2>
<h4 id="translating-theoretical-claims-into-empirical-expectations-2">Translating Theoretical Claims into Empirical Expectations</h4>
<p>Or we could estimate a model treating Partisanship as a <strong>categorical</strong> variable rather than an <strong>ordinal interval</strong> variable.</p>
<p>In our recoding, we set <code>"Democrat"</code> to be the first level of the variable <code>pid3cat</code>, so the model R will estimate by default is:</p>
<p><span class="math display">\[\text{Vaccine Skepticism} = \beta_0 + \beta_1 \text{PID}_{Ind} +  \beta_2 \text{PID}_{Rep}+ X\beta + \epsilon\]</span></p>
</section>
<section id="testing-differences-over-time" class="slide level2 smaller">
<h2>Testing differences over time</h2>
<p>Testing Hypotheses 2 and 3 involve making comparisons across models estimated on data from different surveys.</p>
<p>Formally, testing these expectations is a little more complicated</p>
<ul>
<li class="fragment">we could pool our two surveys together include an interaction term for survey year</li>
</ul>
<p>For our purposes, we’ll treat these as more qualitative/exploratory hypotheses:</p>
<ul>
<li class="fragment"><p>H2a/b implies overall rates of vaccine skepticism will be lower/higher in 2020 compared to 2016</p></li>
<li class="fragment"><p>H3 implies that whatever partisan differences we find in 2016 should be larger in 2020.</p></li>
</ul>
</section>
<section id="progress-report-2" class="slide level2 smaller">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><em>Specify our expectations</em> ✅</p></li>
<li class="fragment"><p><strong>Estimate models to test these expectations</strong> 📥</p></li>
<li class="fragment"><p>Presenting and interpreting results using</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals</li>
<li class="fragment">Hypothesis tests</li>
</ul></li>
</ul>
</section>
<section id="estimating-empirical-models" class="slide level2">
<h2>Estimating Empirical Models</h2>
<p>Having derived empirical implications of our theoretical expectations expressed in terms of linear regressions, now we simply have to estimate our models in R.</p>
<p>When estimating the <strong>same model</strong> on <strong>different datasets</strong> we can write the formulas once</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>f1 <span class="ot">&lt;-</span> <span class="fu">formula</span>(vaccine_skeptic01 <span class="sc">~</span> pid <span class="sc">+</span> age)</span>
<span id="cb15-2"><a></a>f2 <span class="ot">&lt;-</span> <span class="fu">formula</span>(vaccine_skeptic01 <span class="sc">~</span> pid <span class="sc">+</span> <span class="fu">I</span>(pid<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> age)</span>
<span id="cb15-3"><a></a>f3 <span class="ot">&lt;-</span> <span class="fu">formula</span>(vaccine_skeptic01 <span class="sc">~</span> pid3cat <span class="sc">+</span> age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="estimating-empirical-models-1" class="slide level2">
<h2>Estimating Empirical Models</h2>
<p>And then pass it to <code>lm()</code> with different <code>data</code> arguments:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>m1_2016 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f1, <span class="at">data =</span> nes16)</span>
<span id="cb16-2"><a></a>m1_2020 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f1, <span class="at">data =</span> nes20)</span>
<span id="cb16-3"><a></a>m2_2016 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f2, <span class="at">data =</span> nes16)</span>
<span id="cb16-4"><a></a>m2_2020 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f2, <span class="at">data =</span> nes20)</span>
<span id="cb16-5"><a></a>m3_2016 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f3, <span class="at">data =</span> nes16)</span>
<span id="cb16-6"><a></a>m3_2020 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f3, <span class="at">data =</span> nes20)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="estimating-empirical-models-2" class="slide level2 smaller">
<h2>Estimating Empirical Models</h2>
<p>If you’ve:</p>
<ul>
<li><p>coded your data correctly</p></li>
<li><p>developed clear testable implications from your theoretical expectations</p></li>
</ul>
<p>Specifying and estimating empirical models is straightforward. Literally a few lines of code.</p>
</section>
<section id="progress-report-3" class="slide level2 smaller">
<h2>Progress Report</h2>
<p>To explore these questions, we need to</p>
<ul>
<li class="fragment"><p><em>Get setup to work</em> ✅</p></li>
<li class="fragment"><p><em>Load our data</em> ✅</p></li>
<li class="fragment"><p><em>Recode our data</em> ✅</p></li>
<li class="fragment"><p><em>Specify our expectations</em> ✅</p></li>
<li class="fragment"><p><em>Estimate models to test these expectations</em> ✅</p></li>
<li class="fragment"><p><em>Present our results</em> 📥</p>
<ul>
<li class="fragment">Tables</li>
<li class="fragment">Figures</li>
<li class="fragment">Confidence intervals</li>
<li class="fragment">Hypothesis testing</li>
</ul></li>
</ul>
</section>
<section id="presenting-and-interpreting-your-results" class="slide level2 smaller">
<h2>Presenting and Interpreting Your Results</h2>
<p>Presenting and interpreting your results is requires both art and science.</p>
<p>Your goal is to tell a story with your results,</p>
<p>Let’s start by producing a regression table, which provides a concise summary of multiple regression models.</p>
</section>
<section id="regression-tables" class="slide level2 smaller">
<h2>Regression Tables</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Tasks</a></li><li><a href="#tabset-4-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li><li><a href="#tabset-4-3"><i class="fa-solid fa-table" aria-label="table"></i> Basic</a></li><li><a href="#tabset-4-4"><i class="fa-solid fa-table" aria-label="table"></i> Better</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<ul>
<li><p>Giving the variables in substantive names</p></li>
<li><p>Reporting coefficients to 3 decimal places</p></li>
<li><p>Using a single significance threshold of <span class="math inline">\(p &lt; 0.05\)</span></p></li>
<li><p>Giving the models custom names</p></li>
<li><p>Adding a header to group models by year</p></li>
<li><p>Changing the caption of the table</p></li>
</ul>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># Basic</span></span>
<span id="cb17-2"><a></a>tab_basic <span class="ot">&lt;-</span> texreg<span class="sc">::</span><span class="fu">htmlreg</span>(</span>
<span id="cb17-3"><a></a>  <span class="fu">list</span>(m1_2016,m2_2016,m3_2016,</span>
<span id="cb17-4"><a></a>       m1_2020,m2_2020,m3_2020)</span>
<span id="cb17-5"><a></a>)</span>
<span id="cb17-6"><a></a></span>
<span id="cb17-7"><a></a><span class="co"># Formatted</span></span>
<span id="cb17-8"><a></a>tab_better <span class="ot">&lt;-</span> texreg<span class="sc">::</span><span class="fu">htmlreg</span>(</span>
<span id="cb17-9"><a></a>  <span class="fu">list</span>(m1_2016,m2_2016,m3_2016,</span>
<span id="cb17-10"><a></a>       m1_2020,m2_2020,m3_2020),</span>
<span id="cb17-11"><a></a>  <span class="co"># Reporting coefficients to 3 decimal places</span></span>
<span id="cb17-12"><a></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb17-13"><a></a>  <span class="co"># Using a single significance threshold </span></span>
<span id="cb17-14"><a></a>  <span class="at">stars =</span> <span class="fl">0.05</span>,</span>
<span id="cb17-15"><a></a>  <span class="co"># Giving the variables in substantive names</span></span>
<span id="cb17-16"><a></a>  <span class="at">custom.coef.names =</span> <span class="fu">c</span>(</span>
<span id="cb17-17"><a></a>    <span class="st">"(Intercept)"</span>,</span>
<span id="cb17-18"><a></a>    <span class="st">"PID (7pt)"</span>,</span>
<span id="cb17-19"><a></a>    <span class="st">"Age"</span>,</span>
<span id="cb17-20"><a></a>    <span class="st">"PID&lt;sup&gt;2&lt;/sup&gt; (7pt)"</span>,</span>
<span id="cb17-21"><a></a>    <span class="st">"Independent"</span>,</span>
<span id="cb17-22"><a></a>    <span class="st">"Republican"</span></span>
<span id="cb17-23"><a></a>  ),</span>
<span id="cb17-24"><a></a>  <span class="co"># Use SE instead o CIs</span></span>
<span id="cb17-25"><a></a>  <span class="at">include.ci =</span> F,</span>
<span id="cb17-26"><a></a>  <span class="co"># Giving the models custom names</span></span>
<span id="cb17-27"><a></a>  <span class="at">custom.model.names =</span> <span class="fu">paste</span>(<span class="st">"("</span>,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>),<span class="st">")"</span>, <span class="at">sep=</span><span class="st">""</span>),</span>
<span id="cb17-28"><a></a>  <span class="co"># Adding a header to group models by year</span></span>
<span id="cb17-29"><a></a>  <span class="at">custom.header =</span> <span class="fu">list</span>(<span class="st">"NES 2016"</span> <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="st">"NES 2020"</span> <span class="ot">=</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>),</span>
<span id="cb17-30"><a></a>  <span class="co"># Changing the caption of the table</span></span>
<span id="cb17-31"><a></a>  <span class="at">caption =</span> <span class="st">"Partisanship and Vaccine Skepticism"</span></span>
<span id="cb17-32"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-4-3">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 2
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 3
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 4
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 5
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 6
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.46<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.35<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.42<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.34<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.32<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.35<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.04)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.06<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.01)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid^2
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.01<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.00
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.00)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid3catIndependent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.17<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.20<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pid3catRepublican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.02
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.10<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.01)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.05
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
<div id="tabset-4-4">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Partisanship and Vaccine Skepticism
</caption>
<thead>
<tr>
<th>
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2016
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2020
</th>
</tr>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(1)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(2)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(3)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(4)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(5)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(6)
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.458<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.350<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.417<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.343<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.318<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.352<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.025)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.035)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.018)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.024)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.005
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.064<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.037<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.003)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID<sup>2</sup> (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.009<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.002
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.001)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Independent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.175<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.200<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Republican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.016
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.100<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.023
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.028
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.022
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.027
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
</div>
</div>
</section>
<section id="telling-a-story-with-regression" class="slide level2 smaller">
<h2>Telling a Story with Regression</h2>
<p>First, provide an overview the models presented in the table</p>
<ul>
<li>Explain what each model is doing conceptually</li>
</ul>
<p>Then start with your simplest model (first column)</p>
<ul>
<li>Use this as a chance to explain core concepts from the course
<ul>
<li>What is regression</li>
<li>How should I interpret a coefficient substantively</li>
<li>How should I interepret the statistical signficance of a give coefficient</li>
</ul></li>
<li>As you move from left to right (simple to more complex)
<ul>
<li>you need not interpret every single coefficient in the model</li>
<li>instead highlight the factors that are important for the reader to note (e.g.&nbsp;a comparison between one coefficient in model or another.)</li>
</ul></li>
</ul>
</section>
<section id="example" class="slide level2 smaller">
<h2>Example</h2>
<p>Table 1 presents the results of three specifications exploring the relationship between partisanship and vaccine skepticism using data from the 2016 (Models 1-3) and 2020 (Models 4-5) National Election Studies.</p>
<p>Models 1 and 4 operationalize partisanship as a 7-point scale, where 1 corresponds to Strong Democrats, 4 to Indepndents, and 7 to Strong Republicans in the 2016 (Model 1) and 2020 (Model 2) surveys.</p>
<p>Models 2 and 5 allow the relationship between partisanship and vaccine skepticism to vary non-linear again for the 2016 (Model 2) and 2020 (Model 5) elections.</p>
<p>Models 3 and 6 treat partisanship as categorical variable, describing how Independents and Republicans differ from Democrats, the reference category in these models.</p>
<p>All models control age, since (put in substantive justification for controlling for age here)</p>
</section>
<section id="story-testing-for-partisan-differences" class="slide level2 smaller">
<h2>Story: Testing for Partisan Differences</h2>
<ul>
<li class="fragment"><p>The results from Model 1 provide little initial evidence for partisan differences in vaccine skepticism in the 2016 Election.</p>
<ul>
<li class="fragment">The coefficient on the partisanship variable is -0.005, suggesting that a unit increase in partisanship (going from being a Strong Democrat to just a Democrat, or an Independent to an independent who leans Republican), is associated with just a 0.5 percentage point increase in the probability of being a vaccine skeptic (believing that the risks of vaccination outweigh the benefits or that their is no difference in the risks versus benefits).</li>
</ul></li>
<li class="fragment"><p>Furthermore the 95-percent confidence interval for this estimate (-0.011, 0.002) brackets 0, suggesting the true population estimate from this model could be either positive or negative. Similarly, we fail to reject the null hypothesis that the true coefficient on partisanship in this model is 0 as the test statistic for this estimate ( -1.38) corresponds to a p-value of 0.168 suggesting that we would see test statistics this large or larger fairly often when the true relationship was 0.</p></li>
<li class="fragment"><p>In sum, the results from Model 1 provide little support for any of the expectations described by <em>H1</em></p></li>
</ul>
</section>
<section id="testing-for-partisan-differences-model-2" class="slide level2 smaller">
<h2>Testing for Partisan Differences: Model 2</h2>
<ul>
<li class="fragment">While coefficients from Model 1 suggest little evidence of partisan differences in vaccine skepticism, the coefficients on both partisanship, and partisanship squared are statistically significant (p &lt; 0.05).</li>
</ul>
</section>
<section id="interpreting-model-2" class="slide level2 smaller">
<h2>Interpreting Model 2</h2>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Task</a></li><li><a href="#tabset-5-2"><i class="fa-solid fa-code" aria-label="code"></i></a></li><li><a href="#tabset-5-3"><i class="fa-solid fa-chart-lines" aria-label="chart-lines"></i> Figure</a></li><li><a href="#tabset-5-4">Interpretation</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<ul>
<li class="fragment">The coefficients from polynomial regressions can be difficult to interpret jointly and so Figure 1 presents the predicted values from Model 2, holding age constant at its sample mean.</li>
</ul>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>pred_df_m2 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb18-2"><a></a>  <span class="at">pid =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>,</span>
<span id="cb18-3"><a></a>  <span class="at">age =</span> <span class="fu">mean</span>(nes16<span class="sc">$</span>age, <span class="at">na.rm=</span>T)</span>
<span id="cb18-4"><a></a>)</span>
<span id="cb18-5"><a></a>pred_df_m2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_df_m2, <span class="fu">predict</span>(m2_2016,pred_df_m2, <span class="at">interval =</span><span class="st">"confidence"</span>))</span>
<span id="cb18-6"><a></a></span>
<span id="cb18-7"><a></a>fig_m2 <span class="ot">&lt;-</span> pred_df_m2 <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(pid, fit, <span class="at">ymin =</span>lwr, <span class="at">ymax =</span>upr))<span class="sc">+</span></span>
<span id="cb18-9"><a></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb18-10"><a></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span>.<span class="dv">2</span>, <span class="at">fill=</span><span class="st">"grey"</span>)<span class="sc">+</span></span>
<span id="cb18-11"><a></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb18-12"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Partisanship"</span>,</span>
<span id="cb18-13"><a></a>       <span class="at">y =</span> <span class="st">"Predicted Vaccine Skepticism"</span>,</span>
<span id="cb18-14"><a></a>       <span class="at">title =</span> <span class="st">"Independents are the most skeptical of vaccines"</span>,</span>
<span id="cb18-15"><a></a>       <span class="at">subtitle =</span> <span class="st">"Data: 2016 NES"</span></span>
<span id="cb18-16"><a></a>       )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-5-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>fig_m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="12-slides_files/figure-revealjs/pred-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-4">
<p>We see from Model 2 that 29.7 percent [27.3%, 32.1%] of Independents in the 2016 NES were predicted to be vaccine skeptics compared to 23.7 percent [20.8%, 26.5%] of Strong Democrats and only 20.1 percent [16.9%, 23.3%] of Strong Republicans.</p>
</div>
</div>
</div>
</section>
<section id="interpreting-model-3" class="slide level2 smaller">
<h2>Interpreting Model 3</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Interpretation</a></li><li><a href="#tabset-6-2"><i class="fa-solid fa-code" aria-label="code"></i> Code</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>Model 3 tells a similar story to model 2. Again, adjusting for differences in vaccine skepticism explained by age, Model 3 predicts that 41.7 percent [37.7%, 45.6%] of Independents in the 2016 NES are vaccine skeptics compared to 24.2 percent [22.1%, 26.2%] of Democrats, and 22.6 percent [20.4%, 24.8%] of Republicans.</p>
<p>Note the coefficients from Model 3 imply that the differences between Independents and Democrats are statistically significant (<span class="math inline">\(\beta_{Ind} = 0.175, p &lt; 0.05\)</span>), the differences between Republicans and Democrats are not (<span class="math inline">\(\beta_{Rep} = -0.004, p = 0.31\)</span>)</p>
</div>
<div id="tabset-6-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a>pred_df_m3 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb20-2"><a></a>  <span class="at">pid3cat =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>, <span class="st">"Independent"</span>,<span class="st">"Republican"</span>),</span>
<span id="cb20-3"><a></a>  <span class="at">age =</span> <span class="fu">mean</span>(nes16<span class="sc">$</span>age, <span class="at">na.rm=</span>T)</span>
<span id="cb20-4"><a></a>)</span>
<span id="cb20-5"><a></a>pred_df_m3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_df_m3, <span class="fu">predict</span>(m3_2016,pred_df_m3, <span class="at">interval =</span><span class="st">"confidence"</span>))</span>
<span id="cb20-6"><a></a>pred_df_m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      pid3cat      age       fit       lwr       upr
1    Democrat 49.58231 0.2419547 0.2211228 0.2627867
2 Independent 49.58231 0.4169043 0.3773539 0.4564547
3  Republican 49.58231 0.2261496 0.2038046 0.2484947</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="section-4" class="slide level2 smaller">
<h2></h2>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>tab_better</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Partisanship and Vaccine Skepticism
</caption>
<thead>
<tr>
<th>
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2016
</th>
<th style="padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;" colspan="3">
NES 2020
</th>
</tr>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(1)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(2)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(3)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(4)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(5)
</th>
<th style="padding-left: 5px;padding-right: 5px;">
(6)
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.458<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.350<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.417<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.343<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.318<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.352<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.025)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.035)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.018)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.024)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.005
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.064<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.037<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.003)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.004<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.003<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.000)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
PID<sup>2</sup> (7pt)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.009<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.002
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.002)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.001)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Independent
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.175<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.200<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.023)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Republican
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-0.016
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.100<sup>*</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.016)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.011)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.023
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.028
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.022
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.027
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.042
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.032
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.045
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3494
</td>
<td style="padding-left: 5px;padding-right: 5px;">
3507
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7041
</td>
<td style="padding-left: 5px;padding-right: 5px;">
7052
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</section>
<section id="testing-for-differences-over-time" class="slide level2 smaller">
<h2>Testing for Differences Over Time</h2>
<p>The results for the 2016 NES suggest political independents are most skeptical of vaccines.</p>
<p>The results for 2020 suggest the relationship between partisanship and vaccine skepticism has changed overtime.</p>
<ul>
<li class="fragment"><p>The coefficient on partisanship in model 4 is now positive and statistically significant (p &lt; 0.05), suggesting that as respondents become more Republican, they are more likely to be skeptical of vaccines</p></li>
<li class="fragment"><p>The coefficients from Model 5 suggest the relationship between partisanship skepticism is non linear, which is confirmed by model 6.</p></li>
<li class="fragment"><p>In Model 6, we see that independents remain the most skeptical of vaccines in 2020 <span class="math inline">\((\beta = 0.20,\, p &lt;0.05)\)</span>, but that Republicans now tend to be more skeptical of vaccines than Democrats <span class="math inline">\((\beta = 0.10,\, p &lt;0.05)\)</span></p></li>
</ul>
</section></section>
<section>
<section id="presentations" class="title-slide slide level1 inverse center">
<h1><i class="fa-solid fa-magnifying-glass" aria-label="magnifying-glass"></i> Presentations</h1>

</section>
<section id="presentations-1" class="slide level2 smaller">
<h2>Presentations</h2>
<ul>
<li class="fragment"><p>Motivation</p></li>
<li class="fragment"><p>Research Question</p></li>
<li class="fragment"><p>Theory</p></li>
<li class="fragment"><p>Expectations</p></li>
<li class="fragment"><p>Data</p>
<ul>
<li class="fragment"><p>Summary</p></li>
<li class="fragment"><p>Descriptive Table and/or Figure (Optional)</p></li>
</ul></li>
<li class="fragment"><p>Design</p></li>
<li class="fragment"><p>Results</p>
<ul>
<li class="fragment"><p>Summary</p></li>
<li class="fragment"><p>Table (Optional)</p></li>
<li class="fragment"><p>Figure (Optional)</p></li>
</ul></li>
<li class="fragment"><p>Conclusion</p></li>
<li class="fragment"><p>Appendices (Extra Slides Optional)</p></li>
</ul>
</section>
<section id="template" class="slide level2">
<h2>Template</h2>
<p>Let’s open up the <a href="https://josephessig-source.github.io/pols1600_site/assignments/a5.html" target="_blank">template</a> and explore.</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/pols1600_hex.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>POLS 1600</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>